### ISSUE TITLE
Please add eporner.com

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#100]
Can you please look at the possibility of adding eporner.com. This is an extremely good high quality content website with latest updates.

**Comment by imurreflection** [comment]
Hi, if the addition is not possible, please advise and i will close this issue. Thanks

**Comment by 12asdfg12** [comment]
It's possible, in fact it seems quite simple (no encrypted video links, no multiple hosts), the problem is free time, maybe I will do it next week, unless someone else wants.

**Comment by imurreflection** [comment]
Thank you so much mate. Please take your time. Also, there is another very rare Japanese leaked uncensored ( Original videos are censored) site herexxx.com showing the content in HD only. Please see if this can be added as well. Please do take your time and whenever you think you have some spare, please do add them. Have a nice day !

**Comment by dobbelina** [comment]
Merge pull request #107 from 12asdfg12/master

**Comment by imurreflection** [comment]
Thank you so much for the additions brother. This is highly appreciated.
