### ISSUE TITLE
XVideos not loading categories list

### ISSUE THREAD

**Issue by leonardo-mdc** [dobbelina/repository.dobbelina#1000]
Recently updated to Kodi 20.1.0 and reinstalled cumination. It was working OK before, with kodi 19, although sometimes it closed unexpectedly when browsing the lists but I had ruled it to my kodi install being a little defective -- it was freezing on the splash screen.

**Comment by bOuNtYhUnTeR2022** [comment]
> Recently updated to Kodi 20.1.0 and reinstalled cumination. It was working OK before, with kodi 19, although sometimes it closed unexpectedly when browsing the lists but I had ruled it to my kodi install being a little defective -- it was freezing on the splash screen.

Yes, it doesn't load any category's anymore 😕

**Comment by dobbelina** [comment]
A fix will be provided in the next release https://github.com/dobbelina/repository.dobbelina/commit/c0bc815298ee19ef7c2b01b45d4b1e636c44f19f
