### ISSUE TITLE
Rule34Video Crashing on Open/Search

### ISSUE THREAD

**Issue by s4ik0s4n** [dobbelina/repository.dobbelina#1002]
I tried collecting a log with the Kodi Log file Uploader, but it appears to reset the contents of the log on boot. When I try opening Rule34 Video on my Nvidia Shield, Kodi crashes out. It opens sometimes, and when i search various words or scroll over random videos, it'll crash randomly. I'm on Kodo 20.1 I believe. I made a pastebin for the latest kodi.log.
https://pastebin.com/EPxrCjGi

**Comment by DJMix-I-Can** [comment]
Working fine on my Nvidia Shield. That log file is not a debug log file.

**Comment by dobbelina** [comment]
[Here's how you create a debug logfile](https://github.com/dobbelina/repository.dobbelina/issues/968#issuecomment-1427506877)

**Comment by Gujal00** [comment]
Kodi 20.x on Android is still flaky and crashes a lot when playing videos, scanning xmls, etc. it is not specific to any addon,
Try with Kodi19,5

**Comment by s4ik0s4n** [comment]
Using it on 19.5 works just fine. Seems it's just an issue with Kodi 20+
