### ISSUE TITLE
No Quality Selection Option- Xhamster

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#1007]
Please check. No pop-up appears for selecting quality inspite of configuring it to show FHD only. Most of the time, the direct playback is in 4k which really stutters. There is also no playback in Xvideos. I will create a separate issue with debug log if no one is facing the issue. Kindly check

**Comment by DJMix-I-Can** [comment]
It's working fine on my end. Go to "settings, hosts & resolvers." Click on "open ResolveURL settings". See if "Automatically pick best quality" is checked off. If it is, uncheck it & click ok.
As for XVideos, videos are playing. The Categories folder is the only thing not working. A fix will be provided on the next update.

**Comment by DJMix-I-Can** [comment]
Can't check the debug log file right now. What I would try is selecting another country besides the one that is currently selected in your VPN. Try the US, it definitely works here. If it works, that was your issue...

**Comment by frankee123** [comment]
I don't mean to intrude, but is there a way to filter out seeing any really low quality videos such as 480p or 360p that come up searching for videos on any site? Is there a way to disable seeing them at all? I only want to view 720p and above. I just don't know if that is possible. Ty

**Comment by DJMix-I-Can** [comment]
You could try this...Go into Cumination settings, "hosts & revolvers"," preferred maximum video quality" set to 4K if your TV supports it.

**Comment by imurreflection** [comment]
@DJMix-I-Can 
I tried using US IP but the result was same. No playback.

**Comment by Gujal00** [comment]
> I don't mean to intrude, but is there a way to filter out seeing any really low quality videos such as 480p or 360p that come up searching for videos on any site? Is there a way to disable seeing them at all? I only want to view 720p and above. I just don't know if that is possible. Ty

Not possible as you wont know the quality in most cases until the link is resolved. There are some sites which list `HD` in title but is not common for all sites, so can't filter based on that

**Comment by frankee123** [comment]
> > I don't mean to intrude, but is there a way to filter out seeing any really low quality videos such as 480p or 360p that come up searching for videos on any site? Is there a way to disable seeing them at all? I only want to view 720p and above. I just don't know if that is possible. Ty
> 
> Not possible as you wont know the quality in most cases until the link is resolved. There are some sites which list `HD` in title but is not common for all sites, so can't filter based on that

ok, thank you for the response buddy!
