### ISSUE TITLE
Add camcaps.to

### ISSUE THREAD

**Issue by saidma** [dobbelina/repository.dobbelina#1008]
Site: https://camcaps.to/videos
Contact: https://camcaps.to/feedback
DMCA: https://camcaps.to/static/dmca

Mirror 
Site: https://camcaps.io/videos
Contact: https://camcaps.io/feedback
DMCA: https://camcaps.io/static/dmca

 Thanks so much

**Comment by dobbelina** [comment]
Will be in the next release [camcaps](https://github.com/dobbelina/repository.dobbelina/commit/79b4104d8ee2f3eae554c2a1281442de3e274c08)
