### ISSUE TITLE
Site additions

### ISSUE THREAD

**Issue by Poorrichardbar** [dobbelina/repository.dobbelina#1010]
https://motherless.com/

https://www.redtube.com/

 V**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**If it's a site addition request, add url below**
Sites with no DMCA information will not be added

**Comment by dobbelina** [comment]
Motherless is available as a custom site:[Motherless](https://github.com/dobbelina/repository.dobbelina/issues/407#issuecomment-1146847664)
