### ISSUE TITLE
Xhamster.com + Pornhub.com not accessible 

### ISSUE THREAD

**Issue by bOuNtYhUnTeR2022** [dobbelina/repository.dobbelina#1011]
Since 2 days pornhub.com and xhamster.com aren't accessible any more.
Because of time issues, i can't send any log file. Would be great if anyone could send, after checking the sites. 

Maybe it's a local based issue, but seems this time it's not.

Thanks 😉👍

**Comment by dobbelina** [comment]
Both sites works for me.
Could be a cloudflare issue only affecting your country.¨Without a logfile not much we can do.
