### ISSUE TITLE
Myfreecams Error not showing any logged cam models

### ISSUE THREAD

**Issue by losthelp815** [dobbelina/repository.dobbelina#1013]
https://paste.kodi.tv/odupevugob

PC 
Kodi 19.4 Windows 7

Problem with Myfreecams no longer showing any logged-in cam models only able to see tags main hub just started happing in the last 2 days. Dose work if trying to watch through favorites also able to click on tags those also work. Kodi Version 19.4 OS Windows 7. If possible anyone could please try to figure out and repair the missing images?

**Comment by dobbelina** [comment]
A fix will be provided in the next release [beemtube playback, mfc listing](https://github.com/dobbelina/repository.dobbelina/commit/efe326ee0ac4221e4ee34eb26521e37072c1ffd1)
