### ISSUE TITLE
Rule34 Video Pagination broken in 'Tags', non-exisistent in 'Search'

### ISSUE THREAD

**Issue by s4ik0s4n** [dobbelina/repository.dobbelina#1014]
### Bug reports:

When clicking Next Page after selecting a tag, page loops back on itself. When searching anything, no Next Page option available.

### OS environment
On Kodi 19.5 on both Windows and Android (Nvidia Shield)

https://paste.kodi.tv/zibecozetu

**Comment by dobbelina** [comment]
Issue confirmed, thanks for reporting.

**Comment by dobbelina** [comment]
A fix will be provided in the next release [beemtube playback, mfc listing](https://github.com/dobbelina/repository.dobbelina/commit/efe326ee0ac4221e4ee34eb26521e37072c1ffd1)
