### ISSUE TITLE
Hentaihaven error when trying to play all files

### ISSUE THREAD

**Issue by dootsie5times** [dobbelina/repository.dobbelina#1017]
### Bug reports:
Hentaihaven error when trying to play all files

### OS environment
Odriod N2+
Coreleec 19.4

[kodi.log](https://github.com/dobbelina/repository.dobbelina/files/11194223/kodi.log)

**Comment by dobbelina** [comment]
A fix will be provided in the next release [Hentaihaven Video playback fix](https://github.com/dobbelina/repository.dobbelina/pull/1018)
