### ISSUE TITLE
Site sextb has a filter?

### ISSUE THREAD

**Issue by Qwertyful78** [dobbelina/repository.dobbelina#1019]
Why sextb only have reduce mosaic and engsub, how to watch the others (no sub, ...). i remember before still have full video

**Comment by DJMix-I-Can** [comment]
Are you saying you don't get the rest of the directories like this image? If so, it's there & working.  Make sure you're on the latest version of Cumination. If you are, you're going to need to provide a debug log file.
![Sextb](https://user-images.githubusercontent.com/35236592/232259283-ed4794eb-09e1-4104-97e0-f9a7cc175074.jpg)

**Comment by Qwertyful78** [comment]
![1681636236504629731697603555919](https://user-images.githubusercontent.com/130860858/232288845-fbae8856-0905-497b-ac9e-493d9581c57e.jpg)
No the directories full, but when choose Censored, only show video [ English Subtitle] like image, all new videos dont have English sub were hidden

**Comment by DJMix-I-Can** [comment]
Ok, I sent a pull request for the [fix.](https://github.com/dobbelina/repository.dobbelina/pull/1020/files)

**Comment by dobbelina** [comment]
Fix merged, thank you DJMix-I-Can
