### ISSUE TITLE
Chaturbate - empty tags section

### ISSUE THREAD

**Issue by dvgm506** [dobbelina/repository.dobbelina#1023]
### Bug reports:

The tag sections in Chaturbate are empty. It's happened before, sometimes it seems to fix itself, this time it's been like that for 4 days or so?

### OS environment

Windows 11 & multiple nvidia shield TV units using cumination 1.1.73.

### Logs:

https://paste.kodi.tv/selacewodo

**Comment by dobbelina** [comment]
Will be a fix in the next release [chaturbate tags](https://github.com/dobbelina/repository.dobbelina/commit/c5ad2bd5660b29c19f60824b4634d05dddd8e88b)

**Comment by pitsi** [comment]
Can you please make the tags sort in alphabetical order instead of the current one? I do not mind the 50-per-page pagination that cb has now, but this order with the viewers' count is annoying.
