### ISSUE TITLE
Global Search

### ISSUE THREAD

**Issue by CableSix** [dobbelina/repository.dobbelina#1028]
might sound ambitious but pretty insane, would you be able to put a search function on all sites at the same time? I think a lot of people think how annoying it is to check site by site to see if it contains a video you want.

**Comment by DJMix-I-Can** [comment]
Once again, this has [already been discussed](https://github.com/dobbelina/repository.dobbelina/issues/906). Please do a search before posting an issue....

**Comment by CableSix** [comment]
> Once again, this has [already been discussed](https://github.com/dobbelina/repository.dobbelina/issues/906). Please do a search before posting an issue....

sorry bro
