### ISSUE TITLE
FreeOMovie not working Please restore 

### ISSUE THREAD

**Issue by durangorob** [dobbelina/repository.dobbelina#1030]
### Bug reports:

FreeOMovie not working.  

### OS environment
Android, Kodi/dobbelina/cumination/sites/FreeOmovie

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.

**Comment by ErosVece** [comment]
It's fixed, you can find it in the next update.

**Comment by dobbelina** [comment]
[Freeomovie fixed,JapTeenX new site ](https://github.com/dobbelina/repository.dobbelina/commit/fb3bf140438e209565b209905c878025d3a12431)
