### ISSUE TITLE
Camcaps error videos 

### ISSUE THREAD

**Issue by saidma** [dobbelina/repository.dobbelina#1031]
Videos do not play.  
The website was recently updated (player embedded)

Thank you for your trouble

**Comment by ErosVece** [comment]
They play fine for me.

Please submit a debug log.

**Comment by saidma** [comment]
> 
Is rare.  It only happens to me on this website. 
I use Android TV with Kodi Nexus 20.1

https://paste.kodi.tv/vunizadake.kodi

**Comment by ErosVece** [comment]
Just wanted to say, reinstall....because your reallifecams.py isn't the same as the latest on the repository 🤣

**Comment by saidma** [comment]
> I did not realize.  I have manually installed the changes.  😅😅😅



> Just wanted to say, reinstall....because your reallifecams.py isn't the same as the latest on the repository 🤣
