### ISSUE TITLE
Spankbang does not open

### ISSUE THREAD

**Issue by Kodionpi** [dobbelina/repository.dobbelina#1032]
### Bug reports:
Spankbang does not work/open

### OS environment
Libreelec 11.0.1, Raspberry Pi 2 Model B, Kodi 20.1

[kodi.log](https://github.com/dobbelina/repository.dobbelina/files/11361132/kodi.log)

**Comment by dobbelina** [comment]
Read here https://github.com/dobbelina/repository.dobbelina/issues/984

**Comment by Kodionpi** [comment]
Oh, thanks, I hadn't seen that. too bad it no longer works/is blocked...

**Comment by Spanktacular** [comment]
https://scrapeops.io/web-scraping-playbook/how-to-bypass-cloudflare/
