### ISSUE TITLE
Please add deepfake porn site

### ISSUE THREAD

**Issue by Beladeep** [dobbelina/repository.dobbelina#1033]
Dear developers

I would like you to add two best deepfake porn site
https://mrdeepfakes.com/
https://mrdeepfakes.com/dmca

https://adultdeepfakes.com/
https://adultdeepfakes.com/dmca/

Thank you very match

**Comment by DJMix-I-Can** [comment]
@dobbelina I thought I'd give a quick opinion about this matter. Deepfakes & AI content. Personally, deepfakes is nothing but trouble. AI content is beneficially to a certain extant. If AI is being used to create deepfakes, I don't think it's good. If AI is used to help someone learn or resolves issues that is legally beneficial. Then use it. I personally don't think we should included sites that deal with deepfakes or AI. Then again, how do we know if it's any of it? This conversation has been hitting the rounds & it's evolving. I know I'm going to open a can of worms with this question. What do you guys think about it? As for me, no deepfake sites. As for AI, can we tell if it's not disclosed?

**Comment by Beladeep** [comment]
> 

There is nothing wrong with artificial intelligence.
It's just fun. 
On these pages you can see stars in scenes you could only imagine
😃😃 😃
Everybody knows they're not real.
Meanwhile you wonder what AI can do today.

**Comment by dobbelina** [comment]
My first contact with an AI was actually quite recent with the well known chatGTP.
It was a jaw-dropping experience to say the least, and yes, terminator will 
get rid of us all in a not to distant future......
Joking aside, I don't really see any issue with people jerking off to a circuit board :)
I'm more interested in the site/s providing proper DMCA information 
so that our repo don't get involved in legal issues.

**Comment by Beladeep** [comment]
Pandora's box is open.🤪
I believe that this is the future and we shouldn't close ourselves off from it.

**Comment by Beladeep** [comment]
Chat got generated a code for the page, but it doesn't work:
```python
'''
    Cumination
    Copyright (C) 2019 Cumination
    
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
'''

import re

import xbmcplugin
from resources.lib import utils
from resources.lib.customsite import CustomSite

site = CustomSite('Cumination', 'mrdeepfakes')

BASE_URL = 'https://mrdeepfakes.com'

@site.register(default_mode=True)
def Main():
    site.add_dir('[COLOR hotpink]Categories[/COLOR]', BASE_URL + '/celebrities', 'Categories', site.img_cat)
    List(BASE_URL + '/celebrities')
    utils.eod()


@site.register()
def List(url):
    try:
        listhtml = utils.getHtml(url, '')
    except:
        return None
    match = re.compile(r'<a href="(/video/[0-9]+/[^"]+)"><img[^>]+data-src="([^"]+)"[^>]+>\s*</a>\s*<a[^>]+>[^<]+</a>\s*<a[^>]+>([^<]+)</a>', re.DOTALL | re.IGNORECASE).findall(listhtml)
    for videopage, img, name in match:
        name = utils.cleantext(name).title()
        site.add_download_link(name, BASE_URL + videopage, 'Playvid', img, name)
    
    nextp = re.compile('<a href="([^"]+)">Next</a>').search(listhtml)
    if nextp:
        site.add_dir('Next Page', BASE_URL + nextp.group(1), 'List', site.img

```

**Comment by dobbelina** [comment]
Ohh i'm sorry here is the correct code.....:)
