### ISSUE TITLE
spankbang error

### ISSUE THREAD

**Issue by ROOOU** [dobbelina/repository.dobbelina#1034]
![IMG_4541](https://user-images.githubusercontent.com/51469359/235907416-4cfe6e01-9721-4df4-9048-022391ab2672.jpeg)

**Comment by dobbelina** [comment]
Read here https://github.com/dobbelina/repository.dobbelina/issues/984

**Comment by ROOOU** [comment]
> Read here #984 

****

log

info <general>: Loading skin file: MyVideoNav.mI, load type: KEEP_IN_MEMORY
2023-05-04 04:23:53.165 T:29844 error <general>: EXCEPTION Thrown (PythonToppException)
--> Python callback/script returned
the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'TypeError'>
Error Contents: a bytes-like object is required, not 'str' Traceback (most recent call last):
File
"/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cumination/resources/lib/utils.py",line448,in_getHtml
response = urlopen(reg, timeout=30)
ЛАЛАЛАЛАЛЛАЛЛАЛАЛЛАЛЛАЛЛ
File */data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/urllib/request.py",line 216, in urlopen

**Comment by ROOOU** [comment]
https://paste.kodi.tv/mezimoburo.kodi
