### ISSUE TITLE
NETFAPX - NO PLAYBACK

### ISSUE THREAD

**Issue by Spanktacular** [dobbelina/repository.dobbelina#1035]
You can view thumbnails and links, but no video file can be found.

**Comment by DJMix-I-Can** [comment]
Pushed a [fix](https://github.com/dobbelina/repository.dobbelina/pull/1037) for it.

**Comment by dobbelina** [comment]
Fix [pushed](https://github.com/dobbelina/repository.dobbelina/commit/7c5b1233d801abccfac43d7fc0a06d51a9d35414), thanks @DJMix-I-Can
