### ISSUE TITLE
FamilyPornHD and Porn00 no Playback on Nvidia Shield TV

### ISSUE THREAD

**Issue by abefroman69** [dobbelina/repository.dobbelina#1038]
Both sites start to search for sever when playing a video then the box disappears with no playback.  The Porn00 one will lock up all playback for Kodi until force stop and restart

**Comment by dobbelina** [comment]
[FamilyPornHD - fix playback](https://github.com/dobbelina/repository.dobbelina/commit/8070d85392026102b7484f3b4f75059e712e856a)

**Comment by DJMix-I-Can** [comment]
FamilyPornHD did need to be fixed. On the other hand, Porn00 is working fine on both of my Nividia Shields. No lock ups, buffers or kick outs after fast forwarding.

**Comment by abefroman69** [comment]
DJMix-I-Can,

That's strange, mine hasn't works for months.  I'll see if I can get a logfile

**Comment by DJMix-I-Can** [comment]
> DJMix-I-Can,
> 
> That's strange, mine hasn't works for months. I'll see if I can get a logfile

Make sure it's a debug file....

**Comment by abefroman69** [comment]
Here is the link to the dubug file.  This was made going in to Porn00 and playing a video.  On the screen it just gives a loading circle of death.  I let it run for about 2 mins before backing out to upload log file

https://paste.kodi.tv/eroquxuwoj

No VPN, router and fiber box have been the same for years.  Have rebooted both a number of times since this issue started last year. No DNS changes and are the DNS servers from MY ISP

**Comment by DJMix-I-Can** [comment]
I looked at your debug file. I saw an error on line 2717-2719
2023-05-05 23:05:59.307 T:9899    error <general>: ffmpeg[0x3046feedb8]: [mov,mp4,m4a,3gp,3g2,mj2] error reading header
2023-05-05 23:05:59.308 T:9899    error <general>: Open - Error, could not open file https://nedene.b-cdn.net/videos/25000/25677/25677_720p.mp4?token=1CtLPeM4wrXfI72O8zzg4Q&expires=1683353146
2023-05-05 23:05:59.308 T:9899    error <general>: OpenDemuxStream - Error creating demuxer

If your phone ISP (your phone not connected to your homes Wifi ISP) is not the same as your home ISP. Try this link on you phone https://nedene.b-cdn.net/videos/25000/25677/25677_720p.mp4?token=1CtLPeM4wrXfI72O8zzg4Q&expires=1683353146
If your phones ISP is not the same as your homes ISP. Does it play? If your phone & ISP are on the same network. Does it still give you an error even thought you're disconnected of the wifi network. I know it sounds confusing but I'm trying to see if your ISP DNS is blocking.
We don't know you're current location. You could try adding this advancedsettings.xml to see if it works out for you. This is what I use on my Nvidia Shields. I also configured my devices & routers to use the following DNS. Primary 8.8.8.8  & Secondary 8.8.4.4
This is my advancedsettings.xml file on my Shields.
<advancedsettings>
    <cache>
        <memorysize>209715200</memorysize>
        <readfactor>24</readfactor>
        <buffermode>2</buffermode>
    </cache>
    <network>
        <disablehttp2>true</disablehttp2>
        <curlretries>6</curlretries>
        <curlclienttimeout>20</curlclienttimeout>
        <curllowspeedtime>1000</curllowspeedtime>
    </network>
</advancedsettings>

**Comment by abefroman69** [comment]
I don't think it's a DNS issue for Porn00.  Same DNS server on laptop, phone and Nvidia Shield and the shield is the only one with the issue.
