### ISSUE TITLE
animeid doesn't play files

### ISSUE THREAD

**Issue by dootsie5times** [dobbelina/repository.dobbelina#1039]
Coreelec 19.4

AnimeID failes to play any video.

Also, when you go the base url site, https://animeidhentai.com/ it shows a lot of new titles.  
However, the addon shows only older titles.

The "newest releases" category really isn't the newest releases.  It starts with titles form 2021.
If you click on "latest" and then "view more" it brings up a search bar with 2023 filled in in the "years" drop down list and you then get the true newest releases.

It looks like the only way to possibly fix this would be to implement a "search" feature to list titles by year like the website does.

[kodi.log](https://github.com/dobbelina/repository.dobbelina/files/11401640/kodi.log)

**Comment by dobbelina** [comment]
[Animeidhentai - fix playback, listing](https://github.com/dobbelina/repository.dobbelina/commit/9ccc5ba73bba62349a3cb9419cabbb9e4c5c1626)
