### ISSUE TITLE
Quick question about sorting 

### ISSUE THREAD

**Issue by vile80r** [dobbelina/repository.dobbelina#104]
The queue and Play From Here function are working flawlessly. Great job.

I have a question because I don't think it's an issue issue. It's always been this way but it'd be a nice feature.

I've seen this on some other Addons as well but never really understood why. It is the sort feature. It is always, by default, sorted by date with no other options to sort by name, length, rating, etc.

So, when I search for something and it propagates a return of videos is I hit the left arrow or left direction on either my gamepad or Yatse app to open the menu (it slides out from the left on my current build) I can change the list around to big list, poster layout, etc. Underneath is the "sort by" option that just says Date in gray and cannot be changed to something like name or length. Z

Is this something I can fix somehow or is it addon specific?

Thanks

T

**Comment by vile80r** [comment]
This may not even be an issue with the addon but more of a missing feature which means I've posted it in the wrong area and I apologize.

T

**Comment by 12asdfg12** [comment]
This "sort by" option from kodi requires informations which are not available. Usually we can extract from websites only the name, video page url and an image. If there is a possibility on the website to change the order, this can be implemented in the addon (like the 'Current sort' option in WatchXXXFree) but requires some extra work.

**Comment by jdoedev123** [comment]
Just a side note. I experimented with adding different sorts for search results, but the results were inconsistent. Search results sorted by date for example did not always return the correct search result at the top. The feature was not added.

**Comment by dobbelina** [comment]
As 12asdfg12 pointed out, this program scrapes from different websites,
and many of those do not provide the needed data to do any sorting, therefore
making it impossible to use the sort feature in the side panel, as that
would only work if all the websites scraped, provided the same data.
That sort feature in the side panel, is mostly intended for local files
on your hard drive.
Any sort feature that can be implemented, has to be done on a "site by site basis"
with that option as a clickable link.
