### ISSUE TITLE
Categories section of FreeOmovie is not giving any listings when selected.

### ISSUE THREAD

**Issue by durangorob** [dobbelina/repository.dobbelina#1040]
### Bug reports:

"CATEGIORIES" section of FreeOmovie is not giving any listings when selected.  FreeO,ovie does open when selected, but when you go to the top after opening and select "Categories"  you get a blank screen.  This used to work prior before FreeOmovie went down recently. Once it was restored, the Categories does not populate. It is extremely needed to navigate the site. Please look into fixing this asap.  
![Categories](https://user-images.githubusercontent.com/25598789/236638286-b44f10fd-d91a-4778-a043-4f04b49e0ea0.jpg)

### OS environment
Android, Nvidia Shield Pro

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.

**Comment by DJMix-I-Can** [comment]
I wasn't going to comment because I offered a suggestion on what to try. You never responded to it & decided to create a separate issue.That picture is useless!!!! It just shows that you highlighted it. As I stated &  if anyone else could chime in. Does going into the categories section work for you?  It does for me on three different devices. As for your statement, "please fix this asap".  Learn how to code & figure it out yourself. ASAP!!!!

**Comment by durangorob** [comment]
I have tried on three different devices and all yield a blank page when I click on the Categories .  I only included the picture because I assumed that you thought just because the site is opening then it was completely fixed. Why its not working on any of my devices does not make any sense since other sites I open the categories lists on work, but on FreeOmovie it does not .   What is the answer  ????  I am a viewer, not a coder and will never be one.  I even put on a brand new firestick, rebooted my modem, router, and all my streaming boxes, and did a new install of kodi/dobbelina/cumination and it still will not populate any categories when selected.  ?????????????  
BTW, I did respond to you before.

**Comment by DJMix-I-Can** [comment]
Ok @durangorob I have to apologize. The three devices I have used were Android devices with the same build. I keep them consistent. On the other hand, the Windows laptop that I use is for testing purposes, FreeOMovies categories section is not loading. I've been playing with the Android devices through the network off of my Windows laptop. I made changes in order for it to work awhile ago BUT never put a pull request (fix) for it. That is why I stated that it's working. That is my fault & you are correct. My apologies.... I pushed a fix for it.

**Comment by durangorob** [comment]
Thank You for looking a bit deeper into it and, I really appreciate you getting back to me and for all the hard work you guys do for these sites and repos.  
Bob ***@***.*** 

    On Sunday, May 7, 2023 at 06:41:09 PM CDT, DJ Mix-I-Can ***@***.***> wrote:  
 
 


Ok @durangorob I have to apologize. The three devices I have used were Android devices with the same build. I keep them consistent. On the other hand, the Windows laptop that I use is for testing purposes, FreeOMovies categories section is not loading. I've been playing with the Android devices through the network off of my Windows laptop. I made changes in order for it to work awhile ago BUT never put a pull request (fix) for it. That is why I stated that it's working. That is my fault & you are correct. My apologies.... I pushed a fix for it.

**Comment by DJMix-I-Can** [comment]
Thank you for understanding. I've learned my lesson....No more scotch when replying....

**Comment by dobbelina** [comment]
Thanks @DJMix-I-Can 
[Freeomovie Category directory fix](https://github.com/dobbelina/repository.dobbelina/commit/486b69b3182d618d91df63ca91541b924fe204ff)

**Comment by demex2008** [comment]
Hello, there is also a category fix for netfliporno

**Comment by DJMix-I-Can** [comment]
> Hello, there is also a category fix for netfliporno

From what I could see, Netflixporno removed the original categories section. It only consists of Featured & Porn Movies now. If you click on Porn Movies, it's the same as the main page.  It looks like the change happened within this past month. If you do a search with the past category name, I believe it will show those videos. If you go to their webpage on your phone or laptop, you should see it yourself.  I've attached a before & after category section.
![NetlflixPorno](https://github.com/dobbelina/repository.dobbelina/assets/35236592/0101fecc-79c2-4b69-bfb2-74e8373c2f06)

**Comment by durangorob** [comment]
DJMIX-I -Can ...
I'm still on version 1.1.75 and have yet to see an update in over 10 days that would apply the fix to the Categories issue in FreeOmovie.  Any ETA when the new update with the fix will be applied ?
durangorob

**Comment by DJMix-I-Can** [comment]
It will be out on the next update.  If you want to install it yourself, you could [try this](https://github.com/dobbelina/repository.dobbelina/issues/1022).

**Comment by durangorob** [comment]
Thank You very much for following up and fixing this issue and for all that you do.
***@***.*** 

Sent from AT&T Yahoo Mail on Android 
 
  On Sun, May 28, 2023 at 4:13 AM, ***@***.***> wrote:   


Closed #1040 as completed.
