### ISSUE TITLE
hanime.tv site playback issue

### ISSUE THREAD

**Issue by dootsie5times** [dobbelina/repository.dobbelina#1042]
First let me say I'm not providing a log file since there is never any error in playback.

For hanime.tv and first around 2 pages of titles (most recent) exhibit playback issues in the addon.  Older titles play fine.

When playing one of those most recent titles, the file will play fine for a little while and then it will jump backward slightly to a previous point for no apparent reason.  It will then play forward a little and will then jump backward again.  If you hit the "jump forward" key it will take a huge jump and not the 10 sec normal one.  And, sometimes when you hit the "jump forward" key like twice it jump WAY forward (maybe 2 or more minutes) instead of the normal 20 seconds.  Basically it jumps all over the place.
Also, when these crazy jumps start happening, and actual timer counter min:sec may seem to be correct, but the actual place in the file is definitely not.

Strangely, the slightly older titles do not do this at all.

If you require a log file I can provide one, but I'm not sure how much help that will be..  I've tried playing the same files through a web browser in Windoze, and they then play correctly.  I'm really not sure what's happening at all.

To the best of my knowledge, I think this weird issue started around 6-9 months ago.  Previously, this problem didn't exist.

BTW, my internet speed is 300meg so it's not related to lag.

If you require anything to help diagnose this problem, let me know.

**Comment by DJMix-I-Can** [comment]
I don't use hanime.tv at all... I did test it out to see if I can replicate your issue, I couldn't. I played a half an hour video named [Futei with...1](https://hanime.tv/videos/hentai/futei-with-1). Paused it, stepped away for 10 minutes, came back & hit play.  It continued where it left off. Fast forward & backwards was good. You stated that on your Windoze unit, it plays correctly. Is that the same device you're having the issue with or a different device?

**Comment by dootsie5times** [comment]
Sorry, I've been VERY sick and still feel like crap.
I just played https://hanime.tv/inter?r=%2Fvideos%2Fhentai%2Fsuccubus-yondara-gibo-ga-kita-1 and left it play the whole way through, no pauses or forward/backward jumps.  I paid special attention to the timer counter.  On it's own after about 5 min in it would jump backward, go forward a little, then jump back again, then go forward (sometimes it would repeat sections over).  This continued throughout the entire video.  However, the timer itself kept moving forward like normal.  It's almost like someone edited the video and copied and pasted sections out of order and then re-saved it.  I know this is not the case since if I download the video from the site in Windoze it is fully intact.  
I am playing the video through the addon under Coreelec version 19.4 on an Odroid N2+ box..
Like I said before, the slightly older videos on the site play fine.
Let me do some more testing tonight and get back to you on this.

**Comment by dootsie5times** [comment]
When you paused that video for 10 minutes, did it buffer ahead or not?

**Comment by ErosVece** [comment]
It's an issue with the site (or how Kodi handles those m3u files from hanimel).
A m3u file is the video split in dozens of parts, and it serves that to your video player. Somehow during the playback of one of those parts, it stops (connection error or something)...and retry playing that part again. That's why you see the video jumping back in time.

**Comment by dootsie5times** [comment]
Ok, so then why does it happen to only the first 2 or so pages of titles and not every titles on the site?

**Comment by ErosVece** [comment]
In the coming update (or use the github downloader custom site, to grab it now, https://github.com/dobbelina/repository.dobbelina/issues/1022) you will be able to play the mp4 videos, they play normal.
You only need to register an account on the hanime site

**Comment by dootsie5times** [comment]
Can you please tell me what you discovered was causing this crazy behavior when playing them through the addon without a hanime.tv account?  I'm VERY curious.

**Comment by dobbelina** [comment]
A fix will be available in the next update [Hanime play mp4 videos](https://github.com/dobbelina/repository.dobbelina/commit/916fe13448139cc531211ad1a6decb31e893a7e8)

**Comment by ErosVece** [comment]
> Can you please tell me what you discovered was causing this crazy behavior when playing them through the addon without a hanime.tv account? I'm VERY curious.

I didn't fix those m3u8 links, like I said before...it's something how they serve their files or how Kodi handles them.
I can't do anything about that. If it works with earlier videos and not with the current ones, says that they changed something.

If you go to their site, and go to a video, you see under the video a download button. That is a mp4 file you can download.
As you can see, you get a recaptcha (I'm not a robot thing) on the download page, it's hard with Python to handle those. But I figured out how to bypass that, but you'd need a free account for that.

Now it's also possible to add to Cumination the stuff you get when logged in on the site. Like history and Watch later.

**Comment by dootsie5times** [comment]
Is there a way to have Kodi try to use a different player other than the built-in default one to see if it would handle the newer files correctly?

**Comment by ErosVece** [comment]
See https://kodi.wiki/view/External_players

**Comment by ErosVece** [comment]
@dootsie5times 
It looks like that this update https://github.com/dobbelina/repository.dobbelina/commit/23ba87db948b02584003f7d6ab1bc5ab4fc75143 will fix playing the m3u8 (no member) videos.
I tested 2 videos, and I haven't seen it jump back. Also in the debug log I don't see it failing a segment and starting over.

**Comment by dootsie5times** [comment]
Did the update.  Now none of the titles on hanime.tv play at all.  They start to queue and then just stop as soon as the timer appears on the bottom.

**Comment by ErosVece** [comment]
Okay, so you did the update to 1.1.77.

I justed tested it again on my laptop, phone, tv (android tv) and my Odroid N2 running Coreelec.
And it played without problems.

Can you try the other resolutions? So in Cumination settings -> Host & Resolver -> Preferred maximum video quality.....set this to 'Ask'. And when you play a video, start with choosing the lowest quality.

Also, can you make a debug log?

**Comment by dootsie5times** [comment]
Odroid N2+ 19.4

Tried your suggestions, all resolutions, no joy.

Log attached.


[kodi.log](https://github.com/dobbelina/repository.dobbelina/files/11585663/kodi.log)

**Comment by ErosVece** [comment]
`OpenStream - Unsupported stream 1001. Stream disabled.`

You have an outdated inputstream.adaptive: v19.0.3.1
The latest for the Kodi v19 versions is v19.0.7.1

Also your Kodi is outdated, for v19 is 19.5 the latest.
But you can also upgrade to v20.1

If you can't update inputstream.adaptive through addons, here's the download: https://addons.coreelec.org/Amlogic-ng/19.5.1/arm/inputstream.adaptive/inputstream.adaptive-19.0.7.1.zip

**Comment by dootsie5times** [comment]
Updated to 19.5.  Inputstream wouldn't update correctly so used your download to do manual.
Rebooted.
1) Tried to play older file from hanime favorites
2) Tried to play newer file from hanime directly

Same Problem.

Log attached.

[kodi.log](https://github.com/dobbelina/repository.dobbelina/files/11585820/kodi.log)

**Comment by ErosVece** [comment]
It looks like that inputstream.adaptive under 19 doesn't support encrypted streams.

I'll make a toggle in the settings, where you can choose 'the old way' for hanime.

**Comment by ErosVece** [comment]
> Updated to 19.5. Inputstream wouldn't update correctly so used your download to do manual. Rebooted.
> 
>     1. Tried to play older file from hanime favorites
> 
>     2. Tried to play newer file from hanime directly
> 
> 
> Same Problem.
> 
> Log attached.
> 
> [kodi.log](https://github.com/dobbelina/repository.dobbelina/files/11585820/kodi.log)

It's been added: https://github.com/dobbelina/repository.dobbelina/commit/03e01ecba331366fa9f14186a28b14f86a89ff0c

**Comment by dobbelina** [comment]
Fix released in 1.78, closing thread.
