### ISSUE TITLE
SEXTB Search Issue

### ISSUE THREAD

**Issue by EvelK1203** [dobbelina/repository.dobbelina#1043]
When searching multiple word queries there are no returns. When searching the same terms on the web the expected returns are seen.

Single word queries are good.

**Comment by DJMix-I-Can** [comment]
Can you provide an example. I did a three word search & it showed up as their webpage did.

**Comment by EvelK1203** [comment]
This can be closed. I tested on my PC not realizing the addon hadn't been updated for a few versions.

Thanks
