### ISSUE TITLE
Javbangers added features 

### ISSUE THREAD

**Issue by mywayorhighway0** [dobbelina/repository.dobbelina#1051]
Hey guys,

Possible to add "lookup info" and "Go to page" on search results. Appreciate the great work you are doing.

**Comment by ErosVece** [comment]
Here is the lookup info added https://github.com/dobbelina/repository.dobbelina/commit/c551dc334b92d7872d988ce41696177e0e9fb280

**Comment by imurreflection** [comment]
Hi..just to let you know that there is no change. I copied the py file manually but could not see any lookup info any where.

**Comment by ErosVece** [comment]
I think you did something wrong then:

![image](https://github.com/dobbelina/repository.dobbelina/assets/37535332/b530bc35-6627-49ee-b368-97b36c2b17df)

**Comment by imurreflection** [comment]
I copied the py file in your commit and overwrite in lib/sites direct the other files like justfullporn,yourprno works so not sure what could b wrong. Can you give me your original file here pleasé

**Comment by ErosVece** [comment]
My original file is this file: https://github.com/dobbelina/repository.dobbelina/blob/master/plugin.video.cumination/resources/lib/sites/javbangers.py

Open up your javbangers.py, see if you have this starting from line 81:
```
        contextmenu = []
        contexturl = (utils.addon_sys
                          + "?mode=" + str('javbangers.Lookupinfo')
                          + "&url=" + urllib_parse.quote_plus(videopage))
```

**Comment by imurreflection** [comment]
I think, i definitely needs some rest as after copying the file and replacing it with py file, the site simply vanished from cumination. I will wait for @dobbelina to release the update to see if it's me only.  Btw- thank you for your help..
