### ISSUE TITLE
Nothing working

### ISSUE THREAD

**Issue by firetrap71** [dobbelina/repository.dobbelina#1053]
Nothing working since the update

**Comment by dobbelina** [comment]
@firetrap71 @ErosVece

I am aware of the problem.
Please download this fixed version and install manually:
[plugin.video.cumination-1.1.76.zip](https://github.com/dobbelina/repository.dobbelina/raw/master/plugin.video.cumination/plugin.video.cumination-1.1.76.zip)

**Comment by Bolter12** [comment]
I tried installing the file manually from your link above but it did not work for me. I will wait for a proper update to roll out to everyone.

**Comment by dobbelina** [comment]
@Bolter12 
Why did it not work?

**Comment by Bolter12** [comment]
Don't know, has the same error message I got after updating.

**Comment by dobbelina** [comment]
Did you use the option as below?:
![image](https://github.com/dobbelina/repository.dobbelina/assets/46063764/01918f1d-d687-4f26-b9de-4b28b3ce2f36)

**Comment by Bolter12** [comment]
Yes. I am running Kodi 17.6 in Windows. Would this be a problem

**Comment by dobbelina** [comment]
Yes, that is a big problem.
Kodi 17.6 Krypton is stone age, it is almost 6 years old.
You need to update, lol!

**Comment by Bolter12** [comment]
OK. Will update soon.

**Comment by Bolter12** [comment]
I have updated kodi to ver.20.1 all good now thanks.

**Comment by ErosVece** [comment]
Sorry, my bad....it was late 🤣
