### ISSUE TITLE
xHamster site not work

### ISSUE THREAD

**Issue by Format65** [dobbelina/repository.dobbelina#1056]
Hello, I'm not an expert nor a programmer like you but just a user, and sorry if I write improperly here, I just wanted to point out that for the XHamster site, if you go to "categories" any choice you make always comes out video not found. hope someone can fix it.
I use both PC and Android 10
Thank you

p.s. I don't know how to produce the Log file, but if you try you will see the problem.

**Comment by dobbelina** [comment]
Issue confirmed, thanks for reporting.
