### ISSUE TITLE
Perverzija not working 

### ISSUE THREAD

**Issue by Napster955** [dobbelina/repository.dobbelina#1059]

**Comment by Napster955** [comment]
Not able to play video.

**Comment by dobbelina** [comment]
This is related to `<general>: AddOnLog: inputstream.adaptive: adaptive::AdaptiveTree::PreparePaths: URL not valid ()`
A fix will be avaloable in the next release where you can disable the inputstream addon.

**Comment by ErosVece** [comment]
I'll reverse it, let m3u8 play without Inputstream Adaptive, and an option to enable it if you want it

**Comment by dobbelina** [comment]
new release with fix released, closing thread
