### ISSUE TITLE
Tubepornclassic

### ISSUE THREAD

**Issue by Bolter12** [dobbelina/repository.dobbelina#1060]
Tubepornclassic not playing anything. Search, categories and everything else working but will not play anything.

**Comment by dobbelina** [comment]
Hi @Bolter12 

It works for me on windows, so you will need to [create a log file](https://github.com/dobbelina/repository.dobbelina/issues/968#issuecomment-1427506877)

**Comment by Bolter12** [comment]
Sorry for all this trouble. Don't know what the problem was, I downloaded
yor new cumination zip from your github and all works fine now.
