### ISSUE TITLE
Chaturbate categories give error message

### ISSUE THREAD

**Issue by scorsese50** [dobbelina/repository.dobbelina#1064]
Cannot access categories. Getting cumination error.

**Comment by ErosVece** [comment]
You mean tags? No problem here.

Did you read the text that shows when you choose Bug Report, creating an issue?

### Bug reports:

Please replace this line with a brief summary of your issue 

### OS environment
What OS, Device, version etc

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.

**Comment by scorsese50** [comment]
Nvidua Shield Kodi 19.3

**Comment by ErosVece** [comment]
Without debug log I can't do anything, but someone else posted the same.
It will be fixed in the next update: https://github.com/dobbelina/repository.dobbelina/commit/d23020355cb5838a06c7e6b58dfe068e06e5bf9c
