### ISSUE TITLE
Chaturbate Issue With Tags

### ISSUE THREAD

**Issue by losthelp815** [dobbelina/repository.dobbelina#1065]
### Bug reports:

Tags-Female not able to go into category error given provided below. All other tags seem to work fine.

Windows 7 Pro PC
Kodi 19.4 Matrix
Latest Version Of Cumination 1.1.78

https://paste.kodi.tv/oxosisefih

**Comment by ErosVece** [comment]
Fixed in the next update: https://github.com/dobbelina/repository.dobbelina/commit/d23020355cb5838a06c7e6b58dfe068e06e5bf9c
