### ISSUE TITLE
👋Chaturbate site tags dead✔️.

### ISSUE THREAD

**Issue by victore447** [dobbelina/repository.dobbelina#1068]
🖐️ **Hello**, For several weeks 
The Chaturbate site tags no longer work.![46](https://github.com/dobbelina/repository.dobbelina/assets/48101775/4d118445-7c7d-4965-a230-5b63e99f7e5c)
![Tag Chaturbate HS](https://github.com/dobbelina/repository.dobbelina/assets/48101775/4ab76a4b-d5c9-4c5b-bac9-d105bc67d259)

**Thank you for the answer**✔️

**Comment by ErosVece** [comment]
Where's the debug log we ask for when submitting an bug/issue?
Maybe it's hidden underneath that gif emoticon? 🙄  🤣 

So, please provide a debug log, or at least tell us what device, Kodi version and Cumination version.

Btw, it works fine here :)

**Comment by victore447** [comment]
![208](https://github.com/dobbelina/repository.dobbelina/assets/48101775/6e8f912d-602e-49a0-960d-8f2668a67c5a) **I have no debug log.**

👆But Kodi version is 20.1 and Cumination version is 1.1.78 and have this source Repository 👉https://dobbelina.github.io/ via Kodi file manager.
 Finally when I empty the local cache and delete all plugin cookies, there the Tags-Female folder opens half the time.

☝️**Strangely** the "Tags-Transsexual" & "Tags-Couple" folders work perfectly every time.✔️
