### ISSUE TITLE
mrdeepfakes custom site

### ISSUE THREAD

**Issue by Beladeep** [dobbelina/repository.dobbelina#1070]
Deepfake

https://github.com/dobbelina/repository.dobbelina/blob/3c61f2b8cfa68751289779184f41b20dda70b89c/plugin.video.cumination/resources/lib/sites/tabootube.py
Tabootube seems to be using the same CMS, I see that the regex for the videos needs a few small tweaks....maybe there is more

From:
`match = re.compile(r'class="item item-\d+\s*?">\s+<a href="https://www\.tabootube\.xxx/([^"]+)" title="([^"]+)".*?data-original="([^"]+)".*?duration">([^<]+)<', re.DOTALL | re.IGNORECASE).findall(listhtml)`

To:
`match = re.compile(r'class="item\s*?">\s+<a href="https://mrdeepfakes\.com/([^"]+)" title="([^"]+)".*?data-original="([^"]+)".*?duration">([^<]+)<', re.DOTALL | re.IGNORECASE).findall(listhtml)`

_Originally posted by @ErosVece in https://github.com/dobbelina/repository.dobbelina/issues/1067#issuecomment-1575749079_

**Comment by Beladeep** [comment]
Dear ErosVece

Thank you for your good advice.
I'm not a programmer, but I managed to make the mrdeepfakes costum page.
It works nicely.
Unfortunately, there is one mistake.
The search is not working.
Can you help with this?

Thank you verry match

custom-mrdeepfakes.zip](https://github.com/dobbelina/repository.dobbelina/files/11704365/custom-mrdeepfakes.zip)

**Comment by Beladeep** [comment]
It works!!!! 😊☺️😊
Thanks Master
You are the best

**Comment by Beladeep** [comment]
![243220050-c9a7a06e-b2c6-408b-a6a6-10db54ca5ca5](https://github.com/dobbelina/repository.dobbelina/assets/132296655/1ee3a587-44e0-4ea2-870f-8be03d59ce47)

I'm really looking forward to this work of yours. I wish you much perseverance in your development. Thank you especially for being so helpful.

I wish you all the best

**Comment by ErosVece** [comment]
I wanted to have for that something like a Regex tester, or where you can play with Regex. It could also be like a standalone script.
So I tried to make something like that.

You can fill in the regex from a Cumination plugin, or make one yourself (it maybe will have some sort of snippet system with commonly used patterns for matches).
You can put in an url to download, or you paste the html (from view source in your browser) yourself in the textbox.
You click on Test, and it shows on the bottom the matches it found. Click on one and it goes to that match, you'll see the matched parts colored (colors can be random, or pre set...). That what shows on the bottom, is how it is used by Cumination.

![image](https://github.com/dobbelina/repository.dobbelina/assets/37535332/405aa91c-d074-4bd7-8873-1462a9e7a24a)

**Comment by dobbelina** [comment]
Added to [custom sites](https://dobbelina.github.io/custom.html)

**Comment by Beladeep** [comment]
> For the search, it needs a different AJAX url added. Or I think it's that, it was the case for someone else I helped :)
> 
> `searchUrl = searchUrl + title + '?mode=async&function=get_block&block_id=list_videos_videos_list_search_result&category_ids=&sort_by=&from_videos=01'` try this :)
> 
> How I got this:
> 
> * Use Fiddler or press F12 in Chrome (go to Network tab, click on Fetch/XHR to only filter the ajax stuff etc)
> * Now go to the site
> * Search for something (anal)
> * In the search results press on Next page or Page 2
> * Now it does an ajax call, and you can see the url it's using in the Developers window.
> * In this case it's this: `https://mrdeepfakes.com/search/anal?mode=async&function=get_block&block_id=list_videos_videos_list_search_result&q=anal&category_ids=&sort_by=&from_videos=02&from_albums=02&_=1686302042678`
> * I copy that, and paste it in the address bar of the browser, and it shows what it fetches.
> * I looked at the ajax part, and saw it had a few arguments like q=anal, from_albums=02, the _=16863.
> * They seemed not needed to me, so I remove them, and try that link again in the browser....no difference :)
> * Now I just grab the ajax part, change the from_videos to 01, and use that in the Search function
> 
> Here a screenshot of Chrome with F12, I marked the Network and Fetch/XHR red :)
> 
> ![image](https://user-images.githubusercontent.com/37535332/244650373-0bd9a6ee-46b6-491a-9c96-492eacda9fbd.png)

Dear @ErosVece 

There have been some changes to the website in the last few days.
Since then there is no next page in the search results.
I tried to find out what the problem is, but unfortunately I couldn't fix it.
Would you be so kind as to have a look, you should be able to fix it.
thx

**Comment by ErosVece** [comment]
@Beladeep 
Change next page lines to this

```
    np = re.compile(r'class="next">.*?sort_by:[^;]*?;from[^\d]+(\d+)"', re.DOTALL | re.IGNORECASE).search(listhtml)
    if np:
        np = np.group(1)
        nextp = url
        for p in ['from', 'from_videos']:
            nextp = nextp.replace('{}={}'.format(p, str(page)), '{}={}'.format(p, np))
        site.add_dir('Next Page ({})'.format(np), nextp, 'List', site.img_next, page=np)
 ```

**Comment by Beladeep** [comment]
Dear @ErosVece 

Thank you for your fast and excellent work.
I am always amazed at your knowledge.

Perhaps you know of a video or tutorial explaining how to make such a repair?
Maybe how to program a complete site?
Thanks for any advice.

**Comment by mywayorhighway0** [comment]
@Beladeep

Master @ErosVece explained it clearly. However, the fix is attached now,  To check the "next" tab while performing search, u need to use "Context" menu ( Long Press to pull up Context Menu) . Cheers !
[custom-mrdeepfakes.zip](https://github.com/dobbelina/repository.dobbelina/files/11949978/custom-mrdeepfakes.zip)

**Comment by ErosVece** [comment]
> Dear @ErosVece
> 
> Thank you for your fast and excellent work. I am always amazed at your knowledge.
> 
> Perhaps you know of a video or tutorial explaining how to make such a repair? Maybe how to program a complete site? Thanks for any advice.

It was not really difficult. I just looked at the results page of a search. Saw that it's using `from_videos` instead `from`. And changed the regex and other code for that.
I like Regex Buddy to work on regex's

**Comment by Beladeep** [comment]
Unfortunately the site has changed something again... 
Could someone please take a look and fix the problem.
Thanks
[custom-mrdeepfakes .zip](https://github.com/dobbelina/repository.dobbelina/files/13773213/custom-mrdeepfakes.zip)
