### ISSUE TITLE
Xhamster

### ISSUE THREAD

**Issue by Airwolf1978** [dobbelina/repository.dobbelina#1074]
Apologies if this is not the right format, I don't even know what python is.

When you search on Xhamster and set it to 40+ minutes it will only show the first page every time you click next page (This only happens with the search function)

Hope this helps you with your wonderful work

**Comment by Tyke101** [comment]
I can confirm this.  I reported it a few months ago but it was closed without resolution as I probably didn’t explain the problem properly.
When searching 40 minutes plus you get a page of 48 containing videos of less than 40 minutes followed by a page of 48 videos of 40 minutes and over.  These two pages repeat ad infinitum.

If it’s of any relevance I’m using Nvidia Shield, Cumination 1.1.78 and Kodi 20.1.

**Comment by Airwolf1978** [comment]
Bingo

**Comment by Airwolf1978** [comment]
Just looked at the code and in my professional opinion those are some nice colours 😁

Thanks

**Comment by ErosVece** [comment]
Must be a great profession....just looking at colors and say if it's nice or not 🤣
