### ISSUE TITLE
Xhamster next page infinite loop

### ISSUE THREAD

**Issue by Lucky-rain** [dobbelina/repository.dobbelina#1075]
### Bug reports:

When you search on Xhamster and Change the image quality or time duration it will only show the first page every time you click next page(This only happens with the search function). Oh and also being that I’m using OS 12 on my android box it will be impossible for me to manually change or replace any .py files. 

### OS environment
What OS, Device, version etc:
Box W2 with Android 12.0.0 API level 30, kernel: Linux ARM 32-bit version 5.4.125

https://paste.kodi.tv/raqunuyiko

Any bugreports without logfile will be deleted.

**Comment by ErosVece** [comment]
https://github.com/dobbelina/repository.dobbelina/issues/1074

**Comment by Lucky-rain** [comment]
@ErosVece #1074 wasn’t fixed because the issue is still there even with using the fixes.

**Comment by ErosVece** [comment]
I just tested it, and it works fine here with #1074 applied.

Maybe it's an Android thing, I can test later on my phone.

**Comment by ErosVece** [comment]
I just checked it, and no problems here with the #1074 fix.


https://github.com/dobbelina/repository.dobbelina/assets/37535332/0325143c-3b62-4ed2-8119-6f7be04bd31b

**Comment by Lucky-rain** [comment]
This is from my android box with the #1074 fix. 

https://github.com/dobbelina/repository.dobbelina/assets/136459954/6f272e77-03db-47b0-a576-61f5a322fc54

**Comment by ErosVece** [comment]
Okay, I see yes.

 Not that I don't believe you, but you said before it was impossible to change the .py files on your Android 12 box.
You managed to figure that out?
That fix isn't in the normal official release yet.

I'll see what it does on my Android phone.
Do you have a pc/laptop to test it with?

Also, not to hate on your device, but is it always that slow? Or is it because it's screen recording or something?
Going back to the search keywords and then back to African. That should almost be instant (because it's cached), or like when you open the quality selector dialog.

**Comment by ErosVece** [comment]
I tried it also on my Xbox Series X, and yes....so slow. It also doesnt support some stuff (can't remember what), so some sites didn't work.
Maybe you can install Coreelec on your android box with 9 (but it will remove everything you have on there).

**Comment by Lucky-rain** [comment]
I tried that with the is 9 box being that’s it’s not rooted and can’t be I can’t install it on there. I wish I could.

**Comment by ErosVece** [comment]
What box is it?

**Comment by Lucky-rain** [comment]
Ematic 4K Ultra HD Android TV Box with Built-in Chromecast + Netflix. Dual-Band Wi-fi (802.11AC) Model: AGT419

**Comment by ErosVece** [comment]
Ah, probably locked bootloader I see.

**Comment by Lucky-rain** [comment]
Yes it is. I maybe can install it on my new box but idk if I would lose my remote. I know the bootloader can be unlocked and it rooted. 
Android 12 TV Box 4GB RAM 64GB ROM W2 Mali-G31 Smart Set Top Box.

**Comment by ErosVece** [comment]
Oh, no. Coreelec is all you have then. It's Kodi + OS.
So you can't install anything, but maybe someone has made an addon for your anime app :)

**Comment by Lucky-rain** [comment]
😤😤 ok
