### ISSUE TITLE
Favorites in the sky

### ISSUE THREAD

**Issue by Fetterbr61** [dobbelina/repository.dobbelina#1076]
Hi. I have a request.
I use cumination on several devices and would love if it was posible to choose a favorite place in the sky like dropbox for instance to save the link. So you can see your favorites on all devices.
Thanks Finn

**Comment by ErosVece** [comment]
You can set a custom destination folder for the favorites, maybe you can point it to a folder, that gets monitored by your cloud app?

**Comment by TarkusLV** [comment]
I personally use Syncthing to sync mine with other devices.  Kind of my own personal cloud.
