### ISSUE TITLE
Chaturbate

### ISSUE THREAD

**Issue by Ionic-Iconic** [dobbelina/repository.dobbelina#1077]
Hi I’m not savvy enough to know how to get error logs but I’ve noticed Chaturbate doesn’t work with kodi on androidtv with vpn enabled. Works fine on android phones with same vpn however?

**Comment by 12asdfg12** [comment]
Most likely, when you connect via vpn, the website displays a captcha, which prevents the add-on from working.

**Comment by Ionic-Iconic** [comment]
Thanks.is there a work around for this whilst using a VPN?
