### ISSUE TITLE
Porntrex feature to optionally hide Private videos

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#108]
Displaying all private videos in Porntrex can be inconvenient to those without an account on Porntrex.  The site is cluttered enough without inaccessible files being displayed.
Experimenting with adding a Settings option to Enable/Disable Porntrex account. Default would be Disable which would hide all Private videos from listing.

**Comment by dobbelina** [comment]
Good idea.
Kinda annoying if you don't have an account.

**Comment by jdoedev123** [comment]
Here are the modified porntrex with the settings files in a zip

[porntrex.with.support.19.10.11.zip](https://github.com/dobbelina/repository.dobbelina/files/3748793/porntrex.with.support.19.10.11.zip)
.
File                                Directory
----------------------------------------------------------------------------------------------------
settings.xml                 plugin.video.uwc/resource
strings.xml                   plugin.video.uwc/resources/language/english
porntrex.py                  plugin.video.uwc/resources/lib/sites

**Comment by dobbelina** [comment]
Awesome!

Thanks, will incorporate in the next update.
