### ISSUE TITLE
Erogarga

### ISSUE THREAD

**Issue by Ariesun24** [dobbelina/repository.dobbelina#1080]
### Bug reports:

Latest videos work ok but older videos don't load

### Windows 10

New logfile: https://paste.kodi.tv/ehunamofot

**Comment by Ariesun24** [comment]
Ok, I understand that all older videos were removed too.

**Comment by 12asdfg12** [comment]
fixed [8b019fb](https://github.com/dobbelina/repository.dobbelina/commit/8b019fb426f69c544bb30497ff876a32da2f5b60)
