### ISSUE TITLE
Spankbang

### ISSUE THREAD

**Issue by Ariesun24** [dobbelina/repository.dobbelina#1081]
### Bug reports:

Spankbang does'nt work

### Windows 10

Logfile: https://paste.kodi.tv/pigafaluce

**Comment by ErosVece** [comment]
Read here: https://github.com/dobbelina/repository.dobbelina/issues/984

**Comment by Ariesun24** [comment]
Thanks ErosVece for the explanation, I guess Spankbang should disappear from Cummination one day, right?

**Comment by ErosVece** [comment]
No, because for us it works fine.
Rule34video was also a site that had the same thing, for me it didn't work, but for others it did.
Eventually it started to work for me again.

**Comment by Ariesun24** [comment]
Ok

**Comment by Spanktacular** [comment]
> Read here: #984

https://scrapeops.io/web-scraping-playbook/how-to-bypass-cloudflare/
