### ISSUE TITLE
Site Issue

### ISSUE THREAD

**Issue by HMA00** [dobbelina/repository.dobbelina#1082]
### Bug reports:

Speedporn site is empty no videos is in the lists 

### eOS environment
What OS, Device, version etc

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.

**Comment by ErosVece** [comment]
Yeah, site is down or something....maybe it comes back, maybe not and we'll remove it.
Content on there was almost identical to Netflixporno.

**Comment by ErosVece** [comment]
It looks like Speedporn is back again.
