### ISSUE TITLE
Please, add They are huge

### ISSUE THREAD

**Issue by Ariesun24** [dobbelina/repository.dobbelina#1083]
Site: https://www.theyarehuge.com/

DMCA: https://www.theyarehuge.com/dmca/

**Comment by ErosVece** [comment]
It's added: https://github.com/dobbelina/repository.dobbelina/commit/ab9e2579ba1daff43dd1a4e07a68d363e02db9ba

But for the 720p videos you need to be logged in, I think I'll add that later.

**Comment by Ariesun24** [comment]
Thank You Erosvece!!! Can You see what's happening with Erogarga on Cumination?
