### ISSUE TITLE
Xhamster search broken

### ISSUE THREAD

**Issue by mywayorhighway0** [dobbelina/repository.dobbelina#1085]
Hello Goodz peoplz.

Looks like xHamster search is not working example i just search for Gator or Vintage for 40+ and nothing or just 1 or 2 results available. Website has 20 pages individually for individual search. No log can b given bcoz system does not think it as bug :-).

Can ya fix it..thx

**Comment by 12asdfg12** [comment]
No problem here:

Vintage, 40+ min, 20 pages:
![image](https://github.com/dobbelina/repository.dobbelina/assets/48175015/603e45df-a9c2-4993-9323-d12e783f2ae6)

Gator, 40+ min, 11 pages:
![image](https://github.com/dobbelina/repository.dobbelina/assets/48175015/a4d33ed5-e4e1-422a-88f1-ccbbd1cf4cbc)

**Comment by mywayorhighway0** [comment]
Strange...can you try same search again but 720p as selection my friend? Also plz try ' retro is the best" with 40+ and 720p ..it you get any result then i will have to reinstall. Thx again

**Comment by 12asdfg12** [comment]
Retro is the best, 40+ and 720p:
![image](https://github.com/dobbelina/repository.dobbelina/assets/48175015/b5b9fb13-13ac-4e0a-ad8c-9dcd10b2adbb)

Gator, 40+ and 720p:
![image](https://github.com/dobbelina/repository.dobbelina/assets/48175015/3d24a673-55c5-47a1-8690-693a9dd7f758)

Retro, 40+ and 720p:
![image](https://github.com/dobbelina/repository.dobbelina/assets/48175015/65a6ed68-4e41-48e5-b6c5-3016748cf700)

**Comment by mywayorhighway0** [comment]
Thank you my friend. After, the new update, all is well.
