### ISSUE TITLE
Beginning with cumination - more questions

### ISSUE THREAD

**Issue by Budgie2** [dobbelina/repository.dobbelina#1086]
Using Kodi (osmc) on vero4k I have been able to get Real-Debrid working fine but of the two debrid sites you suggested, NaughtyBlog and SeaPorn only NaughtyBlog works and then when offered, K2S often stops working after a few minutes and Rapidgator fails to resolve.

I read from reddit that k2s is not supported on RD so that might explain my problem.

Are ther better Debrid sites I can try to get a better response as the NaughtyBlog has good titles, but not all work as I explained.
 
If I try a k2s premium subscription as a trial, will it work in the same way as RD to get it working or are there different requirements or apps to install please?

**Comment by ErosVece** [comment]
Naughtyblog and Seaporn have both K2S and RG links (like 98% of the time).
With Real-Debrid you should be able to play the RG links.
I just tested a few links from the first page, and they worked.

That it plays K2S for a short while, means it's using the k2s resolver, and that plays only a preview.

Make sure RD is proper set up in Resolveurl, with a priority below 100:
![image](https://github.com/dobbelina/repository.dobbelina/assets/37535332/92b7baae-196c-43f0-9a6e-9a44088786f3)

Also, maybe you can provide a debug log, use this guide, the Kodi Log Uploader one. Note, turning debug log on can also be done from Cumination settings.
https://cinemavision.tv/guides/kodi-entertainment-center/how-to-create-and-upload-logs/

Just to be sure, go to Naughtyblog or Seaporn, pick a new video, and copy from there the Rapidgator link.
Now go to Real-Debrid, log in, and paste that link in that Downloads textbox. And Convert.
That should work.

A debrid service that supports K2S is Boxbit. But it has a 5GB day limit. Resolveurl has support for it.
But, Resolveurl doesn't have support for the K2S Premium Subscription. If you donate one, I can add it 🤣

**Comment by ErosVece** [comment]
If you can play a rapidgator link, you're good.

About all the other stuff.
Sites like Seaporn are offering downloads for new releases, and often a studio send a DMCA to have the images or videos removed.

Having the same resolution does not mean that the filesize is the same. Rapidgator serves the original file. But some are video streaming services, they re-encode the video, give it a lower bitrate....stuff like that. That's why there is a size difference.

**Comment by ErosVece** [comment]
Ow, and about that logfile, 24mb!?
Can you zip it, using 7zip or something,  it's only text, so it would compress to a lot smaller.

**Comment by Budgie2** [comment]
Hi,
Kodi.zip 959.7KiB.  Better for transmission but not for checking the results.  What should I look for in the logs?  Reluctant to waste your time now as system seems to be working, it is just the content that is missing.

If many files cannot be resolved by rapidgator and k2s seems to have a bigger library, is it worth getting a short subscription for test purposes?
B.

**Comment by ErosVece** [comment]
That is why I want to see the log, you can drop that zip file here.
What is a rapidgator video that didn't work?

**Comment by dobbelina** [comment]
No reply, closing thread.
