### ISSUE TITLE
Please, add hqpornero.com

### ISSUE THREAD

**Issue by Akkari1988** [dobbelina/repository.dobbelina#1087]
Please, add https://hqpornero.com/
DMCA pages: https://hqpornero.com/contact-us.html

**Comment by ErosVece** [comment]
I looked at the first video, and they 'borrow' the source from HQPorner. But at the lowest quality.
So why a knockoff, when we have the original in Cumination :)

**Comment by Akkari1988** [comment]
they have same videos but categorized better than hqporner :)
