### ISSUE TITLE
Reuest Feature “Go to page xxx”

### ISSUE THREAD

**Issue by jerry2002mg** [dobbelina/repository.dobbelina#1091]
After using the search function on all sites I have several pages with results but no function to go to specific site of the results.

It would be glad to have a function “Go to” and as second argument: First page, last page and “number” of page with possibility to put in a number of choice.

**Comment by ErosVece** [comment]
Some sites have that function already, that you can find in the contextmenu of the Next page item.
https://github.com/search?q=repo%3Adobbelina%2Frepository.dobbelina%20Gotopage&type=code
