### ISSUE TITLE
[Feature Request, maybe bug] Move or Rename Keyword (for Jav in this case)

### ISSUE THREAD

**Issue by DaisyF8** [dobbelina/repository.dobbelina#1093]
(maybe I found a bug, read 2. below)

 Jav-releases start with letters (studio) followed by dash and numbers (release), so for example "oae-123".  

For following jav-releases of for example studio OAE I create a keyword search in for example site HPjav for "oae-". This gives me a keyword "oae-" which works best while executed in the search-section of HPjav.  But I also have other jav keywords for other jav sites.  And each search is mostly specific to a certain site, ie "oae-" works well in HPjav but not so well in another site.

So now, when I have multiple searches like this over multiple sites, I have all these keywords and need to remember which site a specific keyword like "oae-" belongs to...

Proposal : Being able to rename a keyword. I would choose for this example to rename to "HPjav oae-" : oae- is to be searched in HPJav.

Best scenario : Move the keyword to a custom group (and rename).  
So I would 
1. make the keyword "oae-" while in the site "HPjav". 
Then I would 
2. long-press "Add item to" the custom group "jav-searches".  (**As of now this doesn't work**, tell me if I'm wrong.  The link/shortcut "oae-" you create in the custom group only sends you to the search-section in HPjav, **it doesn't do the search itself**. Is this a bug ? I read [here](https://github.com/dobbelina/repository.dobbelina/issues/906#issuecomment-1335421530) it should be possible).  "Add item to" does rename the "oae-" keyword to "HPjav - oae-" which is nice as a reminder.
3. I would then delete the keyword "oae-" in the search-section of "HPjav" because I have it in the custom group.

**Comment by ErosVece** [comment]
@DaisyF8 this should do it: https://github.com/dobbelina/repository.dobbelina/commit/181976a10df64b73bcd1aed4c8346bfd37172129

**Comment by DaisyF8** [comment]
Thanks so much @ErosVece for having a look.  I will look at the fix when I see 1.1.80 appear.

And I'll give some feedback about "This site only" and "add keyword to this site" too.  I looked in the context-menu but haven't found these options yet.

**Comment by ErosVece** [comment]
That was a suggestion, an alternative option, that needs to be added. It isn't in Cumination.
