### ISSUE TITLE
Change Paradise hill to have front cover

### ISSUE THREAD

**Issue by marshall76963** [dobbelina/repository.dobbelina#11]
Small change to get front cover rather than thumbnails (if you want).

paradisehill.py

line 44: change to:

`match = re.compile(r'Movie">.+?<a href="([^"]+)".+?<span itemprop="name">(.+?)</span.?</div>.+?</span>.+?<img src="(.+?)"', re.DOTALL | re.IGNORECASE).findall(listhtml)`

**Comment by jdoedev123** [comment]
Thanks

**Comment by dobbelina** [comment]
Thanks.
Will add the change next time i update the addon.
