### ISSUE TITLE
Suggestion for the webcam area

### ISSUE THREAD

**Issue by psyco752** [dobbelina/repository.dobbelina#110]
Could you add the personal log in for example in chaturbate to see the cameras you follow? As the web version has, it would be fine since it is annoying to search many times, I hope an answer thanks.

**Comment by DJMix-I-Can** [comment]
You really don't need it.  When you find a cammer you want to save, long press or right click (if you're on windows) to open the context menu. Select "Add To Favorites" [https://imgur.com/qoCPNml](url)
When you enter UWC, there's a folder called favorites.  It's saved in there. [https://imgur.com/UCnVEHz](url)
This is my favorites folder [https://imgur.com/6aMbp7t](url)
You could save anything from UWC in there. You have a favorite video from Pornhub? Add it to favorites and it will be there. You won't have to search for it again. The only time it won't work is if it was removed from Pornhub or if the Pornhub coding changes and the link doesn't work.
I have a backup folder in my download folder for backing up my favorites. Go to UWC settings, favorites and keywords and backup favorites and keywords. If your Kodi ever crashes, you could restore these and won't have to search for the cammers again. Hope that helps.

**Comment by psyco752** [comment]
Friend thanks for this, in my case I use it on an android tv but kodi works fine to do it as you explained I had no idea, now I have also backed up if in the future it is necessary to restore, thanks again for the help .

**Comment by DJMix-I-Can** [comment]
Your welcome, one last mention. I also go to android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.uwc/ and save that favorites.db file. Don't move it, copy it and save it in your backup folder. That's an extra precaution in case re-importing your favorites gives you problems. You could just re copy it back in there to have your favorites back.
