### ISSUE TITLE
[Crash] 1.1.80 broke compatibility with older Kodi versions again (probably python 2.7 issue)

### ISSUE THREAD

**Issue by notimp** [dobbelina/repository.dobbelina#1100]
Here is a log, looks like the culprit is found in the favourites.py module.

![Bildschirmfoto 2023-06-25 um 17 12 14](https://github.com/dobbelina/repository.dobbelina/assets/47777453/70ba3852-0097-4875-ae8b-4f13e7395422)

It crashes parsing the first folder I have in favourites.

Kodi used was 18.1

**Comment by ErosVece** [comment]
https://github.com/dobbelina/repository.dobbelina/commit/8e668ee8eb32f62b71a9076f9f39857791631c3e

Thanks for being a valuable tester 😉

**Comment by notimp** [comment]
hrhr I dont know where I get the motivation from ;)

(seems to be fixed already, looking at the changelog, also can confirm, that it was just the favourites.py, replaced the 1.1.80 one with the 79 one on my end and the plugin loads right up again.)
