### ISSUE TITLE
Jump to page on search listings

### ISSUE THREAD

**Issue by mindisdk** [dobbelina/repository.dobbelina#1101]
**Is your feature request related to a problem? Please describe.**

I often end up using the "one time search" option, and sometimes my prompt returns nearly 2000 pages. But there is no way to jump to fx page 80 if that's where i left off, which leaves you having to push the "next page" button at the end of each page.

**Describe the solution you'd like**

It would be very nice with an option to "jump to page" by inputting the desired page number for a given search prompt. I can't be the only one who tends to be completionistic when they find a prompt that sings xD

**If it's a site addition request, add url below**
Sites with no DMCA information will not be added

**Comment by ErosVece** [comment]
Another option is, when you're done wanking, open the contextmenu for Next Page (80).
Click on 'Add Item To', and add it to main menu, or make a new custom list.
Now, if you go to the main menu, you should see an item for the site search you just added.
Click on it, and you go straight to the search results, page 80.

It doesn't work with every site though, for example Porntrex it doesn't work.

I'll look into it to add Go To Page in the Cumination base code.

**Comment by mindisdk** [comment]
Ah, appreciate it. I don't seem to be able to bring up a context menu at all, but maybe it's because I'm using Kodi on my Nvidia Shield and the remote broke, so I'm using my regular TV remote to navigate. This means some of the button functions are missing (fx also cannot bring up recent apps screen to close apps running in background). This could be the issue.

**Comment by ErosVece** [comment]
Try long press on the button you use to enter/play an item.

Or use the Keymap Editor (https://kodi.wiki/view/Add-on:Keymap_Editor) to give some keys a function.
Like I have mapped the 1 and 3 buttons on my tv's remote for Subtitle sync forward/backward.
Or the 0 in Video/Music library, to remove the item.

**Comment by mindisdk** [comment]
Thank you very much, I tried the 'add item to', but seems it also doesn't work with Txxx or Hclips. But now at least I know how to on the supported sites, thanks a lot.

**Comment by ErosVece** [comment]
txxx and hclips are the same code, all from that network of sites.

Sites that have the listing like this in their file:
```
@site.register()
def List(url, page=1):
```

so with , page=, won't work
