### ISSUE TITLE
homemoviestube, peekvids issues

### ISSUE THREAD

**Issue by toaster345** [dobbelina/repository.dobbelina#1103]
homemoviestube: videos will no longer load (but was working a couple of days ago)
peekvids: After a few pages of navigation (any category), no videos will load (just says not found). Has been an issue for months but I guess nobody has reported it.

Thanks.

**Comment by ErosVece** [comment]
Here is homemoviestube fix: https://github.com/dobbelina/repository.dobbelina/commit/923de5043b7bcc77599025696c0112b468c0f563

Peekvids has a rate limit thing against bots. And visiting the site with Kodi triggers it (for me).
Can you provide a debug log, so I can check you have the same?

**Comment by toaster345** [comment]
No log for peekvids yet, sorry.

But I've noticed the 'download video' option for homemovies tube has stopped working in Kodi ("Download Failed. No response from server.")
