### ISSUE TITLE
Hanime site issues (playback, login/logout)

### ISSUE THREAD

**Issue by dootsie5times** [dobbelina/repository.dobbelina#1109]
Corelec 19.5 on Odroid N2+

After your last fix, 2 issues appeared.

1) Initially, login is listed.  I log in, then logout is listed, I log out and logout is still listed (it does not change back to login)

2) The fix (after logged in) plays the new videos fine; however, when logged in, the older videos do not play at all.  I am attaching log file. "Playback Failed"

[kodi.log](https://github.com/dobbelina/repository.dobbelina/files/11995837/kodi.log)

**Comment by ErosVece** [comment]
1. If you go back to the main menu with all the sites, and then back to Hanime. You'll see that Logout became Login. I'll add a Container Refresh so it updates the listitems.

What older video did you try?
Looking at the (NON DEBUG 🤣 ) log file, I see it tries to play a m3u8.
That only happens when they don't have a Members only video for it.
I can't help that.
So, what video did you try? So I can check myself.

**Comment by dootsie5times** [comment]
Eroriman 2
Harem Cult 1
Girls Rush 1

**Comment by mortael** [comment]
When logged in, Eroriman 2 and Harem Cult 1 plays here with the mp4 (1080p file).

**Comment by dootsie5times** [comment]
Cleared log file, rebooted.
Not logged in, played Harem Cult 1, played fine.
Then logged in and tried to play it again, Playback Failed.
Log attached.

BTW, could you move the option to enable the debug thing to it's own page/tab so it's easier to find?

[kodi.log](https://github.com/dobbelina/repository.dobbelina/files/11996046/kodi.log)

**Comment by ErosVece** [comment]
Can you try this?
https://github.com/dobbelina/repository.dobbelina/commit/914b5e6e85ef71ee2e379716d9bfe807e330c340

**Comment by dootsie5times** [comment]
That patch fixed the issue.   Now logged in, the older and newer files play correctly.
Playing the older files is a little slower, but it works.

**Comment by ErosVece** [comment]
Good, closing it now.

**Comment by dootsie5times** [comment]
So if you are logged in and the file does not exist on gofile thing, it fails to play.  But if you log out, the file will play.  Is there any way to code in a check so when you are logged in and it tries to play the mp4, but the mp4 does not exist, to fall back to playing the file the way it does when you are logged out?  That should be a total fix for all the playing issues.
