### ISSUE TITLE
Feature request : Download in the background

### ISSUE THREAD

**Issue by DaisyF8** [dobbelina/repository.dobbelina#111]
Sorry if this has been asked before.  Didn't find it in previous issues, and I feel it differs from "Download Tip for Windows Users"

I was just wondering if this would be possible to implement.  Just so that you can start a download and don't need to wait for the download to finish before you can do anything else.

Thx

**Comment by dobbelina** [comment]
Sorry for replying so late.
I don't thinks it's straight forward to implement it.
Those other add-ons i've seen that has this functionality, usually pass the download to another addon such as youtube-dl control.
One would then have to add that as a depedency.
Also not sure how well that would work considering the wide array of hosters
that are present in UWC.

**Comment by DaisyF8** [comment]
I see... Yeah, it would open a can of worms.

Thanks for getting back to me :)
