### ISSUE TITLE
Perverzija not working

### ISSUE THREAD

**Issue by Napster955** [dobbelina/repository.dobbelina#1111]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**If it's a site addition request, add url below**
Sites with no DMCA information will not be added

**Comment by ErosVece** [comment]
It works fine here....

But, Malwarebytes popped up with blocking the url, so I added `perverzija.com` to the Allow list, and now it works fine

**Comment by Napster955** [comment]
@ErosVece Thanks.

**Comment by dobbelina** [comment]
Works for me to, closing thread.
