### ISSUE TITLE
Chaturbate Followed Cams Error

### ISSUE THREAD

**Issue by ChoccyStarfish** [dobbelina/repository.dobbelina#1112]
Hi, I'm still having a login error for Chaturbate Followed cams, same error just like last time. I've reinstalled the fresh/latest version (1.1.81), I've also tried clearing cache and cookies etc

Android TV 11, Kodi v20.2, Nvidia Shield TV Pro.

https://paste.kodi.tv/jacaginifo

Would be very grateful if you guys could look into this please, thank you.

**Comment by ErosVece** [comment]
It looks like it now triggers the Cloudflare captcha thing when you go to the Chaturbate login.
This can't be 'solved' using Kodi.

But, I think I have a workaround, but I need to test that more.

**Comment by ChoccyStarfish** [comment]
Hi, If you need me to test anything, please let me know.

**Comment by ReveAnge** [comment]
fixed in v.1.1.82 but now in v.1.1.83 broken again, cant login, every time I tried it says that login/password incorrect

**Comment by ErosVece** [comment]
I messed up somewhere else, that it sends in whole Cumination a wrong cookie. This fixes that:  https://github.com/dobbelina/repository.dobbelina/commit/fb979dd65e0befdf0d23fb1f09972f4d293b20b3

@dobbelina can you release a new version?

**Comment by scorsese50** [comment]
That never worked for me. Cannot get into online favorites in new update.

**Comment by ErosVece** [comment]
1.1.84 is out, where it sends the correct cookies again.

But like I said a month ago, Chaturbate is now using Cloudflare captcha on those login pages.
If you can login, that would be because the cookie (from before) didn't expire yet.
