### ISSUE TITLE
Hanime.tv playback issue when logged in.....Request fix

### ISSUE THREAD

**Issue by dootsie5times** [dobbelina/repository.dobbelina#1114]
If you are logged in and the file does not exist in mp4 format, it fails to play. But if you log out, the file will play. 
I'm requesting a small code update to check if the mp4 exists and if not, to fall back to playing the file the way it does when you are logged out (If - then - else).  That should be a total fix for all the playing issues.

**Comment by ErosVece** [comment]
As before, tell us the title/video that doesn't have the mp4 file. Makes it easier for us.

**Comment by dootsie5times** [comment]
Alright, I'm going to have to try a bunch to find another one.

BTW, there's another problem.  At some point, the addon started a new favorites "hanime.tv" section in addition to the existing hanime.tv one I already had.  All the videos in the older section error out when trying to play them.  The videos in the newer section work like they should.

[kodi.log](https://github.com/dobbelina/repository.dobbelina/files/12053888/kodi.log)

**Comment by dootsie5times** [comment]
Video  "School 2"   no 720 mp4 file

**Comment by ErosVece** [comment]
> 

The function hanime.hanime_play was renamed to hanime.hanime_play_combined.
I'll add the older hanime_play back that redirects to hanime_play_combined, for compatibility with older favorites

**Comment by ErosVece** [comment]
> Video "School 2" no 720 mp4 file

Like I said, I'll see what I can do. For now if you really want to see it, in Cumination settings set it on 'Ask' for video quality. And play 'School 2', and pick the one under 720P.

**Comment by dootsie5times** [comment]
Just remember that it DOES play if you are NOT logged in.

**Comment by ErosVece** [comment]
> Just remember that it DOES play if you are NOT logged in.

I know how it works, I wrote it myself 😉 
Maybe I have some time later today to work on it.
I only need to create a 2nd Hanime account, because my own is Premium member.
So I don't get those videos that are hosted on Gofile or others, just the 1080 from their own servers :)

**Comment by dootsie5times** [comment]
Yeah, that makes testing much harder since the average user will not have a premium account and you have no way to test your fixes yourself.
You'll have to also use a 19.5 version of Kodi to make sure the fixes are backwards compatible.
I'm running 19.5 here (coreelec)

I noticed last night that when logged in I couldn't skip forward through the files I was playing.
After some more testing, skipping forward works for the newer files, but not for the older ones (gofile).  I'm not sure why that is happening.  I don't know that I've ever encountered an issue skipping forward through mp4 files with Kodi.

This whole thing is crazy.  I don't know why they didn't just keep everything consistent on their site.

**Comment by ErosVece** [comment]
Fuck, this took way longer then it should have been, but I think I have it now :)

Check https://github.com/dobbelina/repository.dobbelina/commit/55cc942032eef10c8bd74f80ce80b597c5b5523a

Also, for videos skipping forward with problems, don't think I can do much about it.
What videos did this?

**Comment by dootsie5times** [comment]
Logged In:

Kimi Omou Koi 1               Gofile  No skipping
Anehame: Ore No ... Nai 1 Gofile  No skipping
Otome ...Trinkle Stars 1      Gofile   No skipping
Kime Koi!....Hana 1             Gofile   No skipping

Koihime 2                          Gofile     Skipping works

**Comment by dootsie5times** [comment]
The logout not refreshing to login is still an issue.

**Comment by dootsie5times** [comment]
With your newest fix...  Both these files display [MP4} when they play.

Kimi Omou Koi 1     NO skip
Kimi Omou Koi 2     skip works

**Comment by ErosVece** [comment]
https://github.com/dobbelina/repository.dobbelina/commit/be701baea6c564e6aa5cbed3f0ba2d645d8dff65

This should work for you when you log out...
I also enabled download in the contextmenu when you are logged in, so you can download the mp4 files.

I also tried Kimi Omou 1, and indeed, skipping is off (it does skip, but only a few seconds).
You can try downloading that episode.
Kimi 1 is hosted on Gofile, Kimi 2 is hosted on their CDN.

When I play Kimi 1 from Gofile my Kodi log gets spammed with many lines like this `warning <general>: ActiveAE - large audio sync error: -5433.056867`
So there is something not right with streaming that mp4 from Gofile.

**Comment by dootsie5times** [comment]
Give these a try and see if they all also give you the kodi log spamming.  It's hard to believe that all of them have mp4 file issues, but anything is possible.

Kimi Omou Koi 1 Gofile No skipping
Anehame: Ore No ... Nai 1 Gofile No skipping
Otome ...Trinkle Stars 1 Gofile No skipping
KimeKoi!....Hana 1 Gofile No skipping

**Comment by ErosVece** [comment]
Here they all skip weird, but I think it's Gofile that is the problem.
Logging in with my premium account, I get a mp4 that is hosted on their fast CDN, and that one skips like normal.

I have downloaded the 2, the Gofile and the CDN mp4, and compared them. And they are identical.
So, best solution for you now is get Premium or just download the mp4 using Cumination.

**Comment by dootsie5times** [comment]
If I logout, Kimi Omou Koi 1 skips normally.

**Comment by ErosVece** [comment]
Yeah, that plays through their m3u8 CDN....
Maybe, just maybe....when I feel like it, I'll add an option where you can select between the m3u8 or mp4 when logged in.

**Comment by dootsie5times** [comment]
Well, right now if I want to play the newer stuff which had FF/skip issues bouncing around, I'll just login since they then play fine (as long as the mp4 exists).  Otherwise, to play all the older stuff (which is the majority) I'll just logout.

The only problem with selection when logged in is you never know which version of the file will be the best to use until you try to play it and having to select m3u8 or mp4 for each file would get tedious.

Unless you can think of another way to "fix" it, I think I'd just let it alone for now.

I still don't understand why some files on gofile skip fine and others don't since you said you did binary checksums comparing them to CDN server files and they were an exact match.
If that's the case it make absolutely NO sense at all.

**Comment by ErosVece** [comment]
I can also do it like this, add a contextmenu item that only shows when you are logged in.
MP4 is always the default, so the contextmenu item could be 'Play with m3u8'

**Comment by dootsie5times** [comment]
That seems like a good compromise.

**Comment by ErosVece** [comment]
> That seems like a good compromise.

https://github.com/dobbelina/repository.dobbelina/commit/4b79db5cfaae217ccd506856c8acdcf398ab4186

**Comment by dootsie5times** [comment]
Why do you think skipping forward on MP4 files doesn't work, but fast forward does?
Generally, in my experience, they usually go together.

**Comment by ErosVece** [comment]
When trying to skip I see this in the debug log: `CDVDDemuxFFmpeg::SeekTime - input stream reports it is not seekable`
My money is on that that is the problem, and nothing we can do about it.
