### ISSUE TITLE
PornHub Down

### ISSUE THREAD

**Issue by Maggio86** [dobbelina/repository.dobbelina#1115]
### Bug reports:

PornHub has not been working for a couple of days now

### OS environment
Kodi 20.2

**Comment by dobbelina** [comment]
Works for me, you need to provide a log file.

**Comment by Maggio86** [comment]
@dobbelina 

https://paste.kodi.tv/nacizeninu

**Comment by 12asdfg12** [comment]
Apparently age verification has been added in the UK.
The listing is fixed, for playback @Gujal00 needs to add the 'accessAgeDisclaimerUK=1' cookie in SMR.xxx.

**Comment by Gujal00** [comment]
cookie updated in smr.xxx pornhub resolver for UK
