### ISSUE TITLE
Wizzgirl no sound

### ISSUE THREAD

**Issue by BdaCookieMonster** [dobbelina/repository.dobbelina#1118]
No Sound on Wizzgirl cams, all other sites have sound. 

Using Kodi 20.2 and Cumination 1.04 on Nvidia Shield pro

**Comment by 12asdfg12** [comment]
No problem here, maybe you should add a debug log file

![image](https://github.com/dobbelina/repository.dobbelina/assets/48175015/ed6bae53-504c-42cd-9fc1-3f8d1560adb5)

**Comment by BdaCookieMonster** [comment]
https://paste.kodi.tv/xagivihayi

Looking at your screen shot and mine, My Audio stream shows: [Unknown] - AAC - 0 Channels (1/1)

and weird thing like I said is only on WizzGirls, I have sound on every other site

**Comment by 12asdfg12** [comment]
The stream address from your log file (https://b-hls-24.doppiocdn.com/hls/22453663/22453663.m3u8) plays with sound for me, no idea what could be wrong.

You said you have a shield, have you tried the fix from this post?
https://github.com/dobbelina/repository.dobbelina/issues/1038#issuecomment-1558079022

**Comment by BdaCookieMonster** [comment]
Tried the advanced settings post and no help. Guess I will just keep messing with settings and see if I can figure something out. It's really weird cause I have menu sounds in WizzGirl but no sounds from the cams.

**Comment by ErosVece** [comment]
Do you have the 'play m3u8 with Inputstream Adaptive' (or something like that) enabled in Cumination settings?
If so, turn it off, and try it now.

**Comment by BdaCookieMonster** [comment]
All right got it working, not sure what fixed it lol, cleared cookies, reset function cache, clean settings file and unchecked Play m3u8 streams with Inputstream Adaptive.

**Comment by BdaCookieMonster** [comment]
Ok seen post above and yeah I bet it was Inputstream. Turned it off before I seen post, but Thank you
