### ISSUE TITLE
Streammate cams not working

### ISSUE THREAD

**Issue by felsandric** [dobbelina/repository.dobbelina#112]
Just wanted to let you know - None of streammate cams are working - if someone can push update. you guys are awesome. Thanks community...

**Comment by dobbelina** [comment]
Issue confirmed, thanks for reporting.

**Comment by felsandric** [comment]
Pleasure and kindly give me update when it’s fixed🙏

Regards,
Gary

Sent from my iPhone

On Oct 21, 2019, at 12:20 AM, dobbelina <notifications@github.com<mailto:notifications@github.com>> wrote:


Issue confirmed, thanks for reporting.

**Comment by dobbelina** [comment]
Fixed by 12asdfg12 #117

**Comment by felsandric** [comment]
When it add to search fav when you click you get ultimate white cream error on right.

Sent from my iPad

On Oct 30, 2019, at 1:29 AM, dobbelina <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixed by 12asdfg12 #117<https://github.com/dobbelina/repository.dobbelina/pull/117>

**Comment by felsandric** [comment]
Pls if model goes on private it kicks me out of video. Is it normal. So pod cha
 You won’t see cams .. it gives ultimate white cream error on right screen  when model is in private.



Sent from my iPhone

On Oct 31, 2019, at 2:52 PM, dobbelina <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #112<https://github.com/dobbelina/repository.dobbelina/issues/112>.
