### ISSUE TITLE
Filter to remove unwanted keywords

### ISSUE THREAD

**Issue by K3pt81** [dobbelina/repository.dobbelina#1121]
Get a bunch of videos with descriptions that don’t apply to me in the title name. Filter only gives me results based on a keyword. 

Would love to see an option in a filter to add keywords for which the results can ignore for ex: if I don’t want to see videos with the title ‘big’ I should be able to add that in a filter and it can give me a result of videos that do not contain the word ‘big’ in the title.

**Comment by ErosVece** [comment]
Here: https://github.com/dobbelina/repository.dobbelina/commit/7ff64f8b49cb3790b333f7c665a86a8769c902f8

In the new upcoming release you can use it like this, in Settings -> Advanced.
At for example the keywords 'gay;trans', and that would filter out every video item with one of the 2 words in the name/title.

![image](https://github.com/dobbelina/repository.dobbelina/assets/37535332/6593c96e-052e-422b-ae69-bd019ad04a84)
