### ISSUE TITLE
Broken site: javgg

### ISSUE THREAD

**Issue by Foney555** [dobbelina/repository.dobbelina#1123]
### Bug reports:

Listings are okay but no playback links. Will not play

### OS environment
What OS, Device, version etc

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.

**Comment by ErosVece** [comment]
I just tried 3 random links from the first page, and they all played fine (it was using a doooood stream)

**Comment by dobbelina** [comment]
No log file closing.
