### ISSUE TITLE
Tubepornclassic and luxuretv

### ISSUE THREAD

**Issue by robhig1981** [dobbelina/repository.dobbelina#1128]
Tubepornclassic and luxuretv not working

**Comment by dobbelina** [comment]
Tubepornclassic is working for me, Luxuretv is probably not working because of cloudflare #1105
please provide a log file [How to create a log file](https://github.com/dobbelina/repository.dobbelina/issues/968#issuecomment-1427506877)

**Comment by dobbelina** [comment]
No log file closing.
