### ISSUE TITLE
Pleawe add this site : Whereismyporn

### ISSUE THREAD

**Issue by Napster955** [dobbelina/repository.dobbelina#1129]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**If it's a site addition request, add url below**
Sites with no DMCA information will not be added

https://whereismyporn.com/

https://whereismyporn.com/dmca

**Comment by ErosVece** [comment]
https://github.com/dobbelina/repository.dobbelina/commit/5b6a0918b462015abd8423ab90cec61b6d8d0c4e
and https://github.com/dobbelina/repository.dobbelina/commit/0082c5b648e2de9069ea951be7e14f12f9dba459
