### ISSUE TITLE
Herexxx- No 'Next' tab

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#113]
Hi 12asdfg12 and Dobbelina, please note that there is no 'Next' button available during keyword search on this site. This limits the search to just one page. An example would be keyword search for "Subbed" returned with one page but the website on mobile or pc browser displays 21 pages. Kindly fix it.

**Comment by 12asdfg12** [comment]
fixed

**Comment by dobbelina** [comment]
Thanks 12asdfg12!
Fix merged  #114

**Comment by imurreflection** [comment]
Thank you so much friends. Closing the issue now.
