### ISSUE TITLE
navigating library

### ISSUE THREAD

**Issue by JTVesagie** [dobbelina/repository.dobbelina#1131]
hi guys . im fairly new to kodi but my question is regarding navigating the addons . how do you go from page 1 of 100 to say 80 of 100 

Thanks 
Jason

**Comment by dobbelina** [comment]
A few sites have the Goto Page context menu on the Next Page link but not all.
![bild](https://github.com/dobbelina/repository.dobbelina/assets/46063764/aa980a82-41f1-4f96-956a-8831d33b6fff)
