### ISSUE TITLE
Hanime.tv favorites

### ISSUE THREAD

**Issue by dootsie5times** [dobbelina/repository.dobbelina#1133]
Is there any way to merge the 2 favorites lists into a single list?
I have files in one list for example    bubba_1, bubba_3, bubba_4
And in the other (newer) bubba_2
I really want all 4 of those in a single list.  It's a pain to have to look at both lists to find the correct bookmark.

In the db file, what would happen if I did a search and replace in Mode field and changed all hanime play to hanime play combined?
It looks like all newly added bookmarks go to hanime play combined.

**Comment by ErosVece** [comment]
With the latest commits, you can use hanime play again, so you don't need to change that....but, it wouldn't hurt if you edit the database manually.

For your other question, I think you can use sqlite browser to work on the db file (https://sqlitebrowser.org/)

**Comment by dootsie5times** [comment]
It's been a LONG time since I've done Sql work.
I used 2 different set commands, 1 at a time to change every mode to hanime.hanime_play_combined.

I wanted to do it all at once, but my syntax was wrong so I did it in 2 single steps.

What is wrong with the syntax of this multi-change sql query?

update favorites
set mode = replace(mode, 'hanime.hanime_play_combined', 'hanime.hanime_play')
set mode = replace(mode, 'hanime.hanime_play', 'hanime.hanime_play_combined');

I tried commas and different stuff but couldn't get it to work.

It might be nice to post a working sql query for others who may want to do the same thing I did.

**Comment by ErosVece** [comment]
Why would you do that sql?  First setting HPC to HP, and then HP to HPC?

You forgot a comma, and putting it all in SET command:
```
UPDATE favorites
SET 
    mode = REPLACE(mode, 'hanime.hanime_play_combined', 'hanime.hanime_play'),
    mode = REPLACE(mode, 'hanime.hanime_play', 'hanime.hanime_play_combined');
```
but this is useless, you only need that 2nd SET.

Also, you can use Chatgpt to help you with sql.

**Comment by dootsie5times** [comment]
I wasn't sure if hanime.hanime_play string would also match hanime.hanime_play_combined string so I used those 2 commands.
Like I said, it's been decades since I did programming or used SQL.
