### ISSUE TITLE
Please add this site : DrTuber

### ISSUE THREAD

**Issue by Napster955** [dobbelina/repository.dobbelina#1135]
**If it's a site addition request, add url below**

https://m.drtuber.desi/
https://m.drtuber.desi/dmca

Thanks.

**Comment by Napster955** [comment]
@dobbelina when are we getting next update ? With all newly added sites?

**Comment by dobbelina** [comment]
> @dobbelina when are we getting next update ? With all newly added sites?
@Napster955 6 August

**Comment by Napster955** [comment]
Okay Thanks.
