### ISSUE TITLE
Please add new site : fullporner

### ISSUE THREAD

**Issue by Napster955** [dobbelina/repository.dobbelina#1136]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**If it's a site addition request, add url below**
Sites with no DMCA information will not be added

https://fullporner.org/
https://fullporner.org/dmca/

**Comment by ErosVece** [comment]
Here https://github.com/dobbelina/repository.dobbelina/commit/c3924decadd8633fa84e08b368f1b7a229da1994 :)
