### ISSUE TITLE
Hiding Non-Working and Not Used Sites

### ISSUE THREAD

**Issue by lance77tour** [dobbelina/repository.dobbelina#1137]
Hi,

How do I go about removing sites that I do not use or that are not working within the code?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**If it's a site addition request, add url below**
Sites with no DMCA information will not be added

**Comment by 12asdfg12** [comment]
https://github.com/dobbelina/repository.dobbelina/issues/854

**Comment by lance77tour** [comment]
#854 is more like a pain in the butt. Kodi is open source and it is not asking too much understand where in the code to disable the "sites".

**Comment by 12asdfg12** [comment]
If you are not happy  with this solution, you can delete the .py files corresponding to the sites you don't need from the plugin.video.cumination/resources/lib/sites/ folder on your device.
