### ISSUE TITLE
Hentaistream file resolution issue

### ISSUE THREAD

**Issue by dootsie5times** [dobbelina/repository.dobbelina#1139]
No matter what resolution I set in the the main addon for Max Resolution, it always plays the file at 4k.
The only way to avoid this is to set max res to ask.

First, can you change the max res setting to actual numbers like 720 instead of the current HD, etc?
Second, can you do something to fix the posted issue of it always playing at 4k?

Thanks.

**Comment by ErosVece** [comment]
Here https://github.com/dobbelina/repository.dobbelina/commit/02053ae7700ccdee31045a452ae0e709be595e23
I used the main selector, and not the prefquality one.

About FHD to 1080p etc, I don't know...maybe :)

**Comment by dootsie5times** [comment]
I didn't realize that there were 2 selectors.  Where are each located in the addon and which is considered the main and the prefquality one?

I didn't think changing FHD to 1080, etc would be more than a label/text change (search and replace).  The function should remain the same, unless I'm missing something.

**Comment by dootsie5times** [comment]
If I change the setting to UHD in Host and Resolvers or use Ask and select 1080, the audio plays, but the screen is black/blank.  The same result happens if I use 4k.  My TV is not 4k and that is normal for 4k videos, but I'm not sure why it doesn't play/show the 1080 file.
I've never had a 1080 video not play on my setup before.
I'm using an Odroid N2+ box with Corelec 19.5.

**Comment by dootsie5times** [comment]
If I change the setting to UHD in Host and Resolvers or use Ask and select 1080, the audio plays, but the screen is black/blank.  The same result happens if I use 4k.  My TV is not 4k and that is normal for 4k videos, but I'm not sure why it doesn't play/show the 1080 file.  720 plays fine.
I've never had a 1080 video not play on my setup before.
I'm using an Odroid N2+ box with Corelec 19.5.
This is after your latest fix.

**Comment by ErosVece** [comment]
> I didn't realize that there were 2 selectors. Where are each located in the addon and which is considered the main and the prefquality one?

Look at the PR and you see what changed and where it is.
But here is the selector function https://github.com/dobbelina/repository.dobbelina/blob/master/plugin.video.cumination/resources/lib/utils.py#L1198 
And beneath that, is prefquality located https://github.com/dobbelina/repository.dobbelina/blob/master/plugin.video.cumination/resources/lib/utils.py#L1232 , as you can see prefquality is calling selector when you have it set on 'Ask'. And if not, it tries to pick the highest you have set as max quality.

For changing the labels in settings, you need to change it in the 5(?) language files we have, for example https://github.com/dobbelina/repository.dobbelina/blob/master/plugin.video.cumination/resources/language/resource.language.en_gb/strings.po#L287 here

**Comment by ErosVece** [comment]
> If I change the setting to UHD in Host and Resolvers or use Ask and select 1080, the audio plays, but the screen is black/blank. The same result happens if I use 4k. My TV is not 4k and that is normal for 4k videos, but I'm not sure why it doesn't play/show the 1080 file. 720, however, plays fine. I've never had a 1080 video not play on my setup before. This is with your latest fix.
> 
> I'm using an Odroid N2+ box with Corelec 19.5.

Weird, I have no problems here on my Odroid N2+ (CE 20.2). Maybe reset your inputstream adaptive settings?

**Comment by xXSkizzo89Xx** [comment]
> Corelec 19.5

The site in question uses the new AV1 codec for 1080 and 4k resolution, this does not happen for 720 content, Officially the support for the AV1 codec has been integrated into Kodi with the release of the nexus 20 version, so if you don't want to have problems you need to upgrade to Corelec 20.x (Unfortunately some older processors do not support this codec but that shouldn't be your case)

**Comment by xXSkizzo89Xx** [comment]
> If I change the setting to UHD in Host and Resolvers or use Ask and select 1080, the audio plays, but the screen is black/blank. The same result happens if I use 4k. My TV is not 4k and that is normal for 4k videos, but I'm not sure why it doesn't play/show the 1080 file. 720, however, plays fine. I've never had a 1080 video not play on my setup before. This is with your latest fix.
> 
> I'm using an Odroid N2+ box with Corelec 19.5.

The site in question uses the new AV1 codec for 1080 and 4k resolution, this does not happen for 720 content, Officially the support for the AV1 codec has been integrated into Kodi with the release of the nexus 20 version, so if you don't want to have problems you need to upgrade to Corelec 20.x (Unfortunately some older processors do not support this codec but that shouldn't be your case).
