### ISSUE TITLE
Chaturbate online favorites does not work

### ISSUE THREAD

**Issue by scorsese50** [dobbelina/repository.dobbelina#1142]
Cannot get into online favorites in Chaturbate. Nvidia shield Kodi 19.3.

**Comment by zzyuui** [comment]
Having the same problem in Chaturbate using the latest Cumination release, 1.1.83.  After selecting "Online Favorites", the spinning wheel appears and doesn't stop or go away.  Essentially freezes Kodi.  Have to go to system  Settings and do a Force Stop on Kodi.  The Online Favorites was working correctly in the previous release, 1.1.82.

**Comment by ErosVece** [comment]
https://github.com/dobbelina/repository.dobbelina/issues/1112#issuecomment-1668594851

**Comment by scorsese50** [comment]
It is working now on latest release.
