### ISSUE TITLE
Uflash not working

### ISSUE THREAD

**Issue by brainwaster** [dobbelina/repository.dobbelina#1148]
When I go into.uflash there are no vifeos listed just Catagories & Search. Nothing in catagories works  or does search

**Comment by dobbelina** [comment]
Works for me on Windows.
You need to provide a [log file](https://github.com/dobbelina/repository.dobbelina/issues/968#issuecomment-1427506877)

**Comment by brainwaster** [comment]
I forgot to mention what platform and version I'm using. 

It's LibreElec 11.0.1, Kodi 20.1. I've never beem able to figure out what log file is needed or how to enable that particular log

**Comment by brainwaster** [comment]
Looks like it may have been a LibreElec problem. I upgraded to 11.0.2 a week or so agonand the addon was gone when the upgrade was done, I tried to install it again and it failed so I went back tom11.0.1.

I've just checked the uodates and 11.0.2 is no longer in the update channel but 11.0.3 is. Upgraded to that abd everything works again

**Comment by dobbelina** [comment]
Very good you got it sorted out, closing thread.

**Comment by ErosVece** [comment]
> I forgot to mention what platform and version I'm using.
> 
> It's LibreElec 11.0.1, Kodi 20.1. I've never beem able to figure out what log file is needed or how to enable that particular log

The next time when asked for debug log: https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading
