### ISSUE TITLE
Site Request

### ISSUE THREAD

**Issue by SomeDood** [dobbelina/repository.dobbelina#115]
https://www.hotpornfile.org/

If at all possible. Thanks.

**Comment by dobbelina** [comment]
12asdfg12  have been so kind and added it, #121
However there's an issue with it not working properly,
Under investigation.

**Comment by SomeDood** [comment]
Thanks. I had recently went to the site and noticed the webplayer isn't working for a specific site I search for. So that could probably be an issue. Good site overall tho.

**Comment by vic2252** [comment]
Is it possible to get onlyfans stuff on whitecream?
