### ISSUE TITLE
Please fix agg maal pro site. As no video is playing. Shows no video link found 

### ISSUE THREAD

**Issue by Harryhappy2022** [dobbelina/repository.dobbelina#1152]
### Bug reports:

Please replace this line with a brief summary of your issue 

### OS environment
What OS, Device, version etc

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.

**Comment by dobbelina** [comment]
Works for me on Windows.
You need to provide a [log file](https://github.com/dobbelina/repository.dobbelina/issues/968#issuecomment-1427506877)

**Comment by dobbelina** [comment]
No log file closing.
