### ISSUE TITLE
Xhamster freezing when seeking 

### ISSUE THREAD

**Issue by Dave051987** [dobbelina/repository.dobbelina#1155]
### Bug reports:

A lot of videos from xhamster freez as soon as I seek forward or backward. Playing at normal speed works fine but when using the seekbar to go forward or back it freezes the player.  

Android tv os 10 
What OS, Device, version etc

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted. (Sorry I'm on android tv and have no way to extract the log file)

**Comment by Gujal00** [comment]
Pause video before seeking. This is a quirk of some videos on how they are packaged and kodiplayer handling them. Addon cannot do anything as it has already passed the video url to kodiplayer and its job is done

**Comment by Dave051987** [comment]
> Pause video before seeking. This is a quirk of some videos on how they are packaged and kodiplayer handling them. Addon cannot do anything as it has already passed the video url to kodiplayer and its job is done
> 
> > Sorry I'm on android tv and have no way to extract the log file
> 
> Use kodi logfle uploader addon, it can upload the logfile and will give you a short url which you can share here

When I pause it says press right to frame advance. So it doesn't actually seek it goes forward frame by frame which is slower then just letting the video play. Is there a setting somewhere to make the advancement faster ? Or a different button on remote to jump ahead ?

**Comment by ErosVece** [comment]
> Use kodi logfle uploader addon, it can upload the logfile and will give you a short url which you can share here

More info how to access it from Cumination: https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading

**Comment by Gujal00** [comment]
> > Pause video before seeking. This is a quirk of some videos on how they are packaged and kodiplayer handling them. Addon cannot do anything as it has already passed the video url to kodiplayer and its job is done
> > > Sorry I'm on android tv and have no way to extract the log file
> > 
> > 
> > Use kodi logfle uploader addon, it can upload the logfile and will give you a short url which you can share here
> 
> When I pause it says press right to frame advance. So it doesn't actually seek it goes forward frame by frame which is slower then just letting the video play. Is there a setting somewhere to make the advancement faster ? Or a different button on remote to jump ahead ?

This is standard keyboard/remote howto
whether you have paused or playing, these are the standard key operation in kodi
pressing right once will skip 10 seconds
pressing right two times in succession will skip 30 seconds
pressing right three times in succession will skip 1 minute
pressing right four times in succession will skip 3 minutes
then 5 minutes, 10 minutes, 30 minutes and so on

Never use forward/rewind on streaming media, that is only for locally stored media files

**Comment by robhig1981** [comment]
Xhamster also does this for me since the last 2 updates. The length of the videos all seem to get shortened, longer ones cut to 8 minutes and shorter ones seem to be cut to half the length.

**Comment by dobbelina** [comment]
Issue confirmed seeking doesn't work

**Comment by ErosVece** [comment]
Set Cumination to let it ask for quality. Play a Xhamster video and don't choose `auto` but for example `720p`.
See if you can skip now.

**Comment by dobbelina** [comment]
`Come and get some - S40:E1` set to play 720p tries to seek forward 1 minute 
then cumination and kodi freezes, have to Ctrl Alt Delete kill it.
https://paste.kodi.tv/warukihiri.kodi
Playing the same video set to auto that chooses 1080p and try to seek forward 1 minute. cumination freezes for about 10-15 seconds and you get taken back to the video listing.
https://paste.kodi.tv/egasaqucah.kodi

**Comment by ErosVece** [comment]
Weird, at the moment I also can't skip forward in that video.
auto - or the default choice is playing a m3u8 (using Inputstream Adaptive made things worse).
The other streams are playing a mp4 file, and that one plays still fine here :)

**Comment by ErosVece** [comment]
SMR plays the Xhamster link, there it forces it to grab the video from the /embed/ page.
Looking in the browser, the embed page has the 8:00 min video, and the normal page not.

**Comment by ErosVece** [comment]
@dobbelina can you try this file?
Rename to xhamster.py and put it in the script.module.resolveurl.xxx\resources\plugins\ folder.
 
[xhamster.txt](https://github.com/dobbelina/repository.dobbelina/files/12743642/xhamster.txt)

**Comment by dobbelina** [comment]
Awesome!
Replaced the xhamster.py
Choosing auto i can skip forward, tested on several different videos HD and 4K 👍 
Choosing any quality and it doesn't work.
