### ISSUE TITLE
HentaiStream Errors Out

### ISSUE THREAD

**Issue by dootsie5times** [dobbelina/repository.dobbelina#1157]
As soon as you click on HentaiStream, it errors out.

[kodi.log](https://github.com/dobbelina/repository.dobbelina/files/12446508/kodi.log)

**Comment by ErosVece** [comment]
Yeah, I know.
I had started working on it, got the listing fixed, but the video playback also changed.
Maybe I can finish it tonight.

**Comment by dootsie5times** [comment]
Ok, thanks.

**Comment by ErosVece** [comment]
https://github.com/dobbelina/repository.dobbelina/commit/80ddacea2bf8167f4160ad88f68de7d3b151295d
