### ISSUE TITLE
Failing to master view modes - guidance requested please.

### ISSUE THREAD

**Issue by Budgie2** [dobbelina/repository.dobbelina#1159]
Please could you help me with view modes for cumination.  

When I look for sites now, if I select one of the wall views I cannot easily scan the list.  If I select list view I get an alphabet which I then need to select.  This is slow and I would like to return to the Sites list which just shows the long page of sites in alphabetical order.  It used to be like this but it seems updates everywhere are making life difficult. 
Guidance

**Comment by dobbelina** [comment]
Try changing Settings=>General=>Enable custom view types to off

**Comment by Budgie2** [comment]
Sadly no luck.  All the changed features are driving me nuts.  I had similar problem with YouTube.  Not the end of the earth but a pain.  Meanwhile I have a bigger problem.  Not sure if it is time of day or something but using Naughtyblog with real-debrid and trying to download some older vids from The White Boxx.  I can find the file and most times I am offered K2S 1080, Rapidgator 1080 or Uploaded 1080.  This afternoon all well with either K2S or Rapidgator.  Uploaded not often offered.  This evening they either don't work or stall at about 100 - 200MB.  
I have rebooted device and made fresh connection to vpn and real-debrid just to flush any cache or possible block.  Now what?  Could it be my ISP I wonder.  Any ideas?

**Comment by Budgie2** [comment]
Hi, please forgive but I am having problems here.  I had to rebuild my OSMC device and start over.     All working as required thanks to your help but I have two remaining issues because I had lost the Cumination setup and ipVanish setup.  

I have restored Cumination but the updates last night were being refused, an update is suggested but when I tried last night I had an error and the update would not install.  This morning it appears OK so just checking having lost all confidence in my IT capability.

My second issue is a request; please can you help me with ipVanish.  All the help suggestions ask for playstore or similar and of course I do not have access to a playstore.  I have forgotten entirely how I had this all working before using the remote.  Just have no idea what is the url etc I need to get the app installed.  ipVanish are no help at all and I am stuck.  
If you have time it would be appreciated.
Budgie2

**Comment by Budgie2** [comment]
Hi,
Problem was the Zomboided site has had a small revision so version number is now v1.0.1.  Once I had this sorted all was OK.  Hope I didn't waste your time.
