### ISSUE TITLE
Sxyprn(yourporn) not working

### ISSUE THREAD

**Issue by ahmadabdelhalim** [dobbelina/repository.dobbelina#116]
Whenever I try to open any video from sxyporn it gives me an error. Can you fix that?

**Comment by dobbelina** [comment]
Works for me on Win 10.
What platform are you using?

**Comment by imurreflection** [comment]
Apart from the first 4 videos, everything is playable. I am using kodi 17.6 and 18.4 on Android TV box.

**Comment by dobbelina** [comment]
Non issue, closing.
