### ISSUE TITLE
Xhamster not working windows

### ISSUE THREAD

**Issue by dobbelina** [dobbelina/repository.dobbelina#1165]
### Bug reports:

Xhamster must have changed something, errors accessing the site, see log file
~~Also xhamster videos saved to favourites don't play.~~

### OS environment
What OS, Device, version etc

https://paste.kodi.tv/dedocumoji.kodi

**Comment by Gujal00** [comment]
Seems to be related to XHamster giving `Upgrade your Browser` page instead of the actual embed page under ResolveURL. Have updated all the user-agents in ResolveURL to the latest ones in https://github.com/Gujal00/ResolveURL/commit/68fbb3b16f32410288fef2109c67b97f359dbc1c, and it works with that.
Will be part of the next resolveurl release

**Comment by dobbelina** [comment]
@Gujal00 
Updated common.py manually on ResolveURL with your fix but error persist.
in Cuminations settings.xml current ua is:
`<setting id="current_ua" default="true">Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.147 Safari/537.36 Edg/91.0.4472.147</setting>`

**Comment by Gujal00** [comment]
cumination user-agent is independent of resolveurl user-agent, they are different.
From your log
` {'clientName': 'Microsoft Edge', 'clientVersion': '84.0'},`
and the page has
`Unfortunately, <b>your browser does not support the latest technology used on xHamster</b>. Please update your browser to avoid any inconvenience. If you continue using xHamster without updating your browser, you will be solely responsible for the improper performance of the website and for all potential security issues, including the safety of your personal data.`
I updated all the user-agents used by resolveurl (it picks one randomly) to the latest one in that update I mentioned above and it works correctly

**Comment by dobbelina** [comment]
@Gujal00 
The ResolveURL settings are cached in commoncache.db, after deleting it and restarting now it works, thanks.
