### ISSUE TITLE
Chaturbate no longer working 

### ISSUE THREAD

**Issue by losthelp815** [dobbelina/repository.dobbelina#1166]
Windows 7 Pro
Kodi 19.4 

Issue saying this site has a Cloudflare challenge that just started today.
Not able to enter any sub-menu 

https://paste.kodi.tv/inebipunec

**Comment by zzyuui** [comment]
Chaturbate not working (same Cloudfare Challenge message) on my 2 devices:

Mibox4 (Android tv box), Version 9, Kodi 20.2, Cumination 1.1.86
Fire TV (2nd gen), Fire OS 5.2.9.5, Kodi 19.4, Cumination 1.1.82

As original poster stated, issue started today.  Was working fine yesterday.

**Comment by ErosVece** [comment]
https://github.com/dobbelina/repository.dobbelina/wiki/Cloudflare-Challenges-and-Flaresolverr-Integration-with-Cumination

**Comment by Gujal00** [comment]
Possibly region specific, works fine down under without any cloudflare challenges

**Comment by zzyuui** [comment]
Hey Gujal00....interesting suggestion.  

Using my NordVPN client on my Fire TV device, set up a VPN to Australia (I'm located in the US), restarted Kodi, Cumination add-on, and Chaturbate.  Chaturbate works fine with no cloudflare challenge issues. Turned off VPN, restarted Kodi and got the cloudflare challenge issue again.

Just for the fun of it, set up VPN's to Canada and UK - Chaturbate did not work.  Only Australia.

Thanks so much!

**Comment by ErosVece** [comment]
Yep, setting my VPN to US. I'm getting Cloudflare.
Turning Flaresolverr on, and I can access Chaturbate again with VPN to US :)

**Comment by flhthemi** [comment]
Help a n00b... I went to the advanced settings and entered my routers IP, no luck, entered my PCs IP, no luck. Do I need to change the port from 8191?  Can't figure out what I'm doing wrong.

http://192.168.1.1:8191/v1

**Comment by ErosVece** [comment]
> 

You need to enter the IP of the machine running Flaresolverr.
So if you installed Flaresolverr on your router, fill in that IP. If you installed it on your PC, fill in the ip of your PC.
You only need to change the port, if you changed it in Flaresolverr.

**Comment by flhthemi** [comment]
Oh I thought it was an included .py in the addon. So I have to install Flaresolverr?

**Comment by ErosVece** [comment]
Yes, read that Github wiki page from above how to do it

**Comment by flhthemi** [comment]
> Yes, read that Github wiki page from above how to do it

I did read it. I don't find any info about a Windows install for it and the rest of what's there is greek to me. So I'm totally lost.

**Comment by EvelK1203** [comment]
Download the windows files from here

https://github.com/FlareSolverr/FlareSolverr/releases/download/v3.3.4/flaresolverr_windows_x64.zip

There isn't an installer. Dump the files in a directory and run flaresolverr.exe,

If you are running Cumination on the same PC, use the default settings with localhost. If you are running on a stick or something else external you will need to change the url to show your PC's local IP, http://<ENTER PC IP HERE>:8191/v1.

This advice is all dependent on you running Cumination on the same local network as your PC.

**Comment by flhthemi** [comment]
> Download the windows files from here
> 
> https://github.com/FlareSolverr/FlareSolverr/releases/download/v3.3.4/flaresolverr_windows_x64.zip
> 
> There isn't an installer. Dump the files in a directory and run flaresolverr.exe,
> 
> If you are running Cumination on the same PC, use the default settings with localhost. If you are running on a stick or something else external you will need to change the url to show your PC's local IP, http://:8191/v1.
> 
> This advice is all dependent on you running Cumination on the same local network as your PC.

OK got it. It's working. Thanks so much for the help!!

Wonder if it's possible a mod could be made to Cumination to open the exe file for it in Cumination's settings then when exiting Cumination it would also exit Flaresolverr?? OR am I missing something and Cumination will already do this?

**Comment by dobbelina** [comment]
> Wonder if it's possible a mod could be made to Cumination to open the exe file for it in Cumination's settings then when exiting Cumination it would also exit Flaresolverr?? OR am I missing something and Cumination will already do this?

https://github.com/FlareSolverr/FlareSolverr/issues/70

**Comment by ErosVece** [comment]
I wanted to say something similar, just create a *.bat script that starts flaresolverr, then Kodi using `start /w`, and then kill flaresolverr :)

**Comment by dobbelina** [comment]
I don't have it installed, but have hard to understand all the difficulties they seem to have in that https://github.com/FlareSolverr/FlareSolverr/issues/70 thread i posted above.

If all you want is to autostart flaresolverr.exe when windows starts, create a shortcut to it and move the shortcut here:
`%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`
Easy peasy 😸

**Comment by ErosVece** [comment]
> I don't have it installed, but have hard to understand all the difficulties they seem to have in that [FlareSolverr/FlareSolverr#70](https://github.com/FlareSolverr/FlareSolverr/issues/70) thread i posted above.
> 
> If all you want is to autostart flaresolverr.exe when windows starts, create a shortcut to it and move the shortcut here: `%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` Easy peasy 😸

If only we knew someone who knows his way around Autohotkey 😉 🤣

**Comment by EvelK1203** [comment]
If you want it running in the background on startup this worked for me.

https://github.com/FlareSolverr/FlareSolverr/issues/70#issuecomment-761954514

**Comment by dobbelina** [comment]
> I would like it to start when I start Cumination and end when I exit Cumination. Doesn't need to be left running all the time.
> 
> There is a flaresolverr.py in the /lib. Couldn't it call flaresolverr.exe and kill it on exit? Just asking because I don't code so I don't know.

This approach should work, but instead of the screensaver it will open and close
flaresolver:https://forum.kodi.tv/showthread.php?tid=267458&pid=2461204#pid2461204

Or even better,  create a service addon that handles it, but that is beyond my
expertise:https://kodi.wiki/view/Service_add-ons

**Comment by dobbelina** [comment]
I could easily create a autohotkey app with a tray icon that handles this.
Something along the lines below.
One then creates a shortcut to it and places in the start folder so it autostarts with windows.
When i have time maybe i'll make it.

```
Code that executes every 10 seconds:
If process kodi & flareresolverr exist = exit
If process kodi exist = start flareresolverr and exit
if process kodi don't exist = kill flareresolverr and exit 
```

**Comment by ErosVece** [comment]
Well, only if it's really useful to users here, and someone is gonna use it :)

Maybe an idea, but you can also let it download/extract latest Flaresolverr, set it up and change the settings.xml from the userdata Cumination folder, so it's enables Flaresolverr there.
Use https://api.github.com/repos/FlareSolverr/FlareSolverr/releases/latest to easy get the latest version

**Comment by flhthemi** [comment]
Well...as of a few moments ago, no need for Flaresolverr or any of this as I just tested on 3 different Kodi installs with V1.87 and 1.86 and it appears to be back to normal. i.e. Flaresolverr not needed. Chaturbate may have decided to not use this or maybe it's broke.

**Comment by TarkusLV** [comment]
Well, personally speaking, I live in the U.S. and have never had to use FlareSolverr, except when using my account (for follows).

**Comment by ErosVece** [comment]
Try going to Supjav, Spankbang or Luxuretv. I have to use FlareSolverr for all of those

**Comment by TarkusLV** [comment]
Testing, Supjav and Spankbang require FlareSolverr for me, but not Luxuretv.

**Comment by psyco752** [comment]
I ask out of ignorance, I have used flareresolver on the PC and it worked for my device on Kodi, is it necessary to have the PC on for cumination to work without problems with my chaturbate account?

**Comment by dobbelina** [comment]
> I ask out of ignorance, I have used flareresolver on the PC and it worked for my device on Kodi, is it necessary to have the PC on for cumination to work without problems with my chaturbate account?

If you use Cumination to access chaturbate and get a cloudflare challenge the answer is yes.
If you access chaturbate thru other means like a browser, no.

**Comment by psyco752** [comment]
> > I ask out of ignorance, I have used flareresolver on the PC and it worked for my device on Kodi, is it necessary to have the PC on for cumination to work without problems with my chaturbate account?
> 
> If you use Cumination to access chaturbate and get a cloudflare challenge the answer is yes. If you access chaturbate thru other means like a browser, no.

I think I didn't put it correctly, I use Cumination from an Android device, I was able to solve the problem with flasolverr, but I don't know if it is necessary to have my computer on so that Chaturbate stays logged in on the Android device, thanks in advance for the answer.

**Comment by dobbelina** [comment]
Try closing flaresolver or shutdown the windows computer and you will get your answer.
