### ISSUE TITLE
Pornhorder listing issue

### ISSUE THREAD

**Issue by EvelK1203** [dobbelina/repository.dobbelina#1169]
Search returns are showing the front page as the results. Going to page 2 are showing the identical results. Browsing categories are also only showing the front page results.

Studios and Pornstars are empty.

**Comment by ErosVece** [comment]
Here https://github.com/dobbelina/repository.dobbelina/commit/920a3fd640ded970319f9ba267418bea49c0cab8
Fix will be in the next update, or you can copy the fix yourself
