### ISSUE TITLE
Site Addition Request - WatchMDH.to

### ISSUE THREAD

**Issue by ppppp1992** [dobbelina/repository.dobbelina#1173]
https://watchmdh.to/

Contact: 
admin@watchmdh.biz
abuse@watchmdh.biz
https://watchmdh.to/contact/

**Comment by ErosVece** [comment]
It was added yesterday/today: https://github.com/dobbelina/repository.dobbelina/commit/9af43e2a978029e35da567a4980f6824bf66b999
https://github.com/dobbelina/repository.dobbelina/commit/7ff372187d230f5f7168d0174650c9f4ae7eff53
