### ISSUE TITLE
Tube Porn Classic and Luxure Tv on Cumination

### ISSUE THREAD

**Issue by FrVoors** [dobbelina/repository.dobbelina#1175]
TubePornClassic, no playback. For at least 2 version updates. LuxureTV has a Cloudfare Challenge

**Comment by ErosVece** [comment]
If you used the search, read the changelogs or check the wiki regarding Cloudflare.
You would have found for example this https://github.com/dobbelina/repository.dobbelina/wiki/Cloudflare-Challenges-and-Flaresolverr-Integration-with-Cumination or this https://github.com/dobbelina/repository.dobbelina/issues/1171

**Comment by FrVoors** [comment]
onfiguring Cumination to use Flaresolverr

   1. Navigate to the Cumination settings.
   2. Under the "Advanced" section, find "Flaresolverr".
   3. Enable Flaresolverr support.
   4. Enter the host address where Flaresolverr is running, e.g.,
   http://192.168.0.1:8191/v1

 All I have under settings for Cumination is No Categories available box,
and below Ok Cancel and Defaults..

**Comment by dobbelina** [comment]
If you installed/extracted flaresolverr on a windows computer where kodi is running, leave the default **localhost** as is.
![image](https://github.com/dobbelina/repository.dobbelina/assets/46063764/f0b16726-c96c-42be-bc40-2b4da1776566)

**Comment by ErosVece** [comment]
TubePornClassic is working fine here....so without a debug log, we have no clue what is going on your device :)

**Comment by FrVoors** [comment]
I'm using it via a fire tv and Kodi 18

**Comment by Gujal00** [comment]
So where are you running flaresolverr? FireTV cant run it, so you need to run it on a machine on your home network and then point to that machine's ip address on the settings insteaf of `localhost`, if you cant then these two sites wont be accessible to you.

**Comment by dobbelina** [comment]
Issue resolved.
