### ISSUE TITLE
Feature Request - Option to Install Nightly Builds from GitHub

### ISSUE THREAD

**Issue by ppppp1992** [dobbelina/repository.dobbelina#1176]
I would like to suggest a feature, that allows the installation of nightly builds directly from the addon itself. Other addons I use often do offer that kind of functionality as an opt-in feature in the settings. If you don't opt-in, you only get the updates with the updated repository.

In one of my previous private Kodi builds, there was an addon, that allowed for a similar option for any addon hosted on Github. When I switched devices and created a new Kodi installation, I found out that this addon however is unfortunately broken now.

Native support for installing nigthly builds from Git would be nice to have in the future - although it is no top priority. Thank you for your consideration!

**Comment by dobbelina** [comment]
[New custom site, that isn't a site: Github Master Downloader](https://github.com/dobbelina/repository.dobbelina/issues/1022)
