### ISSUE TITLE
Porntrex.com no videos playing? 

### ISSUE THREAD

**Issue by bOuNtYhUnTeR2022** [dobbelina/repository.dobbelina#1178]
Hi there,

Pls check if you got also an error trying to play any videos on Porntrex.com.

Thanks

**Comment by dobbelina** [comment]
Works for me on windows so you need to create a log file.
[Cumination: Debug Logging and Uploading](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading)

**Comment by frankee123** [comment]
also came to say does not work on my android box.

**Comment by dobbelina** [comment]
No log file, deleting.
