### ISSUE TITLE
Chaturbate not working

### ISSUE THREAD

**Issue by JSmith36** [dobbelina/repository.dobbelina#118]
Running Coreelec nightly 

The last 3 or 4 days chaturbate is not functioning. It will get a list thumb nail and url from the list.

However when it goes to run the Playvid() function which is passed off to the utils libs getHtml() function which then gets sent to the urllib2.urlopen function. At this point the page is not properly being decoded for some reason the javascript on that page so the regex that follows to strip out the url for the playlist is failing when looking for the jsplayer.

Playing around running it from the python2 outside of the kodi's version on the same machine does work. However for some reason the low level urllib2 in kodi does not function.

What I have done is changed the following line in chaturebate.py on line 184

from 

listhtml = utils.getHtml(url, hdr=cbheaders)

to 

listhtml = utils.getHtml3(url)

stripped the headers and let it use the hardcoded headers in that function. It is also using the other requests lib to make the get and it is decoding the page properly for that window with the js in it so the regex is working. Not sure what the proper fix is, probably to make a replacement getHtml function that can handle the headers and all the logic but is using the request lib like getHtml3 is.

**Comment by JSmith36** [comment]
I also should add i did try fixing back to the last stable release of coreelec the 9.2.0 for a month ago or whenever with the same issue. I assume something changed on the site that the embedded kodi urlib2 doesn't like so it is not decoding it right.

**Comment by onknight** [comment]
I find all them pain to open sometimes I have click 3 or 4 times before they open

**Comment by DJMix-I-Can** [comment]
Chaturbate is working fine on my three devices. On the Nvidia shield Kodi 18.4, I had the 1.1.96 version & it was working. I updated it to the 1.1.99 version and it's still working.
On the Windows laptop Kodi 18.4, I had the 1.1.98 version and it was working. Updated it to the 1.199 version and it's also still working.
I've heard about Coreelec & LibreElec but never really played with it, thought; why not now.
I have the MeCool M8S Pro L downstairs and tested it on that. I tried the latest version of CoreElec 9.2.0 and it wouldn't boot after the first initialization, kept rebooting. I tried a different download and different SD card, still kept rebooting. So I downloaded the 9.0.3 version, booted it up, it did it's initialization and rebooted. It booted on the first try. https://imgur.com/31jFLAu
Set up my wifi, added dobbelina repo in file manager, installed the repo and then installed UWC addon. No problems, everything went smooth. I don't have anything else installed besides UWC. Opened UWC, went into Chaturbate & it played fine. **NSFW IMAGE** https://imgur.com/Dmjmnw4
When I first connected to the wifi, I received a CoreElec update notification but wanted to try the 9.0.3 version first. I'm now updating it to the latest version https://imgur.com/aSy27yA
I honestly didn't expect it to boot up being it gave me problems when I first tried it but it worked.
https://imgur.com/nJ4LW2M   &  https://imgur.com/verAzri
I was using the latest version of UWC 1.1.99 https://imgur.com/781eoRW
and it also worked on the 9.2.0 version of CoreElec https://imgur.com/J5vDsCV
I'm not familiar with CoreElec and can't tell you why it's not working for you but it did work for me. Corrupt installation maybe?

**Comment by onknight** [comment]
it dose work but it pain in ass to have click it 3 or 4 times to get a link to work

**Comment by DJMix-I-Can** [comment]
Don't have that issue. Click on it once and it shows. What device are you using?

**Comment by onknight** [comment]
PC  and Kodi  V1.1.99   On all the Live Video I sometimes have click more then once 
It running a AMD 3200 Ryzen with 32 gigs of ram

**Comment by DJMix-I-Can** [comment]
Yeah that shouldn't happen on your PC. My Lenovo laptop is i5 with just 8gigs of ram and it's slower than yours. Did you allow Kodi out on your firewall? Did you check Kodi logs to see if there's a bottle neck somewhere?

**Comment by JSmith36** [comment]
Ya looks like it is my install, I did a backup and fresh wipe worked fine. Will have to keep figuring out what is stepping on it lib wise

**Comment by DJMix-I-Can** [comment]
> 
> 
> Ya looks like it is my install, I did a backup and fresh wipe worked fine. Will have to keep figuring out what is stepping on it lib wise

Good to hear...

**Comment by jdoedev123** [comment]
Weird. Chaturbate stopped working after an update to 1.2.1 even though no difference in Chaturbate. Reverted to 1.1.99 and still no Chaturbate on Linux PC. Meanwhile Android device still OK with 1.1.99. Nvidia Shield is dead and Amazon Fire Kodi is down for maintenance.

**Comment by dobbelina** [comment]
> 
> Weird Part 2: Now working a day latter with no updates.
UWC is self-repairing, didn't you know? :smile:
