### ISSUE TITLE
XFreeHd.com video not working

### ISSUE THREAD

**Issue by Akkari1988** [dobbelina/repository.dobbelina#1181]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [x] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

after login video still not working

### Kodi version

20.2

### Cumination version

last

### Operating System and version

android

**Comment by ErosVece** [comment]
Will be fixed in the next update: https://github.com/dobbelina/repository.dobbelina/commit/3a1a30534fb4d005f947491a5980ef840e9c5922

Next time include the version number of Cumination. Posting 'last' today could mean 1.1.88 or 1.1.87 😉
