### ISSUE TITLE
https://tube.perverzija.com/

### ISSUE THREAD

**Issue by Akkari1988** [dobbelina/repository.dobbelina#1182]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

When I try to open some videos, I get this message "no other video hosts supported yet" ,there is a solution for this

### Kodi version

20.2

### Cumination version

1.1.88

### Operating System and version

android and windows

**Comment by ErosVece** [comment]
Disable 'Play m3u8 streams with Inputstream Adaptive' in Cumination settings.....if it's enabled :)

**Comment by Akkari1988** [comment]
No is already disebled !!!

**Comment by dobbelina** [comment]
It's because there is no playable file on the perverzija website.
Example:
Cumination perverzija search term:**exxxtrasmall allie addison tiny**
Browser search:https://tube.perverzija.com/?s=exxxtrasmall+allie+addison+tiny

**Comment by Akkari1988** [comment]
But there is video source but it cannot be played, probably because of the video provider, for example this link works on PC but this error message does not appear here ,  https://tube.perverzija.com/backroomcastingcouch-sabrina/

**Comment by dobbelina** [comment]
The host for that video is `https://mixdrop.co/e/7rgqpx4dc1wlk9`
Maybe @ErosVece or @Gujal00 can give some insights what the issue might be?

**Comment by ErosVece** [comment]
The site is for like 98% xtremestream.co videos.
Didn't know they had other videohosters....and which ones.
But, now I do....I'll add support for mixdrop (and others supported by SMR)

**Comment by ErosVece** [comment]
And here it is: https://github.com/dobbelina/repository.dobbelina/commit/4db00f7045f28931ba86367e9f2f2a98f2f4579c
