### ISSUE TITLE
I need a configurable timeout value

### ISSUE THREAD

**Issue by Spanktacular** [dobbelina/repository.dobbelina#1183]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.

### Description

I don't know what's changed out there, but lately I've been getting streams that just never start. I can either wait 5-7 minutes, or longer, for it to time out or I can go to settings and force stop on Android TV 12 and start all over.  What's really strange is that it's happening with streams I've added to favorites meaning they worked find once before, but now are just stuck in some kind of limbo.

It kind of a mood killer, to be honest.

If I could set a timeout of say, 30 seconds, then these scenes would timeout much more quickly and I could get on with it. 

Thanks for your time.

**Comment by ErosVece** [comment]
Btw, Cumination already have a timeout of 60s (or 30s) for the Python stuff (so getting videos etc).
But for video playback, you need to set the timeout in advancedsettings.xml curlclienttimeout  https://kodi.wiki/view/Advancedsettings.xml#network

**Comment by dobbelina** [comment]
Related maybe? [Android TV 12 issue](https://github.com/dobbelina/repository.dobbelina/issues/1185#issuecomment-1738202238)

**Comment by ErosVece** [comment]
> Related maybe? [Android TV 12 issue](https://github.com/dobbelina/repository.dobbelina/issues/1185#issuecomment-1738202238)

Who knows, users asks a question....we reply, and then it's a waiting game.

(btw, oops...sorry, I wasn't awake fully and edited your message instead of pressing reply 🤣 )

**Comment by dobbelina** [comment]
No feedback, closing.

**Comment by Spanktacular** [comment]
Wow. I don't live on here 24/7 and I only got an email notice upon closure.
I'm unsure how to gather logs on Android TV 12, I'll have a look at that bug.
