### ISSUE TITLE
Xhamster no video found

### ISSUE THREAD

**Issue by dobbelina** [dobbelina/repository.dobbelina#1184]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Xhamster no video found message and no listing

### Kodi version

20.2

### Cumination version

1.1.88

### Operating System and version

Win 10 64-bit

### URL to debug log file

https://paste.kodi.tv/horemifasa.kodi

**Comment by ErosVece** [comment]
No log, no problem 😉 

It's working fine here :)

**Comment by dobbelina** [comment]
I thought it was one of those "no log filers" ha ha! :blush:
Debug log in first topic and below the screenie:
![image](https://github.com/dobbelina/repository.dobbelina/assets/46063764/50d5fe28-dbfa-4940-888e-91ff673bab25)

**Comment by dobbelina** [comment]
Weird, the error reminded me of the user agent failure last time i had a problem with xhamster, so i commented out line 70 in xhamster.py to get the full error message.
```
    else:
        utils.notify('Cumination', 'No video found.')
        #return   <= added hash sign on line 70
```
And i was right, it is the user agent that is the culprit again, but how?
ResolveURL is version 5.1.109 that @Gujal00 fixed the user agents on a while ago, despite that:
```
{'clientName': 'Firefox', 'clientVersion': '81.0'}
and
<title>Please update your browser to use xHamster | xHamster</title>\n'
<meta name="description" content="Unfortunately, your browser '
does not support the latest technology used on xHamster.">\n'

```
New debug log file:https://paste.kodi.tv/fanifopoqe.kodi

**Comment by ErosVece** [comment]
ResolveURL is only used for resolving the videolink.
Browsing around the sites, we use random_ua.py  (https://github.com/dobbelina/repository.dobbelina/blob/master/plugin.video.cumination/resources/lib/random_ua.py).
It is refreshed with a new user-agent every week.
Or you can manually do that by clearing `current_ua` in the userdata Cumination settings.xml

I remember that I let Chatgpt update and improve that random_ua.py, but I never pushed it, and I've seen to lost it 🤣 

What is the exact current_ua string you have now?

**Comment by dobbelina** [comment]
Current string was:
`Mozilla/5.0 (Windows NT 6.2; WOW64; rv:81.0) Gecko/20100101 Firefox/81.0`
After deleting it created:
`Mozilla/5.0 (Windows NT 6.2; WOW64; rv:82.0) Gecko/20100101 Firefox/82.0`
Didn't work either so i manually changed it to:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36 Edg/102.0.0.0` and had to delete commoncache.db for it to work.
Probaly need some work on that random_ua.py

**Comment by ErosVece** [comment]
Yeah, I'll make sure that for Firefox it's not using a lower 80 number.

I tested some more, because I was curious what the minimum version is.
`Mozilla/5.0 (Windows NT 6.2; WOW64; rv:84.0) Gecko/20100101 Firefox/84.0`  this didn't work
`Mozilla/5.0 (Windows NT 6.2; WOW64; rv:84.1) Gecko/20100101 Firefox/84.1`  this did work :)

**Comment by ErosVece** [comment]
@dobbelina Try this https://github.com/dobbelina/repository.dobbelina/commit/a49ee36293afc879b23619d8905ee419c677fcbd
