### ISSUE TITLE
👋Kodi stuck on startup by Cumination

### ISSUE THREAD

**Issue by victore447** [dobbelina/repository.dobbelina#1185]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

![8](https://github.com/dobbelina/repository.dobbelina/assets/48101775/419a3c35-8840-43a4-b7ff-a862f42e2b81)**Hello,**
For several weeks Chaturbate via cuminarion has caused Kodi to block on startup 
(only Cuminarion is installed in Kodi for the test).

☝️This happens after when I view chaturbate cam girls for a few minutes.
Then Cuminarion remains frozen on an image of a cam girl (photo attached). 

![Chaturbate](https://github.com/dobbelina/repository.dobbelina/assets/48101775/22ee2d8b-5eb9-4da8-bda8-966c32ec6c3d)

☝️The X-rated films on other sites do not cause this.
I would like to point out that the bug still occurs with my favorites and folders created in Cumination.

![Favorite CUMINATION](https://github.com/dobbelina/repository.dobbelina/assets/48101775/95bdbb64-1b3a-4bfc-87ad-725e4d695783)

👆And when I delete all my data from Kodi and reinstall Cuminarion afresh on it I don't have this problem.

Also when I have other addons (video plugins), mkv files, MP3 I don't have this problem.

**Thank you for your response (Log & favorites.db attached)**

[kodi.log](https://github.com/dobbelina/repository.dobbelina/files/12739736/kodi.log)

[favorites.txt](https://github.com/dobbelina/repository.dobbelina/files/12739769/favorites.txt)

### Kodi version

20.2

### Cumination version

1.1.88

### Operating System and version

Android Tv 12 &11 (Shield tv (android 11) & Box tv Leap-S1 (android 12))

**Comment by ErosVece** [comment]
It works fine here, can you try switching the 'Play m3u8 files with Inputstream Adaptive' option in the Cumination settings?
So if it was enabled, disable it. And vice versa :)

**Comment by victore447** [comment]
![143](https://github.com/dobbelina/repository.dobbelina/assets/48101775/fb320c76-dc42-4f96-a286-0bff84ddb8f2)**Good morning,**
You hit the nail on the head and it works 
correctly there👍.

☝️ It was the activation of m3u8 via impustream adaptive which blocked Kodi when starting and playing live cam girls from chaturbate.

 **Thanks for the response** ✅

**Comment by dobbelina** [comment]
Issue resolved, closing thread ![143](https://github.com/dobbelina/repository.dobbelina/assets/48101775/fb320c76-dc42-4f96-a286-0bff84ddb8f2)
