### ISSUE TITLE
ShemaleZ stalls out 

### ISSUE THREAD

**Issue by highlander109** [dobbelina/repository.dobbelina#1186]
When accessing shemaleZ. After selecting the file. The file goes to load and then crashes

**Comment by dobbelina** [comment]
Works for me on windows, you need to provide a [debug log file](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading)

**Comment by dobbelina** [comment]
Deleting, there's a [bug report](https://github.com/dobbelina/repository.dobbelina/issues/new?assignees=&labels=&projects=&template=bug_report.yml) template
