### ISSUE TITLE
Jump 10 pages or goto page # feature

### ISSUE THREAD

**Issue by INaughtyguy4u** [dobbelina/repository.dobbelina#1187]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.

### Description

Can you add a jump 10 pages or go to a certain page feature as common link in the page browsing? Currently we could only go page by page and that takes a long time to go to say page 1534.

**Comment by dobbelina** [comment]
[navigating library](https://github.com/dobbelina/repository.dobbelina/issues/1131)
[Jump to page on search listings](https://github.com/dobbelina/repository.dobbelina/issues/1101)
