### ISSUE TITLE
filter out keywords 

### ISSUE THREAD

**Issue by freakindeacon** [dobbelina/repository.dobbelina#1188]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.

### Description

how do you properly input the keywords? I've tried every possible way to use ; as a separator however nothing with more than one keyword works.

**Comment by dobbelina** [comment]
Is it on a particular site?
Keywords should in most cases be separated by a space

**Comment by freakindeacon** [comment]
I've only tried on pornhub and spaces don't work either

**Comment by dobbelina** [comment]
I had no issues using 2 keywords pornhub, what is the keyword?

**Comment by freakindeacon** [comment]
hm that's odd then, any string of keywords don't work on my end. maybe it's because I'm on android

**Comment by dobbelina** [comment]
Without an example it's impossible to know.
If i search for **Filthy Family Anastasia**
First hit is: 
FILTHY FAMILY - Anastasia Knight, Melissa Lynn, Miley Star And More! 12:47

**Comment by freakindeacon** [comment]
no I'm referring to filtering OUT keywords in the advanced settings not using the search tool

**Comment by dobbelina** [comment]
Ahh, sorry i misunderstood,(too early in the morning here lol)
Never used that functionality and the separator should be ;
Maybe @ErosVece can give some more feedback.

**Comment by ErosVece** [comment]
It was indeed bugged, and now fixed: https://github.com/dobbelina/repository.dobbelina/commit/aee70aa1eb8f442673f415360c5b4040341cedc4
