### ISSUE TITLE
add this site plz  :)   https://fuxmovies.com/

### ISSUE THREAD

**Issue by Akkari1988** [dobbelina/repository.dobbelina#1190]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.

### Description

https://fuxmovies.com/
https://fuxmovies.com/dmca.html

### URL to DMCA information

https://fuxmovies.com/dmca.html

**Comment by ErosVece** [comment]
Thanks, nice find....it looks like a good one. Wish there are more of these 🤣 

Anyway, https://github.com/dobbelina/repository.dobbelina/commit/42aaa0ae7ab9c37d815abaea7b6f582e1cbc2527 here it is....wait for the next update, or install it yourself
