### ISSUE TITLE
Pornhoarder - Studios error

### ISSUE THREAD

**Issue by EvelK1203** [dobbelina/repository.dobbelina#1193]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Pornhoarder errors out when entering the Studios menu item. Happens with Windows and Android (Fire Cube)

### Kodi version

20.2

### Cumination version

1.1.89

### Operating System and version

Windows 11 Home

### URL to debug log file

https://paste.kodi.tv/asuvoyixir

**Comment by dobbelina** [comment]
Fixed, closing
