### ISSUE TITLE
https://fuxmovies.com/ and https://supjav.com/  are broken 

### ISSUE THREAD

**Issue by Akkari1988** [dobbelina/repository.dobbelina#1197]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

https://fuxmovies.com/ and https://supjav.com/  are broken

### Kodi version

20.2

### Cumination version

1.1.90

### Operating System and version

android and windows

**Comment by ErosVece** [comment]
Fix for Fuxmovies: https://github.com/dobbelina/repository.dobbelina/commit/30dd1cf74c255335ecc414be369140b15d019a85

Supjav works fine for me, you need Flaresolverr for this site. Check here https://github.com/dobbelina/repository.dobbelina/wiki/Cloudflare-Challenges-and-Flaresolverr-Integration-with-Cumination
