### ISSUE TITLE
Windows issues after last update

### ISSUE THREAD

**Issue by Ourkidsdad** [dobbelina/repository.dobbelina#1198]
Working fine until the last update, now I can open the app but when I try to open the sites, none are opening, any ideas?

**Comment by ErosVece** [comment]
Maybe an antivirus/firewall thing, where it blocks adult sites?
Try going to for example porntrex in your browser.

**Comment by Ourkidsdad** [comment]
In a browser I get the "your connection is not private" message in chrome.

Bizarrely?, clicking on porntrex on Kodi I get the login popup

**Comment by dobbelina** [comment]
There is a [Bug Report](https://github.com/dobbelina/repository.dobbelina/issues/new?assignees=&labels=&projects=&template=bug_report.yml) template
Use that, deleting thread.
