### ISSUE TITLE
YesPornPlease only displays 3 pages

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#12]
YesPornPlease only displays 3 of pages of scenes. This is due to some incorrect logic and pages 2 and 3 are not correct for most recent scenes.
A correction to yespornplease.py is being tested and will be uploaded soon.

**Comment by dobbelina** [comment]
Thanks jdoedev123.
I noticed that to.
Looking forward to a fix.

**Comment by Sameer888** [comment]
Hi dobbelina Awesome work done by u all for fixing uwc issues but i wanna know that where will i get updated versions for download .I am unable to see any link for downloading new upgraded 1.1.66 fixed uwc please help me with this 👍

**Comment by dobbelina** [comment]
HiSameer888,

Here: https://github.com/dobbelina/repository.dobbelina/raw/master/plugin.video.uwc.1.1.66.zip

**Comment by Sameer888** [comment]
Thanks Dobbelina whenever there are uwc fixes help me with the link please and Thanks once again👌keep it going Good work

**Comment by jdoedev123** [comment]
[yespornplease.py.zip](https://github.com/dobbelina/repository.dobbelina/files/2897252/yespornplease.py.zip)

Proposed fix to YesPornPlease pagination

**Comment by dobbelina** [comment]
Beautiful, thanks!
Addon will be updated.
