### ISSUE TITLE
Streamango

### ISSUE THREAD

**Issue by DJMix-I-Can** [dobbelina/repository.dobbelina#120]
A heads up...
Any site from UWC that used streamango is no longer going to work.
Streamango has been shut down by The Alliance For Creativity & Entertainment.

**Comment by dobbelina** [comment]
That's a shame.
Another hollow victory for the anti piracy league.
Some other provider will fill the gap in no-time.

**Comment by DJMix-I-Can** [comment]
As well as opeload.
https://torrentfreak.com/openload-and-others-taken-down-by-anti-piracy-alliance-ace-191031/

**Comment by dobbelina** [comment]
In UWC this is perhaps not a big problem, as most stuff here is hosted elsewhere.
Bu if you use Exodus, i'd suggest you disable openload & Streamango in the 
UrlResolver settings as none of these provide any working links anymore.
