### ISSUE TITLE
New Site FuxMovies doesn't show any content, no search results 

### ISSUE THREAD

**Issue by bOuNtYhUnTeR2022** [dobbelina/repository.dobbelina#1200]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Don't got a log, just visit the site and you see the mess :) 

### Kodi version

19

### Cumination version

1.1.90

### Operating System and version

Libreelec nightly 11.0-20231008

**Comment by dobbelina** [comment]
You didn't search closed issues.
Issue [resolved](https://github.com/dobbelina/repository.dobbelina/issues/1197) in next update

**Comment by jojodat** [comment]
Tho then there is already the next Problem: Videos can't be played since a few hours after the fix.

**Comment by bOuNtYhUnTeR2022** [comment]
😅🤷‍♂️
