### ISSUE TITLE
Pornhoarder - Studios error

### ISSUE THREAD

**Issue by Akkari1988** [dobbelina/repository.dobbelina#1204]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Pornhoarder - Studios error

### Kodi version

20.2

### Cumination version

1.1.90

### Operating System and version

android and windows

**Comment by dobbelina** [comment]
Duplicate, closing
Existing thread https://github.com/dobbelina/repository.dobbelina/issues/1193
