### ISSUE TITLE
Porntrex Errors

### ISSUE THREAD

**Issue by SomeDood** [dobbelina/repository.dobbelina#1208]
Porntrex gives an error of "no videos found" when using search and goes into an infinite loading when trying to access the categories section.

Kodi version
20.2

Cumination version
1.1.91

Operating System and version
Amazon Fire Stick 4k

**Comment by ErosVece** [comment]
No log, no problem.... 😉 

Also just tested it here, and everything works fine.

**Comment by SomeDood** [comment]
https://paste.kodi.tv/jegemerufa

**Comment by Akkari1988** [comment]
porntrex kategories still doesn't work it charges all the time, then have to turn off kodi

**Comment by tarapiatapioca** [comment]
I'm asking for the same issue. Everytime I click on categories It blocks itself.

**Comment by rversion4125** [comment]
Categories still not working on firestick Kodi 20.2 as of today. Just says ‘working’ and is stuck there on that screen.

**Comment by ErosVece** [comment]
Debug log still not provided....
