### ISSUE TITLE
Can't open Chaturbate categories from custom menu

### ISSUE THREAD

**Issue by TarkusLV** [dobbelina/repository.dobbelina#1211]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

I can open Chaturbate categories from the main Chaturbate menu, but I can't open categories added to a custom menu. I've created new category links since the recent changes, and even tried adding to a completely new custom listing, but I still get an error each time.  

### Kodi version

20.2

### Cumination version

1.1.92

### Operating System and version

Fire OS 7.6.6.4

### URL to debug log file

https://paste.kodi.tv/kihofohoqu

**Comment by Gujal00** [comment]
Test with [this patch](https://github.com/dobbelina/repository.dobbelina/commit/f07d983214477d3b8442612fc6e7fd80b9c6e40f) and report back

**Comment by TarkusLV** [comment]
> Test with [this patch](https://github.com/dobbelina/repository.dobbelina/commit/f07d983214477d3b8442612fc6e7fd80b9c6e40f) and report back

That fixed it, thank you very much!
