### ISSUE TITLE
https://www.porntrex.com/ categories and search error 

### ISSUE THREAD

**Issue by Akkari1988** [dobbelina/repository.dobbelina#1214]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

https://www.porntrex.com/ categories and search error 

### Kodi version

20.2

### Cumination version

1.1.92

### Operating System and version

android and windows

**Comment by ErosVece** [comment]
You put a mark 

> ### Prerequisites
> 
>     * [x]  I have searched the issue tracker to avoid opening a duplicate issue.

3 or 4 rows down the issue list: https://github.com/dobbelina/repository.dobbelina/issues/1208 🤦

**Comment by tarapiatapioca** [comment]
I'm asking for the same issue. Everytime I click on categories It blocks itself.
