### ISSUE TITLE
hanime.tv and hentaistream both give playback failed error

### ISSUE THREAD

**Issue by dootsie5times** [dobbelina/repository.dobbelina#1222]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Both hanime.tv and hentaistream give playback failed errors.   Hanime.tv looks like it actually tries to locate/load the file before erroring and hentaistream errors out immediately.
I'm attaching 1 log file.
I rebooted and first tried a video from hanime.tv and then immediately tried one from hentaistream.
[kodi.log](https://github.com/dobbelina/repository.dobbelina/files/13209188/kodi.log)

### Kodi version

20.2

### Cumination version

newest

### Operating System and version

coreelec 20.2

**Comment by ErosVece** [comment]
Both are working fine here.

Turn on debug logging in Cumination or Kodi settings, because this is very minimal and I can't see what is going on.

Try toggling the Play m3u8 with Inputstream Adaptive.

**Comment by dootsie5times** [comment]
I'm pretty sure inputstream adaptive is already on.  Those 2 sites worked fine on Friday.  There was an update since then.
I'm attaching the kodi.log file, which is the one I sent previously, but now I turned on debugging logging and tried both sites again.
[kodi.log](https://github.com/dobbelina/repository.dobbelina/files/13212312/kodi.log)

**Comment by ErosVece** [comment]
With toggling I mean, if it's on...try turning it off and see if that works.

I see that something indeed changed with playing through Inputstream Adaptive with the latest update, it got past me.
I've asked my 'colleague' why he did that change.

For now, https://github.com/dobbelina/repository.dobbelina/blob/master/plugin.video.cumination/resources/lib/utils.py#L430
remove that `if KODIVER < 20.0:` line, and remove the 4 spaces in front of the next line. so it matches with the lines below it.

**Comment by Gujal00** [comment]
Kodi 21 beta plays these streams without using Inputstream Adaptive as it uses newer ffmpeg
https://github.com/dobbelina/repository.dobbelina/blob/master/plugin.video.cumination/resources/lib/utils.py#L430 has been now updated to only disable for Omega, and leave it enabled for Nexus and below
