### ISSUE TITLE
Latest porn dont play video

### ISSUE THREAD

**Issue by karci78** [dobbelina/repository.dobbelina#1227]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Site Latest Porn dont play video. Site is ok,but video dont play...
Tried on Android and Win10

### Kodi version

Kodi 20.2

### Cumination version

1.1.93

### Operating System and version

win10 , Android TV 9

**Comment by dobbelina** [comment]
Issue confirmed, thanks for reporting.

**Comment by ErosVece** [comment]
It plays the rapidgator links they have on the site fine here.
They used to have direct links, but they are gone now.
It looks like they switched to filemoon iframes, I'll see to let it pick those too.

**Comment by karci78** [comment]
working....little slowly but working..

**Comment by ErosVece** [comment]
> working....little slowly but working..

If you have a service like Real-Debrid, you can get the Rapidgator links....those should be fast :)
