### ISSUE TITLE
Please fix shemalez and spankbang, and add ashemaletube

### ISSUE THREAD

**Issue by TechnicRick** [dobbelina/repository.dobbelina#1231]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.

### Description

Please fix shemalez and spankbang, and add ashemaletube

**Comment by dobbelina** [comment]
1. wrong issue template
2. You have not searched, [ashemaletube](https://github.com/dobbelina/repository.dobbelina/issues/1189) already requested
3. [Spankbang](https://github.com/dobbelina/repository.dobbelina/issues/1104) needs Flaresolverr
4. Logfile missing as shemalez is working for me
closing issue
