### ISSUE TITLE
xmovies4you not working 

### ISSUE THREAD

**Issue by pan9966** [dobbelina/repository.dobbelina#1235]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

When starting playback,  it shows loading page, then seraching supported host and error: could not find supported link.

Can you fix?

### Kodi version

19.5 Matrix

### Cumination version

1.1.96

### Operating System and version

Coreelec 19

**Comment by ErosVece** [comment]
I had to use a VPN to access the site (VPN set to my own country), but after that the site works fine.
The few videos I tested had all 3 links to choose from.

**Comment by pan9966** [comment]
Debug log:
https://pastebin.com/Wz42Y5f6

**Comment by ErosVece** [comment]
https://github.com/Gujal00/ResolveURL/

**Comment by pan9966** [comment]
Ok it works now
