### ISSUE TITLE
Why does clicking on my Chaturbate- webcams - Online Favorites folder take so long?

### ISSUE THREAD

**Issue by frankee123** [dobbelina/repository.dobbelina#1239]
I'm not sure how else to explain this but I usually buy android boxes just for Cumination and mainly for the webcam girls.(MFC and Chaturbate) I currently have about 1130 saved girls in my Favorite videos folder. My issue I had on my older android box is sometimes clicking to open it would take forever, just the same as if I click on the folder to view my Online Favorites from chaturbate only. I just thought it was my android box that was the problem. I just bought a new one with android 12. It has 4 GB of RAM fwiw, and I have Cumination installed and nothing else. I am also hardwired and my speed is good so I know that isn't the issue. When I click on my main Favorite video folder that seems to load pretty fast and I cannot complain about that. I notice however clicking on the shortcut folder for Chaturbate - webcams - Online Favorites it unfortunately is taking forever just like my previous android box. I just did it and counted roughly 85 seconds it took to open it. Does anybody have the issue or know how to speed it up please? I also have tried Cumination on my Xbox Series X and it is lightning fast. I wish I could get my android box to work the same...Thank you

**Comment by ErosVece** [comment]
Question, do you know how to replace one or more python files on your Android box?
And are willing to do so and share your log here?

I'm curious why or what makes it take so long, so I'll be adding some timers into a few files, so if you share the log, I can see what functions is the culprit :)

**Comment by frankee123** [comment]
> Question, do you know how to replace one or more python files on your Android box? And are willing to do so and share your log here?
> 
> I'm curious why or what makes it take so long, so I'll be adding some timers into a few files, so if you share the log, I can see which function is the culprit :)

Ty for the help my friend, but I am am dumb as they are when it comes to anything on here. I've had lots of help by others on here before literally telling me step by step what to do. I was thinking of just sending the android box to Amazon where I got it. It was on sale for like 30-40 bucks but had all good reviews hence why I got it. How tough is it to post what you are asking? I will try to do it bro. Ty

**Comment by frankee123** [comment]
Also, would it be ok or helpful to post the link to the box I have bro? Let me know please

**Comment by Gujal00** [comment]
Online favorites is a CPU intensive task. It pulls a list of all online models and then searches through your favorites for each model and compares with the received list to see if the model is online. If you have over thousand models, on cheap android boxes it will take forever as the CPU is not grunty enough.

**Comment by ErosVece** [comment]
Gujal is correct, we understand perfectly what you are talking about :)
But you not what he is saying, let me explain:

You have your Cumination Favorites, you added there the 1200 girls from Chaturbate. Opening that is just reading the database table and showing the content of the favorites table.

Now you have in Chaturbate the Online favorites.
Opening that is downloading a json file from Chaturbate with info about every model that is online (I just saw 6457 models at this moment). After that it's getting your Cumination favorites, filtered op Chaturbate (around 1200 in your case).
Now it's checking using that downloaded json file for each of your 1200 models, if it's online, 
If online, show it in Kodi. As you say under 100 girls that are online.

You understand what I'm talking about? 😉 

But looking up 1200 items from a set of 6400, I'll see if we can improve it.....make it faster.

Another possible solution that maybe would be faster is to not favorite them, but follow them (using a chaturbate account).

**Comment by ErosVece** [comment]
I think I have optimized it, can you try this: https://github.com/dobbelina/repository.dobbelina/commit/1224dce7d664c2eaff719e2e7dd65aaa4ac5693d  ??

**Comment by frankee123** [comment]
> Gujal is correct, we understand perfectly what you are talking about :) But you not what he is saying, let me explain:
> 
> You have your Cumination Favorites, you added there the 1200 girls from Chaturbate. Opening that is just reading the database table and showing the content of the favorites table.
> 
> Now you have in Chaturbate the Online favorites. Opening that is downloading a json file from Chaturbate with info about every model that is online (I just saw 6457 models at this moment). After that it's getting your Cumination favorites, filtered op Chaturbate (around 1200 in your case). Now it's checking using that downloaded json file for each of your 1200 models, if it's online, If online, show it in Kodi. As you say under 100 girls that are online.
> 
> You understand what I'm talking about? 😉
> 
> But looking up 1200 items from a set of 6400, I'll see if we can improve it.....make it faster.
> 
> Another possible solution that maybe would be faster is to not favorite them, but follow them (using a chaturbate account).

Ohhh I see what you mean lol. Sorry, I am stupid when it comes to most things one here before I understand guys. Thank you.

**Comment by frankee123** [comment]
> I think I have optimized it, can you try this: [1224dce](https://github.com/dobbelina/repository.dobbelina/commit/1224dce7d664c2eaff719e2e7dd65aaa4ac5693d) ??

Ty bro, how do I try this? What do I do?

**Comment by ErosVece** [comment]
I think the easiest way is to install the Github Master Downloader custom site.
Link and instructions here: https://dobbelina.github.io/custom.html

After that, you can download the latest files from github, and copy them over.

Another way is to download the chaturbate.py file [from here](https://raw.githubusercontent.com/dobbelina/repository.dobbelina/master/plugin.video.cumination/resources/lib/sites/chaturbate.py) and copy that over to your Android box, and in the correct folder using the Kodi Filemanager.
If you don't see your addons folder in Filemanager, add the source: special://home 
After that you see addons, go the there, then plugin.video.cumination, then resources, lib, sites....and copy over the file.

**Comment by Gujal00** [comment]
> 
> Ohhh I see what you mean lol. Sorry, I am stupid when it comes to most things one here before I understand guys. Thank you. I would try the follow, but ever since the cloudflare thing happened, it won't work for me.

This fix is not going to solve your cloudflare stuff. You need to setup flaresolverr for it to work and as you are using Android, there is nothing that can be done there.

**Comment by frankee123** [comment]
> I think the easiest way is to install the Github Master Downloader custom site. Link and instructions here: https://dobbelina.github.io/custom.html
> 
> After that, you can download the latest files from github, and copy them over.
> 
> Another way is to download the chaturbate.py file [from here](https://raw.githubusercontent.com/dobbelina/repository.dobbelina/master/plugin.video.cumination/resources/lib/sites/chaturbate.py) and copy that over to your Android box, and in the correct folder using the Kodi Filemanager. If you don't see your addons folder in Filemanager, add the source: special://home After that you see addons, go the there, then plugin.video.cumination, then resources, lib, sites....and copy over the file.

Thank you so much for the help sir. I will try to figure out how to get this on my android box.

**Comment by frankee123** [comment]
> > Ohhh I see what you mean lol. Sorry, I am stupid when it comes to most things one here before I understand guys. Thank you. I would try the follow, but ever since the cloudflare thing happened, it won't work for me.
> 
> This fix is not going to solve your cloudflare stuff. You need to setup flaresolverr for it to work and as you are using Android, there is nothing that can be done there.

Yea I know that bro ty.

**Comment by dvgm506** [comment]
> I think the easiest way is to install the Github Master Downloader custom site. Link and instructions here: https://dobbelina.github.io/custom.html
> 
> After that, you can download the latest files from github, and copy them over.
> 
> Another way is to download the chaturbate.py file [from here](https://raw.githubusercontent.com/dobbelina/repository.dobbelina/master/plugin.video.cumination/resources/lib/sites/chaturbate.py) and copy that over to your Android box, and in the correct folder using the Kodi Filemanager. If you don't see your addons folder in Filemanager, add the source: special://home After that you see addons, go the there, then plugin.video.cumination, then resources, lib, sites....and copy over the file.

Third way would be to download the release zip file and edit the .py in there, copy it over to the device then install it :)

I don't have 1000+ in favorites, but it would take 30s or more to load. Just updated to the newest build and online favorites load lightning fast on my shield.

**Comment by frankee123** [comment]
> > I think I have optimized it, can you try this: [1224dce](https://github.com/dobbelina/repository.dobbelina/commit/1224dce7d664c2eaff719e2e7dd65aaa4ac5693d) ??
> 
> Ty bro, how do I try this? What do I do?

Thank you so much for this bro. It now takes less than 10 seconds if that to load. You rock sir lol.
