### ISSUE TITLE
repository.dobbelina needs to update

### ISSUE THREAD

**Issue by joseejohn4** [dobbelina/repository.dobbelina#124]
chaturbate not working from last week can you look after please

**Comment by DJMix-I-Can** [comment]
Chaturbate has been working for me but as of today, it's not working.

**Comment by dobbelina** [comment]
Confirmed, broken.

**Comment by pitsi** [comment]
It is a site issue. Youtube-dl also broke and can not parse any info.
https://github.com/ytdl-org/youtube-dl/issues/23010

**Comment by Buhric** [comment]
Looks like they switched over to FLASH player... and no jsplayer anymore...
can someone fix ?

**Comment by DJMix-I-Can** [comment]
It's already fixed, there's a pull request for it. It will get updated soon...

**Comment by psyco752** [comment]
> It's already fixed, there's a pull request for it. It will get updated soon...
are you going to update the application soon? in the repository I don't see any new version.

**Comment by dobbelina** [comment]
Is fixed by 12asdfg12  #125, thank you!
