### ISSUE TITLE
[old Kodi] not working from 1.1.96 - Non-ASCII character '\xc3'

### ISSUE THREAD

**Issue by gtr33m** [dobbelina/repository.dobbelina#1240]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Same as #1236. Reporting again as the issue is closed, but not fixed, at least not for me.
Error: Non-ASCII character '\xc3'

### Kodi version

Leia 18.5

### Cumination version

1.1.96

### Operating System and version

Android 6.0.1 API level 23

### URL to debug log file

https://paste.kodi.tv/omevawacax

**Comment by Gujal00** [comment]
The fix is not in a release yet. If you want it you need to run it from git or wait for 1.1.97 to be released

**Comment by gtr33m** [comment]
The error is caused by a special character in thepornfull.py on line 51

There is a special "o" in "Proximo"

I was able to fix it by adding:

`# coding=utf-8`

To the top of the file.

Leaving issue open so it can be added to the repository.
