### ISSUE TITLE
chaturbate does not work on cumination.. kodi 20

### ISSUE THREAD

**Issue by foofoo11** [dobbelina/repository.dobbelina#1248]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

the favorite opens and shows names but no other options work.. female section, feature section.. and so on.. nothing seems to be working and getting warning notice on firestick Kodi 20..

### Kodi version

20

### Cumination version

https://dobbelina.github.io

### Operating System and version

firestick

**Comment by ambishus** [comment]
Do you run over a VPN?

**Comment by foofoo11** [comment]
Yes.. from my con.. and I figured out Australia works.. New Mexico works.. but LA or Phoenix and other locations do not work.. it’s weird..

**Comment by ambishus** [comment]
It might be a Cloudflare challenge?

**Comment by BdaCookieMonster** [comment]
Did you find a fix? I have the same issue and it's only chaturbate all the other webcam sites work fine.

**Comment by timsplinge** [comment]
Try running Kodi without a VPN. If that works, then you know it's Chaturbate blocking some IPs and not Cumination.

I've rarely had problems connecting without a VPN, it's only when I'm running one that issues are more frequent.
