### ISSUE TITLE
Request to remove sites

### ISSUE THREAD

**Issue by desireyes** [dobbelina/repository.dobbelina#1253]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.

### Description

Dear friend
I asked while back to add my sites to cumination repo. I had no idea that my cheap server load handling capacity is just not there.
Users are having difficulty to load videos as the hard drive is working at 100% load.
I have only one server and can't afford another one.
May I request to please remove the following sites from the repo
https://www.alluretube.com
https://www.desihoes.com
https://www.porncaper.com

I am really sorry and really appreciate your help.
Thanks
Desi Reyes

**Comment by dobbelina** [comment]
Hi @desireyes 
Alluretube/Desihoes are already removed in the latest update, will remove porncaper also for the next update.

**Comment by desireyes** [comment]
Thank you very much.
Really appreciate your consideration.
