### ISSUE TITLE
Playback problems with HentaiStream 

### ISSUE THREAD

**Issue by chavezmaduro123** [dobbelina/repository.dobbelina#1254]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Hello, I wanted to know if someone else is having trouble playing videos from HentaiStream. It stutters and freezes with some excessive buffering while using Kodi on my Hisense Android TV. I tried lowering the quality to 720 and 1080 but the problem remains. 

It required me to download InputStream Adaptive before playing the video, maybe the problem is related to that Add-on?

Thank you very much for your hard work, I usually use Naughtyblog and is great

### Kodi version

Latest

### Cumination version

Latest

### Operating System and version

Android TV

**Comment by xXSkizzo89Xx** [comment]
> ### Prerequisites
> * [x]  I have searched the issue tracker to avoid opening a duplicate issue.
> * [x]  I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.
> 
> ### Description
> Hello, I wanted to know if someone else is having trouble playing videos from HentaiStream. It stutters and freezes with some excessive buffering while using Kodi on my Hisense Android TV. I tried lowering the quality to 720 and 1080 but the problem remains.
> 
> It required me to download InputStream Adaptive before playing the video, maybe the problem is related to that Add-on?
> 
> Thank you very much for your hard work, I usually use Naughtyblog and is great
> 
> ### Kodi version
> Latest
> 
> ### Cumination version
> Latest
> 
> ### Operating System and version
> Android TV
> 
> ### URL to debug log file
> _No response_

The site in question uses the new AV1 codec for 1080 and 4k resolution, this does not happen for 720 content, officially the support for the AV1 codec has been integrated into Kodi with the release of the nexus 20 version, so if you don't want to have problems you need to upgrade to CoreELEC 20.x (Unfortunately some older chipset don't support hardware acceleration for this codec but only software).

**Comment by xXSkizzo89Xx** [comment]
The site in question uses the new AV1 codec for 1080 and 4k resolution, this does not happen for 720 content, officially the support for the AV1 codec has been integrated into Kodi with the release of the nexus 20 version, so if you don't want to have problems you need to upgrade to CoreELEC 20.x (Unfortunately some older chipset don't support hardware acceleration for this codec but only software).

**Comment by chavezmaduro123** [comment]
Thank you, I understand so its a problem with my TV. 

Best regards!
