### ISSUE TITLE
HQPorner doesn’t work

### ISSUE THREAD

**Issue by max834eiie** [dobbelina/repository.dobbelina#1255]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

HQporner doesn’t work, the video list is updated but when you try to play a video, it appears an error: “ reproduction failed “. 

### Kodi version

20.3

### Cumination version

1.1.98

### Operating System and version

Firestick

**Comment by emmastevens989x0fv** [comment]
Any one find out the resolution?

**Comment by max834eiie** [comment]
Nope. No solutions. On 13 May 2025, at 19:47, emmastevens989x0fv ***@***.***> wrote:﻿
emmastevens989x0fv left a comment (dobbelina/repository.dobbelina#1255)
Any one find out the resolution?

**Comment by dobbelina** [comment]
> Why has this been closed when the pronblem still persists?

Fix coming in the next release https://github.com/dobbelina/repository.dobbelina/commit/6ee388389fce8775820e3188f47f3e1a4b20cb96
