### ISSUE TITLE
PornHoarder : 'Could not find a supported link' error

### ISSUE THREAD

**Issue by CeeBro082** [dobbelina/repository.dobbelina#1258]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

PornHoarder : 'Could not find a supported link' error

### Kodi version

Nexus 20.1

### Cumination version

1.1.98

### Operating System and version

Fire OS 6.7.0

**Comment by EvelK1203** [comment]
The links that can't be found are generally hosted by netu. There is a click captcha on those links

Is it possible to add the host filter that the site supports? There is a drop down that allows you to select hosting servers, you can deselect unsupported hosts. I've tried adding "netu" in the advanced setting filter but it doesn't seem to take.

**Comment by CeeBro082** [comment]
This seems to work now
