### ISSUE TITLE
familypornhd doesn't playback

### ISSUE THREAD

**Issue by UnbeatableYeti** [dobbelina/repository.dobbelina#1259]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

familypornhd doesn't playback when you select a video. It doesn't give an error, it just returns to the screen where you select the video you want to watch. This bug report is done on a Windows 11 pc, but it also doesn't work on a AmLogic box with CoreElec 20.3-Nexus.

### Kodi version

kodi-20.3-Nexus-x64

### Cumination version

v.1.1.98

### Operating System and version

Windows 11 22H2

### URL to debug log file

https://paste.kodi.tv/enifakinum.kodi

**Comment by ajssss12** [comment]
I still have the same issue with this site.

I am running Kodi on a Nvidia Shield.

**Comment by dobbelina** [comment]
> I still have the same issue with this site.
> 
> I am running Kodi on a Nvidia Shield.

It will be in the next release on sunday 28th jan.
