### ISSUE TITLE
Downloads from HQPorner have stopped working

### ISSUE THREAD

**Issue by tetzy** [dobbelina/repository.dobbelina#1262]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

For the past week or so, downloading files from the site "HQPorner" has been impossible. The site allows me to select the quality of the file I'm hoping to download, but then reports the following error message when I start the download:

Download failed No response from server

HQPorner has been a dead reliable source for years, I hope you can help get the downloads online for us again.

Thanks for your work.

### Kodi version

20.2

### Cumination version

1.1.98

### Operating System and version

Linux Mint 21.2  (Kernel: 5.15.0-91-generic)

### URL to debug log file

https://paste.kodi.tv/umogakuhok

**Comment by dobbelina** [comment]
Has been fixed, will be in the next version 1.1.99 to be released on sunday 28th Jan.
https://github.com/dobbelina/repository.dobbelina/commit/c5950ad37bbfca34eb85cba8f79b3c98b078f421
