### ISSUE TITLE
Add site request

### ISSUE THREAD

**Issue by Sameer888** [dobbelina/repository.dobbelina#127]
Hi dobbelina, 12asdfg12 
There are 2 sites which i have been using on browser they have full length video content, Can yu please add these 2 sites if possible
http://www.cumlouder.com
http://www.joysporn.com

**Comment by Sameer888** [comment]
Hi Dobbelina 
If these site addition is not possible shall i close the issue

**Comment by 12asdfg12** [comment]
First site is done, I'll make a pull request later.
I haven't looked at the other one yet.

**Comment by Sameer888** [comment]
12asdfg12 yu are awesome thanks for adding this site 👍

**Comment by 12asdfg12** [comment]
cumloder added
joysporn uses encrypted video links, I will not add this site

**Comment by Sameer888** [comment]
Its ok thanks for adding 1site

**Comment by dobbelina** [comment]
Awesome work 12asdfg12 !
Thanks.
