### ISSUE TITLE
Americass

### ISSUE THREAD

**Issue by Cuban4lf** [dobbelina/repository.dobbelina#1273]
### Prerequisites

- [x] #1274
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Americass will not play any videos. (No play back )  tried clear cache and no luck.  Hope it wasn't reported already.  My first time reporting.  ThanQ 

### Kodi version

Nexus 2.0.1

### Cumination version

1.1.99

### Operating System and version

Firestick

**Comment by dobbelina** [comment]
Duplicate, 2 post below.
_I have searched the issue tracker to avoid opening a duplicate issue._ :thinking:
