### ISSUE TITLE
Hentaihaven not working again

### ISSUE THREAD

**Issue by gutho877** [dobbelina/repository.dobbelina#128]
When you try to load a video, it will get to the end of the loading bar before returning to the previous screen.

**Comment by dobbelina** [comment]
Issue confirmed.

**Comment by 12asdfg12** [comment]
The videos play on the website ?

**Comment by dobbelina** [comment]
I get an error on recent videos here: https://hentaihaven.org/pick-your-poison/
Uncensored works, and so do they in UWC.
