### ISSUE TITLE
“Download video” not working on Chaturbate menu

### ISSUE THREAD

**Issue by Dave-newman** [dobbelina/repository.dobbelina#1281]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Not sure if you are aware but, “Download video” is not working on the Chaturbate menu. 
I am running Cumination on my 3rd generation Amazon cube (android). It has never worked for me. 

It could be a very useful feature if it worked. 

Any help or feedback would be very much appreciated. 

### Kodi version

20.3

### Cumination version

1.1.100

### Operating System and version

Android TV 9.0.0 API level 28

**Comment by ErosVece** [comment]
It's disabled for Chaturbate (and other cam sites), because there is no video to download...it's a live stream.

**Comment by Dave-newman** [comment]
Thanks for the prompt responses, could it be removed from the menu as it's very misleading. It's not an option on the other streaming sites. Thanks again for the feedback.

**Comment by Megaworld1** [comment]
Hi , mega here I was a admin in mashup , phoenix years ago ,, was trying to play vids from chaturbate (webcams) today it’s coming back playback failed , checked other sites there working , has chaturbate changed the link ? 

Cheers Mega
