### ISSUE TITLE
Skip/Jump pages 

### ISSUE THREAD

**Issue by mkliao** [dobbelina/repository.dobbelina#1284]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.

### Description

Add a new feature so that by long holding "next page" there is a selection to which page to jump/skip to directly. Current implementation takes forever to pick up where left off due to unable to skip pages.

**Comment by dobbelina** [comment]
Some sites have this feature but not all, you can read more here:https://github.com/dobbelina/repository.dobbelina/issues/1101
