### ISSUE TITLE
I need some help to solve a coustom site problem

### ISSUE THREAD

**Issue by Beladeep** [dobbelina/repository.dobbelina#1289]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.

### Description

Hello dear developers

I created a custom site. It's a page where you can see what films are currently showing in cinemas.
I got as far as writing the program so that I could list the titles of the movies on the site and find the youtube trailer for each movie.
But unfortunately I cannot play the youtube trailers.
I even tried to add a section to the program that would print out the movie details and an index image, but that didn't work properly either.
I would be very grateful if someone could help me and finish the program to make it work properly.

Here is the website:
https://www.malommozi.hu/

A picture from my custom site:
![malommozi list](https://github.com/dobbelina/repository.dobbelina/assets/132296655/0222dba3-0c78-490c-b7a5-5b403e1b99dc)

My custom site:
[custom-malommozi.zip](https://github.com/dobbelina/repository.dobbelina/files/14401632/custom-malommozi.zip)

The code:

```
import re

import xbmcplugin
from six.moves import urllib_parse
from resources.lib import utils
#from resources.lib.adultsite import AdultSite
#site = AdultSite('Malommozi', '[COLOR hotpink]Malommozi[/COLOR]', 'https://www.malommozi.hu/', 'malommozi.png', 'Malommozi')

from resources.lib.customsite import CustomSite
 

site = CustomSite('Beladeep', 'Malommozi')
BASE_URL = 'https://www.malommozi.hu/'

@site.register(default_mode=True)
def Main():
    List(BASE_URL)

@site.register()
def List(url):
    list_html = utils.getHtml(url, '')
    trailers = extract_trailers(list_html)
    
    for title, link in trailers:
        full_url = urllib_parse.urljoin(BASE_URL, link)
        site.add_download_link(title, full_url, 'PlayTrailer', '', title)
    
    utils.eod()

def extract_trailers(html_content):
    trailers = []
    match = re.findall(r'<a href="([^"]+)"><div class="yt_link"><h1>(.*?)<\/h1>', html_content)
    for link, title in match:
        trailers.append((title, link))
    return trailers

@site.register()
def PlayTrailer(url, name, download=None):
    vp = utils.VideoPlayer(name, download)
    vp.play_from_direct_link(url)

```

Log file:
https://paste.kodi.tv/garitibudo

THX

**Comment by Gujal00** [comment]
`vp.play_from_direct_link(url)`  is the issue, youtube links are not direct playing m3u8/mpd links, they are webpages.
Change it to `vp.play_from_link_to_resolve(url)` and it should work.

**Comment by Beladeep** [comment]
Dear @Gujal00 
Thank you very much for your help. Thanks to you, it now plays the trailers of the movies very nicely.

**Comment by Gujal00** [comment]
@Beladeep please close the issue if it has been resolved

**Comment by Beladeep** [comment]
Problem solved.
