### ISSUE TITLE
Repo addon.xml TVAddons

### ISSUE THREAD

**Issue by DJMix-I-Can** [dobbelina/repository.dobbelina#129]
@dobbelina I have a question for you, I never installed the repo for this addon. The reason being is because when I download the zip files, I modify this xbmcplugin.setContent(utils.addon_handle, 'addons') line so I could change the view in my skin. Well, I decided to install the repo zip and as soon as I installed it,  I received these update notifications for Crypto Libraries, Streamlink Library & URL Resolver. https://imgur.com/k5awVdA
This repo is showing a higher version for those files. https://imgur.com/qFMNoq9  I checked the dependencies for this UWC add-on and they're not in there. I looked at my UWC addon.xml file and didn't see the requirements or directory for it. I checked the addon.xml for the repo and noticed that TVAddons dir was included and those updates are coming off of them. Why was TVAddons added as a directory if it's not required? If it's because of the ResolveURL & ResolveURL.XXX, then ResolveURL from Jsergio https://github.com/jsergio123/script.module.resolveurl should be in there. TVAddons just copies Jsergios update into their URLResolver anyway & URLResolver is not needed for UWC. I personally, don't install anything from TVAddons. UWC still works without having TVAddons repo. The only repo I have installed for UWC is JSergios.
Thanks.

**Comment by dobbelina** [comment]
URLResolver, Streamlink Library etc is not needed for UWC.
However, you must have other addons that have these as depedencies,
otherwise you wouldn't be notified of a newer version.
The tva-resolvers-repo only contain resolvers, it is not their release repo.
They keep it fairly up to date and i don't see any harm in using it.
I could switch to jsergio123 and add the script.video.F4mProxy dependency
to my own repo.
Maybe i do that one of these days.

**Comment by DJMix-I-Can** [comment]
I understand that I have those files installed, what I'm getting at is that they're not the official GitHub accounts. What they're doing is just forking over the files, they're also distributing this UWC in their repo. I'm personally going to remove the repo and just wanted to inform you of it. Thanks

**Comment by dobbelina** [comment]
Thanks for telling.
I know about their bad rep.
Ever since they pulled all illegal content, i guess they are grasping for straws
to keep visitor numbers up.
The Exodus saga is another TVAddons beauty .... 😄

**Comment by dobbelina** [comment]
Ok, change has been made.
TVAddons has been removed and replaced by jsergio123.
script.video.F4mProxy dependency is added to my own repo.

**Comment by DJMix-I-Can** [comment]
Good to hear..
