### ISSUE TITLE
PornEZ and Fullporner not working, and perhaps other problems (do not know if these are related - Unhandled exception detected)

### ISSUE THREAD

**Issue by Kodionpi** [dobbelina/repository.dobbelina#1293]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

PornEZ is not playing any videos. Fullporner as well...but the problem on Fullporner does not show up on the logs. 

I'm not familiar with it, but after a quick look at the logs, there seems to be another problem with Cumination. I can't describe it exactly, but the logs don't usually look like this. It seems to be an "Unhandled exception detected" -->"Index Error". "list index out of range"
Most of the other sites work without any problems and play all videos. 
Perhaps someone here can enlighten me about this. This log confuses me.

[kodi.log](https://github.com/dobbelina/repository.dobbelina/files/14510950/kodi.log)

### Kodi version

20.3

### Cumination version

1.1.101

### Operating System and version

LibreELEC 11.0.6

### URL to debug log file

https://paste.kodi.tv/ujeyuxeyon.kodi

**Comment by 12asdfg12** [comment]
pornez - fixed
fullporner - will work with the next version of Resolveurl (5.1.128)

**Comment by Kodionpi** [comment]
@12asdfg12 

Thanks for your reply and the work you put into the fix! 

Is the particularly excessive log I posted related to the two issues you fixed or is there another problem? Would you please take a look at it?

**Comment by 12asdfg12** [comment]
This is the enhanced debug log, it can help fix issues but can be disabled if it bothers you (Settings - Advanced - Enable Enhanced Debug Log)
