### ISSUE TITLE
Xvideos

### ISSUE THREAD

**Issue by EvelK1203** [dobbelina/repository.dobbelina#1294]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Hit an miss on some videos on finding a supported link. Same videos play ok on the web site.

### Kodi version

20.2

### Cumination version

1.1.101

### Operating System and version

Windows 11 Home

**Comment by dobbelina** [comment]
I can confirm the issue.
This started happen very recently, Xvideos have been working for ages before without any issues.
Probably a new unsupported host in ResolveURL

**Comment by Gujal00** [comment]
can you link a video that doesnt play so that it can be looked at?

**Comment by 12asdfg12** [comment]
Media_id can also be a string not just numbers (https://www.xvideos.com/embedframe/ktvpvub6f17), changing the pattern in SMRxxx to `pattern = r'(?://|\.)(x(?:v-)?videos1?\.(?:com|es|mx))/(?:video|embedframe/|embed/)(.+)` works for me.

**Comment by dobbelina** [comment]
2 examples:
https://www.xvideos.com/video80278347/her_proposal

https://www.xvideos.com/video20601005/pretty_amateur_young_french_slut_hard_sodomized_dp_and_facialized

**Comment by dobbelina** [comment]
> Media_id can also be a string not just numbers (https://www.xvideos.com/embedframe/ktvpvub6f17), changing the pattern in SMRxxx to `pattern = r'(?://|\.)(x(?:v-)?videos1?\.(?:com|es|mx))/(?:video|embedframe/|embed/)(.+)` works for me.

Thanks @12asdfg12  it works, (The oneliner is missing a `'` in the end)
xvideos.py line 26
`pattern = r'(?://|\.)(x(?:v-)?videos1?\.(?:com|es|mx))/(?:video|embedframe/|embed/)(.+)'`

**Comment by Gujal00** [comment]
Please test with this commit https://github.com/Gujal00/ResolveURL/commit/b2e05c120400ec725bbf0de032574e25003a4de1

**Comment by dobbelina** [comment]
@Gujal00 thanks works just fine.
