### ISSUE TITLE
WatchXXXFree not working again

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#13]
WatchXXXFree  support went down due to changes in the webpage. 
Testing changes will upload a revised watchxxxfree.py soon.

**Comment by jdoedev123** [comment]
Listing, Categories, and Top Performers working. Search still limited to 1 page.
[watchxxxfree.py.zip](https://github.com/dobbelina/repository.dobbelina/files/2897494/watchxxxfree.py.zip)

**Comment by jdoedev123** [comment]
Proposed fix for update WatchXXXFree with Search pagination fixed
[watchxxxfree.py.zip](https://github.com/dobbelina/repository.dobbelina/files/2897648/watchxxxfree.py.zip)

**Comment by dobbelina** [comment]
You're a genius, thanks!
I'm updating the addon immediately with a new version number 1.1.67

**Comment by Sameer888** [comment]
Hi dobbelina before updating new version can you mates fix tubepornclassic and daftsex if possible please 

Otherwise no issue

**Comment by john12345670** [comment]
jdoedev123, is there any chance you can look into daftsex.py?

**Comment by jdoedev123** [comment]
WatchXXXFree broke again. They changed the webpage again. May wait a few days until their design settles.

**Comment by jdoedev123** [comment]
Temporary solution is to change line 36 in watchxxxfree.py to:
    WXFList('https://watchxxxfreeinhd.com/index11/page/1/',1)

**Comment by dobbelina** [comment]
Thanks for the fix!
added a repo now as well so it auto-updates,(repository.dobbelina-1.0.0.zip).

**Comment by Sameer888** [comment]
Hi Mate can you send me the link to download repository.dobbelina1.0.0 please

**Comment by Sameer888** [comment]
I Got it thank yu 👍

**Comment by jdoedev123** [comment]
WatchFreeXXX broke again .
They changed the webpage design back again.  Testing fix before posting code. Largely reversion to a couple weeks ago.

**Comment by dobbelina** [comment]
Hi jdoedev,

You are right, i uncommented the old code and got it working again.

Have incorporated it with v1.1.69 together with the updated chaturbate fix.

**Comment by onknight** [comment]
Great work guys tested both and they working fine again 
Big Thanks

**Comment by imurreflection** [comment]
Hello mate
Porntrex is not working. Kindly fix it
