### ISSUE TITLE
naked.com webcams down

### ISSUE THREAD

**Issue by onknight** [dobbelina/repository.dobbelina#130]
Look like they redid they sight and it longer works on addon

**Comment by dobbelina** [comment]
Camster?

No such site in UWC.

**Comment by onknight** [comment]
Camster  and Pink cams use the same Data   it just new site name

**Comment by 12asdfg12** [comment]
The certificate used by naked.com(camster, ...) is not recognized in Kodi, therefore the web page cannot be downloaded. Until I can solve this issue i will not be able to fix it.

**Comment by onknight** [comment]
then why not remove it from list of site for now till it fixed

**Comment by onknight** [comment]
Naked was Brought by Camster.com  and they have Merged into 1 site now 
so we can delete naked from the App 

https://www.xbiz.com/news/248095/flirt4free-acquires-camster-com-naked-com-camdolls-com
