### ISSUE TITLE
Cloudfare issue with NaughtyBlog

### ISSUE THREAD

**Issue by SomeDood** [dobbelina/repository.dobbelina#1301]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

I only seem to get this issue on my pc's, never have this happen on my firestick. I even installed the flareslover/flarekodi.

### Kodi version

20.5

### Cumination version

1.1.102

### Operating System and version

Windows 10 Pro

### URL to debug log file

https://paste.kodi.tv/dihayadelo.kodi

**Comment by ErosVece** [comment]
It looks like it can't find Flaresolverr. Can you access http://192.168.0.19:8191/ with your browser?
You should see something like this:

```
{"msg": "FlareSolverr is ready!", "version": "3.3.16", "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}
```

**Comment by SomeDood** [comment]
Nothing loads up and it gives me an error. Do I need docker for it? I thought I could also just flarekodi inside of the flaresolverr folder.

**Comment by Gujal00** [comment]
It is most probably python issue in windows if it works fine in android without flaresolverr
Python version is 3.8 in Windows Kodi and 3.11 in Android Kodi which supports more modern ssl schemes that pass cloudflare browser fingerprinting tests. This is not the same as the browser challenge that flaresolverr solves
