### ISSUE TITLE
Xvideos inaccessible

### ISSUE THREAD

**Issue by grntbggr** [dobbelina/repository.dobbelina#1303]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Every video says there are no supported links.  There's another issue saying Xvideos is hit and miss, but now all videos have the same problem,  That previous issue says it's fixed, but Xvids still doesn't work.  If this counts as a duplicate, please disregard it.

### Kodi version

19.4

### Cumination version

1.1.101

### Operating System and version

Android

### URL to debug log file

https://paste.kodi.tv/urovamurin

**Comment by dobbelina** [comment]
A fix has been issued but it is not yet released, you can apply the fix manually
with this file until then:https://github.com/Gujal00/ResolveURL/commit/b2e05c120400ec725bbf0de032574e25003a4de1

**Comment by grntbggr** [comment]
Thanks for all your hard work.

**Comment by dobbelina** [comment]
> Thanks for all your hard work.
> 
> Do you know when it will be released?

No, I am not the owner of that repo, but probably not within a too distant future.

**Comment by grntbggr** [comment]
Got it, thanks!
