### ISSUE TITLE
tnaflix no content 

### ISSUE THREAD

**Issue by grntbggr** [dobbelina/repository.dobbelina#1305]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

tna flix content is missing.  When accessed, there are no videos, just empty menu options.  There was no error message, but I've included a log just in case.  I did notice another tnaflix issue posted right around the time that it went blank, but the issue says it's closed, but tna is still not functioning.  if a duplicate, please disregard this.

### Kodi version

19.4

### Cumination version

1.1.101

### Operating System and version

Android

### URL to debug log file

https://paste.kodi.tv/tozofeyuyu

**Comment by Gujal00** [comment]
Site is working fine in cumination

**Comment by grntbggr** [comment]
Yeah, I saw it around the time of the Resolver Update.  Thx

**Comment by Gujal00** [comment]
@grntbggr please close the issue if it is resolved

**Comment by grntbggr** [comment]
Done!
