### ISSUE TITLE
Favorites chaturbate 

### ISSUE THREAD

**Issue by jegfonseca** [dobbelina/repository.dobbelina#1306]
Hello

Refresh imagen is not working in real time (favorites chaturbate)
Kissjav is not open videos

Thanks

**Comment by frankee123** [comment]
I already posted about this issue in a seperate thread bro fwiw

**Comment by jegfonseca** [comment]
Thanks

**Comment by foofoo11** [comment]
> Hello
> 
> Refresh imagen is not working in real time (favorites chaturbate) Kissjav is not open videos
> 
> Thanks

yup same here.. it hasn'r worked in days now.. all other seem ok but the "Online Favorites" section does not update new images no matter how many times you click it..

**Comment by foofoo11** [comment]
KOdi is having alot of issues these days with no free addon to watch.. everything is click here and copy the code and eventually a paid debrid type ad addons.. scrubs2 is not working Crew is not working.. basically any addon to Kodi is not working unless you pay.. hope someone or new addons will make kodi useable again.. all u can do do is watch movies..

**Comment by frankee123** [comment]
Dumb question, but is there a manual way to update cumination now manually on a android box please?  I cannot take the images being out of whack any longer lol.
