### ISSUE TITLE
Spankbang not working

### ISSUE THREAD

**Issue by Oldmanjac** [dobbelina/repository.dobbelina#1310]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Spankbang wont open just gives an error message.

### Kodi version

20.3

### Cumination version

1.0.4

### Operating System and version

Firestick

**Comment by xXSkizzo89Xx** [comment]
Read here https://github.com/dobbelina/repository.dobbelina/issues/984

**Comment by CeeBro082** [comment]
This is because of the Cloudflare challenge, there's a thread already on a workaround
