### ISSUE TITLE
Chaturbate favourites thumbnails not being refreshed

### ISSUE THREAD

**Issue by Chrisni2** [dobbelina/repository.dobbelina#1311]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.

### Description

It seems that the thumbnails in Chaturbate aren't being refreshed in the online favourites view.  I've tried clearing cache and cookies in the add-on and cleared cache in Kodi app too.  Tried refreshing the thumbnail by adding the favourite again and also by deleting the favourite and adding again.  Same old thumbnail nothing like the content at the time

**Comment by dobbelina** [comment]
Already posted, closing https://github.com/dobbelina/repository.dobbelina/issues/1306
