### ISSUE TITLE
Fresh Cumination install, strange behaviour...

### ISSUE THREAD

**Issue by tetzy** [dobbelina/repository.dobbelina#1319]
I finally got around to doing a long over-due reformat and reinstall of Linux Mint to its newest version last night and I'm having a weird problem with my Cumination install:

When I tried to set my download folder location, I made a mistake misspelling that location. Now it won't let me change that misspelled location, for some inexplicable reason it's 'sticky' and refuses to change. I'm hoping to edit it manually by modifying the file that holds that information - I just can't find it. 

Any idea where that data is saved?

Thanks.

**Comment by dobbelina** [comment]
On Linux the path to the settings.xml file should be:
`~/.kodi/userdata/addon_data/plugin.video.cumination/settings.xml`
The setting  attribute in settings.xml is named **download_path**

**Comment by tetzy** [comment]
Thanks for your help.
