### ISSUE TITLE
Taboofantazy not loading links

### ISSUE THREAD

**Issue by Cheekysmile4u** [dobbelina/repository.dobbelina#1321]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

When trying to load one of the listed videos it attempts to load the link then throws an error. 

Ive attached the qr code the debug log. 

![Screenshot_20240331_113424_Kodi](https://github.com/dobbelina/repository.dobbelina/assets/165557618/183c0d8d-bd82-434d-ba02-6a4a4eb381d6)

### Kodi version

21.0.RC2

### Cumination version

1.1.103

### Operating System and version

Android 14

### URL to debug log file

https://paste.kodi.tv/utayunogol

**Comment by Gujal00** [comment]
resolveurl update (automatic) should have fixed the issue, as it plays fine with 5.1.131 version
