### ISSUE TITLE
Hanime.tv disappeared from favorites but appears under different site names each time you open favorites.

### ISSUE THREAD

**Issue by dootsie5times** [dobbelina/repository.dobbelina#1322]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Hanime.tv gone from favorites.  The links are still there, but appear under a different site name each time you go into favorites.  1 time it might be assparade, the next it might be girlpower, etc.  The only reason I can still find the link is because hanime.tv has a huge amount of links and I can then tell by the amount of links listed.  The issue started with the last update.
I'm not including a log file as I feel in this particular case it will not help at all.

### Kodi version

20

### Cumination version

1.1.104

### Operating System and version

openelec 20.2

**Comment by xXSkizzo89Xx** [comment]
Similar problem with Sxyprn favorites
