### ISSUE TITLE
LatestPorn : Listing is broken

### ISSUE THREAD

**Issue by CeeBro082** [dobbelina/repository.dobbelina#1324]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

LatestPorn listing is broken, nothing being displayed

### Kodi version

Nexus 20.1

### Cumination version

1.1.104

### Operating System and version

Fire OS 6.7.0.0

**Comment by 12asdfg12** [comment]
The website no longer exists.

**Comment by dobbelina** [comment]
I have removed it in the next update.
