### ISSUE TITLE
https://tube.perverzija.com/ play error

### ISSUE THREAD

**Issue by Akkari1988** [dobbelina/repository.dobbelina#1331]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

https://tube.perverzija.com/ play error

### Kodi version

21

### Cumination version

v.1.1.105

### Operating System and version

windows

**Comment by 12asdfg12** [comment]
It works for me, post a debug log file.
