### ISSUE TITLE
xHamster url's don't play

### ISSUE THREAD

**Issue by dobbelina** [dobbelina/repository.dobbelina#134]
xHamster url's don't play.

**Comment by 12asdfg12** [comment]
xhamster.py:

insert the following line between lines 72 (    if match ...) and 73 (        vp.play_from _direct_link ...)
```
        if not match.startswith('http'): match = 'https://xhamster.com/' +  match
```

**Comment by dobbelina** [comment]
Awesome,

Thanks!
