### ISSUE TITLE
Stripchat closes after a few seconds

### ISSUE THREAD

**Issue by geekcanion** [dobbelina/repository.dobbelina#1340]
Hi to all, I have issues with stripchat, when I enter when I enter in a cam, automatically closes after a few seconds

**Comment by zzyuui** [comment]
Same thing happens to me on my Android TV box.  However, all videos were playing properly on my Fire TV box.  Why it works on Fire TV but not Android is well above my technical level of expertise, LOL!  BTW, just submitted a issue reporting that Stripchat has completely stopped working.

**Comment by 12asdfg12** [comment]
[stripchat.com](https://stripchat.com/) is down

https://downforeveryoneorjustme.com/stripchat.com

**Comment by Gujal00** [comment]
@geekcanion 
For stripchat enable this option and try
![screenshot00003](https://github.com/dobbelina/repository.dobbelina/assets/17394059/731f2b2d-5d54-4c9d-b63e-6a3923cf5053)

**Comment by Gujal00** [comment]
@geekcanion the strip chat listing issue was fixed two days ago, but not yet released. It definitely works fine with the above option enabled
![screenshot00000](https://github.com/dobbelina/repository.dobbelina/assets/17394059/16fedeb9-9be2-4f18-9450-c15b242a0eb5)
![screenshot00001](https://github.com/dobbelina/repository.dobbelina/assets/17394059/0fe27678-57b3-4749-9cc3-983b593b4399)

**Comment by TheRightOneLaughs** [comment]
I have the same problem, streams are disconnected after a few seconds.

Using the m3u8 option fixes this, however audio doesn't work. Is it a known issue for no audio when using m3u8?

**Comment by TheRightOneLaughs** [comment]
The issue with stripchat streams closing after a few seconds (when not using m3u8 input stream adaptive option) seems to be related to using a recent version of Kodi.

I have one FireTV stick with Kodi 19.4 on it, and I don't experience the problem on it.

I have another FireTV stick on a later version ( I think it's 21.sonetbing, I'll double check later) which has the issue with streams stopping after a few seconds.

@geekcanion are you able to try and older version of Kodi and see if you still have this problem?

**Comment by geekcanion** [comment]
> @geekcanion 
> For stripchat enable this option and try
> ![screenshot00003](https://github.com/dobbelina/repository.dobbelina/assets/17394059/731f2b2d-5d54-4c9d-b63e-6a3923cf5053)
> 

Well, once the addon has been updated to version 1.1.108 and the 'play m3u8 streams with inputstream adaptive' option has been enabled, stripchat works again without problems and without interruptions, therefore I close the topic, thank you very much @Gujal00 👍
