### ISSUE TITLE
Stripchat Not Working

### ISSUE THREAD

**Issue by zzyuui** [dobbelina/repository.dobbelina#1343]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Clicking on any category in the Stiprchat menu (Female HD, Female, Couples HD, Couples, etc) produces the spinning wheel for about 2-3 seconds with screen remaining on the Stipchat menu when wheel stops spinning.  Had been working properly up until a day ago.

Running Cumination 1.1.107 on an older Fire TV box and on an Android TV box.  Same issue on both boxes.

### Kodi version

21

### Cumination version

1.1.107

### Operating System and version

Android TV OS 12

**Comment by 12asdfg12** [comment]
[stripchat.com](https://stripchat.com/) is down

https://downforeveryoneorjustme.com/stripchat.com

**Comment by zzyuui** [comment]
Having no problems accessing stripchat using my browser on PC.  My problem as described in my original post is still valid.  Just rechecked.

**Comment by 12asdfg12** [comment]
It doesn't work for me, probably a regional problem, but I can't fix it if I can't access the site.

![image](https://github.com/dobbelina/repository.dobbelina/assets/48175015/bf7bdd32-a5d2-4476-947b-49920c8c368e)

**Comment by zzyuui** [comment]
Understand.  Thanks for all of your hard work....appreciate it very much.

 Just double checked my configurations... I don't have any VPN running on my PC or streaming box and both are connected to the same wifi network.  Stripchat still working great through the browser.  Hopefully your access will return soon.  Thanks again.

**Comment by Gujal00** [comment]
@zzyuui 

> Stripchat still working great through the browser.

What url are your using in your browser?
