### ISSUE TITLE
Need help trying to restore my favorites and keywords onto the new Onn 4k Pro please

### ISSUE THREAD

**Issue by frankee123** [dobbelina/repository.dobbelina#1345]
I am at my wits end trying to figure this out so I'm asking for help if anybody knows here please. I have both my keywords and favorites .bak files onto a usb drive as well as manually moved them from my pc to the internal storage of the Android 12 Onn 4k pro box. The only thing is when I go into Cumination and try to restore them, they simply are not showing up period for me. I do not understand as to why I can't even see them to try to restore them. Is this an android 12 thing where the files are hidden for some reason? Does anybody know what I am talking about or how to actually fix this please? I have like 1500 favorites, I do not want to start over again. Thank you.

**Comment by 12asdfg12** [comment]
I'm not using Kodi on Android, but it seems to be a permissions issue.
Check the settings:
"Settings -> Apps - Kodi -> Permissions -> Files and Media" and select "Allow all the time".

**Comment by frankee123** [comment]
Thank you so much, I never knew I had to do that. You made my day bro lol.

**Comment by frankee123** [comment]
@12asdfg12 fixed my issue, thank you so much.
