### ISSUE TITLE
Backup keywords

### ISSUE THREAD

**Issue by Puhl1986** [dobbelina/repository.dobbelina#135]
Dear all,
The Funktion Backup Keywords and restore it is not working. Is there a way to correct it?
Thanks for your help

**Comment by DJMix-I-Can** [comment]
I went on my Nvidia Shield that has UWC 1.2.4, backed up my favorites and keywords into my download folder. I downloaded the backups onto my phone, fired up Kodi, opened UWC 1.2.4 & restored both files without a problem. I remember prior to Kodi 18.4, restore was a problem on Android devices but was working in Windows. What device, Kodi version & UWC version are you using?

**Comment by Puhl1986** [comment]
I use a mibox s based in Android 8.1
KODi is the Last in with 18.5
After restore it says the File is invalide.
![IMG_20191130_113330](https://user-images.githubusercontent.com/37249016/69899373-624c1780-1365-11ea-8e73-6dc38627ed09.jpg)

**Comment by DJMix-I-Can** [comment]
That's the same error I was getting prior to Kodi 18.4.  So you're able to backup but can't restore?  Any chance you're backing up to your local download folder, then moving the backups to a USB stick? You're trying to restore from the USB stick? Creating a debug file and checking what it says might help.
