### ISSUE TITLE
EroGarga doesn't open

### ISSUE THREAD

**Issue by ghost** [dobbelina/repository.dobbelina#1353]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

If I try to open EroGarga a message appears saying that the Site is down. Can you fix it?

### Kodi version

21

### Cumination version

109

### Operating System and version

Android

**Comment by jazzy1980** [comment]
Erogarga doesn't open, there is a massage saying the site is down.
Can you fix it?
thank you

**Comment by 12asdfg12** [comment]
It wasn't working the other day due to Cloudflare, but it's working now.

**Comment by jazzy1980** [comment]
EroGarga doesn't open again

**Comment by jazzy1980** [comment]
Another site doesn't work, Anybunny open up but video not playing

**Comment by OBonio** [comment]
EroGarga not opening here either.  Error is caused by utils.getHtml returning an empty list.  

[kodi.log](https://github.com/user-attachments/files/15746114/kodi.log)

Passing in site.url as referer to getHtml  looks like it works.
