### ISSUE TITLE
Xhamster

### ISSUE THREAD

**Issue by dobbelina** [dobbelina/repository.dobbelina#1365]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

About 20% of videos no longer plays.
Attached debug file is an example.

### Kodi version

Kodi 20.2

### Cumination version

1.1.110

### Operating System and version

Win 10 64 bit

### URL to debug log file

https://paste.kodi.tv/tidigiqowu.kodi

**Comment by 12asdfg12** [comment]
Some HLS streams don't play, as a workaround, disable "Automatically pick best quality" in resolveurl settings and choose an mp4 stream.
