### ISSUE TITLE
Fuxmovies can't open list

### ISSUE THREAD

**Issue by ngannguyen89** [dobbelina/repository.dobbelina#1366]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Fuxmovies can't open list

### Kodi version

Kodi v21

### Cumination version

1.1.110

### Operating System and version

Windows 10

**Comment by 12asdfg12** [comment]
The website no longer exists, it is redirected to pornegy.com
