### ISSUE TITLE
Noodlemagazine

### ISSUE THREAD

**Issue by EvelK1203** [dobbelina/repository.dobbelina#1367]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

All search results show no file found. No issue on website.

### Kodi version

21

### Cumination version

1.1.110

### Operating System and version

Windows 11 Home

**Comment by 12asdfg12** [comment]
Search works for me, playback will be fixed in the next release.
