### ISSUE TITLE
Pdcams Is it possible to 

### ISSUE THREAD

**Issue by memil33m** [dobbelina/repository.dobbelina#1373]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.

### Description

Can Pdcams be added?

### If it's a site addition request, add url below

https://pdcams.com

### URL to DMCA information

https://pdcams.com/dmca

**Comment by memil33m** [comment]
Wrong Dmca this should be https://pdcams.com/dmca

**Comment by Gujal00** [comment]
It is just an aggregator of the individual cam sites that are already there in cumination. No point adding it

**Comment by memil33m** [comment]
Trannytube.tv yı you can add thanks

10 Tem 2024 Çar 00:03 tarihinde gujal ***@***.***> şunu yazdı:
