### ISSUE TITLE
Amatuer TV Not working 

### ISSUE THREAD

**Issue by memil33m** [dobbelina/repository.dobbelina#1374]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Amatuer TV Not working 

### Kodi version

21.0 (21.0.1)

### Cumination version

1.1.111

### Operating System and version

Android TV 22.0.0 API 31 ( kernel:  linux 5.4.242-ab61762)

**Comment by dobbelina** [comment]
No log file, closing thread.
