### ISSUE TITLE
xhamster Not working 

### ISSUE THREAD

**Issue by memil33m** [dobbelina/repository.dobbelina#1376]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

xhamster not working 

### Kodi version

21.0 (21.0.1)

### Cumination version

1.1.111

### Operating System and version

Android TV 22.0.0 API 31 ( kernel:  linux 5.4.242-ab61762)

**Comment by dobbelina** [comment]
Works on windows, you need to make a log file.
Some more information regarding the error would be helpful.
Does the site load?
Does a particular link create an error or is it all of them?

**Comment by memil33m** [comment]
All of them are not working, I cannot log in to the site. I also requested
two sites from you. I would appreciate it if you could add them as well.
pdcams.com trannytube.com

7 Tem 2024 Paz 13:44 tarihinde dobbelina ***@***.***> şunu
yazdı:

**Comment by memil33m** [comment]
All of them are not working, I cannot log in to the site. I also requested
two sites from you. I would appreciate it if you could add them as well.
pdcams.com trannytub <http://trannytube.com/>.tv

9 Tem 2024 Sal 22:25 tarihinde Memil Mert ***@***.***> şunu yazdı:

**Comment by memil33m** [comment]
All of them are not working, I cannot log in to the site. I also requested
two sites from you. I would appreciate it if you could add them as well.
pdcams.com trannytube.tv

9 Tem 2024 Sal 22:33 tarihinde Memil Mert ***@***.***> şunu yazdı:

**Comment by dobbelina** [comment]
No log file, closing thread.
