### ISSUE TITLE
speedporn not populating 

### ISSUE THREAD

**Issue by durangorob** [dobbelina/repository.dobbelina#1381]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Site Speedporn in Cumination is not populating any streams.  Categories also not working properly.   I will also report that in the past 6 months under the category " Lesbian" there are usually a few different ones , but the main one that had all the listings that had over 3000,  for Lesbians had disappeared.   I am viewing on an android streaming box.  Please check it out using android.  

### Kodi version

21.0

### Cumination version

1.1.111

### Operating System and version

android 12

### URL to debug log file

not available

**Comment by dobbelina** [comment]
Issue confirmed, thanks for reporting.
