### ISSUE TITLE
SexTB - No thumbnails

### ISSUE THREAD

**Issue by EvelK1203** [dobbelina/repository.dobbelina#1383]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

No thumbnails for any videos

### Kodi version

21

### Cumination version

1.1.111

### Operating System and version

Windows 11 Home

**Comment by dobbelina** [comment]
Issue confirmed, thanks for reporting.

**Comment by TapeMeOh** [comment]
Also noticed that search doesn't seem to work either.
