### ISSUE TITLE
Eporner Video - Blank listing

### ISSUE THREAD

**Issue by Skazza967** [dobbelina/repository.dobbelina#1386]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Blank results for main page, search and tags. Categories populate but no results once entering.

### Kodi version

21

### Cumination version

1.1.111

### Operating System and version

Android aosp 9

**Comment by dobbelina** [comment]
Issue confirmed, thanks for reporting.
