### ISSUE TITLE
video speed control

### ISSUE THREAD

**Issue by tkl45** [dobbelina/repository.dobbelina#1396]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.

### Description

can you add a .5 And a .25 video speed control option? that would be amazing!!!

**Comment by 12asdfg12** [comment]
You can set the speed from the kodi player

![image](https://github.com/user-attachments/assets/6ebb1bd3-10b6-4943-b3df-a0c485f82f51)

![image](https://github.com/user-attachments/assets/dc140a79-7751-496c-aa99-427e81beb809)

**Comment by tkl45** [comment]
thank you for responding. i do not have that option on firestick. i do have the latest version

**Comment by 12asdfg12** [comment]
go into the Kodi settings and turn on Sync Playback to Display

**Comment by tkl45** [comment]
yess!! 1000 thank yous!

**Comment by tkl45** [comment]
it only goes down to .80 :/ kinda bummed, i do appreciate your help and knowledge

**Comment by 12asdfg12** [comment]
it's a player setting, it can't be adjusted from the add-on

**Comment by tkl45** [comment]
so it is something that can be changed in the kodi settings?

**Comment by 12asdfg12** [comment]
As far as I know, the limits are set in the player, I don't think they can be changed

**Comment by tkl45** [comment]
gotchya, again your help is much appreciated!!!!
