### ISSUE TITLE
Naughty blog (derbid only) 

### ISSUE THREAD

**Issue by Cgritsch89** [dobbelina/repository.dobbelina#1398]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.

### Description

How I can login in derbid and how I can watch the scenes of this blog?

**Comment by EvelK1203** [comment]
In Cumination addon settings go to "Hosts and Resolvers". Click on "Open ResolveURL settings".  Click on "Universal Resolvers 2" and scroll to Real-Debrid. Authorize your RD account and you will be good go.

I've only used this with RD, not sure how effective the other debrid services are.

**Comment by Cgritsch89** [comment]
Thx
