### ISSUE TITLE
DaftSex does not play videos

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#14]
A number of posters have mentioned in other threads that DraftSex does not currently work. It displays a list of scenes but they are not playable.

**Comment by jdoedev123** [comment]
A number of posters have mentioned in other threads that DraftSex does not currently work. It displays a list of scenes but they are not playable.

**Comment by jdoedev123** [comment]
Example DEBUG log:
16:44:18.025 T:140599553259264   DEBUG: ResolveURL: adding resolver to cache: <class 'resolveurl.plugins.vk.VKResolver'>
16:44:18.026 T:140599553259264   DEBUG: ResolveURL: Resolving using VK.com plugin
16:44:18.487 T:140599553259264   ERROR: ResolveURL: ResolverError Error - From: VK.com Link: https://vk.com/video-158318140_456239784: No Video Link Found
16:44:18.487 T:140599553259264   DEBUG: ResolveURL: Traceback (most recent call last):
                                              File "/home/martin/.kodi/addons/script.module.resolveurl/lib/resolveurl/hmf.py", line 186, in resolve
                                                stream_url = resolver.get_media_url(self._host, self._media_id)
                                              File "/home/martin/.kodi/addons/script.module.resolveurl/lib/resolveurl/plugins/vk.py", line 49, in get_media_url
                                                source = helpers.pick_source(sources)
                                              File "/home/martin/.kodi/addons/script.module.resolveurl/lib/resolveurl/plugins/lib/helpers.py", line 71, in pick_source
                                                raise ResolverError(common.i18n('no_video_link'))
                                            ResolverError: No Video Link Found

**Comment by john12345670** [comment]
Thank you very much for looking into daftsex jdoedev123! it's by far the most up to date with new videos releases. I've looked at the source code page for daftsex and they have mostly moved from VK.com to crazycloud.ru. So some videos still plays from VK.com but when it's hosted on crazycloud.ru it failed to resolve the video. I've tried changing the line from:
video = 'https://vk.com/video' + re.compile("Fav.Toggle\(this, '([^']+)'",
to:
video = 'https://crazycloud.ru/videos/' + re.compile("Fav.Toggle\(this, '([^']+)'",

But the sever numbers keeps changing (https://psv20-3, https://psv20-2, https://psv17-2 etc) so it won't work.

Thanks for taking the time to look into it, if it's too much work to fix then there's nothing that can be done about it. Again it's much appreciated that you spent your time trying fix the addon.

**Comment by dobbelina** [comment]
Another addon to add to the "Fix-whishlist" is **tubepornclassic**

**Comment by ohmichael** [comment]
Please fix

**Comment by 12asdfg12** [comment]
I found a solution for the crazycloud.ru links.
It's not perfect, and requires to try different server links until the right one is found, but it works.
No solution for daxab.com links, but the latest videos are hosted on crazycloud.
[daftsex.zip](https://github.com/dobbelina/repository.dobbelina/files/3004617/daftsex.zip)

**Comment by dobbelina** [comment]
Thanks 12asdfg12!

I have updated the addon.

**Comment by john12345670** [comment]
Thanks 12asdfg12!

Much appreciated that you use your spare time to look at the plugin!

**Comment by imurreflection** [comment]
Hi 12asdfg12,Dobbelina,John12345670 and Jdoedev123. 
Thank you for getting the daftsex issue fixed. Now, may I please request you to extend your expertise and look at Hclips under "Tubes" section please . This site has huge library and very good content similar to daftsex,porntrex,hqporner etc

**Comment by mhtamal** [comment]
> I found a solution for the crazycloud.ru links.
> It's not perfect, and requires to try different server links until the right one is found, but it works.
> No solution for daxab.com links, but the latest videos are hosted on crazycloud.
> [daftsex.zip](https://github.com/dobbelina/repository.dobbelina/files/3004617/daftsex.zip)

hey can anyone tell me what to do with this zip file to fix the issu
