### ISSUE TITLE
Javwhores private videos - account not working

### ISSUE THREAD

**Issue by DaisyF8** [dobbelina/repository.dobbelina#140]
If I go to the website with my account the videos play, but in the addon they don't.

Error-message "Add an account in settings to watch..."

```
2019-11-21 06:32:30.824 T:139766457566976 WARNING: Attempt to use invalid handle -1
2019-11-21 06:32:30.955 T:139766457566976  NOTICE: ResolveURL: Initializing ResolveURL version: 5.0.36
```

**Comment by DJMix-I-Can** [comment]
I'm not familiar with Javwhores & wanted to test it out BUT how do you know if the video is private. I don't see a private section or any type of notification stating it's private. I went through numerous videos and they all played. Can you provide a private video link?

**Comment by DaisyF8** [comment]
Go with a browser to the website, they are marked there wether they are private or not.

**Comment by imurreflection** [comment]
Please advise Kodi version. It seems to be an issue with  Kodi 18. Please roll back to 17.6 and retry. Also, if you go to settings of UWC, you will find the account credentials required info for javwhores and porntrex. Input your credentials there and please try.

**Comment by DaisyF8** [comment]
I'm in 18.5 and staying there.

I'm using my account credentials in UWC for both.  That's why I said the acount isn't working, but it is "If I go to the website with my account".

Could this be the same ResolveURL-issue there was with AnimeID-Hentai ?

**Comment by DaisyF8** [comment]
Solved

JavWhores is now JavBangers (I think, as part of Porntrex) and my accountinfo works !

Thx, however this got solved.
