### ISSUE TITLE
Unable to play videos from

### ISSUE THREAD

**Issue by Keymag007** [dobbelina/repository.dobbelina#1407]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Unable to play videos from Perverzija, xVideos, FamilypornHD

Not working: PeekVids, PlayVids, Thepornfull.

### Kodi version

21.0 and 21.1

### Cumination version

1.1.113

### Operating System and version

Android 13, Android 14, and Win 10

**Comment by Keymag007** [comment]
I will add more when I see the rest

**Comment by dobbelina** [comment]
duplicate
