### ISSUE TITLE
Updates not available

### ISSUE THREAD

**Issue by user91234** [dobbelina/repository.dobbelina#1408]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Recent updates are not available in the addon, it seems that the addon is still in version 1.1.113

### Kodi version

21

### Cumination version

1.1.113

### Operating System and version

Android, Windows

**Comment by dobbelina** [comment]
Yes, version 1.1.114 has not been released yet.
It will be on Aug 25
