### ISSUE TITLE
Not letting me install

### ISSUE THREAD

**Issue by Joemo3344** [dobbelina/repository.dobbelina#1418]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Trying to update to 1.1.115 and its keeps saying failed dependency for 
Websocket failed to install .

### Kodi version

21.1

### Cumination version

1.1.115

### Operating System and version

HP Google

**Comment by dobbelina** [comment]
Try to download the dependency zip file and install it manually.
[script.module.websocket-1.6.4.zip](https://mirrors.kodi.tv/addons/matrix/script.module.websocket/script.module.websocket-1.6.4.zip)
