### ISSUE TITLE
Camsoda only works partly 

### ISSUE THREAD

**Issue by onknight** [dobbelina/repository.dobbelina#142]
Okay guys,
When using the camsoda part of the app I find that it only works partially
Yes it will open some cam models but not all of them it shows on the list
I can click on it several times and it just bounces me out
I am using Kodi on Windows 10 PC  
But this also happens on my Mibox  as well 
so right now cam soda is very hit and miss 

Is there any way to make it more consistent
Also any word on fixing naked.com

**Comment by DJMix-I-Can** [comment]
Yup, it's an authentication issue. I checked on the Sheild & Win7 laptop. This is the error in the log file.
" ERROR: CCurlFile::FillBuffer - Failed: Peer certificate cannot be authenticated with given CA certificates(60)
2019-12-08 11:49:48.780 T:2620   ERROR: CCurlFile::Open failed with code 0 for https://edge17-ord.camsoda.com/cam/mp4:cam_high/miawilddoll-flu-ingest2-bog_h264_aac_480p/playlist.m3u8?token=eyJpdiI6IkpJZGJGcHZwSlJZaHltenhhTXpJZ2c9PSIsInZhbHVlIjoiaFRPMzBuYkpuXC9uWmt1Mm90RGFPM1E9PSIsIm1hYyI6IjI3ZjgzYmU3ZWE0ZjRkMmY2Nzk3ZjNhNDgwZGYwMWE2OGZiY2U3ZWE0NzhhNjU2ZDFjZWUxNjdiMWUxNjI2NTEifQ==:"

**Comment by jdoedev123** [comment]
I am also getting inconsistent results with CamSoda. It may not be a UWC problem but a problem with the website. I am seeing SSL certificate errors for some streams which may indicate CamSoda may not have set up their Certificates correctly for all of their edge servers. This may be a different problem then you saw in Dec 2019 as the Certificates were changed in late May- Early June   2020.
