### ISSUE TITLE
Better Gay search results

### ISSUE THREAD

**Issue by Durutti72** [dobbelina/repository.dobbelina#1426]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.

### Description

Many of the sites EG X-Hamster have gay sections. These are not reflected in cumination. Also The Gay does not work.

**Comment by 12asdfg12** [comment]
In xhamster, you can change the category to gay or shemale in the context menu:
The gay works for me.

![image](https://github.com/user-attachments/assets/7d15eb63-e405-4dac-99af-39399a1ec045)

**Comment by Durutti72** [comment]
Mine doesn't have that as an option. Categories are all straight porn types.
