### ISSUE TITLE
Porntrex.com, Noodlemagazine.com, Spankbang.com,Luxure.tv

### ISSUE THREAD

**Issue by bOuNtYhUnTeR2022** [dobbelina/repository.dobbelina#1427]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

The Sites in the title got Isuues/stopped working at all:

PORNTREX.COM = site opens but no Videos, no search result, no categories
Spankbang.com = site doesn't open up at all
Luxuretv.com = site doesn't open up at all
Noodlemagazine.com = no pictures, search working, vids playing

guys, sadly I got no time to send individual log files. Maybe someone with more free time can do this. I tried my best to get you informed. Would be great if you could get these sites back to life again :)

Habe a great day 

### Kodi version

21.1

### Cumination version

1.1.116

### Operating System and version

Libreelec 13.0

**Comment by 12asdfg12** [comment]
porntrex works for me
spaknkbang & luxuretv - works with flaresolverr
noodlemagazine - most of the thumbnails are displayed. I found some that are not displayed, this will be fixed in the next version

**Comment by bOuNtYhUnTeR2022** [comment]
> porntrex works for me spaknkbang & luxuretv - works with flaresolverr noodlemagazine - most of the thumbnails are displayed. I found some that are not displayed, this will be fixed in the next version

Hey, thanks for the quick response. OK, can you tell me what to set as port if flaresolverr is activated? If I set it to active some sites even Stopp working, as port I choosed a random one not released inside my fritz.box. But none of the sites 'should' work does. :( thanks for a short response

**Comment by dobbelina** [comment]
@bOuNtYhUnTeR2022 
My flaresolverr is set to port 8191
