### ISSUE TITLE
JustPorn has a fragment of code in the titles of the videos

### ISSUE THREAD

**Issue by Ariesun24** [dobbelina/repository.dobbelina#1428]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

There is a "< /div >" in all the titles of the videos

### Kodi version

20.5 Nexus

### Cumination version

1.1.117

### Operating System and version

Windows 10

**Comment by 12asdfg12** [comment]
Fixed in 1.1.118
