### ISSUE TITLE
[Add-on] Does not remember/save interface view type

### ISSUE THREAD

**Issue by thereddestdog** [dobbelina/repository.dobbelina#1433]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.

### Description

I tested with both Artic Zephyr Reloaded and the default Estuary skins, and I was wondering if it could be fixed so that whatever view I selected (Poster, large wall, etc) it would remember 

Is there some overwrite happening when going into sub menus?

**Comment by dobbelina** [comment]
@thereddestdog 
Check in settings if "Enable custom view types" is selected, if it is, de-select it.

**Comment by deejayadhd** [comment]
I just started having this issue a few days ago also. On kodi 21 with arctic zephyr reloaded skin and default kodi skin. I checked and "enabled custom view types" is checked.
