### ISSUE TITLE
Bug : Aagmaal listing broken, domain changed

### ISSUE THREAD

**Issue by CeeBro082** [dobbelina/repository.dobbelina#1434]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Aagmaal has shifted domain to Aagmaal.monster, the listing has broken on Kodi now

### Kodi version

Omega 21.1

### Cumination version

1.1.117

### Operating System and version

FireOS 6.7.0.5

**Comment by dobbelina** [comment]
Fixed in 1.1.118
