### ISSUE TITLE
Porntrex.com pagination doesn't work (only user uploaded content works) 

### ISSUE THREAD

**Issue by bOuNtYhUnTeR2022** [dobbelina/repository.dobbelina#1435]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

The pagination seems doesn't work anymore. If you browse through user uploaded content by pressing context menu, then click user on bottom it does the pagination 🤔

### Kodi version

21

### Cumination version

1.1.117

### Operating System and version

Libreelec

**Comment by 12asdfg12** [comment]
Everything works for me, you need to post a log file.
