### ISSUE TITLE
Whereismyporn: No Thumbnail for first entry of each page - fix included

### ISSUE THREAD

**Issue by jojodat** [dobbelina/repository.dobbelina#1448]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Hi,
i noticed, on Whereismyporn, there is no Thumbnail for first entry of each page
i modified the RegEx a bit and now it works:
`    match = re.compile('<img.*?src="([^"]+)".*?entry-title"><a href="([^"]+)"[^>]+>([^<]+)<', re.DOTALL | re.IGNORECASE).findall(listhtml)
`

### Kodi version

21.1

### Cumination version

v.1.1.119

### Operating System and version

Fire OS 7.6.6.9 (AndroidTV 9)

**Comment by dobbelina** [comment]
@jojodat Thanks for the fix, will be in the next release.
