### ISSUE TITLE
StreamXXX search function lacks Next Page

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#145]
Thanks for fixing StreamXXX.  Search function shows Next Page (038) which leads nowhere at bottom of search page.

**Comment by 12asdfg12** [comment]
fixed, thanks.

**Comment by dobbelina** [comment]
Hi 12asdfg12,

Next page works but search and categories are missing?

**Comment by 12asdfg12** [comment]
Maybe you are looking in Movies, Streamxxx from Scenes have tags and search.

xhamster:
"header_block" is just a part of the web page (which does not contain the "Next" link), you have to search the entire page, which is "response"

`        next_page = re.compile('data-page="next" href="([^"]+)"', re.DOTALL | re.IGNORECASE).findall(response)[0]`

**Comment by dobbelina** [comment]
> 
> 
> Maybe you are looking in Movies, Streamxxx from Scenes have tags and search.
Ahh, sorry, you are right. 
> xhamster:
> "header_block" is just a part of the web page (which does not contain the "Next" link), you have to search the entire page, which is "response"
> 
> ` next_page = re.compile('data-page="next" href="([^"]+)"', re.DOTALL | re.IGNORECASE).findall(response)[0]`
Awesome, thanks!
Now i learned something as well 😄
