### ISSUE TITLE
XHamster : Video Listing broken

### ISSUE THREAD

**Issue by CeeBro082** [dobbelina/repository.dobbelina#1453]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

XHamster listing broken, displays no videos

### Kodi version

20.1

### Cumination version

1.1.120

### Operating System and version

FireOS 6.7.0.5

**Comment by dobbelina** [comment]
Thanks for reporting, I can confirm the issue
