### ISSUE TITLE
Speedporn, no thumbnails

### ISSUE THREAD

**Issue by grntbggr** [dobbelina/repository.dobbelina#1461]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Speedporn hasn't shown Thumbnails in about a week.

### Kodi version

19.4

### Cumination version

1.1.120

### Operating System and version

Android

**Comment by Gujal00** [comment]
Duplicate of recently fixed and closed #1457

**Comment by grntbggr** [comment]
My mistake.  Forgot to check the log.  Thx
