### ISSUE TITLE
SSL certificate troubles with Gounlimited files?

### ISSUE THREAD

**Issue by tetzy** [dobbelina/repository.dobbelina#148]
I'm using the auto update version of Whitecream on Android:

I'm being stopped from viewing and downloading files from gounlimited. Apparently, the SSL certificate can't be verified. All other sites work as expected.

Is this just on my end, or is this a problem across the board?

![Screenshot_01](https://user-images.githubusercontent.com/59111079/71308830-61376480-23be-11ea-9d68-9aadc6c4a4c2.png)
![Screenshot_02](https://user-images.githubusercontent.com/59111079/71308831-64325500-23be-11ea-9ae5-f7f9d804074d.png)
![Screenshot_03](https://user-images.githubusercontent.com/59111079/71308833-6694af00-23be-11ea-9519-28059375659b.png)
![Screenshot_04](https://user-images.githubusercontent.com/59111079/71308835-6a283600-23be-11ea-8d5a-13ffd6d5575c.png)

**Comment by DJMix-I-Can** [comment]
Yeah, it's a problem with the gounlimited.py file in the ResolveURL by Jsergio123.  The same problem [occurred last month](https://www.reddit.com/r/Addons4Kodi/comments/dtnssa/resolveurl_problem_with_ssl/)

**Comment by dobbelina** [comment]
Closing issue because  ResolveURL related.
