### ISSUE TITLE
a few updates

### ISSUE THREAD

**Issue by 12asdfg12** [dobbelina/repository.dobbelina#15]
Fixed: Porn-czech 
Added: xvideoshits.com
Minor fixes: poldertube & sextube

please consider updating the addon
Thanks!

[update.zip](https://github.com/dobbelina/repository.dobbelina/files/2922975/update.zip)

**Comment by Sameer888** [comment]
Hi Mate can you please add perfectgirls.net or Porndoe.com or Cliphunter.com any two which ever you like as they have all HD content and there is vast collection of full length videos on these sites

http://m.perfectgirls.net/
https://porndoe.com/
https://www.cliphunter.com/

**Comment by Sameer888** [comment]
I have updated the addon please help me how to upload a zip file on github

**Comment by 12asdfg12** [comment]
You can't update the addon on github, only dobbelina can, this is his repository.
Here is the files for perfectgirls, i have no time to add the other 2 sites

[update1.zip](https://github.com/dobbelina/repository.dobbelina/files/2923352/update1.zip)

**Comment by Sameer888** [comment]
12asdfg12 thank yu very much for updating one of the site please add 2 sites whenever you have time i am very thankful for your reponse and i have copied the zip .py files to the addon and created a zip of the addon to make dobbelina work easy to upgrade the addon 
 So that is why i wanted to upload zip to our issue on this page

**Comment by dobbelina** [comment]
Thanks 12asdfg12!

Addon will be updated to Version 1.1.68

**Comment by Sameer888** [comment]
Hi 12asdfg12 the other 2 sites has been added to another addon so its not necessary to update here if yu wish than its Ok 

Thank yu once again👍

**Comment by Sameer888** [comment]
Hi dobbelina Pls add one more site perfectgirls.com its created by 12asdfg12 in this issue 
Thanks

**Comment by bbox1** [comment]
Added porndoe & cliphunter.
[update.zip](https://github.com/dobbelina/repository.dobbelina/files/2949654/update.zip)

**Comment by 12asdfg12** [comment]
Added: cliphunter & porndoe

[update.zip](https://github.com/dobbelina/repository.dobbelina/files/2949658/update.zip)

**Comment by dobbelina** [comment]
Thanks Thanks 12asdfg12!, will update the addon again.

**Comment by Sameer888** [comment]
Thank you so much 12asdfg12

**Comment by 12asdfg12** [comment]
No problem!

2 more fixes:
Porndoe - Channels directory (i forgot a '/'  )
Yourporn

[porndoe.zip](https://github.com/dobbelina/repository.dobbelina/files/2962617/porndoe.zip)
[yourporn.zip](https://github.com/dobbelina/repository.dobbelina/files/2962618/yourporn.zip)

**Comment by dobbelina** [comment]
Thanks again!

**Comment by 12asdfg12** [comment]
beeg & spankbang:

[beeg&spankbang.zip](https://github.com/dobbelina/repository.dobbelina/files/3055323/beeg.spankbang.zip)

**Comment by dobbelina** [comment]
Thanks 12asdfg!

**Comment by imurreflection** [comment]
Hey mate ..can you please look at hclips under tubes section please and fix it. The site URL has been changed to https and the landing page URL gives 404 error

**Comment by 12asdfg12** [comment]
SORRY ... hclips is hard to fix, the links for videos is generated by obfuscated javascript functions

Found a bug in beeg.py (crashed at start, on some configurations), fixed, k18 fixed
[beeg.zip](https://github.com/dobbelina/repository.dobbelina/files/3076320/beeg.zip)
[k18.zip](https://github.com/dobbelina/repository.dobbelina/files/3076321/k18.zip)

**Comment by dobbelina** [comment]
Again, much thanks!

**Comment by 12asdfg12** [comment]
Thanks, also there is an issue with category names containing Space.

updates:
[uwc.zip](https://github.com/dobbelina/repository.dobbelina/files/3097767/uwc.zip)

Videomegaporn replaced with viralvideosx.
Added: xmoviesforyou & freepornstreams
Removed: Elreyx

**Comment by dobbelina** [comment]
Once again, awesome work.
Thanks 12asdfg!

**Comment by 12asdfg12** [comment]
added: xozilla
fixed: xmoviesforyou (next page + categories)

[3.zip](https://github.com/dobbelina/repository.dobbelina/files/3121278/3.zip)

**Comment by dobbelina** [comment]
Thanks Thanks 12asdfg!

Will update tomorrow, tired today.

**Comment by imurreflection** [comment]
Hi 12asdfg12.  Can you please add javhihi.me. thus is one of the best Japanese uncensored HD site

**Comment by 12asdfg12** [comment]
javhihi use javascript for the video links, i'll pass

fixed xtheatre, pornhive & xvideohits(images)

[4.zip](https://github.com/dobbelina/repository.dobbelina/files/3168945/4.zip)

**Comment by imurreflection** [comment]
Thank you so much sir

**Comment by dobbelina** [comment]
Thanks a lot.
I'll update immediately.

**Comment by 12asdfg12** [comment]
daftsex updated (daxab.com links works)
[daftsex.zip](https://github.com/dobbelina/repository.dobbelina/files/3194978/daftsex.zip)

**Comment by dobbelina** [comment]
Thanks 12asdfg12,

Will update in next release.

**Comment by 12asdfg12** [comment]
viralvideosx - removed false message 'website is down'
freeomovie - fixed (except filecrypt, probably broken on website) 

[viralvideosx.zip](https://github.com/dobbelina/repository.dobbelina/files/3220096/viralvideosx.zip)
[freeomovie.zip](https://github.com/dobbelina/repository.dobbelina/files/3220097/freeomovie.zip)

**Comment by dobbelina** [comment]
You are awesome 12asdfg12, thanks!

**Comment by 12asdfg12** [comment]
xvideoshits - fixed
xtheatre -  updated to work with the new utils.py from WhitecreamDev 

[xt-xv.zip](https://github.com/dobbelina/repository.dobbelina/files/3269350/xt-xv.zip)

**Comment by dobbelina** [comment]
Thanks 12asdfg12 !
Will update addon after you had a look at Daftsex, as it seems broken again?

**Comment by imurreflection** [comment]
Hi Dobbelina, I randomly played 3 videos from Daftsex and they appears to be working fine. Kindly update the add-on.

**Comment by 12asdfg12** [comment]
The server address for video links on Daftsex was changed (from daxab.com to dxb.to), i fixed the addon, then the change was reverted, that's why the latest version doesn't work.
daftsex.py from version 1.1.80 should work, or there is a version which works with both address, daxab and dxb
[daftsex.zip](https://github.com/dobbelina/repository.dobbelina/files/3272179/daftsex.zip)

**Comment by dobbelina** [comment]
Amazing!
Thanks 12asdfg12.

**Comment by 12asdfg12** [comment]
xvideoshits - fixed

[xvideoshits.zip](https://github.com/dobbelina/repository.dobbelina/files/3291524/xvideoshits.zip)

**Comment by dobbelina** [comment]
Thanks 12asdfg12,

Will update now.
