### ISSUE TITLE
Auto Update?

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#16]
Hi Dobbelina, I tried updating the add-on to 1.1.68 using your repository but did not find it. The only version available there is 1.1.67. It seems like auto update is broken. Can you please look at this

**Comment by Sameer888** [comment]
Send the Repo

**Comment by dobbelina** [comment]
I did some stuff with the addon about your time of posting.
go into the repo again and it will be there.
you have downloaded and installed this right?
https://github.com/dobbelina/repository.dobbelina/raw/master/repository.dobbelina-1.0.0.zip

**Comment by imurreflection** [comment]
Yes and it appears that Kodi 18 is not supporting this. Switched back to Jarvis and the add-on was there. Thank you. Should I close this issue now?
