### ISSUE TITLE
Daftsex issue

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#161]
On most links, getting "VK Link could not be resolved." I even tried using VPN bit its of no use. Could you please look into this.

Thanks

**Comment by 12asdfg12** [comment]
I tried the videos on the first page and they all worked.
Try with the version from the latest PR, i added 2 new servers.
VK links works only with a premium account.

**Comment by imurreflection** [comment]
Thank you mate. The issue is resolved now. Closing it.
