### ISSUE TITLE
Seaporn

### ISSUE THREAD

**Issue by java-jet** [dobbelina/repository.dobbelina#162]
Please add seaporn.org

**Comment by 12asdfg12** [comment]
not possible, not a streaming website

**Comment by java-jet** [comment]
I see, but most links on this website are in .mp4 format which can be easily played through Kodi with URL resolver.

**Comment by 12asdfg12** [comment]
you cannot stream from the hosts used (uploaded, rapidgator, uptobox, keep2share) without a paid account
