### ISSUE TITLE
Woxtube not working

### ISSUE THREAD

**Issue by Orbeatle** [dobbelina/repository.dobbelina#165]
Videos won't start playing. Been the case now for some weeks.

**Comment by dobbelina** [comment]
Confirmed, marked broken.

**Comment by Orbeatle** [comment]
Too bad tho. Great resource..

**Comment by 12asdfg12** [comment]
website changed to pornaq.com, fixed

**Comment by dobbelina** [comment]
Thanks 12asdfg12!, closing issue.
