### ISSUE TITLE
Chaturbate down ... quick fix

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#17]
Chaturbate down again.
A quick fix replace line 131:    
match = re.compile(r'<li.+?data-slug="(.+?)".+?<a href="(\/.+?)".+?<img\s+src="(.+?)".+?_label.+?>(.+?)<.+?age.+?>(.+?)<', re.DOTALL | re.IGNORECASE).findall(listhtml)

Optionally cleanup age display with line 134:
        age = utils.cleantext(age.strip())

**Comment by dobbelina** [comment]
Thanks jdoedev for the fix.
I'll incorporate it in the next release.

**Comment by jdoedev123** [comment]
[chaturbate.py.zip](https://github.com/dobbelina/repository.dobbelina/files/2943692/chaturbate.py.zip)

Proposed fix for Chaturbate
