### ISSUE TITLE
Add Fantasti.cc from (probably) abandoned project

### ISSUE THREAD

**Issue by DaisyF8** [dobbelina/repository.dobbelina#173]
Fantasti.cc would be a great site to add. There is a now partially working addon, search and login not working.

I tried contacting people at xbmc-adult for information but no response.  Addon hasn't been updated in a long time. I don't know how to contact dev Ksosez.

https://github.com/xbmc-adult/xbmc-adult/tree/ghmaster/plugin.video.fantasticc
https://github.com/xbmc-adult/xbmc-adult/issues/325
https://github.com/dobbelina/repository.dobbelina/issues/37

**Comment by Gujal00** [comment]
@DaisyF8 addon in xbmc-adult repo is fixed, waiting for approval
https://github.com/xbmc-adult/xbmc-adult/pull/334
