### ISSUE TITLE
Absoluporn

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#175]
Does not play at all. Nothing happens when you click a link. Moreover, no thumbnails.

**Comment by DJMix-I-Can** [comment]
Just tested, everything is working.

**Comment by imurreflection** [comment]
Ever since the entire add-on is available through VPN only, I am experiencing most of the issues. How are you accessing it mate?

**Comment by DJMix-I-Can** [comment]
Not sure what you mean by this "Ever since the entire add-on is available". I'm just connected normally, no VPN. Cable modem, router to devices. I'm in the U.S.

**Comment by imurreflection** [comment]
I India, UWC is now available through VPN only on my ISP.

**Comment by dobbelina** [comment]
Site works fine, though I don't need vpn to access it.

**Comment by imurreflection** [comment]
This seems to be an issue with my set-up and I have raised another issue for it. Closing the issue now.
