### ISSUE TITLE
Addon Issue - Please help.

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#176]
Hi Dobbelina and 12asdfg12!,

I am experiencing a unique issue. Please help.

Till version 1.2.8 everything was playable trough direct connectivity and no VPN was required.  VPN was required only when sites which are geographically blocked are watched. However, after version 1.2.9 and latest 1.2.10, I am facing issue that entire addon can be opened only once VPN is connected. However, this also brings along multiple issues like no thumbnails in various sites, speed throttling and some sites not playing at all one such example would be absoluporn. This is on Kodi 18.5 and on Kodi 17.6 and Android Boxes are Mecool KM9 Pro (Android 9) and MX9 Pro (Android 8). The skin I am using is AEON NOX SILVO MOD.

However, I tried multiple options like upgrading/downgrading Kodi versions from 18.5 to 17.6 and vice versa on both the boxes including installing versions 1.2.9 and 1.2.10, copying all "Sites" from working version 1.2.8 to latest version 1.2.10, changing skins to confluence and others
but to no avail. It seems like some changes were made in version 1.2.9 which eventually resulted in this. 

Kodi Error log is attached. Kindly let me know if you need anything else

[current log.txt](https://github.com/dobbelina/repository.dobbelina/files/4169458/current.log.txt)

**Comment by imurreflection** [comment]
Upon further digging of log, I found that it was pointing to some error in myfreecams so I manually copied all latest commits (except myfreecams)of 12asdfg12! and pasted them in their respective folders in version 1.2.8 and installed on Kodi. Though, I was not helpful, the add-on worked without VPN connectivity. I thought I must mention this to you.

**Comment by 12asdfg12** [comment]
In your log file you received an error when trying to download a server list from address https://new.myfreecams.com/server
Try this address in a browser to check if you can access the server without errors.
In any case, this should not affect the rest of uwc.

**Comment by imurreflection** [comment]
The URL is accessible when using VPN. However, the UWC add-on does not open.  If I remove myfreecams commits, it works just fine. Even on VPN, the add-on does not open as confirmed by one of other UWC user. Kindly help mate

**Comment by 12asdfg12** [comment]
Install the latest uvc and replace myfreecam.py with the attached one.
[myfreecams.zip](https://github.com/dobbelina/repository.dobbelina/files/4174536/myfreecams.zip)

This should fix the addon crash issue, but MFC probably won't work if you have problems downloading from MFC.

**Comment by imurreflection** [comment]
Bro, thank you so much. Let me do this and I will revert to you.

**Comment by imurreflection** [comment]
Thank you again mate. Its working now. May I know what exactly went wrong here to avoid future issues like this please.

CC: Dobbelina : Kindly include this fix in next update please.

**Comment by 12asdfg12** [comment]
In the latest version, a list of servers has been downloaded on startup.
In your case, the failure to download this list cause an exception that crash the add-on. I have changed the download code so it's executed only for MFC.

**Comment by imurreflection** [comment]
Thank you again bro..this is really appreciated

**Comment by dobbelina** [comment]
Awesome!

Will include in next update.

**Comment by imurreflection** [comment]
Hi 12asdfg12 and Dobbelina...thank you for addressing the issue. Closing this now.
