### ISSUE TITLE
Adroid UWC: Resolver issues ::: Amended 2/11/20

### ISSUE THREAD

**Issue by tetzy** [dobbelina/repository.dobbelina#177]
Edited 2/11/2020: 

My initial report stated that playing/downloading Gounlimited files were met with a "Resolve failed, Gounlimited link could not be resolved" error message.

For the most part the issue has been fixed with new files, but older files (even 24hrs before the fix) kept in the "Favorites" menu still get the same error:

Resolve failed
Gounlimited link could not be resolved 

There were 11 pages of error details, I don't know which are pertinent to the problem so I uploaded them  all:

![Screenshot_2020-02-10-23-29-33](https://user-images.githubusercontent.com/59111079/74218782-1de3ce80-4c68-11ea-9788-5147b570356a.png)

![Screenshot_2020-02-10-23-29-47](https://user-images.githubusercontent.com/59111079/74218791-276d3680-4c68-11ea-9fb0-a1ce7ee2ddc4.png)

![Screenshot_2020-02-10-23-29-54](https://user-images.githubusercontent.com/59111079/74218820-3f44ba80-4c68-11ea-95bb-2d1644d8c386.png)

![Screenshot_2020-02-10-23-30-06](https://user-images.githubusercontent.com/59111079/74218850-4ff53080-4c68-11ea-86d6-1ec58f343b0c.png)

![Screenshot_2020-02-10-23-30-17](https://user-images.githubusercontent.com/59111079/74218861-55527b00-4c68-11ea-8105-86d46f120d7f.png)

![Screenshot_2020-02-10-23-30-23](https://user-images.githubusercontent.com/59111079/74218887-67341e00-4c68-11ea-8a85-1a5c878a96ef.png)

![Screenshot_2020-02-10-23-30-28](https://user-images.githubusercontent.com/59111079/74218902-74510d00-4c68-11ea-802a-7de8a025bfbc.png)

![Screenshot_2020-02-10-23-30-40](https://user-images.githubusercontent.com/59111079/74218912-7d41de80-4c68-11ea-89be-2bcd878711d7.png)

![Screenshot_2020-02-10-23-30-45](https://user-images.githubusercontent.com/59111079/74218928-85018300-4c68-11ea-9459-9fc306ef1db9.png)

![Screenshot_2020-02-10-23-30-52](https://user-images.githubusercontent.com/59111079/74218943-8fbc1800-4c68-11ea-8d04-dba06d061ca5.png)

![Screenshot_2020-02-10-23-31-02](https://user-images.githubusercontent.com/59111079/74218956-95b1f900-4c68-11ea-9f17-1394ee2f1158.png)

It appears I've found a wasps nest...

Any help you can provide will be greatly appreciated. 
Thank you.

**Comment by 12asdfg12** [comment]
Resolver issues should be reported on resolveurl github (https://github.com/jsergio123/script.module.resolveurl/issues).
