### ISSUE TITLE
Repo not working

### ISSUE THREAD

**Issue by onknight** [dobbelina/repository.dobbelina#18]
I been able to get repo to install  on kodi `18.1
is there a work around

**Comment by dobbelina** [comment]
Are you having the same problem as this?:
https://github.com/dobbelina/repository.dobbelina/issues/16

**Comment by Sameer888** [comment]
Kodi 17.6 is the stable version and many other addon updates are not working in kodi 18 leia so its better to downgrade your kodi version

**Comment by onknight** [comment]
ya I just upgrade my hand till the repo works with 18.1
Thanks guys

**Comment by norteno44** [comment]
What is the repo for dobbelina please anyone???

**Comment by 12asdfg12** [comment]
https://github.com/dobbelina/repository.dobbelina/blob/master/repository.dobbelina-1.0.0.zip
btw repo is working great for me, with kodi18.2

**Comment by norteno44** [comment]
The repo is blank will it not work for 17.6 krypton?

**Comment by Anchor71** [comment]
repo is empty tried on 18.2 and 18.3

**Comment by yorkie07** [comment]
This worked for me with uwc on 18.2

https://bestdroidplayer.com/kodi-addons-install-guides/best-kodi-adult-addons/

**Comment by rrico27** [comment]
Can't get repo to work just blank any help pls

**Comment by yorkie07** [comment]
Who's repo bro?

Kind regards,
Craig Dyson.

________________________________

**Comment by yorkie07** [comment]
https://www.firesticktricks.com/best-kodi-addons.html

**Comment by Spokieone** [comment]
Have Kodi 18.2 and laest version 1.1.91 and all I get is the message "OH No could not find supported link"
Any help?
Thanks
