### ISSUE TITLE
Android UWC:  Memory leak error

### ISSUE THREAD

**Issue by tetzy** [dobbelina/repository.dobbelina#180]
Stumbled upon this error last night and thought I'd upload just in case it hasn't been seen before.

![Screenshot_2020-02-11-06-08-16](https://user-images.githubusercontent.com/59111079/74244639-fbb97300-4c9e-11ea-95b6-abdd691ab6e4.png)

![Screenshot_2020-02-11-06-08-28](https://user-images.githubusercontent.com/59111079/74244661-01af5400-4c9f-11ea-97d8-1d38cc580fb8.png)

Cheers, and good morning.

**Comment by 12asdfg12** [comment]
this is fixed in version 1.2.10, i guess you don't have the latest version
