### ISSUE TITLE
Eporner under "scenes" section not working

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#187]
No content. Kindly fix it.

**Comment by 12asdfg12** [comment]
fixed

**Comment by imurreflection** [comment]
Thank you for fixing this. However, the site now takes huge amount of time to open. Only spinning circle for a very very long time. This continues for categories, search etc. Before going down, the site was working fine. Can you please see if its me or everyone is facing this issue?

**Comment by 12asdfg12** [comment]
You are right. The site opens in ~10s on my PC, but it takes about 1-2 minutes on a less powerful device. I'll check tomorrow.

**Comment by 12asdfg12** [comment]
fixed
