### ISSUE TITLE
Hotpornfile

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#189]
Not working. Getting UWC error on every link.

**Comment by dobbelina** [comment]
Works for me.

**Comment by imurreflection** [comment]
Oh...not working for me though..is it something to do with latest resolve url? The new version is 2.0.01 but we used to use 2.0.03. Can you please confirm your version?

**Comment by DJMix-I-Can** [comment]
It's a hit or miss for me. What I noticed is that if the website doesn't have an embedded video on it, it won't play. If it does, it would play. All the videos have download links but they're not passing through ResolveURL, I believe.

**Comment by 12asdfg12** [comment]
I have removed from UWC the links containing "iMAGESET" in the name.
Resolveurl is not required for hotpornfile.

**Comment by imurreflection** [comment]
Thanks for addressing this. Closing the issue now.
