### ISSUE TITLE
Pornsland

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#190]
Not working. Can see quality selection page but video does not work.Kindly fix it

**Comment by DJMix-I-Can** [comment]
Looks like a site issue. If you go to porn.land and try to watch any video under https://porns.land/recent-porns, you get an "error loading media: File cannot be played." error. If you browse to any other tabs, you won't be able to play anything either.

**Comment by 12asdfg12** [comment]
website issue, video links are dead, latest video was added on 04.08.2019

**Comment by imurreflection** [comment]
Looks like they have moved to a new site porner.tv and givemeaporn.com.
