### ISSUE TITLE
Hclip don`t play

### ISSUE THREAD

**Issue by rounilax** [dobbelina/repository.dobbelina#192]
it stop to show videos and before that it don`t refresh with new videos

**Comment by 12asdfg12** [comment]
fixed

**Comment by rounilax** [comment]
![image](https://user-images.githubusercontent.com/61365480/75613071-43128100-5b32-11ea-8844-3b27e6220429.png)

**Comment by 12asdfg12** [comment]
wait for the next version, the fixed version is not  yet released

**Comment by rounilax** [comment]
your answers  is very quickly!! nice job guys!!!  continue it!!!

**Comment by dobbelina** [comment]
Issue fixed, closing.
