### ISSUE TITLE
AnimeIDHentai not updating

### ISSUE THREAD

**Issue by s4ik0s4n** [dobbelina/repository.dobbelina#195]
Not sure if this is just me, but the video listing on AnimeIDHentai is not updating. The last video I see on the add-on is for Meltys Quest Episode 1, which was posted on the website February 22nd.

**Comment by s4ik0s4n** [comment]
Tried clearing the cache, reinstalling the add-on, and restarting my device. No such luck.

**Comment by DJMix-I-Can** [comment]
The code in AnimeID points to this address https://animeidhentai.com/genre/2019/ Which on the website is under New Releases.  Which is showing correctly but you feel that it should be this instead,
https://animeidhentai.com/genre/2020/ correct?

**Comment by s4ik0s4n** [comment]
I guess that's the problem.

**Comment by s4ik0s4n** [comment]
Went and updated line 30 in animeidhentai.py from    animeidhentai_list('https://animeidhentai.com/genre/2019/') to     animeidhentai_list('https://animeidhentai.com/genre/2020/') and it appears to be working. I don't know how to suggest edits on here, so I'll just leave that for someone who does.

**Comment by s4ik0s4n** [comment]
I think I did the commit and pull request correctly. #198

**Comment by DJMix-I-Can** [comment]
Correct, it was under line 30. The PR looks good to me.

**Comment by dobbelina** [comment]
Thanks s4ik0s4n  for the contribution, merging your fix.
