### ISSUE TITLE
sxyporn issue

### ISSUE THREAD

**Issue by Sameer888** [dobbelina/repository.dobbelina#196]
sxyporn has listing problem

![Screenshot_20200301-032747_Kodi](https://user-images.githubusercontent.com/43412503/75615733-fb114f80-5b6d-11ea-8b34-b21cae671a8a.jpg)
![Screenshot_20200301-032727_Kodi](https://user-images.githubusercontent.com/43412503/75615734-fc427c80-5b6d-11ea-98c5-4f820ab81c87.jpg)

**Comment by dobbelina** [comment]
Woprks for me.

**Comment by Sameer888** [comment]
Hi dobbelina and 12asdfg12 please check once more if its working fine i will close the issue but still its not showing full list

**Comment by DJMix-I-Can** [comment]
When I first checked it out, my listing also looked like Sameers. It looks like they were tweaking the site because it now lists but it won't play the videos.

**Comment by 12asdfg12** [comment]
The video link, on the website is no longer posted on the video page, but in the title.
On the video page is just a short trailer.
I will try to fix it when i have more time.

**Comment by 12asdfg12** [comment]
fixed

**Comment by dobbelina** [comment]
Thanks for the fix 12asdfg12 , merged #204

**Comment by Sameer888** [comment]
Thanks dobbelina and 12asdfg12 for fix , Closing issue
