### ISSUE TITLE
Yespornplease issue 

### ISSUE THREAD

**Issue by Sameer888** [dobbelina/repository.dobbelina#197]
It is showing uwc error on playing 

![Screenshot_20200301-033226_Kodi](https://user-images.githubusercontent.com/43412503/75615793-afab7100-5b6e-11ea-89fd-13839491f940.jpg)

![Screenshot_20200301-033255_Kodi](https://user-images.githubusercontent.com/43412503/75615789-ab7f5380-5b6e-11ea-96e9-4337b977a462.jpg)
and 

Yespornplease is not working please check

**Comment by dobbelina** [comment]
Both issues confirmed.

**Comment by DJMix-I-Can** [comment]
Yesporn site has the following message, "This page (https://yespornplease.com/) is currently offline. However, because the site uses Cloudflare's Always Online™ technology you can continue to surf a snapshot of the site"
HQ Porner loads but videos don't play. Kodi log error:
File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.uwc\resources\lib\sites\hqporner.py", line 93, in HQPLAY videourl = getBMW(iframeurl)
File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.uwc\resources\lib\sites\hqporner.py", line 113, in getBMW videourl = videos[-2]
  IndexError: list index out of range

**Comment by jdoedev123** [comment]
HQPorner looks like the video player page changed. Previously their was usually only one choice for playback but now their can be multiple choices and the code changed to pick the video files. I will try to get back to it soon.

**Comment by jdoedev123** [comment]
Testing a temporary work around defaulting to always play 1080p with minimal code changes. Intend to add resolution choices before final submittal.
line 112:      videos = re.compile(r"<a href='([^']+)' style='color:#ddd'>", re.DOTALL | re.IGNORECASE).findall(videopage)
line 113:     videourl = videos[-1]

**Comment by jdoedev123** [comment]
As for YesPornPlease.com I am getting an error 521 which is a cloudflare specific error code indicating that cloudflare cannot connect to the website on port 443 or 80. Googling around it seems most likely a configuration problem by yespornplease.com that we hope they will fix soon but until then we can do nothing.

**Comment by 12asdfg12** [comment]
here is the code for resolution selection

```
    videos = re.compile(r'source src=\\"(.+?)\\" title=\\"(.+?)\\"', re.DOTALL | re.IGNORECASE).findall(videopage)
    list = {}
    for video_link, quality in videos:
        quality = quality.replace('4K', '2160p')
        list[quality] = video_link
    videourl = utils.selector('Select quality', list, dont_ask_valid=True, sort_by=lambda x: int(re.findall(r'\d+', x)[0]), reverse=True)
    if videourl.startswith('//'):
        videourl = 'https:' + videourl
    return videourl
```

**Comment by jdoedev123** [comment]
Thanks 12asdfg12 that works but I prefer the slightly cleaner:

    videos = re.compile(r"<a href='([^']+)' style='color:#ddd'>(.+?)</a>", re.DOTALL | re.IGNORECASE).findall(videopage)
    list = {}
    for video_link, quality in videos:
        quality = quality.replace('4K', '2160p')
        list[quality] = video_link
    videourl = utils.selector('Select quality', list, dont_ask_valid=True, sort_by=lambda x: int(re.findall(r'\d+', x)[0]), reverse=True)
    if videourl.startswith('//'):
        videourl = 'https:' + videourl
    return videourl

Changed the RegEx to scrape a slightly more straightforward version of the URLs which appear twice in the source HTML. Should be easier to understand and modify for future maintainers.

**Comment by jdoedev123** [comment]
Fixed original problem and added quality selection based on 12asdfg12's code to most of the videos on the site.
[hqporner.py.zip](https://github.com/dobbelina/repository.dobbelina/files/4290032/hqporner.py.zip)

**Comment by jdoedev123** [comment]
YesPornPlease is still down. It only returns:
"Maintenance."

**Comment by imurreflection** [comment]
It looks like the site domain name has been changed to yespornplease.name. this site is working fine. Can you please check it?

**Comment by jdoedev123** [comment]
Update. YesPornPlease.com still down for "Maintenance."
Took a look at YesPornPlease.Name.  The videos are much shorter etc and unlikely the same.
Did build a test scraper that works for the Name site but not posting.

**Comment by jdoedev123** [comment]
YesPornPlease.com is gone.
https://reclaimthenet.org/yespornplease-website-goes-down-after-being-hit-with-lawsuit/
Returns: 
Our website is banned in your country.

**Comment by dobbelina** [comment]
Ok, Guess we will remove it in the next update.

**Comment by jdoedev123** [comment]
???
Website suddenly back along with UWC display (but not playback). 
Not sure how long this will last. They just updated their Domain Registry a few hours ago.
Probably best  to let it stabilize a few days before attempting to fix.

**Comment by Sameer888** [comment]
Hi Dobbelina , the site has been removed so  therefore  closing issue    Thanks to all for trying your best for this issue
