### ISSUE TITLE
Delete Keyword does not work in 1.1.65 - simple fix

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#2]
Delete keyword function stopped working between version 1.1.64 and 1.1.65.
The simple fix is a missing comma in line 821 of utils.py
    c.execute("DELETE FROM keywords WHERE keyword = ?" (keyword,))
should be:
    c.execute("SELECT * FROM keywords WHERE keyword = ?", (keyword,))

**Comment by jdoedev123** [comment]
My typo this time. Should be:
    c.execute("DELETE FROM keywords WHERE keyword = ?", (keyword,))

**Comment by dobbelina** [comment]
Thanks for the fix!
Will update the addon, but not change version number.
I'm not the author of all the fixes.
