### ISSUE TITLE
Woxtube fixes being tested

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#209]
First I accidentally opened a related issue. Someone please delete it. It was too early in morning.

Based on lance77tour bug list I did a quick fix of the first item: Woxtube.
Search and Categories fixes are being tested:
In hdporn;py :
lines 31 and 32:
    utils.addDir('[COLOR hotpink]Categories[/COLOR]','http://www.pornaq.net/categories/',63,'','')
    utils.addDir('[COLOR hotpink]Search[/COLOR]','http://www.pornaq.net/s/',68,'','')
line 107:
            videolist = "http://www.pornaq.net" + videolist + "videos/1/"

Plan to post after testing. Now back to sleep.

**Comment by DJMix-I-Can** [comment]
It worked @jdoedev123 . I almost had this, On line 107 I put "videos" in the url instead of after videolist. Thanks.. Everything is now working.

**Comment by jdoedev123** [comment]
[hdporn.py.zip](https://github.com/dobbelina/repository.dobbelina/files/4331684/hdporn.py.zip)

Thanks DJMix-I-Can for help testing.

**Comment by DJMix-I-Can** [comment]
NP, I'll do the PR for this one & PornDoe once I get home.
Thanks
