### ISSUE TITLE
PornDoe mostly working

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#211]
Following up on another of lance77tour bug reports. Working on fixing PornDoe. After started realized why I never use PornDoe, because it is mostly short previews.
In any case to avoid duplication, finished so far is normal video listing, playback (now with quality selection) and Categories.
Not working yet are Channels and Pagination.
Plan to post code when finished testing.

**Comment by jdoedev123** [comment]
[porndoe.py.zip](https://github.com/dobbelina/repository.dobbelina/files/4331655/porndoe.py.zip)

Fixes incorporated. Does not play VR links tested. Also on rare occasion video does not play but this is due to website redirecting to a pay website.
About as far as I plan on working on this.

**Comment by DJMix-I-Can** [comment]
It's all good... I tested it out & everything worked. Thanks.... Pushed a PR for it.
