### ISSUE TITLE
XVideoSpanish video playback

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#216]
Another spin off of Lance77Tour's extensive bug listed under "Thumbnails".
Did not see anyone else attempt a pull request so taking a look at code which I have repaired some months ago.
This site is a pain because of the non-English URL creates problems and ResolveURL does not cover many of the videos.  Still doable but requires lots of testing and if statements. 
Currently have maybe 50% of cases covered.

**Comment by dobbelina** [comment]
Thanks for the effort jdoedev123!
