### ISSUE TITLE
[Bug?] Tags missing, content type incorrect

### ISSUE THREAD

**Issue by DaisyF8** [dobbelina/repository.dobbelina#217]
When navigation the addon in Arctic Horizon by jurialmunkey, the content type for the main menu seems to be set to Video.  This enables icon-view instead of list-view.

![screenshot005](https://user-images.githubusercontent.com/10348988/76961976-a36d3500-691e-11ea-8024-bb76bb0c598b.png)

Also, when content is video, no title-tag is present. (no screenshot because of GitHub rules maybe ? Just being cautious)

**Comment by DJMix-I-Can** [comment]
![ArcticHorizonUWC](https://user-images.githubusercontent.com/35236592/77013880-69645900-6947-11ea-808c-06f8c98fea21.jpg)
Is that the look you want? If so, edit the defaulty.py in the addon.
Line 34 xbmcplugin.setContent(utils.addon_handle, '**movies**') Change movies to addons.

**Comment by jurialmunkey** [comment]
BTw In this screenshot the content type is set to Movies not Videos. However, that also looks like the wrong content type based upon the view. A list of directories should have no content type set.

**Comment by DaisyF8** [comment]
Thanks for that solution. Sorry it took so long to react. Real life and washing hands and stuff.
