### ISSUE TITLE
4k playback 

### ISSUE THREAD

**Issue by SomeDood** [dobbelina/repository.dobbelina#222]
I'm just curious if anyone else has this problem as well. But I have an android box and I can play 4k content (Seren) very well, but with whitecream I always have an lagging and constant stopping issue when I try to play 4k vids. Is that something that can be fixed? I also have my interest wired to the box as well fyi.

**Comment by DJMix-I-Can** [comment]
Which sites are you using? I'll test it on my end. If you're using Seren, you have a premium account? Real-Debrid, Premiumize, Alldebrid?

**Comment by SomeDood** [comment]
The sites i mainly use are porntrex and hqporner. And I have real debrid.

**Comment by DJMix-I-Can** [comment]
Porntrex wasn't that bad. I tried about 4 links and let them play for about two minutes, they didn't buffer. I did get one that buffered. I went directly to the website, found the same video, clicked on it, it also buffered. On the other hand, hqporner does have a lot of buffering issues. If you go directly to their webpage & play the same video, you'll still get buffering. It's not a UWC issue. 
The video links are direct links (from he site), I thought maybe they would've been passing through ResolveURL to Real Debrid, but they're not. Basically, whatever the site gives, is what we get. Also have to take into consideration, a lot of people are home during this epidemic. You probably know best, prior to epidemic was it ever working for you?

**Comment by SomeDood** [comment]
It was much better months ago iirc, but it was buffering before the epidemic as well. I wasn't sure if it was an uwc issue, because I can stream without of thru Kodi. I also thought it could have been my android box, but I don't have the issue when I use Seren... But I chalked that up to it being streamed directly thru the site because I've had issues before with it lagging on 1080p as well. Anyway thanks for the checking it out your self.

**Comment by DJMix-I-Can** [comment]
NP I checked on my Nvidia Shield, Windows Laptop & Android Phone... Same issue...
Be safe.

**Comment by SomeDood** [comment]
Oddly enough I tired again last night and it was lag free lol.
