### ISSUE TITLE
Is UWC updating resolveurl properly?

### ISSUE THREAD

**Issue by tetzy** [dobbelina/repository.dobbelina#223]
For the past few days I've been experiencing problems downloading files from Gounlimited and VK. 

I've posted my error to the jsergio123/script.module.resolveurl page and been assured the problem is fixed for both, yet I'm still seeing that error with every file hosted by those two sources. The project mod there mentioned that the UWC repo points to jsergio's zips which are apparently out of date.

My UWC is set to update automatically, but the problem still exists. Is UWC updating resolveurl properly? 

Thanks

**Comment by dobbelina** [comment]
repository.dobbelina-1.0.2 has now been released that has changed ResolveURL path to Gujal00

**Comment by tetzy** [comment]
Works like a charm - Cheers!
