### ISSUE TITLE
Lots of sites down.

### ISSUE THREAD

**Issue by joxdfrt** [dobbelina/repository.dobbelina#225]
Lots of sites down any chance these getting fixed.Thanks

**Comment by dobbelina** [comment]
updated:
daftsex,datoporn,freepornstreams,hotpornfile,justporn,mangoporn,perfectgirls,porndoe,sxyprn,Amateur Cool
removed:
watchxxxfree,yourfreetube,xtasie,pornsland,yespornplease,xvideohits,xtheatre
added:
cambro, ipornovideos, reallifecam,voyeurhouse,videomegaporn

Thanks to 12asdfg12!

**Comment by joxdfrt** [comment]
Has this been rolled out to Kodi yet. Thanks.

**Comment by dobbelina** [comment]
Yes, updates are in v.1.2.17

**Comment by 12asdfg12** [comment]
my mistake. the new site is vipporns not videomegaporn

**Comment by dobbelina** [comment]
> 
> 
> my mistake. the new site is vipporns not videomegaporn

Aha, ok thanks.
