### ISSUE TITLE
AnimeIDHentai Uncensored did not open

### ISSUE THREAD

**Issue by wintuxx** [dobbelina/repository.dobbelina#231]
There is no access to the folder Uncensored

**Comment by dobbelina** [comment]
Edit animeidhentai.py line 27 to:

> https://animeidhentai.com/hentai/uncensored-hentai/
[animeidhentai.zip](https://github.com/dobbelina/repository.dobbelina/files/4550331/animeidhentai.zip)


Or download edited file below.

**Comment by dobbelina** [comment]
Will release in next update Version 1.2.19
