### ISSUE TITLE
Yespornplease is back with a new name

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#235]
The new site name is porngo.com. the site has exactly the same content as yespornplease.com. also, when you enter the website name it redirects you to porngo.com. the site was last updated on 7th May. For more information, check this link
https://homepagecached.com/yespornplease.com/

**Comment by dobbelina** [comment]
Thanks for the heads-up!

**Comment by imurreflection** [comment]
Hi 12asdfg, can you please add this site as yespornplease was the best site and was removed recently and now has come back.

**Comment by jdoedev123** [comment]
FWIW I have am testing a version of PornGo based on YesPornPlease. Most functions seem to work such as Video List, Search, Catagories, Pagination etc. Sorting no longer works but not a major loss. It is defaulting to latest.
Video Playback mostly works except for maybe some older and foreign language links so far in testing.

**Comment by jdoedev123** [comment]
Having some strange issues with playback on test version of PornGo. No matter what video resolution requested it plays in 720p. In the kodi logs it is requesting the higher resolution video but always returns 720p strange. Anyway needs more work.

**Comment by imurreflection** [comment]
Hi, is it possible to give the test version here. I will check and revert if I encounter similar issue. However, in my opinion, 720p is more than sufficient.

**Comment by jdoedev123** [comment]
Ok, here is the unfinished code. A bit more testing shows it plays 720p when requesting 720p or higher resolution and plays nothing when requesting a lower resolution.
Also remember to include a line in default.py requesting the website. Something like:
utils.addDir('[COLOR hotpink]PornGo[/COLOR]','https://www.porngo.com/latest-updates/1/',690,os.path.join(imgDir, 'yespornplease.png'),'')

[porngo.py.zip](https://github.com/dobbelina/repository.dobbelina/files/4775497/porngo.py.zip)

**Comment by imurreflection** [comment]
I m sorry mate but how do I use it. I deleted yesporn.py and added this but I cannot see it in addon

**Comment by jdoedev123** [comment]
Imurreflection,
As mentioned previously you need to edit the default.py file in the plugin.video.uwc directory to add the reference to porngo.com.  The easiest way with version 1.2.20 of UWC is to change the commented out line referring to the old YesPornPlease:
Old line 86 in default.py:
#    utils.addDir('[COLOR hotpink]YesPornPlease - DOWN !!![/COLOR]','https://yespornplease.com/',690,os.path.join(imgDir, 'yespornplease.png'),'')
New edited line 86:
utils.addDir('[COLOR hotpink]PornGo[/COLOR]','https://www.porngo.com/latest-updates/1/',690,os.path.join(imgDir, 'yespornplease.png'),'')

I can't send you my default.py since my own development version of UWC is based on 1.2.15 which is slightly different.

**Comment by imurreflection** [comment]
As instructed, I did everything correctly but it breaks the entire, so I reverted back and I think I should wait once you are able to resolve the issue but thank you for your efforts mate.

**Comment by jdoedev123** [comment]
OK, I have been down for an OS update on my main Workstation.

**Comment by dobbelina** [comment]
Sorry jdoedev123 i missed this one on the latest update, but i will add
it to the next release.

**Comment by imurreflection** [comment]
Hi jdoedev123, Many thanks for this addition. However, please note that videos marked as 1080,720p are being played at 540p only. Can you please check and fix this.

**Comment by dobbelina** [comment]
On my Windows rig 1080 & 720 are all played as 720.

**Comment by imurreflection** [comment]
I am sorry for not being clear but I was talking about android tv box running Android 9. All videos are being played at 540p only.

**Comment by jdoedev123** [comment]
I have not taken a look at the code in awhile. I will try to take a look over the weekend. 
The last I checked it was playing nearly all videos in 720p on my 4k Linux workstation even when a higher resolution was chosen.
