### ISSUE TITLE
Auto-maintain favorites?

### ISSUE THREAD

**Issue by TarkusLV** [dobbelina/repository.dobbelina#238]
I use the favorites function for tracking cam models, particularly on Chaturbate, where the thumbs work best.  I move the active ones to the end, where they're easier to find, and let the inactive ones fall back to the beginning.  I delete those at the beginning, as needed, to keep it manageable.

I was wondering it it might be possible to have an option to auto-maintain the favorites database to a certain size?  Say, for example, if the option were to maintain it at 100 favorites, when going over that, it would automatically delete the first one to keep it at 100 entries.

Feasible?

**Comment by dobbelina** [comment]
You are aware of the backup & Restore function of favorites in
the settings right?

**Comment by TarkusLV** [comment]
Yes, I'm aware of backup and restore, but that wouldn't automatically purge old favorites.  That would just restore old favorites while losing new ones.

**Comment by jdoedev123** [comment]
To OP, anything is feasible the question is does any one have the time to add a feature which may have limited utility. Personally I tend to maintain my larger favorite files outside of UWC. I either backup or use different "profiles" to separate the favorites. When things get really large or convoluted I use an outside tool to edit the SQLlite file that contains the favorites and keywords (favorites.db should be backed up and  is under .kodi/userdata/profiles/PROFILENAME/addon_data/plugin.video.uwc). On Android I use "g8 SQlite Editor" and on the desktop I use  "DB Browser for SQLite" i.e. sqlitebrowser. I realize this is a bit extreme and we should really be adding these maintenance features to UWC but for now it easier to trim and sort the favorites using SQL tools and export and import them back into favorites.db. For the truly insane it is also possible to have multiple favorites list in the same favorites.db SQLite database file as long as only one active Table is named "favorites".  This is actually a handy feature as I can maintain a Chat only list or a sorted list by website or delete old favorites from now dead websites. Theoretically anything that can be done with an outside tool can be added to the Python code if a developer has enough time and their is a community need.

**Comment by WhitecreamDev** [comment]
A nice idea which (in my opinion) would benefit a lot of people is adding folder support in Favorites (I have it in my personal version and no...I won't share that).
So for example you can have a subfolder in Favorites called 'webcams', 'inactive babes' or whatever. You can also rename the subfolder, move the items around and everything.
It's not that hard to add (maybe I'll add it when I've got some spare time).

You'll need to create a new table called favfolders or something, And edit the favorites table to include folderid (no folderid set -> the favorite is in the main/root of Favorites).
A lot of code to make it work is already in UWC, you'll only need to copy/paste and edit it to work with the favfolders table.

**Comment by jdoedev123** [comment]
WhitecreamDev, good points. For the moment my personal test version has a few "extra" features as well. One feature, for test purposes only, I am running displays only the Chat from the favorites. This should be fairly easy to add without any additional flags but just different levels of filtering (i.e. WHERE conditionals)  in the SQL SELECT. I am by no means a SQL expert but I can test various features in sqlitebrowser and "cut and paste to" the Python in favorites.py. Other useful features can similarly be added by filtering by modes (websites) or a keyword or phrase (a search within "name" in  favorites). All of these can be done with simple SQL in favorites.py. Like you I may some day get around to adding the full code.
