### ISSUE TITLE
Pornvibe plays videos only in SD

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#240]
On site, the videos are available in HD. Seems like an issue with the fallback url.please check

**Comment by 12asdfg12** [comment]
The videos is not playing for me (on the site).

**Comment by imurreflection** [comment]
Hi. Firstly, please take care of yourself and your family in this hard time. Family is paramount. Secondly, the site is back and running. I checked two videos and they played fine. However, in our addon, they are playing in SD only. Once, you have some time, please have a look

**Comment by imurreflection** [comment]
It appears that there is no solution for this issue. I am closing this issue now.
