### ISSUE TITLE
watchxxxfree site 

### ISSUE THREAD

**Issue by GoldProlificAce** [dobbelina/repository.dobbelina#241]
What happen to the best site watchxxxfree . I see it's now .xyz

www.watchxxxfree.xyz

**Comment by dobbelina** [comment]
It was removed in Version 1.2.17
Maybe it can be re-added again?, let's see what 12asdfg12
has to say about it.

**Comment by 12asdfg12** [comment]
it was removed because netu.tv (the host used for the videos) is not working in Resolveurl
