### ISSUE TITLE
Reallifecam not working

### ISSUE THREAD

**Issue by toddwylde47** [dobbelina/repository.dobbelina#248]
I can't seem to get Reallifecams links to work properly on Ultimate Whitecream. It gives me an error message every time i try to watch a link. I am using the latest version of the addon on Kodi 18.6. Thank you for your help and for the work you do for us. I know i sure appreciate it.

**Comment by dobbelina** [comment]
Confirmed broken, thanks for reporting.

**Comment by DJMix-I-Can** [comment]
It seems those sites are no longer working.  If you go to the site, the videos don't play & if they do, you'll get a "No Video Available. Please Try Refreshing This Page." message. The same goes with Voyeur-House.

**Comment by dobbelina** [comment]
Fixed in v.1.2.25, 
Thanks for the fix 12asdfg12 and welcome back!

**Comment by windblown2** [comment]
Thanks for response. I had version 1.2.24. so tried update. Now have version 1.1.54 which doesn't even have Realifecam or Voyeur House in it.  Have I used the wrong repository? If so, which repository will have the correct version?

**Comment by onknight** [comment]
https://github.com/dobbelina/repository.dobbelina/blob/master/plugin.video.uwc-1.2.25.zip 
Just click down load

**Comment by windblown2** [comment]
Great! That worked.  Thanks.
