### ISSUE TITLE
My Freecams 

### ISSUE THREAD

**Issue by onknight** [dobbelina/repository.dobbelina#254]
The newest version I find  it take 2 or 3 times before a Stream will open on myfreecams .

**Comment by wwilesco** [comment]
it is now almost impossible to open streams, successful about once in a hundred attempts

**Comment by frankee123** [comment]
Yes. Please fix it. Tyvm.

**Comment by onknight** [comment]
a no streams will open now :(

**Comment by onknight** [comment]
Any word on this one guys ?

**Comment by onknight** [comment]
This is the best adult site on the net we need to get it back

**Comment by abk857** [comment]
Was there a fix?
