### ISSUE TITLE
Movies not playing 

### ISSUE THREAD

**Issue by chocovola** [dobbelina/repository.dobbelina#258]
Hello guys I'm not an expert, I'm using kodi on a raspberry pi 2, the addon was working fine but now all of the movie sites aren't working, it loads up to 25% and show me an error on the log shows that van find  module six (check that is there and updated) and also an error DoWork -direct texture file loading failed
Please any help?

**Comment by DJMix-I-Can** [comment]
Module six is not a dependency for this add-on. Double check and see if any other updates you did screwed with your setup.
