### ISSUE TITLE
Links to stream videos not working in ParadiseHill

### ISSUE THREAD

**Issue by daveocampo** [dobbelina/repository.dobbelina#259]
Can you please fix link to stream videos in ParadiseHill?  Thanks.
Most of the streams in Movies are not working.  Hope you release an update soon.  Thanks.

**Comment by DJMix-I-Can** [comment]
A fix has been implemented but hasn't been released yet. If you're familiar with coding, you could make the changes yourself from the pull request over [here. ](https://github.com/dobbelina/repository.dobbelina/pull/257/commits/562cdaeaee5b77843246a5e3d732cd1dfd3ee013#diff-edbc67863ea7ce16aa1009c3fa0fcdfe)
