### ISSUE TITLE
k18.co relaunch

### ISSUE THREAD

**Issue by wilbalt** [dobbelina/repository.dobbelina#26]
k18.co has had a relaunch over Easter. Is that an easy fix?

**Comment by 12asdfg12** [comment]
cannot play any video on k18 site, maybe they are still working on the site

**Comment by jdoedev123** [comment]
Have a version under test. Videos play but pagination still a work in progress. Will upload when finished.

**Comment by dobbelina** [comment]
Awesome, thanks!

Will upload all the fixes when you are done with this one.

**Comment by 12asdfg12** [comment]
I fixed the menus and pagination for k18 when they changed the site, you can use this if you want, just replace the code for play.
[k18-needs fixing.zip](https://github.com/dobbelina/repository.dobbelina/files/3191784/k18-needs.fixing.zip)

Pornsland fixed.
[pornsland.zip](https://github.com/dobbelina/repository.dobbelina/files/3191787/pornsland.zip)

**Comment by jdoedev123** [comment]
Thanks 12asdfg12. I was just finishing up the code for play when I noticed not all video links are the same. I have the links to PornHub videos working but noticed other links are direct ... and not working yet.

**Comment by dobbelina** [comment]
I also noticed some odd behaviour with the same video being played, regardless of link without audio.

**Comment by jdoedev123** [comment]
Dobbelina, the original code plays the same short video. Test version now plays most of recent videos which are usually links to  10-12 minute trailers. Older links dont play correctly but I am not sure they ever will as the the source webpage has what appear to be "fake" links to download the videos on vidlox, openload, and filefactory. They are really links to what I assume are sponsored links to sites like babesnetwork.com. 
I will clean up test version and post soon. Not worth time for trailers etc. but may be useful to some.

**Comment by jdoedev123** [comment]
Long forgotten partially working k18 from back in May. Have not worked on it since. Only some of videos play (at least they are correct videos) but may benefit from WhiteCreamDev's contributions elsewhere for complicated playback in Hentai etc.
[k18.py.zip](https://github.com/dobbelina/repository.dobbelina/files/3303650/k18.py.zip)

**Comment by dobbelina** [comment]
Closing issue.
