### ISSUE TITLE
xHamster?

### ISSUE THREAD

**Issue by ZabriskiSF** [dobbelina/repository.dobbelina#264]
Hi..is there an issue with xHamster? Every link keeps getting ‘Can’t find video’

**Comment by dobbelina** [comment]
Issue confirmed, thanks for reporting.
TubePornClassic seems down as well.

**Comment by maxpro59** [comment]
> Hi..is there an issue with xHamster? Every link keeps getting ‘Can’t find video’

...still not working....

:-(

**Comment by ZabriskiSF** [comment]
Thanks for fixing :-)
