### ISSUE TITLE
Xvideospanish not working

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#266]
Videos does not play. Please check

**Comment by jdoedev123** [comment]
Xvideospanish is a pain in the .... It uses non English coding in the website URL. Every few months they change something and non ASCII slips through and breaks the Python code. I will take a look.

**Comment by dobbelina** [comment]
Issue confirmed, thanks for reporting.

**Comment by imurreflection** [comment]
Hello jdoedev123. Is there any update on this bro?

**Comment by dobbelina** [comment]
Thanks for the fix camilt!

However, quality selector only plays SD, regardless of choice.

**Comment by imurreflection** [comment]
Hi @camilt if there is no solution available for this, please advise and I will close this issue.

**Comment by camilt** [comment]
There is no solution, the site provides (from xvideos and xhamster) only 250p, 360p and 480p, very rare at 720p. The site don't provide good quality clips. Sorry for the late reply

**Comment by camilt** [comment]
As jdoedev123 said, it's a pain in the... AS(s)CII. There are more good sites then this

**Comment by imurreflection** [comment]
Thank you for your response. Closing the issue now.
