### ISSUE TITLE
Dos attack ack

### ISSUE THREAD

**Issue by xyz236** [dobbelina/repository.dobbelina#268]
As of recent if have been testing some site because my log reported a few 1k dos attack but I’m have problems narrowing down which one it is for I have to run a site for 15 mins then go check the router logs and see when the attack begin is it possible for anyone to scan these sites and see which is the one causing the attacks I don’t have much protection on my android box as for malware. Suspected site are hqporner,synprn and xmovies for you.i think it’s xmovies but I would like to hear from you guys since of you run ulwc on pc which I feel would be easier to find the malicious site. Thanks in advanced

**Comment by jdoedev123** [comment]
Thanks, for the heads up. I enabled some extra network protection so I may not be able to diagnose.

**Comment by xyz236** [comment]
No problem, just hope someone can narrow down the sites.
