### ISSUE TITLE
Favorites Question

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#273]
Hi, this may be a dumb question but please assist if you know how can I find the exact site name from the link marked as favourite. Example..I mark one video as favourite and later want to find out from which site I have used it to mark as favourite to find similar content. This is on android tv box running Android 10. I am using Aeon Nox Silvo.

**Comment by dobbelina** [comment]
You have to open the favorites.db file located at **Kodi\userdata\addon_data\plugin.video.uwc** with a texteditor.
There you can see the url.

**Comment by imurreflection** [comment]
Hi Dobbelina, thank you so much and this really helps for UWC favorites but actually I was referring about Kodi Favorites. Example on a search page 43, if you mark 'Next' as  favorite so that you don't have to go manually to that page, it will appear in 'Kodi' favorites and not in UWC favorites. Now, if you have 10 such favorites,how do you find from which site that particular 'Next' has been favorited from.

**Comment by dobbelina** [comment]
Those are located in a file called favourites.xml that can be found in this folder:
**Kodi\userdata**
Open favourites.xml with a texteditor and you can see the url.

**Comment by imurreflection** [comment]
Thank you so much dear. Closing the issue now
