### ISSUE TITLE
Can u fix vipporn and porngo 

### ISSUE THREAD

**Issue by deanogers** [dobbelina/repository.dobbelina#279]
Nothing playing on porngo and vipporn hasn’t worked since last update can u take a look please

**Comment by dobbelina** [comment]
Both these sites works for me on Windows.
A few PornGo videos don't play.

**Comment by jdoedev123** [comment]
A quick check shows most links work on both for my main workstation. The first few links do not work on either but after 5-10 links they work for me.

**Comment by deanogers** [comment]
Using it on kodi keeps saying oh oh no supported link on everything and paradisehill has stopping working also porngo works vipporns doesn’t

**Comment by dobbelina** [comment]
VipPorns Fixed by DJMix-I-Can #286
Will be in next release Version 1.2.26
