### ISSUE TITLE
ParadiseHill fails - always

### ISSUE THREAD

**Issue by dammer264** [dobbelina/repository.dobbelina#281]
Hi guys been 4 days ParadiseHill fails - always
Both, play & download
Can you please check and if possible fix it
Thanks!

**Comment by dobbelina** [comment]
Issue confirmed, thanks for reporting.

**Comment by dobbelina** [comment]
Fixed by DJMix-I-Can #282
Will be in next release Version 1.2.26

**Comment by deanogers** [comment]
When is the update coming out thank you for the hard work
