### ISSUE TITLE
vidup links of the SpeedPorn and MangoPorn are not working 

### ISSUE THREAD

**Issue by neptunus123** [dobbelina/repository.dobbelina#283]
Although the https://vidop.icu/pair procedure is completed and the screen shows the streaming is enabled for3-4 hours, the links in the Speedporn and Mangoporn do not work.

**Comment by DJMix-I-Can** [comment]
This is a ResolveURL issue, you have multiple play options. If you want to disable hosters with pairing notifications.
Go to kodi, settings, system settings, add-ons, manage dependencies & scroll down to ResolveURL. Go to the ResolveURL settings. Under ResolveURL , uncheck Enable PopUps, reset the function cache and select ok.
Another thing, if you google Vidop pairing error, it's been an ongoing issue.
