### ISSUE TITLE
Javhoho- No Thumbnails

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#284]
Kindly check and fix it please

**Comment by dobbelina** [comment]
Issue confirmed, thanks for reporting.

**Comment by dobbelina** [comment]
Fixed by DJMix-I-Can #286
Will be in next release Version 1.2.26

**Comment by DJMix-I-Can** [comment]
As I was looking into this, I noticed the errors when selecting Playtube. This has to do with the plugin within the ResolveURL addon. Once the update gets pushed and you want to fix this yourself,  browse to .kodi/addons/script.module.resolveurl/lib/resolveurl/plugins and select playtube.py to edit. Scroll down to the last line "return self._default_get_url(host,media_id,template='https://{host}/embed-{media_id}.html')" Remove "embed-", it should now be "return self._default_get_url(host,media_id,template='https://{host}/{media_id}.html')" & save the file. You should now be able to play from Playtube.

**Comment by imurreflection** [comment]
Thank you bro. It's a pleasure learning from you.

**Comment by dobbelina** [comment]
Gujal00 have now fixed the issue, should be implemented in the next release.
https://github.com/jsergio123/script.module.resolveurl/issues/371#issuecomment-691621178

**Comment by Gujal00** [comment]
Can you give me a embed that is giving issue, I did test quite a few from the javhoho site with the latest code in git and it works.

**Comment by DJMix-I-Can** [comment]
@Gujal00 I implemented your fix and it's working. I tried it on numerous links within this add-on.
Thanks for the fix.

**Comment by dobbelina** [comment]
> 
> 
> @dobbelina
> Can you give me a embed that is giving issue, I did test quite a few from the javhoho site with the latest code in git and it works.
> The changes were to two files helpers.py and playtube.py, did you replace them both from the the git when you tested?

My bad, i didn't.
Confirmed working now, thanks for the fix!! 👍
