### ISSUE TITLE
Ipornovideos

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#285]
On every link getting " couldn't find a supported host' error. Kindly check

**Comment by darktones123** [comment]
I have the same problem as well.

**Comment by deanogers** [comment]
Same problem here hopefully update comes out soon

**Comment by dobbelina** [comment]
Issue confirmed, thanks for reporting.

**Comment by imurreflection** [comment]
Hi .looks like this hasn't been fixed in the new version. Still the same error. Please check.
