### ISSUE TITLE
Porngo not working

### ISSUE THREAD

**Issue by deanogers** [dobbelina/repository.dobbelina#287]
Won’t play anything can u take a look and any eta on the when new update is coming out cheers xhamster not working either keeps saying ultimate white cream error can u have a look please cheers

**Comment by dobbelina** [comment]
Issue confirmed, thanks for reporting.

**Comment by DJMix-I-Can** [comment]
I took a look last night & it was working, not working, working, not working. Site issue or they're testing changes. As of right now, PornGo is not working and XHamster is.
