### ISSUE TITLE
Ipornovideos

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#294]
Please check. This hasn't been fixed in the new version. As old issue is closed, creating a new one.

**Comment by DJMix-I-Can** [comment]
It was fixed in the new version, I tested it myself! Something changed...

**Comment by darktones123** [comment]
I have the same problem as well.

Thanks

**Comment by dobbelina** [comment]
Thanks DJMix-I-Can for the fix #295
Will be in next update Version 1.2.28

**Comment by deanogers** [comment]
When is new update coming out for ipornvideo cheers m8

**Comment by dobbelina** [comment]
> 
> 
> When is new update coming out for ipornvideo cheers m8
Today.

**Comment by DJMix-I-Can** [comment]
I believe it won't work again. They reverted back to their previous code. Anyone can confirm, it's not working again?

**Comment by darktones123** [comment]
It was working yesterday but today its not.

**Comment by DJMix-I-Can** [comment]
Thanks @darktones123 Let's wait it out and see if they're still messing with it.

**Comment by deanogers** [comment]
Is the problem going to be fixed anytime soon as still nothing working on it cheers for the hard work

**Comment by darktones123** [comment]
There might be a problem again with Ipornvideos. It was working fine the last week or so but now its only giving you two options to stream vidlox and videobin. Usually both of those streams do not work for me. If you could check that would be great. 
Thanks
