### ISSUE TITLE
Txxx

### ISSUE THREAD

**Issue by deanogers** [dobbelina/repository.dobbelina#296]
Won’t play any videos can u have a look

**Comment by DJMix-I-Can** [comment]
It works fine. I tried about 6 videos & without any problems.

**Comment by deanogers** [comment]
Most don’t play just keeps saying playing video but doesn’t load up and thumbnails have disappear as well

**Comment by DJMix-I-Can** [comment]
Check your log file. I just checked again, thumbnails and video play are working. Do you use a VPN? If so, have you tried with it off?  You also had play back issue with Freeomovie about a month ago and that was also working for everyone else. It's something on your end.

**Comment by dobbelina** [comment]
Works fine for me to.

**Comment by imurreflection** [comment]
Working fine..no issues

**Comment by deanogers** [comment]
Don’t use a vpn they are all back on now wouldn’t work yesterday very strange

**Comment by imurreflection** [comment]
can you close this issue now please
