### ISSUE TITLE
YesPornPlease missing

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#3]
Does anyone know if this "1.1.65" is based on 1.1.64 or 1.1.63? Noticing a few fixes and improvements in 64 are missing in 65. For example, keyword search deletion was fixed in 64 but broken again 65 and YesPornPlease was added in 64 but missing in 65.

Adding YesPornPlease is simple. Add the yespornplease.py file from 1.1.64 and add one line back into default.py after line 85:

utils.addDir('[COLOR hotpink]YesPornPlease[/COLOR]','https://yespornplease.com/',690,'','')

**Comment by lukehansford** [comment]
[plugin.video.uwcfixedv3.zip](https://github.com/dobbelina/repository.dobbelina/files/2824368/plugin.video.uwcfixedv3.zip)

Try this one
