### ISSUE TITLE
HQPorner simple fix

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#30]
First thanks to all for continuing to maintain a great plugin. I have been busy last few weeks and have not been able to contribute.

HQPorner  in versions 76 and 77 was not working when I checked it today.

Simple fix is a minor change to line 43 of hqporner.py
Old line :      match = re.compile('<a href="([^"]+)" class="image featured non-overlay click-trigger".*?<img id="[^"]+" src="([^"]+)" alt="([^"]+)"', re.DOTALL | re.IGNORECASE).findall(link)

New line:     match = re.compile('<a href="([^"]+)" class="image featured non-overlay atfib".*?<img id="[^"]+" src="([^"]+)" alt="([^"]+)"', re.DOTALL | re.IGNORECASE).findall(link)

Have only done a quick test but seems to work.
[hqporner.py.zip](https://github.com/dobbelina/repository.dobbelina/files/3184896/hqporner.py.zip)

**Comment by dobbelina** [comment]
Thanks for fix jdoedev123,

Will incorporate it in fix.
