### ISSUE TITLE
"One list, to watch them all" dupes

### ISSUE THREAD

**Issue by TarkusLV** [dobbelina/repository.dobbelina#301]
When using "One list, to watch them all," from the Scenes category, it repeats the first 12 videos on every single page.  So, you only start getting new content on each additional page starting with the 13th video.

**Comment by dobbelina** [comment]
Thanks for reporting, i'm aware of the issue.

**Comment by TarkusLV** [comment]
I discovered Porn00 is the problem child.  There are 12 videos on each page, and for some reason, the ONELIST code keeps showing the first page.

There is currently only one other active site (Porntrex) in the ONELIST code, so I guess it's not real useful anymore anyways.  I always assumed it was grabbing more sites than it was, till I took a closer look.
