### ISSUE TITLE
Camsoda Results aren't generating

### ISSUE THREAD

**Issue by ADRideau** [dobbelina/repository.dobbelina#302]

**Comment by onknight** [comment]
They where not working to start with 
yes you'd see models but 95%  of them when clicked on the link you get nothing 
now you don't see anything at all it just a dead part of the addon

**Comment by jdoedev123** [comment]
Camsoda, Cam4, and BongaCams don't work for me. I can't always tell if this is a problem in UWC or I got banned for trying to fix the UWC Cam plugins. Some cam sites are sensitive to incorrect access common during debugging.

**Comment by jdoedev123** [comment]
I am working on a fix for CamSoda. It is partially working but trying to add more messaging of why connections fail which is usually due to Models quickly moving into Private. I might be missing other features but plan to post version soon.

**Comment by ADRideau** [comment]
I appreciate your efforts, JDoe. Can't wait to see what you come up with.
You're right on Chaturbate when the models go private the screen just returns back to results page but on there each visible model can be accessed. There was a disconnect in contrast to CamSoda.

**Comment by onknight** [comment]
**Thank you done for community your efforts have not gone unnoticed**

**Comment by jdoedev123** [comment]
About to upload an experimental CamSoda.  Not all Models work on my workstation. Specifically, any Edge server (video streaming server)  of the form 'edgeX-XXX.camsoda.com' fails (with an SSH Cert error) while Edge servers of the form 'videX-ord.camsoda.com' usually work. Unfortunately this is most of the models but not all.  The VoyuerCams all seem to work.
For now I have put messages to display 'Model Edge Server Error' for the problematic cases.
Another Error message was added for the case 'Model is Offline or Private' .
Please report if the 'Model Edge Server Error' cases play for you.

[camsoda.py.zip](https://github.com/dobbelina/repository.dobbelina/files/5478848/camsoda.py.zip)

**Comment by jdoedev123** [comment]
Testing new version with most but not all Models working. Will clean up code and post soon.

**Comment by onknight** [comment]
Great work Jdeodev

**Comment by jdoedev123** [comment]
Fixed CamSoda for test.

[camsoda.py.zip](https://github.com/dobbelina/repository.dobbelina/files/5491316/camsoda.py.zip)

**Comment by jdoedev123** [comment]
Also fixed streamlink plugin for CamSoda and posted it over at:
[Damianonymous GitHub repo for streamlink_plugins](https://github.com/Damianonymous/streamlink-plugins)

He should incorporate it soon. He already incorporated my MyFreeCams fix based on 12asdfg12 fix to UWC. It is good to cross-pollinate fixes.
Streamlink is a Python tool to download video streams.

**Comment by dobbelina** [comment]
Awesome jdoedev123!

Will incorporate the fix in the next release.

**Comment by onknight** [comment]
Bravo man your a coding God Jdoe

**Comment by imurreflection** [comment]
Hey @jdoedev bro...could you please look at javhoho also. This is the best Japanese site we have.

**Comment by ADRideau** [comment]
@jdoedev123 ,...forgive my late appreciation.  I'm just getting power restored after getting punched in the face by Hurricane Zeta here in New Orleans.  Anyway, thank you for all your professional talents.

AD

**Comment by jdoedev123** [comment]
AD, sorry to hear of your power and weather problems. We had power and regional fire problems a few weeks ago that forced the shutdown of my main Workstation. Just getting back to the code.

All
I am currently working on the Naked cam site plugin. Everything seems to work but the videos won't play in UWC but do play in streamlink. Trying to track down the problem.

**Comment by ADRideau** [comment]
Thank you, yeah...it was definitely an inconvenience.

Is your CamSoda fix something that will be incorporated into UWC update?  Or is there an alternative method in getting it added into the existing build I'm using?

**Comment by jdoedev123** [comment]
dobbelina  maintains the UWC updates, incorporating everyone's fixes as they come in and releasing the updated versions in the code section of this repo. Alternatively it is possible, but much more complicated to manually incorporate the fixed code by overwriting the local files in .kodi/addons/plugin.video.uwc/resources/lib/sites 
dobbelina was kind enough to start this repository after the original maintainers no longer maintained the original UWC.  Developers used to post fixes in places like Reddit forums and everyone would have to hunt down and patch their own versions of UWC.
