### ISSUE TITLE
Eporner not working

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#305]
No listing. Please check

**Comment by dobbelina** [comment]
Issue confirmed, thanks for reporting.

**Comment by imurreflection** [comment]
@charly923 I saw your fix for this site on video devil plugin..can you try looking at issues on this plugin as well?

**Comment by jdoedev123** [comment]
Thxs imurreflection, charly923 fix was helpful. I am working on a fix. So far most everything works except pagination.

**Comment by jdoedev123** [comment]
A repaired version for test.

[eporner.py.zip](https://github.com/dobbelina/repository.dobbelina/files/5448115/eporner.py.zip)

**Comment by dobbelina** [comment]
Thanks for the fix!
Will incorporate in the next release.

**Comment by deanogers** [comment]
When is new update coming out to fix issues thanks for the hard work
