### ISSUE TITLE
FreeOMovie pagination fix

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#31]
urie57 reported a problem on reddit with the pagination of FreeOMovie.

Relativiely easy fix in freeomovie.py line 47:
        nextp = re.compile('class=\'current\'>.+?</span><a class="page larger".*?href="([^"]+)"', re.DOTALL | re.IGNORECASE).findall(listhtml)

Seems to work in testing.

**Comment by dobbelina** [comment]
Thanks jdoedev123!

Will incorporate the fix when you are done with k18.co.

**Comment by kapslock16** [comment]
White cream freeomovie why are the no openload links nothing will open
