### ISSUE TITLE
Possible Options

### ISSUE THREAD

**Issue by lance77tour** [dobbelina/repository.dobbelina#311]
1. gues I'm being picky :-) is there a way 2 have the length of vid on ea result? I hate when u c something n then it opens 2 3/5/8 min n wasted time lol 
2. could there be an option 2 hide tubes/etc u don't use  
3. could code b inserted n ea tube/etc where u can sort by time?
4. how come some tubes have no thumbnails. where they are just the camera thumbnail?

**Comment by dobbelina** [comment]
Sorting options can't be done universally as each scraper/website has individual
settings for this.
Some scrapers give more options than others.
Some scrapers has broken thumbnails, and they hopefully will be fixed
whenever contributing members have the time to fix them.
