### ISSUE TITLE
Search in speedporn and mangoporn doesn't work

### ISSUE THREAD

**Issue by tonymacc** [dobbelina/repository.dobbelina#313]
Have tried with default skin and Arctic Horizon skin. Basically you set a search on both of these movie sections and you only get one page of results, there is no next option to cycle through the results.

Anything that can be done about this? Never used to behave this way. Thanks.

**Comment by jdoedev123** [comment]
Confirmed problems with Pagination during Search on both websites.
I made some quick corrections in the code but also noticed MangoPorn may have some larger problems as the website is showing WordPress errors and "Categories", "Years", "Studios", and "Pornstars" are not working.

**Comment by camilt** [comment]
#320 Fixed pagination on Search in MangoPorn
