### ISSUE TITLE
Eporner broke

### ISSUE THREAD

**Issue by dobbelina** [dobbelina/repository.dobbelina#316]
Eporner broke after camilt updated it.
If no fix is presented i'll revert back to the previous version that worked.
Btw thanks camilt for the other fixes 👍

**Comment by imurreflection** [comment]
Hi Dobbelina... with all other fixes, I have copied version 1.2.29 eporner.py into 1.2.30 version. Its attached here...hope, this helps.
[plugin.video.uwc-1.2.30.zip](https://github.com/dobbelina/repository.dobbelina/files/5522007/plugin.video.uwc-1.2.30.zip)

**Comment by camilt** [comment]
Fixed scraper and player in #328
