### ISSUE TITLE
Naked Cam site does not work

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#317]
Currently the Naked Cam plugin in UWC does not work and is correctly marked as broken.

Currently working on a fix but it may take awhile. Everything works except video play which is the most important feature.
Traced the problem to a bug in the ffmpeg component of Kodi itself which is not accepting the encryption key URI from the playlist. This was supposedly fixed in the latest versions of ffmpeg but not every version of Kodi has the latest ffmpeg. I am working on a work around.

**Comment by dobbelina** [comment]
Thanks for working on it, appreciate every effort 👍

**Comment by jdoedev123** [comment]
So far have a work around that is working for Kodi 18.8 but not 18.6. Close enough. Will clean up code and post soon.

**Comment by onknight** [comment]
BRavo !!

**Comment by jdoedev123** [comment]
This is a working UWC plugin for Naked Cams.
[naked.py.zip](https://github.com/dobbelina/repository.dobbelina/files/5541331/naked.py.zip)

Some Caveats: This plugin requires "InputStream Adaptive" Kodi Addon to be installed and Enabled. Most newer Kodi builds 18 should have it installed but not necessarily enabled. On Android it is installed and enabled in the App on Linux some versions required a separate install of "kodi-inputstream-adaptive". Have not tested on Windows.

**Comment by Gujal00** [comment]
You could use the RTMP stream as an alternative

**Comment by jdoedev123** [comment]
Perhaps, but as a Linux and Android Dev that would be my last choice as the support in browsers is terrible for debugging.

**Comment by dobbelina** [comment]
Thanks  jdoedev123!

Will have a look at it when time permits.
"InputStream Adaptive" i think most users got as it's required for the youtube addon.
