### ISSUE TITLE
Javhoho. Some issues.Plz check

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#319]
While performing search, Every keyword returning with 'Monday.' Also, the link upon playing displays only 3 hosters but on site, we have 7. This limits the choice to one hoster always available for playback. Also, when you click on any videos,it takes more than usual time to display playback options. Can you please check.

**Comment by camilt** [comment]
#320 For Search

**Comment by imurreflection** [comment]
Thanks @camilt. Search is working fine now. Closing the issue.
