### ISSUE TITLE
Suggestion: Grey out obviously non working website Labels

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#32]
Suggest coloring non working website labels to grey. This is easily done and would help users and developers quickly identify what websites to either avoid (users) or address (developers).
This is easily done in the default.py file 

Example for version 77
[default.py.zip](https://github.com/dobbelina/repository.dobbelina/files/3189162/default.py.zip)

**Comment by dobbelina** [comment]
Thanks for tip jdoedev123,

Will do.
