### ISSUE TITLE
Can't download the newest Version

### ISSUE THREAD

**Issue by onknight** [dobbelina/repository.dobbelina#326]
The newest version of white cream won't download
I've tried it to the repository and downloading it Direct
Any ideas how I can get it to download

**Comment by dobbelina** [comment]
Hi onknight,

Immediately after an update at github it can take a while before all the files
gets updated.
That is even if you can see them in the repository.
Weird, i know.
Mine just updated fine.

**Comment by onknight** [comment]
If I try to download from the depository it fails
**If I download from GitHub it won't install
I get it failed due to an invalid structure**

**Comment by imurreflection** [comment]
Can you tell me your system environment?  PC, Android Box, Android version and Kodi version? It has issues with Kodi Alpha. Try with Kodi Leia 18.9.

**Comment by onknight** [comment]
i have 3  Devices  

2 are PC Running Windows 10 and Kodi 18.9 Both have tones of space  **(Worked fine )**
1 Google Chrome cast Running Android TV 10.0  (the Chromecast has 2.1 Gig Free on main Device and 12 Gig on Flash Drive)
Won't take the update I get it failed due to an invalid structure

**Comment by onknight** [comment]
so Deleted the added  1.2.29 was last one that works on my Chromecast

**Comment by onknight** [comment]
Okay so I got it download  I took it back to 1.2.20  then upgraded to 1.2.29 **(all done Manually )**
Then ran that update in Kodi and it updated to current version 
alot work but it's working Now
