### ISSUE TITLE
HQPorner slow? 

### ISSUE THREAD

**Issue by Kodionpi** [dobbelina/repository.dobbelina#329]
HQPorner is very slow on my device.  I run Kodi 18.8 (Libreelec 9.2.4) on Raspberry Pi 2 Model B (ARM7). Is this normal? 
The videos are very fast (playing normal), but before that --> when I click on the link it takes about 15 seconds until the selection appears to choose the resolution.

**Comment by jdoedev123** [comment]
No similar problems on a Linux box (8 cores x86_64) running Kodi 18.6 or Android 7 (8 cores ARM 64)  running Kodi 18.9.

**Comment by imurreflection** [comment]
No such issues observed on Kodi 18.9 running on Android TV Box
