### ISSUE TITLE
Porntrex and Javbangers web timeout.

### ISSUE THREAD

**Issue by Brozzers** [dobbelina/repository.dobbelina#330]
Everytime i try to play long video from Porntrex and Javbangers (longer than 109 minutes) it cannot played. 

after choosing the resolution, the loading circle icon showed..circling around 35 times (yes I count it) and then loading icon dissapear and back to video page.. no error notification. is there any way to extend the web request timeout for porntrex and javbangers? or the problem is not because the web request timeout.
this issue is not happening in other channels, i tried porn00, datoporn and cliphunter.. all can play video over 109 minutes playtime. 

Btw im using kodi 18.9 in Mi TV (1gb ram with Mali 450 proc).

**Comment by imurreflection** [comment]
I just played a movie with duration of 968 minutes from Porntrex and it played just fine. The movie is over 16 hours. As I also have MITV first generation with 55 inch with 2gb ram, I can say that it is not optimised for Kodi as you must have noticed that it shows Kodi in Trash after installation. I then purchased KM9 Pro with 4gb ram and 32 gb rom and updated it recently to Android 10 and never had any issues. Suggest you to look for an alternative. MITV cannot handle Kodi
