### ISSUE TITLE
Sxyprn(yourporn)

### ISSUE THREAD

**Issue by xyz236** [dobbelina/repository.dobbelina#332]
Sxynprn is down.

**Comment by jdoedev123** [comment]
The website is not down but the UWC plugin is down due to a new Cloudflare challenge.

Testing a quick fix in utils.py:

OLD CODE (Lines 426-429)
        if e.code == 503 and 'cf-browser-verification' in result:
            result = cloudflare.solve(url,cj, USER_AGENT)
        else:
            raise

NEW CODE: (Lines 426-431)
        if e.code == 503 and 'cf-browser-verification' in result:
            result = cloudflare.solve(url,cj, USER_AGENT)
        elif 'trk_jschal_nojs' in result:
            result = cloudflare.solve(url,cj, USER_AGENT)
        else:
            raise

Have not tested if it affects other sites.

**Comment by jdoedev123** [comment]
Hmmm now the unmodified version is working too. May have been a short term problem.
