### ISSUE TITLE
RedTube Live cam minor bug with video resolution selector

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#333]
Thanks to Camilt for RedTube Live. The video resolution selector has a minor bug of the Labels do not match the Resolutions. 1280x720->768x431  , 256x144->1280x720,  768x432->256x144

**Comment by camilt** [comment]
Fixed in #336

**Comment by jdoedev123** [comment]
BTW Many of the RedTubeLive Cam Girls look familiar and the video uri looks familiar. Does "RedTubeLive"  go by another name? Or did the website go by another name?

**Comment by jdoedev123** [comment]
Answering my own question RedTubeLive looks like same database of Cam Girls and video streams as Streamate. I like  the new interface better.
I had been considering creating  Streamlink plugins for Streamate and  RedTubeLive but may only need to build 1 plugin that can handle both. Streamlink is a Python tool to download video streams. Plugins basically parse the videopage URL  (ex:  https://www.redtubelive.com/cam/MistressAdina ) into playable video streams which can be played or stored.

**Comment by camilt** [comment]
Both seems to use the same servers, but RedTube uses API (json) to access info of models. That gives the advantage of more detailed filtering. In Add-on Settings you can set one or more filtering criteria (i.e. Age and Country and Gender in the same time). The JSON also offers you different resolutions streams

"TotalResultCount | 61864" - that's the total number of models!
I used the websocket just to get the status (offline, Payed chat, Private, etc)

**Comment by onknight** [comment]
did anyone know else notice Redtube is just a sub of Streammate

**Comment by 12asdfg12** [comment]
@camilt 
Another small bug, the option for auto choosing the best resolution (option "Don't ask for videohost" in settings) doesn't work for eporner, pornhd, redtube, beeg (fixed)...
Please consider using the selector function from utils with the option  dont_ask_valid=True
