### ISSUE TITLE
Porntrex Account?

### ISSUE THREAD

**Issue by Kodionpi** [dobbelina/repository.dobbelina#334]
Is there something I am missing? How to use the porntrex account? Should I see my saved videos when I type in my porntrex account info under Ultimate Whitecream settings?

**Comment by imurreflection** [comment]
No, saved videos will be under the folder you have specified in download folder settings. Porntrex has lots of ' Private' videos which will be accessible and playable only when you are logged on to the account. Just enter your credentials in account settings for Porntrex and you should be able to access those "Private" videos.

**Comment by Kodionpi** [comment]
Oh, okay. Thanks for the answer! Sry, I put that wrong.  --by "saved videos" I meant those "Favourite Videos" from the Porntrex Account. Is there a way to show these favorite videos from the porntrex account profile within der Ultimate Whitecream addon?

**Comment by imurreflection** [comment]
Hmmm...not sure if the question is the ability to see all videos favorited from Porntrex only. However, there is no way to see videos favorited from one particular site only if other sites videos are also favorited. All favorites are available under ' Whitecream Favorites" on UWC main menu.

**Comment by Kodionpi** [comment]
Okay. Yeah, that is what I meant by that. On the first page of the Porntrex Addon in UWC next to "Categories" "Channels" "JAV" "New" "Longest" "Search" there should be a "Favourite Videos" which shows the videos that are saved in my profile of the porntrex account. That would be very nice, if this is somehow possible.
