### ISSUE TITLE
[Request] Add Favourite Videos from Porntrex Account

### ISSUE THREAD

**Issue by Kodionpi** [dobbelina/repository.dobbelina#335]
Hi, thanks for your work! Is it possible to add Favourite Videos from Porntrex? On the first page of the Porntrex Addon in UWC next to "Categories" "Channels" "JAV" "New" "Longest" "Search" there should be a "Favourite Videos" which shows the videos that are saved on the profile of the porntrex account.

Thank you!

**Comment by jdoedev123** [comment]
I dont have a Porntrex account so someone else would have to add that feature. 
I do have a means to sort UWC favorites by website but that is done with a third party tool and is independent of "Porntrex Account".

**Comment by 12asdfg12** [comment]
added in #345, works for porntrex and javbangers, but add/delete is slow for porntrex (requires a few minutes), this is a website issue

**Comment by imurreflection** [comment]
Hi @12asdfg12. Welcome back and thanks for this. One request if is it possible to add 'videos being watched' feature. This is on the main page of Javbangers when you open the site and really has good hand picked videos and it gets refreshed regularly. If this can be added,it would b great. Thanks
