### ISSUE TITLE
Javhoho- No Thumbnails

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#338]
Suddenly, thumbnails have been disappeared. @camilt, please check

**Comment by camilt** [comment]
#339

**Comment by imurreflection** [comment]
Thanks @camilt mate. Can you please look at my issue on porngo.com please

**Comment by imurreflection** [comment]
Thanks again for the fix. However, please note A) Its now taking some extra time to go to stream selection menu B) out of three available hosters bitporno,streamz.cc and youvideos.ru, only the last one is playable. streamz.cc i am not sure but bitporno.com should play as we have it in our addon. can you please look into these issue before Dobbelina releases final update? Thanks in advance !
