### ISSUE TITLE
Hentaihaven

### ISSUE THREAD

**Issue by gutho877** [dobbelina/repository.dobbelina#34]
Any chance getting links to work again? Thanks.

**Comment by dobbelina** [comment]
Both hentai sites have been marked broken.

**Comment by gutho877** [comment]
Just realised that none of the links on the site work anymore to begin with. Sorry for wasting your time.

**Comment by gutho877** [comment]
Okay, links with HH site are working again. Anyone got a fix?

**Comment by 12asdfg12** [comment]
HH fixed

[hentaihaven.zip](https://github.com/dobbelina/repository.dobbelina/files/3243881/hentaihaven.zip)

**Comment by dobbelina** [comment]
Thanks for fix 12asdfg12,

Will update addon soon.

**Comment by WhitecreamDev** [comment]
Here is a fixed AnimeidHentai :)

[animeidhentai.zip](https://github.com/dobbelina/repository.dobbelina/files/3263110/animeidhentai.zip)

(No, i'm not back.....I'll just upload some fixes/improvements from my non public version now and then)

**Comment by imurreflection** [comment]
Hey WhitecreamDev, is it possible for you to look at tubepornclassic and hclips please. Its an opinion that it cannot be fixed ...can you please check this.

**Comment by dobbelina** [comment]
Thanks for Animeid Hentai fix WhitecreamDev.
Hentaihaven fix doesn't work for me?, links don't play.

**Comment by 12asdfg12** [comment]
Right now the links don't work on the site, i think the fix for HH is ok.

**Comment by WhitecreamDev** [comment]
Your fix is only for one of the hosts they use, some videos like for example Resort Boin (or something) still have <source video direct links.

**Comment by 12asdfg12** [comment]
I tried to add these direct links, but it does not works in kodi, the "workig" message appears,
but it stops with error 404, looks like the connection is interrupted before the video starts playing. No idea how can be fixed, could be a problem on server side.

[hentaihaven.zip](https://github.com/dobbelina/repository.dobbelina/files/3282071/hentaihaven.zip)

**Comment by WhitecreamDev** [comment]
I just did a quick test, if you add the referer and user-agent to the direct source links, they would play.

`videourl = videourl + '|Referer=%s&User-Agent=%s' % (url, utils.USER_AGENT)`

**Comment by WhitecreamDev** [comment]
This would work with both direct links and iframed ones (that are supported by Resolveurl)

```
def Playvid(url, name, download=None):
    links = {}
    vp = utils.VideoPlayer(name)
    vp.progress.update(25, "", "Loading video page", "")
    videopage = utils.getHtml(url)
    iframes = re.compile('<iframe.+?src="([^"]+)"[^>]+>.*?</iframe', re.DOTALL | re.IGNORECASE).findall(videopage)
    if iframes:
        for link in iframes:
            if vp.resolveurl.HostedMediaFile(link):
                links[link.split('/')[2]] = link
    srcs = re.compile('label="([^"]+)" src="([^"]+)" type=', re.DOTALL | re.IGNORECASE).findall(videopage)
    if srcs:
        for quality, videourl in srcs:
            links['Direct ' + quality] = videourl + '|Referer=%s&User-Agent=%s' % (url, utils.USER_AGENT)

    videourl = utils.selector('Select link', links, dont_ask_valid=True)
    if '|Referer' in videourl:
        vp.play_from_direct_link(videourl)
    else:
        vp.play_from_link_to_resolve(videourl)
```

**Comment by dobbelina** [comment]
Thanks for input WhitecreamDev,

For some strange reason all the links are now playing fine without above fix?

**Comment by 12asdfg12** [comment]
awesome. i had no idea that resolveurl can resolve this links

**Comment by WhitecreamDev** [comment]
> 
> 
> Thanks for input WhitecreamDev,
> 
> For some strange reason though, all the links are now playing fine without above fix?

Could be yes, but still, my addition is currently the best way to play most videos from Hentaihaven. I now even use this in my non-public personal Ultimate Ultimate Whitecream 2.0 Advanced Plus Edition :)

**Comment by WhitecreamDev** [comment]
> 
> 
> I tried to add these direct links, but it does not works in kodi, the "workig" message appears,
> but it stops with error 404, looks like the connection is interrupted before the video starts playing. No idea how can be fixed, could be a problem on server side.
> 
> [hentaihaven.zip](https://github.com/dobbelina/repository.dobbelina/files/3282071/hentaihaven.zip)

BTW, I noticed you used the tab char (/t) in your file. It's common practice with Python (and used in UWC) to have the tab be 4 space chars. I don't know what editor you use, but with for example you could easily set the behavior of the Tab to insert 4 spaces for Python files.
See for example https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces

**Comment by 12asdfg12** [comment]
You are right, i was using the editor from Far Manager, i guess i'll switch to notepad++.
BTW, i am not a programmer and python is pretty new to me, but it's fun

**Comment by dobbelina** [comment]
Will update addon soon with WhitecreamDev's addition.

**Comment by imurreflection** [comment]
Hi Whitecreamdev, can you please look at my issue. Being the author, I thought you are the best person for getting this fixed. However, if its not possible,kindly say so and I won't trouble you further.

**Comment by WhitecreamDev** [comment]
Yes, I have fixed the txxx sites (hdzog, tpc etc)

```
def GetTxxxVideo(vidpage):
    vidpagecontent = utils.getHtml(vidpage)
    posturl = 'https://%s/sn4diyux.php' % vidpage.split('/')[2]

    pC3 = re.search('''pC3:'([^']+)''', vidpagecontent).group(1)
    vidid = re.search('''video_id["|']?:\s?(\d+)''', vidpagecontent).group(1)
    data = '%s,%s' % (vidid, pC3)
    vidcontent = utils.getHtml(posturl, referer=vidpage, data={'param': data})
    vidurl = re.search('video_url":"([^"]+)', vidcontent).group(1)

    replacemap = {'M':'\u041c', 'A':'\u0410', 'B':'\u0412', 'C':'\u0421', 'E':'\u0415', '=':'~', '+':'.', '/':','}
    
    for key in replacemap:
        vidurl = vidurl.replace(replacemap[key], key)

    vidurl = base64.b64decode(vidurl)

    return vidurl + "|Referer=" + vidpage
```
it's up to the others to incorporate this :)

**Comment by WhitecreamDev** [comment]
If it breaks after this, I wont push a fix public again.....

**Comment by 12asdfg12** [comment]
thanks for sharing this fix 
Fixed hdzog & tpc.

**Comment by imurreflection** [comment]
@WhitecreamDev ..Hi, thank you so much for extending your expertise and support. However, please see that in initial request, I requested tubepornclassic and hclips not hdzog to be fixed. hclips has huge content library. Can you please look into it.

**Comment by 12asdfg12** [comment]
the fix works for hclips too, same network
[hclips.zip](https://github.com/dobbelina/repository.dobbelina/files/3364539/hclips.zip)

**Comment by imurreflection** [comment]
Ah..you guys are just awesome. Thank you so much WhitecreamDev and 12asdfg12

**Comment by imurreflection** [comment]
Hi, 12asdfg12, there is an extremely nice japanese site from the same network. It's vjav.com. is it possible to get this added please.

**Comment by Donny-Pandairaz** [comment]
It would appear that skipping forward in a video passed the point of what as already been loaded in the video player causes the video to halt and boot you back to the video selection menu.
