### ISSUE TITLE
ParadiseHill it's gone in latest 1.2.35

### ISSUE THREAD

**Issue by flapbird1** [dobbelina/repository.dobbelina#344]
ParadiseHill it's gone in latest 1.2.35, reverted to 1.2.34 bring it back

Can you please check? Many thanks all

**Comment by dobbelina** [comment]
Really odd?

It should be there.
When i change the name ParadiseHill to Paradise Hill in default.py it reappears?
I wonder if it's the new addition to hide sites that's spooking?
See example below.
Is hidden:
`utils.addDir('[COLOR hotpink]ParadiseHill[/COLOR]','http://www.paradisehill.tv/en/',250,os.path.join(imgDir, 'paradisehill.png'),'')`
Is shown:
`utils.addDir('[COLOR hotpink]Paradise Hill[/COLOR]','http://www.paradisehill.tv/en/',250,os.path.join(imgDir, 'paradisehill.png'),'')`

Maybe camilt know why this happens.

**Comment by camilt** [comment]
I found the explanation. In settings.xml is already a key with the id=paradisehill (for "Play all parts"). So, in addDir you should let it be "Paradise Hill"

**Comment by dobbelina** [comment]
> 
> 
> I found the explanation. In settings.xml is already a key with the id=paradisehill (for "Play all parts"). So, in addDir you should let it be "Paradise Hill"
Aha, that explains it.
Change has been made, thank you for investigating.
