### ISSUE TITLE
Yourporn issue

### ISSUE THREAD

**Issue by Sameer888** [dobbelina/repository.dobbelina#35]
Hi dobbelina , Yourporn is not working i think there are some changes done by site 
Eg: Typing yourporn.sexy does not yield any result on browser as before but after typing sxyprn.com its giving result 
Please look yu know much better Thanks

**Comment by dobbelina** [comment]
Hi Sameer888,

Seems they changed url for the site.
Here's a fix:
[yourporn.zip](https://github.com/dobbelina/repository.dobbelina/files/3196590/yourporn.zip)

Will update the addon in the next release.

**Comment by Sameer888** [comment]
Thank yu for the fix
