### ISSUE TITLE
IPornovideos Issue 

### ISSUE THREAD

**Issue by darktones123** [dobbelina/repository.dobbelina#350]
Both Vidlox and Videobin are not working. I get a error message to check the log. Is anyone else experiencing this issue? 

Thanks

**Comment by flapbird1** [comment]
Hello there,
Videobin only works form me, recently had issues too with videobin links,  cleaning RevolveURL cache manually fixed those, but no need now.
My current setup:
 Android 7, UWC 1.2.36 and RevolveURL 5.1.15
I hope this helps

**Comment by camilt** [comment]
Vidlox resolver needs to be updated. Till then, make a backup of the original in script.module.resolveurl\lib\resolveurl\plugins\, then replace vidlox.py with this:
[vidlox.zip](https://github.com/dobbelina/repository.dobbelina/files/5621888/vidlox.zip)
(unpacked/unzipped)

**Comment by darktones123** [comment]
Is there a way to do what you suggested through the firestick? Do I use Downloader? Sorry my technical abilities are limited haha Thanks, your help is much appreciated!

**Comment by flapbird1** [comment]
**@camilt** 
Your fix works flawlessly, well done
**@darktones123** 
To apply Camilt's fix you're going to need an APP like ES File Explorer details: 
www.youtube.com/watch?v=hGo5OFNIk0Y

As follows:
1 download above vidlox.zip
2 unzip it with ES File Explorer and copy
3 Paste & overwrite existing vidlox.py with the new vidlox.py located at:

Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.resolveurl/lib/resolveurl/plugins

I don't have firestick above path should be similar to yours

I hope this helps
