### ISSUE TITLE
[Request] Chaturbate followed cams

### ISSUE THREAD

**Issue by Kodionpi** [dobbelina/repository.dobbelina#351]
Thank you so much for your work  @12asdfg12  @dobbelina  -that we can now access the favorites in the Porntrex Addon!!  

Would it also be possible to make a login at Chaturbate, so that we can access the followed cams? 
--> chaturbate.com/followed-cams/

Thanks a lot!

**Comment by jdoedev123** [comment]
I am sure this can be done. But a word of caution. I used to use a tool which accessed Chaturbate accounts and favorites. It eventually got banned for signing in and checking  favorites too frequently.
