### ISSUE TITLE
PornHD download filenames

### ISSUE THREAD

**Issue by TarkusLV** [dobbelina/repository.dobbelina#352]
First, thanks for fixing the PornHD download function.

There is still a very small issue.  Normally when downloading, UWC uses a "tmp......" filename while downloading and then renames the completed file to match the name of the source.  However, in PornHD, it retains the temporary filename, so you're left with a bunch of videos with generic filenames.

I would appreciate it if you could look into that.  Thanks.

**Comment by camilt** [comment]
Fixed in #354
