### ISSUE TITLE
Naked.down again

### ISSUE THREAD

**Issue by onknight** [dobbelina/repository.dobbelina#355]
I went back to use naked again abd it down 
you click on it and it shows nothing just Refresh image icon

**Comment by jdoedev123** [comment]
Confirmed.  Noticed a few hours ago while testing  UWC in Kodi 19 and checked it is down in  Kodi 18 UWC  too.

**Comment by camilt** [comment]
Try #357

**Comment by dobbelina** [comment]
Still no playable webcam links after the fix.

**Comment by onknight** [comment]
Yep agree tried them last night

**Comment by jdoedev123** [comment]
I am taking another try at a fix. They changed the website again.

**Comment by jdoedev123** [comment]
Weird I have an experimental fix that should work but only works after I go to Kodi 
Settings->Add-Ons->All->My Addons->InputStream Adaptive
and Disable and Renable InputStreams Adaptive.
Otherwise it defaults to ffmpeg within Kodi which has a known bug.

**Comment by onknight** [comment]
seems keeping this one up is going to be a challage
