### ISSUE TITLE
Just to talk - Future of uwc

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#356]
Hi Dobbelina, kindly send the invite for same to all available community members please. I understand we may not be able to provide any technical support but we can always support the ongoing discussions and provide inputs. It always will be discretion of developers including yourself to decide what's good for our UWC but please let us also witness the new growth. Kindly consider.

**Comment by dobbelina** [comment]
Hi imurreflection,

That discussion is not initiated by me or any of our team members.
It is at their discretion as to who gets invited.

**Comment by imurreflection** [comment]
Thank you for the response. Closing the issue now
