### ISSUE TITLE
Downloaded filenames:  Files showing underscores instead of spaces 

### ISSUE THREAD

**Issue by tetzy** [dobbelina/repository.dobbelina#358]
I'm using Linux:  In my testing, all files downloaded (multiple sites) show underscores instead of spaces in the file names.
ex: 
'File_Downloaded_To_My_Linux_PC.mp4" instead of "File Downloaded To My Linux PC.mp4"

I'm hoping this was an inadvertent error in the newest update instead of a new 'feature' - It's forcing me to manually rename every file.

Thanks for your efforts in making and updating UWC - you're doing God's work ;)

**Comment by camilt** [comment]
Fixed in #357
