### ISSUE TITLE
Freeomovie 

### ISSUE THREAD

**Issue by kapslock16** [dobbelina/repository.dobbelina#36]
Freeomovie is not working no links work please sort this out

**Comment by kapslock16** [comment]
Hi dobbelina will this get fixed then?

**Comment by kapslock16** [comment]
Please add openload links to freeomovie

**Comment by kapslock16** [comment]
Guess u pick what u answer to

**Comment by dobbelina** [comment]
Somebody with the knowledge have to provide a fix.
I'm not that person.

**Comment by kapslock16** [comment]
Sorry dobberlina can anyone help on this
