### ISSUE TITLE
Strange issue- Freevideo.cz

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#362]
Hi. First, thanks to @m-incognito for adding freevideo.cz. This is an amazing site. 

Issue- I m not sure if others are experiencing this issue but I have discovered a strange issue is about the exact content availability on the site. Let me explain: 

1) When you first click on the site,it opens and all links plays fine but there is no 'Next' tab available. Surprisingly, when you reopen site site, the ' Next' tab reappears and you can browse til it disappears again.
2. When you search kategory, it sometime shows you 58,63,68,75,82,88 and finally 95. I m not sure exactly how many categories are actually there.
3. Categories like japonky etc are missing due to above error till you click many times.
4. If you put the category in " Favorites' and then access them, you will not find 'Next' page no matter how many times you re-access them. From the site Kategory, till the time you don't find the 'japonky" , you need to keep refreshing the "Kategory' and once you locate it, you will sometime find the "Next' page to go to second page till the time 'Next' tab disappears again.

Since @m-incognito added this site, he may be able to provide some insight but at the same time time, I request everyone to check if they are experiencing this issue or its an issue with my setup. I am not facing this issue with any other site. 

I am using official Android TV box running Android 10. The box has 4 gb ram and 32 gb rom.

**Comment by imurreflection** [comment]
Hi @dobbelina @jdodev123 @camilt and @djmixican, can you all please confirm if you are also experiencing the same issue please?

**Comment by jdoedev123** [comment]
@imurreflection  quick look at the code and website. Code looked very good at first glance. Website was hard to navigate for someone that doesn't know the language. Plugin seemed very usable with nice features and good quality content. I did not do the deep dive you did with functionality and I was lucky to figure out where "Big Boobs", "Lesbian", etc were. I wouldn't mind a translation feature if possible.

**Comment by imurreflection** [comment]
Thank you so much bro @jdoedev123 and you are really lucky to navigate through any category as for me, there is no luck..every time clicking link redirects me to another site but overall the site has excellent content...may be better than Porntrex. 

May I request you to please check atleast category in our add-on. Are you able to get 95 categories at one go?

**Comment by m-incognito** [comment]
Your issue is really strange. I cannot reproduce the issue even when trying different VPNs. 

The website is a bit tricky, it displays different content for Czech/Slovak IP adressses and rest of the world. So the addon internally uses a free Czech proxy https://www.katedrala.cz/ to fetch all video links. In your case, it looks like the page is not fully loaded sometimes (the last category should be "Zrzky" - "redheads"). That's why the "next page" button misbehaves for you.

Maybe a different czech/slovak proxy or anonymizer would help. But I'm not sure if there are any reliable.

**Comment by imurreflection** [comment]
Thank you for your reply @m-invognito. It seems that this issue could not be resolved but this is a wonderful site and thanks for the addition. Closing the issue now.
