### ISSUE TITLE
UWC, add move favorite to the beginning

### ISSUE THREAD

**Issue by surreydave** [dobbelina/repository.dobbelina#370]
Not sure how difficult this is to do, but think I will ask anyway. Can move favorite to the beginning be added to the dropdown menu please? this would help very much with organising my favorites.

**Comment by dobbelina** [comment]
Hi @surreydave ,

It's being worked on, but it will probably be a "move to the end" solution.

**Comment by TarkusLV** [comment]
"Move to end" is already there (my request filled from long ago).  :)

**Comment by dobbelina** [comment]
@TarkusLV 
Ooops, sorry you are right 😊

**Comment by camilt** [comment]
#378
