### ISSUE TITLE
freeomovie.com (currently .to) fails playing any hosting

### ISSUE THREAD

**Issue by flapbird1** [dobbelina/repository.dobbelina#374]
Hi guys,
freeomovie.com (currently .to) 
play & download fails on my end, 
any hosting:

-streamtape
-aparat
-upstream
-jetload 

Checked on Android 7 and macOs 11.1.
Could you please check & fix?
Many thanks in advance

**Comment by dobbelina** [comment]
Must be a platform issue, on Windows it works fine.

**Comment by flapbird1** [comment]
Thanks **dobbelina** for taking your time on this.
Could you please share your windows configuration and I'll check against mine.I have nothing installed in Kodi but UWC:

Do you have:
Any other resolver other than UWC included?
RealDebrid or similar?

Many thanks!

**Comment by flapbird1** [comment]
Thanks **dobblelina** for your spent time on this.
Changed VPN and I can play / download streamtape links (some times gives "no links found" but retry will fix it), at least.
Feel free to update UWC logo with the attached
Keep up the great job!

![freeomovie-to-logo](https://user-images.githubusercontent.com/74716864/102686260-b206b680-41e6-11eb-884a-383a5464edec.png)

**Comment by flapbird1** [comment]
Ok now

**Comment by dobbelina** [comment]
@flapbird1 
Thanks for the image.
Will be updated in the next release.
