### ISSUE TITLE
How to force chaturbate to use best quality when streaming

### ISSUE THREAD

**Issue by Doktor-X** [dobbelina/repository.dobbelina#379]
Hello, so i did not see that this question is been adressed before so i dont know is this problem with addon itself or with kodi/coreelec, but when i open models stream stream starts with lowest quality possibe and i need to go to kodi's menu and select stream 3 for best quality, so my question is can this problem be solved with any setting in addon to force best quality stream

**Comment by imurreflection** [comment]
In add-on settings under 'General' select 'Filter by Quality' to your choice and under 'Hosts and Resolvers' select 'don't ask  for videohost' to yes/clicked.

**Comment by Doktor-X** [comment]
Its not working i still need to manualy select higher stream

**Comment by imurreflection** [comment]
I am not sure mate. Guess, we have to wait for our friendly developers to look at this.

**Comment by Doktor-X** [comment]
Yes we need dev to give his input

**Comment by 12asdfg12** [comment]
> 
> 
> ... i need to go to kodi's menu and select stream 3 for best quality ...

Which Kodi menu and where is this "stream 3"? Can you put a picture?

**Comment by Doktor-X** [comment]
I have made screenshot on android since its easyer to upload image but its same menu
![Screenshot_20201223-095735_Kodi](https://user-images.githubusercontent.com/2572698/102979116-e5f31c00-4505-11eb-8757-de23c4ed6aa9.png)
![Screenshot_20201223-095747_Kodi](https://user-images.githubusercontent.com/2572698/102979140-edb2c080-4505-11eb-80e4-204bb37c467a.png)

**Comment by 12asdfg12** [comment]
I am not sure, maybe is related to Inputstream Adaptive addon (is installed, enabled?) or try to change the settings.

**Comment by Doktor-X** [comment]
Yes i have it for 4k youtube, maybe ill try clean install of coreelec (but im not fan of setting up all my stuff all over again)

**Comment by Doktor-X** [comment]
Cleen install of kodi 18.9 (running on coreelec nightly 20201210) and same problem like before

**Comment by 12asdfg12** [comment]
Try looking for a chaturbate video link in kodi.log, something like:
`....  NOTICE: VideoPlayer::OpenFile: https://edge153.stream.highwebmedia.com/live-hls/amlst:yum_yum_-sd-1835c8decc13f52cfc25a6dd45d61f649870ab9d42a7893d325e1c8294b0e17c_trns_h264/playlist.m3u8`

You can play directly this link in kodi (create a file with .strm extension and open it from kodi/ videos/ files) or vlc (open network stream) and see the quality.

If you open the link in a browser and choose "save", you get a playlist.m3u8 file which contain links with different resolutions.
This is a hls stream and is handled by kodi (and inputstream adaptive addon: https://www.kodi-guide.com/how-to-enable-inputstream-adaptive-in-kodi/).

**Comment by Doktor-X** [comment]
Inputstream works fine since i can play 4k youtube just fine, but i dont understand why this addon wont play best resolution video automagically but i need to select it manualy. Is it possible to add some sort of option in addon settings to force best possible video

**Comment by 12asdfg12** [comment]
The video link contains all the resolutions, there are no different links for each resolution, we cannot choose from UWC which resolution to play.
