### ISSUE TITLE
Cam Site  problems

### ISSUE THREAD

**Issue by onknight** [dobbelina/repository.dobbelina#38]
Cam soda is not working  none cam models are showing at all
Cam4 is also down Same problem as cam soda

**Comment by 12asdfg12** [comment]
[cam.zip](https://github.com/dobbelina/repository.dobbelina/files/3203673/cam.zip)

fix for camsoda & cam4

**Comment by dobbelina** [comment]
Thanks 12asdfg12,

Will update in next release
