### ISSUE TITLE
Freeomovie

### ISSUE THREAD

**Issue by deanogers** [dobbelina/repository.dobbelina#380]
Keep getting http error forbidden on kodi can u fix

**Comment by imurreflection** [comment]
On Android it's running fine. May be it's related to your network. Please try using VPN

**Comment by dobbelina** [comment]
No problems on Windows either.

**Comment by flapbird1** [comment]
Same issue happened to me recently, please check:

https://github.com/dobbelin/repository.dobbelina/issues/374

**Comment by deanogers** [comment]
Still getting errors with this keeps saying can’t find any links and streamtape links don’t work can u fix please
