### ISSUE TITLE
streamxxx.tv - add search like website, possible?

### ISSUE THREAD

**Issue by flapbird1** [dobbelina/repository.dobbelina#381]
Hi guys,
@ streamxxx.tv 
add search functionality, like website, possible?
Many thanks in advance

Current logo attached below, if you willing to update it

![current_streamxxx](https://user-images.githubusercontent.com/74716864/102922174-e0f28600-448d-11eb-9fa4-7d0abf0ef70d.png)

**Comment by dobbelina** [comment]
@flapbird1 
"Search Overall" is already there?
Thanks for the image.

**Comment by flapbird1** [comment]
No "search" given like others, just back to menu, pic below:

![IMG_20201222_233423](https://user-images.githubusercontent.com/74716864/102939650-f0ce9200-44ae-11eb-9d0a-6172430c573d.jpg)

**Comment by dobbelina** [comment]
What are you talking about?
There is 2 search options from the main menu:
<img width="960" alt="screenshot000" src="https://user-images.githubusercontent.com/46063764/102940374-7868d080-44b0-11eb-9e88-2f1fd41a7b0e.png">

**Comment by camilt** [comment]
![image](https://user-images.githubusercontent.com/33828321/102942760-db616400-44be-11eb-8eb7-ac3766612325.png)
Please check under Add-on Settings, ReEnable Sites/Categories. Maybe you disable it?

**Comment by flapbird1** [comment]
Hi guys,
Thanks for your feedback. 
Above screenshots left me puzzled. 
Oddly enough, I've never seen those menus on streamxxx. 😱

Checked on both, Android 7 and 
macOs 11.1 ,same result:

1-Started a fresh Kodi install
2-Install repo and latest UWC from repo
3-Checked "ReEnabled Sites" as per above advise,
   screenshot below:

![Screenshot_2020-12-23-08-03-49-947_org xbmc kodi](https://user-images.githubusercontent.com/74716864/102970797-762a6480-44f8-11eb-9a4b-50c4f03db292.png)

If I click in the red rectangle, "ReEnabled Sites" 
disappears and don't show up in menu any longer.
4- Still no menus, like above, on streamxxx
5- Checked Paradise Hill, screenshot below:

![Screenshot_2020-12-23-08-11-53-586_org xbmc kodi](https://user-images.githubusercontent.com/74716864/102971148-18e2e300-44f9-11eb-9c77-8395bc6c9faa.png)

What's wrong? Is this just me?
Many thanks all

**Comment by 12asdfg12** [comment]
Try streamxxx from Scenes, not Movies.

**Comment by dobbelina** [comment]
> 
> 
> Try streamxxx from Scenes, not Movies.

@12asdfg12 Good one! 👍

**Comment by flapbird1** [comment]
We have 2 streamxxx 😂😂😂 and just find out.
**@12asdfg12** 👍

**@dobbelina**  shall we remove 1 from UWC, avoid duplicity and towards better and easier troubleshooting?
Keep up the great work

**Comment by camilt** [comment]
Streamxxx have 2 sections, clips and movies. The search is common for both. #384

**Comment by flapbird1** [comment]
Awesome **@camilt** many thanks
