### ISSUE TITLE
PornTrex proposed improvements

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#39]
PornTrex is a great source especially for 4k and HD but the quantity sometimes overruns quality. In an effort to assist users, experimenting with adding additional filters. So far have added a "Channels" section from the source website, a "JAV" section (actually a link to uploads of a top contributor of Japanese JAV porn) and a "New" section for videos tagged as New.
Any other suggestions (within reason)?

[porntrex.py.zip](https://github.com/dobbelina/repository.dobbelina/files/3219787/porntrex.py.zip)

**Comment by dobbelina** [comment]
Thanks for the effort jdoedev123,
It's an improvement for sure.
I think it looks really good, (I wish i had more appendages, ha ha lol)

Will update in next release.

**Comment by jdoedev123** [comment]
Also added a "Longest" section. Wish I could add a reliable filter for Movies but no consistent use of naming or tags for Movie, DVD, etc. to use as a filter.
Will upload after further testing of latest changes.

**Comment by dobbelina** [comment]
Look forward to it, thanks.

**Comment by imurreflection** [comment]
Hello there.. Waiting for the addition of "Longest" section. This would be a great improvement.

**Comment by withoutprefix** [comment]
thanks all for the above improvements.
it would be helpful if the PornTrex search results will be sorted by newest date

thanks again.

**Comment by jdoedev123** [comment]
In testing Longest feature works except the very first result is ridiculously long  7624 minutes otherwise times seem correct. I will post shortly just want to check a few things.

**Comment by jdoedev123** [comment]
Search results are tricky. Current default are sorted by "Most Relevant". Testing with sorting by "Latest-Updates" leads to inconsistent results. Some of the current results for close but incorrect matches now may appear at top of list.

**Comment by jdoedev123** [comment]
PornTrex with Longest feature.
[porntrex.py.zip](https://github.com/dobbelina/repository.dobbelina/files/3288454/porntrex.py.zip)
