### ISSUE TITLE
Websock Library won't install  

### ISSUE THREAD

**Issue by onknight** [dobbelina/repository.dobbelina#390]
I can use any of the addons on Kodi PC Version cause  Websocket Library won't install
This has to be a way to fix this

**Comment by ErosVece** [comment]
Are you on Matrix?
Do you have an old websocket module installed and disabled (because of Kodi version update)?
See if you have this folder: %appdata%\kodi\addons\script.module.websocket  (remove it and try installing again)

**Comment by onknight** [comment]
ErosVece,
Thanks Got working on Kodi 19  
But 18.9 is a no so for Now I disabled the Repo till I know we get something that works

**Comment by godsrice** [comment]
I had this issue on fire tv 18.9 if anyone is having issues with this go to the dependencies list for cumination and go to websocket library and try to install/update it on its own. Mine errored out there as well so click on dependencies for websocket and update those files individually and then everything should install properly. Hope this helps my firetv and firestick family.
