### ISSUE TITLE
Keywords/Favorites error

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#391]
Hi, for some reason,I had to uninstall Kodi and when I reinstalled, my keywords and favourite's are not getting restored using new UWC version. Please help, Favorites I can manage but I had more than 250 keywords. It's extremely difficult to first remember and then type them manually. I am getting invalid file error. I am using Kodi Leia 18.9 and both UWC and Cumination are working fine.

**Comment by 12asdfg12** [comment]
Restoring keywords from uwc does not work in the current version of combination.

If you can't restore the keywords in uwc, check the integrity of the backup files.
- change the extension of the backup files from bak to gz
- extract the content of the archive with 7zip or winrar
- open the extracted file with notepad, you should see something like:
`{"meta": {"version": 1, "type": "uwc-keywords", "datetime": "2021-01-03_11-11-35"}, "data": [{"keyword": "aaa"}, {"keyword": "bbb"}]}`

**Comment by imurreflection** [comment]
Can you advise on which version is it supported on Kodi 18.9. I will first install that version, restore keywords and favorites and then upgrade it to latest version. Will that work mate?

**Comment by 12asdfg12** [comment]
You can't upgrade from uwc to cumination, cumination is a new addon.
Keywords restore will work in the next version of cumination  .
Favorites restore should work in the current version.

**Comment by imurreflection** [comment]
I am trying to restore keywords in UWC and not in Cumination. I know Cumination is a separate add-on and my saved keywords won't work there but atleast they should work in UWC bro

**Comment by 12asdfg12** [comment]
Restoring keywords works for me in uwc latest version, maybe your backup file is corrupted.

**Comment by imurreflection** [comment]
I don't know what to say here but if everyone is able to restore the keywords then there is some issue at my end..all I can say is HARD LUCK for me. Closing the issue now.
