### ISSUE TITLE
Pornhub not working in UWC

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#393]
Hi, Pornhub in our add-on UWC not working. Checked the same on Cumination and it's working fine there though next page is throwing error example a search on the keyword 'ourshdtv.' Checked it on Video Devil and it's working fine there along with next page. Can't see the reason why it's down in UWC. Can you please check.

**Comment by Gujal00** [comment]
same as #369

**Comment by imurreflection** [comment]
I agree this is same as other issue mentioned by @Gujal00 but please see there is no response on that issue after Dec 17 whereas the site is working fine on Cumination and Video Devil. UWC has keyword function but it's not there in Videodevil whereas in Cumination, there is an error when trying to access Next tab.

**Comment by dobbelina** [comment]
@imurreflection 
Next page is fixed in 1.1.2

**Comment by imurreflection** [comment]
Yes and thank you so much for it..all you guys are amazing...thanks again and closing the issue now
