### ISSUE TITLE
Cumination-Keywords still not fixed

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#394]
In the new Cumination update, it says in the change log that keywords restore function has been fixed but sadly it hasn't been. Still getting invalid file error Can you please recheck this

**Comment by ErosVece** [comment]
I just tested this from latest UWC to Cumination on Leia and Matrix (Windows). It imported fine for me.
Maybe share your backup, so we can see what is going on.
Also, if you get an error message, please provide debug log.

**Comment by Kodionpi** [comment]
I had the same issue as @imurreflection (though before the fix).  To "solve" it, I accessed the Pi2 with Libreelc via Windows. I opened the folder \\LIBREELEC\Userdata\addon_data\plugin.video.uwc\ and copied "favorites.db". Then paste this file (favorites.db) under the folder \\LIBREELEC\Userdata\addon_data\plugin.video.cumination\ and overwrite the existing file there.

**Comment by ErosVece** [comment]
That would work too, but only for the keywords.
You would need to clear the favorite videos, and import it back from UWC to get them to work.

**Comment by Kodionpi** [comment]
True, only for the keywords. The backup of the favorite videos worked from the beginning. -so nothing additional had to be tried here.

**Comment by imurreflection** [comment]
Hi @kodionpi and @erosvece, can you please provide me the actual location where uwc keywords are stored please? Please for uwc and not Cumination. I can then try to do manual copy paste as suggested. I had 250 plus keywords and manual typing will take lot of time. Please note that I am on official Android TV Box KM9 Pro running Android 10.

**Comment by Kodionpi** [comment]
There are several ways to do this. I usually use the SMB service or SSH to access Libreelec from Windows.Maybe you should backup the "favorites.db" in uwc to another directory first.I don't take any responsibility for this process, - myself I used only the way via SMB. 


Without SMB, SSH, Windows:

Kodi --> File manager --> (on the left column) Profile directory --> addon_data --> plugin.video.uwc

On the right column: Profile directory --> addon_data --> plugin.video.cumination

--->back to the left column with uwc --> select "favorites.db" --> copy--> so that the file in cumination is overwritten.

**Comment by godsrice** [comment]
I was able to manually copy my favorites.db file from uwc to cumination within kodi and also using es file explorer and it shows all my favorites but they all error out when trying to play. But the favorites play fine in uwc. This is on fire tv on 18.9 and neither restore favorites or keywords work I am also getting invalid file error

**Comment by dobbelina** [comment]
@godsrice 
If you are going to do a manual export of favorites you have to use a database tool
like [DB Browser for SQLite Portable](https://portableapps.com/apps/development/sqlite_database_browser_portable).
The 2 databases have different structure, you can't just copy it over.

**Comment by godsrice** [comment]
Got it thank you @dobbelina I will give it a try! And will report back if I pull it off and help others having difficulty with Amazon fire products
