### ISSUE TITLE
Cumination 1.1.2 / Xtheatre plays nothing

### ISSUE THREAD

**Issue by flapbird1** [dobbelina/repository.dobbelina#395]
Hi guys,
First, congrats for Cumination, finally got an excuse for Kodi 19 to be installed 👏

Also Xtheatre plays nothing, can you please check?

Many thanks in advance

**Comment by Gujal00** [comment]
The recent videos are using netu/waaw/hqq/richioon hoster (all 4 domains are the same hoster), which enforces google recaptcha v2, so cant be done. Older videos on the site play fine as they use mixdrop and videobin

**Comment by flapbird1** [comment]
Many thanks for your prompt response **@Gujal00**

If all "providers" are taking this path we're in trouble

Any chance to implement?

www.reddit.com/r/node/comments/kppze7/a_tool_to_break_google_recaptcha_v2_with_puppeteer/

**Comment by Gujal00** [comment]
No Not possible to evade click captcha that this hoster is using.

**Comment by flapbird1** [comment]
Thanks **@Gujal00** keep up the great work with
https://github.com/jsergio123/script.module.resolveurl
