### ISSUE TITLE
UWC- Freevideo.cz not working

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#396]
No listings. Please check

**Comment by m-incognito** [comment]
It looks like the czech proxy www.katedrala.cz that is used internally by the addon is down. I don't know any alternative 

The addon is working well from czech republic

**Comment by imurreflection** [comment]
You mean to say from chezch vpn, it should work?

**Comment by imurreflection** [comment]
You are right bro..I tried Nord with Czech proxy and it's working fine..thank you so much for this wonderful site and prompt support. Closing the issue now
