### ISSUE TITLE
Cumination - Adding back missing UWC webcams etc

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#397]
MyFreeCams and RedTube Live webcams are missing from Cumination release.
I have been testing adding them back using the version of UWC  already converted for PY2/PY3/Kodi 18/Kodi 19.
Starting from this version only requires a few updates to accommodate  the Cumination API vs UWC API changes.
I have tested on Kodi 18/PY2 and now intend to test in Kodi 19/PY3.
Also added back RedTube  non-live content as a separate entity.
Also added Tags search back into Chaturbate.

**Comment by Gujal00** [comment]
Redtube live is same as streamate, so no point adding it to cumination.
Streamate in cumination uses api calls and not scraping the website like uwc did, so no need to include redtube live as well whicih uses the same

**Comment by jdoedev123** [comment]
RedTube Live has a much better interface with a far more advanced Search and Channel features.

**Comment by onknight** [comment]
Still would like my Freecams back ASAP  it one of the better cam Sites  Stream mate sucks ..

**Comment by TarkusLV** [comment]
Sounds great.  MFC is the only reason I'm still keeping UWC around, so that would be awesome to see it in Cumination.

**Comment by onknight** [comment]
it why I am running two version  of Kodi 18.9 and 19

**Comment by jdoedev123** [comment]
Here is a test version of MFC. Should only need to drop into the "sites" directory.  Enjoy "Testing"
[myfreecams.py.zip](https://github.com/dobbelina/repository.dobbelina/files/5778845/myfreecams.py.zip)

**Comment by Gujal00** [comment]
myfreecams will be in next cumination release.

**Comment by onknight** [comment]
Glad it will be back nice work fellas thank you
