### ISSUE TITLE
Pornhub?

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#40]
Looks like Pornhub is not working. Pease take a look

**Comment by dobbelina** [comment]
Works fine for me?

**Comment by imurreflection** [comment]
I tried both normal internet and VPN but the site doesn't open at all. Looking at error log it says, error getting directory. Can anyone else confirms if it is working?

**Comment by jdoedev123** [comment]
Also works for me. Do you know your version of "script.module.resolveurl"  ?
Mine is version  5.0.31

**Comment by imurreflection** [comment]
Jsergio 5.0.31. This site works fine on videodevil add-on. It was working fine here too but suddenly stopped

**Comment by jdoedev123** [comment]
Interesting, videodevil , version 1.7.228, is a bit unstable for pornhub for me. It sometimes works, sometimes throws an error.  Both UWC and VideoDevil use the xbmc.python plugin. Mine is 2.25.0
VideoDevil does not use resolveurl
My default Python is version 2.7.12
