### ISSUE TITLE
Forced download

### ISSUE THREAD

**Issue by stevieland58** [dobbelina/repository.dobbelina#400]
Mate, love the work with Whitecream but this new forced addon is like what TV Addons got dicked for! Very bad!
I have kids so having this new addons that I don’t want forced added to my kodi that can’t be disabled is really bad. 
So please enable the option to disable it, and please don’t say "add a pin" the point of hiding it isn’t so they don’t get access, its so they cannot see it exists. — Also wife is pissed!

**Comment by imurreflection** [comment]
We have the option of disabling or even uninstalling Cumination completely on Kodi 18.9 on Android. What is your environment

**Comment by stevieland58** [comment]
Android v18.9

Since v1.1.2 it says that "Cumnation cannot be disabled because it is a part or Whitecream" or whatever.

I disabled it on my other tv when it was running v1.1.1 but on my other tv it updated to v1.1.2 before i had a chance to disable it and now it won't let me disable it. 
My other tv has it still disabled and on v1.1.1 



> We have the option of disabling or even uninstalling Cumination completely on Kodi 18.9 on Android. What is your environment

**Comment by 12asdfg12** [comment]
You should uninstall UWC and then you can disable Cumination.
OR (and this is the recommended solution for you)
move the adult stuff to a different password-protected profile.
https://kodi.wiki/view/Profiles

**Comment by stevieland58** [comment]
🤦🏻‍♂️

> You should uninstall UWC and then you can disable Cumination.
> 
> OR (and this is the recommended solution for you)
> 
> move the adult stuff to a different password-protected profile.
> 
> https://kodi.wiki/view/Profiles
> 
>

**Comment by dobbelina** [comment]
I will remove the dependency of UWC in an update today, then you can disable it.

**Comment by stevieland58** [comment]
Thank you! 


> @stevieland58
> 
> I will remove the dependency of UWC in an update today, then you can disable it.
