### ISSUE TITLE
Films haven’t updated 

### ISSUE THREAD

**Issue by deanogers** [dobbelina/repository.dobbelina#401]
The movie in pornhive paradisehill netflixporn mangoporn and speedporn haven’t updated in ages can u fix please

**Comment by flapbird1** [comment]
Sadly, original websites haven't been updated for long time, except Paradise Hill: 

www.pornhive.tv/en/page/
https://netflixporno.net/
https://en.paradisehill.cc/all/?page=1
https://mangoporn.net/genres/featured-movies/
https://speedporn.net/

**Comment by dobbelina** [comment]
This is up to the content providers, not an issue for the addon.
