### ISSUE TITLE
Naked Locks up Kodi on PC 

### ISSUE THREAD

**Issue by onknight** [dobbelina/repository.dobbelina#408]
So when I try to use the new add-on with naked
It starts to search for the link and we get a spinning icon and it never finishes it just locks up
If I try to go back Kodi locks up and I have to restart

**Comment by TarkusLV** [comment]
I just tried using Cumination on Kodi 18.9 in Windows, and Naked works fine here.

**Comment by Gujal00** [comment]
@onknight you had earlier reported another issue with installing websocket module as well. Can you please try on clean install and if it works close both issues. It works fine for others

**Comment by onknight** [comment]
> @onknight you had earlier reported another issue with installing websocket module as well. Can you please try on clean install and if it works close both issues. It works fine for others and if it is still crashing for you, provide a full debug log

Have done clean install still had the problems will stay White cream and Kodi 18.9 for now

**Comment by Gujal00** [comment]
So no debug log?

**Comment by onknight** [comment]
it not locking up i just deleted the addon and reinstalled just no video

**Comment by Gujal00** [comment]
And still no debug log!
