### ISSUE TITLE
Cumination- Aag Maal not working

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#409]
No listings. Please check.

**Comment by Gujal00** [comment]
Fixed. Will be in next release

**Comment by imurreflection** [comment]
Thank you so much mate..once update is released, I will close the issue

**Comment by imurreflection** [comment]
@Gujal00 can you please advise when can we expect the new release?

**Comment by Gujal00** [comment]
@dobbelina is the person who determines when to do a new release

**Comment by imurreflection** [comment]
Thank you @dobbelina for releasing the update. All is working fine and closing the issue now
