### ISSUE TITLE
Interesting new websites

### ISSUE THREAD

**Issue by Oxycon25** [dobbelina/repository.dobbelina#41]
I've maybe a few new interesting websites to add in the addon.

https://speedporn.net
https://mangoporn.net/
https://watchpornfree.ws/
https://pandamovie.xyz/
https://xopenload.me/
https://youwatchporn.com/
https://xtapes.me/adult/
https://adultvideoz.net/

I don't know if they are safe enough to put in the addon? But I thought it was interesting to send them to you.

**Comment by jdoedev123** [comment]
Took a quick crack at list. SpeedPorn is disappointing ... none of the play video links work either in the browser or in an experimental addition to UWC.  The experimental addition otherwise looks and works great but is useless. Should have tested in browser more before starting effort. All video links are really advertising links.

**Comment by jdoedev123** [comment]
These websites are all hosted by Cloudflare and most were created using namecheap.com. More importantly none of them have playable video links on my browser which makes it highly unlikely they would work in UWC and not worth the effort. Side note: someone went to a lot of effort to create these click bait websites.

**Comment by foxnight23** [comment]
There is one interesting website I've found, which could be a valuable addition to the addon: hdpornz.biz as an alternative to k18.co.

**Comment by jdoedev123** [comment]
HDPornz is more doable. Here is an experimental first version.
Also added an experimental line in default.py around line 95:
    utils.addDir('[COLOR hotpink]HDPorn[/COLOR]','http://www.hdpornz.biz',950,os.path.join(imgDir, ''),'')

[hdpornz.py.zip](https://github.com/dobbelina/repository.dobbelina/files/3305029/hdpornz.py.zip)

**Comment by 12asdfg12** [comment]
I tried these sites and they worked for me, so I implemented speedporn (maybe not the best choice).
The video links hosted on mangoporn.pw always works, other links(which use resolveurl)  are not that good.
Probably the Playvid function from speedporn.py can be used with any of this sites.

[speed.zip](https://github.com/dobbelina/repository.dobbelina/files/3326947/speed.zip)

**Comment by dobbelina** [comment]
Thanks jdoedev123 & 12asdfg12,

will implement soon.
One nice site i noticed from videodevil is https://www.xvideos.com

**Comment by imurreflection** [comment]
Well then you can search Vintage HD in xhamster and you will be really pleased by the results

**Comment by 12asdfg12** [comment]
Added xvideos:
[xvideos.zip](https://github.com/dobbelina/repository.dobbelina/files/3341985/xvideos.zip)

**Comment by dobbelina** [comment]
Just amazing!

Thanks 12asdfg12.

**Comment by 12asdfg12** [comment]
Added mangoporn (much better than speedporn) 

[mango.zip](https://github.com/dobbelina/repository.dobbelina/files/3363417/mango.zip)

**Comment by dobbelina** [comment]
Thanks 12asdfg12!

Will update addon soon.

**Comment by CrYpT0n1T3** [comment]
showup.tv ;-) cams, Polish girls, requires login
