### ISSUE TITLE
Cache Setting

### ISSUE THREAD

**Issue by TarkusLV** [dobbelina/repository.dobbelina#413]
Is the reason for the new Cache setting for our benefit, or to not be a burden on sites?

If it's for our benefit, I'd like to disable it (or have the counter be able to go to 0).  I use Cumination mostly for the cams, and I like having the cam pages up to date.  They are very fluent, and even set to 1 hour, they can be very much behind, with some models leaving and others entering.

I totally get it for regular sites that don't change content near as often, and when they do, all new content is first anyway.  Cam pages are a different animal, though.

**Comment by Gujal00** [comment]
Caching removed completely from camsites. Will be in the next release

**Comment by TarkusLV** [comment]
@Gujal00 
Thank you very much!

**Comment by Gujal00** [comment]
@TarkusLV please check with 1.1.4 and if working close this issue

**Comment by TarkusLV** [comment]
@Gujal00 
Working as expected.  Thanks again.
