### ISSUE TITLE
[Request] Adding Settings--> Accounts --> Porntrex for Cumination - like in UWC

### ISSUE THREAD

**Issue by Kodionpi** [dobbelina/repository.dobbelina#414]
Under UWC it was possible to save Porntrex account data permanently under the settings. Is it possible that we can have this again under Cumination?

Why? There is already the possibility to log in to Porntrex.
--> Right. -but unfortunately Porntrex often requires logging out and then logging in again - always when PV and Favorites can no longer be played without a new login. Username and password must be entered again and again. If the data were permanently stored under settings, everything would not always have to be entered. The re-login (if it is then still necessary)  would be much easier. Like with UWC.

Thanks in advance for your work!

**Comment by 12asdfg12** [comment]
I guess we could add the possibility to keep the login data at log-off.

**Comment by 12asdfg12** [comment]
fixed in the next version

**Comment by Kodionpi** [comment]
Thank you guys, you are the best!!
