### ISSUE TITLE
Streamate and RedTube Live down on UWC and Cumination

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#422]
Down on UWC 1.2.43
Cumination  1.1.2
Also not working
UWC 1.2.44
Cumination 1.1.4

**Comment by jdoedev123** [comment]
In case some one else wants to look into this the problem seems to be with the direct calls to the "api.naiadsystems.com" API. Testing with "curl" the connections are rejected on port 80 and port 443. The websites are using "member.naiadsystems.com"  with a member domain and a method to send tracking ids and platform info. RedTube Live sends info in headers while Streamate may use a challenge and reply with server keys of similar info.

**Comment by Gujal00** [comment]
@jdoedev123 fixed a while ago on cumination. you can take the code and fix uwc
