### ISSUE TITLE
Cumination 1.1.5 breaks Kodi 18 compatibility 

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#423]
Cumination 1.1.5 does not work on Kodi 18.6

utils.py throws an error:
                           File "...utils.py", line 36, in <module>
                                                import StorageServer
                                            ImportError: No module named StorageServer

**Comment by Gujal00** [comment]
Install the cumination addon from repo and it will install the relevant dependencies
`StorageServer` is part of `script.common.plugin.cache` and is available from Kodi Official repo for all versions of Kodi

**Comment by jdoedev123** [comment]
Thanks that fixed it. I don't normally install from repos plugins that I might modify.
