### ISSUE TITLE
[Request] Adding peekvids, xxxfiles, xnxx, pornhd

### ISSUE THREAD

**Issue by Kodionpi** [dobbelina/repository.dobbelina#427]
Would it be possible to add the following sites to cumination?

https://www.peekvids.com/
https://www.xxxfiles.com/
https://www.xnxx.com/
https://www.pornhd.com/

Thanks in advance for your hard work guys. You are the best!!!

**Comment by p8ckachu** [comment]
Also these.

www.xozilla.com/
https://sxyprn.com/

These are all in uwc, surprised not to see them.

**Comment by dobbelina** [comment]
peekvids added in v1.1.5
