### ISSUE TITLE
Utils improvements

### ISSUE THREAD

**Issue by WhitecreamDev** [dobbelina/repository.dobbelina#43]
Hey,

this should improve the speed of the addon (only import resolveurl when playing a video).
It should also fix filecrypt, and improve the VideoPlayer class.
[utils and randua.zip](https://github.com/dobbelina/repository.dobbelina/files/3263205/utils.and.randua.zip)

**Comment by dobbelina** [comment]
Thanks for the improvement WhitecreamDev,
Will incorporate in the next release.

**Comment by dobbelina** [comment]
Improvement incorporated, closing thread.
