### ISSUE TITLE
Can't install Cumination on Kodi 19.0 (Windows)

### ISSUE THREAD

**Issue by TarkusLV** [dobbelina/repository.dobbelina#432]
# Please fill in below:

- [x] Cumination Bug
- [ ] Ultimate Whitecream Bug

### Bug reports:

With the official release of Kodi Matrix 19.0, I decided to do a clean install, but I can't get Cumination to install from the 1.0.3 repository.  It keeps giving a, "The dependency on script.module.six version 1.14.0+matrix.2 could not be satisfied."  Looking at the dependencies, it says that script.module.cryptopy is not available.  That's the only issue there.

### OS environment
Windows 10 64-bit

**Comment by Gujal00** [comment]
script.module.cryptopy is listed as an optional module in resolveurl dependencies. that is not an issue here.
script.module.six has no external dependencies, so need a FULL debug log to see what is happening

**Comment by dobbelina** [comment]
@TarkusLV 
You can upload the debug log here:https://paste.kodi.tv/

**Comment by TarkusLV** [comment]
This seems to be the relevant portion of the log:

`2021-02-19 15:30:45.889 T:16504   DEBUG <general>: CAddonInstaller: installing 'plugin.video.cumination' version '1.1.6' from repository 'repository.dobbelina'
2021-02-19 15:30:46.011 T:11576   DEBUG <general>: CAddonMgr: enabled script.module.six
2021-02-19 15:30:46.023 T:11576   DEBUG <general>: CAddonInstallJob[script.module.websocket]: requires script.module.six version 1.14.0+matrix.2 which is not available
2021-02-19 15:30:46.033 T:11576   ERROR <general>: CAddonInstallJob[plugin.video.cumination]: The dependency on script.module.six version 1.14.0+matrix.2 could not be satisfied.`

Here is the entire log:
https://paste.kodi.tv/zanaduwuto.kodi

**Comment by Gujal00** [comment]
@TarkusLV this seems to be an issue with Kodi Repo. Get `script.module.six version 1.14.0+matrix.2` from kodi mirror and install manually for now until they sort it out
It is there in their [mirror here](http://mirrors.kodi.tv/addons/matrix/script.module.six/)

**Comment by TarkusLV** [comment]
@Gujal00 
That did the trick.  Thank you very much!
