### ISSUE TITLE
UWC refuses to install on my system since the new update and Cumination download problems

### ISSUE THREAD

**Issue by tetzy** [dobbelina/repository.dobbelina#434]
The new "better" Kodi bricked both UWC and Cumination. I managed to get Cumination installed by following advice in the other thread (download/install "script.module.six-1.14.0+matrix.2") and by reading the error logs to install both "script.module.resolveurl" and "script.module.resolveurl.xxx" but Ultimate Whitecream is still broken.

![Screenshot from 2021-02-20 01-28-22](https://user-images.githubusercontent.com/59111079/108589559-172c7480-731c-11eb-80b0-ba519cde91bf.png)

Edit: Cumination won't download Porntrex files, it plays them instead. Also in Porntrex, we're not given the choice of file size to play/download; it chooses for us (full disclosure, I haven't used Porntrex on Cumination before - UWC gave us the choice of file sizes...perhaps Cumination didn't? Either way, I really miss not being given the choice). 

Another Cumination issue: Downloaded files from other sources with filenames that are displayed in brackets within Cumination ex: "[WebsiteName] Name of file.mp4" are saved without any filename at all, showing up as simply ".mp4".

I'm running Linux Mint 20.1 Ulyssa on a PC. 

Any ideas?

**Comment by 12asdfg12** [comment]
> The new "better" Kodi bricked both UWC and Cumination. I managed to get Cumination installed by following advice in the other thread (download/install "script.module.six-1.14.0+matrix.2") and by reading the error logs to install both "script.module.resolveurl" and "script.module.resolveurl.xxx" but Ultimate Whitecream is still broken.
> 
UWC is not compatible with matrix.

> 
> Edit: Cumination won't download Porntrex files, it plays them instead. Also in Porntrex, we're not given the choice of file size to play/download; it chooses for us (full disclosure, I haven't used Porntrex on Cumination before - UWC gave us the choice of file sizes...perhaps Cumination didn't? Either way, I really miss not being given the choice).
> 
Download for porntrex will be fixed in the next version.
For quality selection check the addon settings (Hosts and resolvers: Preferred maximum video quality; Don't ask for videohost), and ResolveUrl settings (Automatically pick best quality).

> Another Cumination issue: Downloaded files from other sources with filenames that are displayed in brackets within Cumination ex: "[WebsiteName] Name of file.mp4" are saved without any filename at all, showing up as simply ".mp4".
> 
Can you give an example?
