### ISSUE TITLE
UWC- Masalaseen not working

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#436]
Getting ' This site seems to be down' error but the site is working fine on mobile and pc browser. Just to let you know that they changed the domain from Masalaseen.com to Masalaseen.net. it appears that this has broken the site on UWC. Kindly check

**Comment by imurreflection** [comment]
@camilt can you please look into this

**Comment by imurreflection** [comment]
It appears that UWC is not developed anymore. If this is the case,please advise and I will close this and other issues related to it.

**Comment by camilt** [comment]
@imurreflection 
In desinxnn.py at line 59 change `listhtml = utils.getHtml(url)`
into `listhtml = utils.getHtml3(url)`
and in line 68 change `xbmc.Player().play(videourl, listitem)` 
into `xbmc.Player().play(videourl + '|verifypeer=false', listitem)`

**Comment by imurreflection** [comment]
Thank you my friend
