### ISSUE TITLE
Cumination install fails on Shield Android TV

### ISSUE THREAD

**Issue by emuweb** [dobbelina/repository.dobbelina#437]
# Please fill in below:

- [X] Cumination Bug

### Bug reports:

Since my Nvidia Shield Pro (Android TV 9) updated Kodi automatically to Kodi 19, Cumination and UWC disappeared as expected, but a new install of Cumination always fails with 3 errors. I made a screenshot from the logs. Yeah, the OS language is german. Hope this is not a big issue and I can still get help. Thank you in advance!

### OS env

Nvidia Shield Pro
Android TV 9
![20210221_220333](https://user-images.githubusercontent.com/79423035/108639209-9d1efb80-7493-11eb-93a0-aa4f77e126cf.jpg)

**Comment by ErosVece** [comment]
Go to the addon dependencies (https://kodi.wiki/view/Settings/System/Add-ons#Manage_dependencies) and see of those bottom 2 are disabled or out of date.
If so, enable/update them.
If not, reinstall them.

**Comment by emuweb** [comment]
Looks like I was a bit impatient. Today lots of other plugins did update automatically. Afterwards a new install of Cumination v.1.1.6 was possible and it seems to work as before. Cheers @all :-)
