### ISSUE TITLE
Cumination won't download

### ISSUE THREAD

**Issue by KSTV28** [dobbelina/repository.dobbelina#439]
# Please fill in below:
So when I am trying to download a video using Cumination on kodi using a raspberry pi it gives me a error messages saying Unknown filesize, unable to download is there anyway to fix that issue?

- [x] Cumination Bug
- [ ] Ultimate Whitecream Bug

### Bug reports:

Please replace this line with a brief summary of your issue 

### OS environment
What OS, Device, version etc

**Comment by dobbelina** [comment]
There will be a download fix for porntrex, javbangers, and daftsex in the next release.
Are there from any of those sites that you tried to d/l?

**Comment by KSTV28** [comment]
theres a couple, Hanime.tv and something else I can't remember

**Comment by ErosVece** [comment]
Hanime.tv has m3u8 video urls, you can't download those with the downloader in Cumination.

**Comment by KSTV28** [comment]
then how can I download without going to the main site??

**Comment by dobbelina** [comment]
@KSTV28 
To download m3u8 you need ffmpeg installed, don't know how to do that in Raspberry?
In Windows it works fine with https://github.com/dobbelina/repository.dobbelina/issues/392

**Comment by KSTV28** [comment]
can you add a other jav site?
