### ISSUE TITLE
Datoporn and Paradisehill Issue

### ISSUE THREAD

**Issue by Sameer888** [dobbelina/repository.dobbelina#44]
Hi Dobbelina
You all have been doing a great work by making this addon work fine i have seen issues on 2sites
1. Datoporn - No Next tab 
2. Paradisehill - Only one movie per page 
 thanks

**Comment by 12asdfg12** [comment]
fixed
[datoporn.zip](https://github.com/dobbelina/repository.dobbelina/files/3269790/datoporn.zip)
[paradisehill.zip](https://github.com/dobbelina/repository.dobbelina/files/3269791/paradisehill.zip)

**Comment by Sameer888** [comment]
Thank yu for the fix 12asdfg12 👍

**Comment by 12asdfg12** [comment]
there is no next page on website(datoporn.co), so no next on main page.
next page is fixed for categories and search results.

**Comment by Sameer888** [comment]
Yes i did not know about datoporn site thank yu once again for fix 👍👍

**Comment by MacDub757** [comment]
how do you rezip the file so it will open in kodi once you drag the daftsex.py into the folder

**Comment by Sameer888** [comment]
Note :This solution is for mobile 
Download the file then go to download folder unzip and move .py file to Android/data/org.xbmc.kodi/files/kodi/addon/plugin.video.uwc/resources/lib/sites (replace it)

If yu want for windows then after doing the upper procedure zip plugin.video.uwc and go to install from zip and reinstall it

**Comment by dobbelina** [comment]
Thanks for fixes 12asdfg12, closing issue.
