### ISSUE TITLE
Files hosted by Keep2Share freeze while downloading

### ISSUE THREAD

**Issue by tetzy** [dobbelina/repository.dobbelina#442]
For some reason, files hosted by Keep2Share (k2s) stop and ultimately time-out while being downloaded in Cumination (I can't speak to their behaviour in Ultimate Whitecream, it doesn't work on the matrix build for some reason). It wouldn't be a problem, but k2s seems to be becoming very popular with uploaders.

![K2s Problem](https://user-images.githubusercontent.com/59111079/108964601-e5c3e980-7638-11eb-8774-f07f0d1ce88c.jpg)

Any idea what's going on?

I'm running Linux Mint 20.1 Ulyssa on a PC.

**Comment by Gujal00** [comment]
k2s is a premium hoster and only allow a limited download for free users

**Comment by flapbird1** [comment]
Thank @Gujal00 
Then:

Registered today https://k2s.cc
Free account gives 10 GB daily, enough for my needs
When back to Cumination, but download still freezes around 40/50 MB downloaded, hopping sharing same IP will do the job

Checked k2s.cc/knowledge_base/item/171110 and download managers are supported, 
but how put my logging details in Cumination?

Any pointers?
Many thanks
