### ISSUE TITLE
Rssponse to request for an example

### ISSUE THREAD

**Issue by tetzy** [dobbelina/repository.dobbelina#443]
> Another Cumination issue: Downloaded files from other sources with filenames that are displayed in brackets within Cumination ex: "[WebsiteName] Name of file.mp4" are saved without any filename at all, showing up as simply ".mp4".
> 
>>Can you give an example?

Certainly - the following file was found on "XXXStreams (org)" and when downloaded was saved as just ".mp4" leaving me to fill in the name manually. The complete file name was "[ScoreHD.com|PornMegaLoad.com] Mia Sweetheart - And The Man From Deep Fingers (2021)" It was hosted by StreamTape, if that matters.

![Screenshot from 2021-02-24 00-43-52](https://user-images.githubusercontent.com/59111079/108966051-f2e1d800-763a-11eb-8c4d-69fd3a80e8ae.png)

_Originally posted by @12asdfg12 in https://github.com/dobbelina/repository.dobbelina/issues/434#issuecomment-782864561_

**Comment by 12asdfg12** [comment]
thanks. Resolved in next release
