### ISSUE TITLE
Live Cams on Cumination and Whitecream

### ISSUE THREAD

**Issue by badguybadgirl** [dobbelina/repository.dobbelina#446]
# Please fill in below:

- [x] Cumination Bug
- [x] Ultimate Whitecream Bug

### Bug reports:

Many Live cams do not work like Chaturbate, Camsoda, bongacams.com.

Android nvidia shield and 4k firestick

**Comment by TarkusLV** [comment]
I use Windows 10 and a Firestick 4k, and all the cam sites are currently working for me in Cumination.

**Comment by 450plus** [comment]
I have a shield and they are working perfectly on mine.

**Comment by Gujal00** [comment]
@badguybadgirl Under Cumination Settings, in Cam Sites Tab, Check if `Select Playback mode` is set to `HLS`
`RTMP` mode also works but required installation of patched inputstream.rtmp, instructions are there under the settings. and is not recommended on Android devices such as Shield and Firestick,
