### ISSUE TITLE
Move favorites from uwc to cumination

### ISSUE THREAD

**Issue by p8ckachu** [dobbelina/repository.dobbelina#448]

**Comment by p8ckachu** [comment]
How to can someone edit the favorite.db or favorites.bak files?

**Comment by dobbelina** [comment]
@p8ckachu 
Export favorites in UWC to file, then import them into Cumination.

**Comment by TarkusLV** [comment]
@p8ckachu
You can edit db files in the free DB Browser (SQLite).

**Comment by p8ckachu** [comment]
> @p8ckachu
> Export favorites in UWC to file in the settings page, then import it into Cumination.

This didn't work that's why I posted this request.

**Comment by p8ckachu** [comment]
> @p8ckachu
> You can edit db files in the free DB Browser (SQLite).

Thanks, tried this. Unfortunately I don't know all the mode types in Cumination, so can only covert some of the uwc favorites. But this works the best. Hoping for another solution.

**Comment by saidma** [comment]
> @p8ckachu
> Export favorites in UWC to file in the settings page, then import it into Cumination.

I tried and it fails

**Comment by saidma** [comment]
> @p8ckachu
> Export favorites in UWC to file in the settings page, then import it into Cumination.

I tried and it fails
