### ISSUE TITLE
PornGO Search

### ISSUE THREAD

**Issue by EvelK1203** [dobbelina/repository.dobbelina#449]
# Please fill in below:

- [x] Cumination Bug
- [ ] Ultimate Whitecream Bug

### Bug reports:

When searching with PornGO Kodi throws an error. Testing on FireTV (K18) and Windows 10 (K19)
[kodi.log](https://github.com/dobbelina/repository.dobbelina/files/6054938/kodi.log)

**Comment by dobbelina** [comment]
Issue confirmed, thanks for reporting.

**Comment by dobbelina** [comment]
Will be fixed in the next update.
