### ISSUE TITLE
daftsex

### ISSUE THREAD

**Issue by MacDub757** [dobbelina/repository.dobbelina#45]
Daft sex not working again.

I get the ultimate white cream error check the log for more information

**Comment by 12asdfg12** [comment]
fix for daftsex
[daftsex.zip](https://github.com/dobbelina/repository.dobbelina/files/3269755/daftsex.zip)

**Comment by MacDub757** [comment]
how do i install that

**Comment by 12asdfg12** [comment]
unzip and replace daftsex.py from folder addons\plugin.video.uwc\resources\lib\ ... or wait until dobbelina updates the addon in repository

**Comment by MacDub757** [comment]
Im having trouble getting it to install once I rezip it

**Comment by MacDub757** [comment]
do you know how to rezip it in a manner that kodi will recognize the newly zipped file and install it

**Comment by MacDub757** [comment]
I will just wait for the next update

**Comment by Sameer888** [comment]
Daftsex is working well after fix thanks 12asdfg12

**Comment by MacDub757** [comment]
how do I install the fix

**Comment by MacDub757** [comment]
its fixed now for whatever reason

**Comment by dobbelina** [comment]
I updated the latest fix from 12asdfg12, but i get errors?
Have they changed something again perhaps?

**Comment by imurreflection** [comment]
Yes, after manual update, I add-on does not open. Had to revert to previous version.

**Comment by dobbelina** [comment]
Fixed, closing thread.
