### ISSUE TITLE
Daftsex (Empty Folder)

### ISSUE THREAD

**Issue by crst31** [dobbelina/repository.dobbelina#451]
# Please fill in below:

- [x] Cumination Bug
- [ ] Ultimate Whitecream Bug

### Bug reports:

 Only getting “Categories and Search” when I open it. Tried search and categories coming up with no results

### OS environment
Shield, Kodi 18 and 19

**Comment by dobbelina** [comment]
Issue confirmed, thanks for reporting.

**Comment by camilt** [comment]
In daftsex.py replace lines 38 and 39 with this:
`    match = re.compile(r'setTitle\(this\);">([^<]+).+?video-item.+?href="([^"]+).+?url\(\'([^"]+)\'.+?time">([^<]+)', re.DOTALL | re.IGNORECASE).findall(response)`
`    for name, video, img, length in match:
`

**Comment by dobbelina** [comment]
Will be fixed in the next update.
