### ISSUE TITLE
No title under thumbnails

### ISSUE THREAD

**Issue by p8ckachu** [dobbelina/repository.dobbelina#453]
# Please fill in below:

- [x] Cumination Bug
- [ ] Ultimate Whitecream Bug

### Bug reports:

 For any folder view type with multiple thumbnails there are no titles under the thumbnails. Noticed this for all "sites". Multiple skins including Estuary. Folder view types, "Icons", "Info wall", "wall". Etc. 

### OS environment
What OS:Android TV, Device:All, Version:latest version etc

**Comment by fjthrowaway** [comment]
Same here. I would like to have the old wall view back if possible.

**Comment by Gujal00** [comment]
That is a design choice by Kodi 19. Can't do anything about it in the addon

**Comment by fjthrowaway** [comment]
> That is a design choice by Kodi 19. Can't do anything about it in the addon

Are you sure? VideoDevil (another porn addon) still looks exactly like with Kodi 18

**Comment by p8ckachu** [comment]
> That is a design choice by Kodi 19. Can't do anything about it in the addon

This is actually happening in Kodi 18.

**Comment by Gujal00** [comment]
Actually is Estuary skin feature, so common for both Kodi 18 and 19

**Comment by p8ckachu** [comment]
I think I'm not explaining this issue properly unfortunately. 

When you launch any site in Cumination (Daftsex for example), and change the "Viewtype" to "Infowall" or "Wall", you will a difference between how "Search" and "Categories" are shown vs the videos. The thumbnails for "Search" and "Categories" are aligned to top with a label underneath, the thumbnails for the videos are aligned in the middle with no labels underneath. Now check this in uwc and the videos will also be aligned to the top, not middle, with labels underneath. I'm still on Kodi 18 on one device, so this is not a kodi 19 issue.

**Comment by Gujal00** [comment]
This is a Estuary Skin choice as I said and is common to 18 and 19
UWC classes all clips as "videos" so will always shows a cropped 16:9 thumbnail with label underneath
Cumination classes all clips as "movies" so will show poster style icons cropped to 2:3 with no label underneath

Cumination "Infowall" or "Wall" will look good when the site is hosting movie style posters, have a look at FreeoMovie and change the view to "Wall" or "Infowall" and see the difference. Now compare with UWC and see how it is rendered there

**Comment by ErosVece** [comment]
In a coming update, you can switch the content type in Cumination settings to 'video', so the wall view will be like in UWC.
