### ISSUE TITLE
(Updated)ParadiseHill 

### ISSUE THREAD

**Issue by flapbird1** [dobbelina/repository.dobbelina#454]
# Please fill in below:

- [x] Cumination Bug
- [ ] Ultimate Whitecream Bug

### Bug reports:

ParadiseHill, poster not shown when film selected, thumbnails instead

### OS environment
Both Android 7 and macOS BigSur
Latest Cumination version

Updated
Screenshot s below
UWC (top) vs Cumination (bottom)

![Screenshot_2021-03-03-10-04-40-867_org xbmc kodi](https://user-images.githubusercontent.com/74716864/109782281-011a9000-7c09-11eb-9d7c-19a5b2675b48.png)
![Screenshot_2021-03-03-10-06-16-940_org xbmc kodi](https://user-images.githubusercontent.com/74716864/109782314-0b3c8e80-7c09-11eb-9626-815afbdecde3.png)

**Comment by dobbelina** [comment]
Has been fixed in v.1.1.8

**Comment by flapbird1** [comment]
Keep up the great work, all.
Closing now
