### ISSUE TITLE
timeout trying to load video page all devices

### ISSUE THREAD

**Issue by alazare619** [dobbelina/repository.dobbelina#455]
# Please fill in below:

- [x] Cumination Bug
- [x] Ultimate Whitecream Bug

### Bug reports:
All devices report fail to load video page started about 3 days ago this affects desktop (windows) and android on leia and on matrix

### OS environment
Firestick (Non 4k), Fire stick 4k, FireTV, Kodi for Windows 10 20h2, Tested with 18.9 and 19.0 on all.

**Comment by Gujal00** [comment]
No DEBUG LOG, no issue

**Comment by dobbelina** [comment]
Closing issue because of missing debug log.
