### ISSUE TITLE
Netflixporno.net,no films available

### ISSUE THREAD

**Issue by flapbird1** [dobbelina/repository.dobbelina#456]
# Please fill in below:

- [x] Cumination Bug
- [x] Ultimate Whitecream Bug

### Bug reports:
Seems Netflixporno.net changed something,no films available

### OS environment
Android 7 & Bigsur
Latest versions of UWC & Cumination

**Comment by 12asdfg12** [comment]
fixed in v1.1.9

**Comment by flapbird1** [comment]
You're da BEST👏🏻
