### ISSUE TITLE
Usability suggestions

### ISSUE THREAD

**Issue by withoutprefix** [dobbelina/repository.dobbelina#46]
hi,

two suggestion that might help if they could be implemented
- the ability to search / navigation and view the results while video is being played (and to be still able to see the video)
- having different theme / colors as the purple is not always clear

Thank you dobbelina and the rest for taking the time and effort in doing around this plugin.

**Comment by jdoedev123** [comment]
Not sure how difficult the task of navigation etc while playing would be within kodi. Can not recall any kodi video plugin with this capability.
It is possible to access the playing video and download on the same or another computer in the background allowing simultaneous or later playback. This is how I typically run my system.

**Comment by dobbelina** [comment]
If you want to search while a video is playing, press Tab key on your keyboard.
To go back to video, press Tab key again.

**Comment by jdoedev123** [comment]
Good catch dobbelina. I had not noticed that feature. I had accidently entered that mode over the years but never knew how to reproduce.
