### ISSUE TITLE
Cumination favorites display problem

### ISSUE THREAD

**Issue by tetzy** [dobbelina/repository.dobbelina#461]
After installing Cumination-1.1.8 last night, every file I add to my favorites menu is added without the quality tags (sd, hd, 4k etc) and also without the tags noting the run times of the videos. The following screenshot shows titles added to my favorites menu from 3 different providers:

![Screenshot from 2021-03-11 00-57-11](https://user-images.githubusercontent.com/59111079/110754440-12fdc380-8205-11eb-93de-d5b3d1669011.png)

Aside from missing the detailed information, there's no way to tell the providers apart - kind of a big loss for me - These tags are the only way to tell which site the file is being downloaded from. I've had my IP blocked in the past for over use, so I download from as many different providers as I can. 

I've looked through the settings menu and can't find an obvious fix - I'm hoping you can help.

Thanks again for all you do for us.

I run the latest version of Linux Mint on a PC.

**Comment by ErosVece** [comment]
With the change of _'Added the possibility to display the duration and quality of the video using the ListItem properties (selectable in settings, default is duration and quality added to filename).'_, showing the quality/runtime when adding a video to favorites got broken.

This will be fixed in a future version.

**Comment by foofoo11** [comment]
i've been seeing similar issues on my firestick.. the saved favorite video section of chaturbate doe not renew or update images.. it stays the same old images for days now and won't update even when you click on "Refresh Chaturbate images".. hope DOBBELINA  figures it out soon..
