### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by lance77tour** [dobbelina/repository.dobbelina#462]
How can I get the Thumbnails using the WALL View to not be so big? They’re much larger than UW’s

**Comment by Gujal00** [comment]
same as #453

**Comment by ErosVece** [comment]
In a coming update, you can switch the content type in Cumination settings to 'video', so the wall view will be like in UWC.

**Comment by lance77tour** [comment]
thank you

Thanks

Keith Pillsbury
Ret. (Med) US Army

Sent from iPhone 12 Pro Max
________________________________

**Comment by dobbelina** [comment]
Fixed, closing issue.

**Comment by lance77tour** [comment]
Hi,

How do I go about removing sites that I do not use or that are not working within the code?


***@***.***
