### ISSUE TITLE
xxxstreams.eu (fails) seems to be now xxxstreams.watch

### ISSUE THREAD

**Issue by flapbird1** [dobbelina/repository.dobbelina#466]
# Please fill in below:

- [x] Cumination Bug
- [x] Ultimate Whitecream Bug

### Bug reports:

xxxstreams.eu (fails) seems to be now xxxstreams.watch

### OS environment
Android 7
Big Sur
Both, Cumination 1.1.9 and UWC 1.1.6
Keep up the great work

**Comment by ErosVece** [comment]
https://github.com/dobbelina/repository.dobbelina/commit/46ee9cdef18eca99c01e893251c1e69868ce9e70
It's already fixed, will be in the next version release.

**Comment by flapbird1** [comment]
🚀 work 👏🏻
