### ISSUE TITLE
Freepornstream 

### ISSUE THREAD

**Issue by xerel89** [dobbelina/repository.dobbelina#469]
# Please fill in below: hey the stream break up in few Seconds, please fix it

- [x] Cumination Bug
- [ ] Ultimate Whitecream Bug

### Bug reports:

Please replace this line with a brief summary of your issue 

### OS environment
What OS, Device, version etc

**Comment by xerel89** [comment]
Any news? Will fix it?

**Comment by 12asdfg12** [comment]
If the stream starts playing, this is probably not an issue with the addon (but maybe with your internet connection, or hardware, or the video host is overloaded).
Anyway without a log file, nobody can figure out where is the problem.

**Comment by dobbelina** [comment]
I can confirm there's an issue with free porn streams.
Missing thumbnails and unplayable streams.
Win 10 Matrix/Leia

**Comment by xerel89** [comment]
I have no idea about the log file

**Comment by 12asdfg12** [comment]
Fixed in the next version, but the videos are hosted on ks2.cc, which is a premium host that does not allow full download of videos without a subscription.

**Comment by xerel89** [comment]
I don't want to download, just see, I hope then I have full access to the file to see the fix
