### ISSUE TITLE
Proposed Chaturbate Filtering by Tags

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#47]
Chaturbate has so many active cams additional filtering is suggested.
Currently testing some of the most popular Female Tags (Anal, Asian, BigAss, BigBoobs, Ebony, Latina, Lesbian, MILF, Squirt). Will upload after further testing.

**Comment by WhitecreamDev** [comment]
Just scrape the first page: https://chaturbate.com/tags/female/
(same for couples etc)

**Comment by jdoedev123** [comment]
WhitecreamDev that is an excellent suggestion and I considered it first but got lazy and just added some of the most popular tags to the Chaturbate page after "Status" and before "Region" links. 
Never actually set up a new page for scraping in uwc, always relied on your and predecessors excellent work to start from but it does not appear too difficult to scrape keying on "tag_row" or "<span class="tag">". The code should be very similar to that for  "Categories" on other sites.

**Comment by WhitecreamDev** [comment]
The scraping stuff functions is really easy, just having a look at Categories is enough to get the gist.

**Comment by jdoedev123** [comment]
Ok testing enhanced Chaturbate with full Tag support. Assume tags are self assigned as a few Blondes among "ebony" and teenagers among MILF etc but that is the Internet.

**Comment by jdoedev123** [comment]
Chaturbate with full Tag support.
[chaturbate.py.zip](https://github.com/dobbelina/repository.dobbelina/files/3288450/chaturbate.py.zip)

**Comment by WhitecreamDev** [comment]
Seems about right yes. Not sorting the results should keep the most popular tags on top. It's just what your preference is.
Also i've disliked code wise the many lines for each 'section' in the main list. I believe that could improve slightly with having the female, male, couple stuff in a dictionary, and iterate through that. I guess that would decrease the code lines by at least 50% :)

**Comment by jdoedev123** [comment]
Choose to sort alphabetically  mostly because that is standard most everywhere else for Tags and Categories etc. (Looked a little funky before adding sorting.)  I have not added pagination through multiple pages of Tags as later Tags are not very popular but that is a possibility. Also a possibility is adding a number for either Viewers or Rooms to indicate popularity.
As for code cleanup that maybe a task for another day but the near 100 line block of if statements is bit wonky and can be streamlined. 
While on subject of wonky code. Have you looked at XVideoSpanish lately? I have a mostly working version. The main problem was they now use non-ASCII in their domain URL/IRI. Added some code in xvideospanish.py to do the conversions but not sure if the code really belongs in utils.py.  Thoughts?

**Comment by dobbelina** [comment]
Chaturbate with Tag support incorporated in. addon
