### ISSUE TITLE
chaturbate error in ultimate white cream

### ISSUE THREAD

**Issue by joselbcn36** [dobbelina/repository.dobbelina#470]
Hi there can access to chaturbate through ultimate white cream, It was working until yesterday. Now it displays message to check the register

**Comment by joselbcn36** [comment]
Sorry, here you have a log file

/home/perilla/Documentos/kodi.log.zip

**Comment by frankee123** [comment]
Yes I get same error. chaturbate is one of my fav parts of WC, hopefully it will get fixed. Ty!

**Comment by 12asdfg12** [comment]
Why don't you guys use Cumination? UWC is deprecated, not compatible with matrix and not developed.

**Comment by pitsi** [comment]
Here is the real error in the log. 
```
2021-03-24 09:14:21.231 T:139890318567168   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: '_'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.uwc/default.py", line 234, in <module>
                                                sys.exit(main())
                                              File "/storage/.kodi/addons/plugin.video.uwc/default.py", line 228, in main
                                                utils.url_dispatcher.dispatch(mode, queries)
                                              File "/storage/.kodi/addons/plugin.video.uwc/resources/lib/url_dispatcher.py", line 91, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.uwc/resources/lib/sites/chaturbate.py", line 143, in List
                                                info = "\n\n[B]Status:[/B] " + status + "\n\n[B]Gender:[/B] " + genders[gender] + "\n\n[B]Age:[/B] " + age + "\n\n[B]Location:[/B] " + location + "\n\n[B]Activity:[/B] " + activity + "\n\n[B]Room topic:[/B] " + roomtopic
                                            KeyError: '_'
                                            -->End of Python script error report<--
2021-03-24 09:14:21.347 T:139890297980672   ERROR: GetDirectory - Error getting plugin://plugin.video.uwc/?channel=None&keyword&mode=221&name=%5bCOLOR%20hotpink%5dFemale%5b%2fCOLOR%5d&page&section=None&url=https%3a%2f%2fchaturbate.com%2ffemale-cams%2f%3fpage%3d1
2021-03-24 09:14:21.359 T:139891745216640   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.uwc/?channel=None&keyword&mode=221&name=%5bCOLOR%20hotpink%5dFemale%5b%2fCOLOR%5d&page&section=None&url=https%3a%2f%2fchaturbate.com%2ffemale-cams%2f%3fpage%3d1) failed
```
It seems that something goes wrong with the paginagion or scraping that uwc does, but I am no expert to find it. Cn works just fine and playback from bookmarks works as well.

A small request.
If uwc is not developed anymore, because I am about to move to kodi 19 and I had this question too, can you PLEASE backport the tags feature of cb from uwc to cn? It is the best feature of uwc ever, and I have been using is before it was forked by @dobbelina!

**Comment by joselbcn36** [comment]
hi there, I know is working properly in cumination, but what i like from uwc is that in icons view ( with Estuary skin ) you can see the cams name under the thumbnail and in cumination you do not.

**Comment by pitsi** [comment]
Let me check that. I do not use the estuary skin (I hate it actually) and I keep all my menus in list view.

**Comment by frankee123** [comment]
> Why don't you guys use Cumination? UWC is deprecated, not compatible with matrix and not developed.

I like the layout of UWC better. Also my fav view mode is wall or big wall, but on Cumination it zooms in way too much unlike how it does in UWC if that makes any sense.

**Comment by pitsi** [comment]
So, with the confluence skin, there are names under the cam thumbnails in thumbnail and the poster wrap views.

**Comment by 12asdfg12** [comment]
> A small request.
> If uwc is not developed anymore, because I am about to move to kodi 19 and I had this question too, can you PLEASE backport the tags feature of cb from uwc to cn? 

Tags will be added in the next version.

**Comment by joselbcn36** [comment]
> I like the layout of UWC better. Also my fav view mode is wall or big wall, but on Cumination it zooms in way too much unlike how it does in UWC if that makes any sense.

I like also the layout in wall view in stuary skin. One reason i use estuary skin is because i can put all my addons in home screen through favourites like a wall view   , and it looks like so simple and easy to use (before i used mimic skin and it was also so simple and clean).
![stuary layout](https://user-images.githubusercontent.com/75742054/112351624-57d82e80-8cca-11eb-833c-ade42c4c8702.png)

**Comment by frankee123** [comment]
> > I like the layout of UWC better. Also my fav view mode is wall or big wall, but on Cumination it zooms in way too much unlike how it does in UWC if that makes any sense.
> 
> I like also the layout in wall view in stuary skin. One reason i use estuary skin is because i can put all my addons in home screen through favourites like a wall view , and it looks like so simple and easy to use (before i used mimic skin and it was also so simple and clean).
> ![stuary layout](https://user-images.githubusercontent.com/75742054/112351624-57d82e80-8cca-11eb-833c-ade42c4c8702.png)
> 
> Here how it looks like uwc in wall view with the names of cams in the thumbnail:
> 
> ![bongacams in wall view with uwc](https://user-images.githubusercontent.com/75742054/112352661-3d528500-8ccb-11eb-8dc6-851cb05870d9.png)
> 
> and here with cumination
> 
> ![bongacams in cumination](https://user-images.githubusercontent.com/75742054/112352724-4d6a6480-8ccb-11eb-968f-f4f71d4d1c81.png)
> 
> If uwc will not be supported anymore, I will love to see this feature in cumination.
> thanks in advance

I agree with you bro. I use the same view as well. I am super thankful for UWC and everybody that works on it. I can't leave it lmao.

**Comment by ErosVece** [comment]
In a coming update, you can switch the content type in Cumination settings to 'video', so the wall view will be like in UWC.

**Comment by joselbcn36** [comment]
thank you so much!!!

**Comment by jdoedev123** [comment]
@pitsi  Thanks for porting the Tags feature to Chaturbate. I have been too busy with life to get to it.
Here is a working version of Chaturbate backported to UWC  from Cumination to fix the errors.
To Be clear this is for UWC.
[chaturbate.py.zip](https://github.com/dobbelina/repository.dobbelina/files/6214286/chaturbate.py.zip)

**Comment by joselbcn36** [comment]
Thank you 

> @pitsi Thanks for porting the Tags feature to Cumination. I have been too busy with life to get to it.
> Here is a working version of Chaturbate backported to UWC from Cumination.
> To Be clear this is for UWC which I still sometimes use for the Tags feature and other features I have not gotten around to porting to Cumination.
> [chaturbate.py.zip](https://github.com/dobbelina/repository.dobbelina/files/6214286/chaturbate.py.zip)

Thank you so much its works!!!!

**Comment by pitsi** [comment]
@jdoedev123 
Thank you for doing the backport! Please consider making a pull request to include it in uwc's code, so as to help others get it... in case uwc gets ever updated.

p.s. I am not involved in uwc's (or any other addon's) development. I am just a simple user whose coding skills are close to 0 :P

**Comment by jdoedev123** [comment]
@pitsi It is kind of my shtick to not do conventional pulls as this persona. It keeps me out of the official "authors" list. Kind of a dick move but most of the Devs know my code is good.

**Comment by camilt** [comment]
@joselbcn36 @frankee123 @pitsi 
You can replace line 143 in chaturbate.py:
`info = "\n\n[B]Status:[/B] " + status + "\n\n[B]Gender:[/B] " + genders[gender] + "\n\n[B]Age:[/B] " + age + "\n\n[B]Location:[/B] " + location + "\n\n[B]Activity:[/B] " + activity + "\n\n[B]Room topic:[/B] " + roomtopic`
with this lines:
`        info = "\n\n[B]Status:[/B] " + status 

        try:

            info = info + "\n\n[B]Gender:[/B] " + genders[gender]

        except:

            pass

        info = info + "\n\n[B]Age:[/B] " + age + "\n\n[B]Location:[/B] " + location + "\n\n[B]Activity:[/B] " + activity + "\n\n[B]Room topic:[/B] " + roomtopic
`

**Comment by pitsi** [comment]
Today's update to v1.2.46 fixes this issue of cb, so please close it.
