### ISSUE TITLE
VIP porn porn00 and porngo 

### ISSUE THREAD

**Issue by deanogers** [dobbelina/repository.dobbelina#471]
Keep getting play back error on every video and can’t seem to find the log on kodi 19 to say wat is causing it on firestick 4K any help please

**Comment by deanogers** [comment]
Ccurlfile Fillbuffer failed http error 410 open failed think it’s something to do opening input stream that’s all I can see about issue

**Comment by dobbelina** [comment]
How to find the logfile firestick:
https://www.firesticktricks.com/check-kodi-log-for-more-information.html
You can upload the logfile here:
https://paste.kodi.tv/

**Comment by deanogers** [comment]
CAddoninfobuilder ParseXML addon from inputstream adaptive for binary type kodi inputstream doesn’t contain library and addon becomes ignored that’s everything it says on screen about error

**Comment by dobbelina** [comment]
@deanogers 
Check if you have inputstream adaptive installed:
https://www.kodi-guide.com/how-to-enable-inputstream-adaptive-in-kodi/

**Comment by deanogers** [comment]
Both are enabled and still won’t play the videos on them websites

**Comment by deanogers** [comment]
They play on kodi 18.9 but don’t play on kodi matrix for some reason just keep getting playback failed please check log

**Comment by Gujal00** [comment]
@deanogers unless you provide a full debug log capturing the playback failures it is hard to diagnose as it works for others

**Comment by deanogers** [comment]
Cvideoplayer:open inputstream error opening https://www.vipporns.com are ccurlfile fillbuffer failed to open http returned error code 410 that’s all it says about issue

**Comment by Gujal00** [comment]
@deanogers Provide a full **debug** log as requested or close the issue, normal log snippets are of no use,
