### ISSUE TITLE
Allow to search by Time  or Video  Size

### ISSUE THREAD

**Issue by onknight** [dobbelina/repository.dobbelina#472]
The search Function we have is good  but I'd like Expand it search buy more parameters
I'd like be able to search for Video not just title but Size  or Time or both 

Let say I am look videos that 720P or High Quality It be great update 
Let say I am look vids that 5 mins or longer  it would be great to be able to search by how I want vid to be 

Let say Look 10 mins video that 1080P I'll like to be able to search Each addon by  these parameters

Cambro & Webcam Show are two favourite Adam I'd like to be able to search more in death
Strictly because there's so much content there

**Comment by ErosVece** [comment]
The search function you see in the addon is like using the search on the sites.
So if you search for 'big boobs' in Porntrex, it's the same as going to the site and putting 'big boobs' in the search bar there.

So searching for specifiek parameters won't work if that's not available on the sites.

**Comment by onknight** [comment]
too bad cause I like to better search but where stuck with this I guess

**Comment by dobbelina** [comment]
Impossible to implement globally.
On those sites that do support it, one has to create a custom search button on that particular site.
Closing issue.
