### ISSUE TITLE
Can add Кинокрад.NET??

### ISSUE THREAD

**Issue by xerel89** [dobbelina/repository.dobbelina#474]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**If it's a site addition request, add url below**https://Кинокрад.NET

**Comment by xerel89** [comment]
Is an russian site but she looks nice and great

**Comment by flapbird1** [comment]
+ 1 
please add it up
We need more full film feauted on Cumination
Just checked and uses among others, as a hosting

https://netu.io
https://start.u-stream.in
