### ISSUE TITLE
Wanted to no if possible that this feature could be added to a avoid this

### ISSUE THREAD

**Issue by losthelp815** [dobbelina/repository.dobbelina#476]
Problem is when you order your favorites video for chaturbate or mfc cams or general cam models that are to your order liking. Is the issue is when adding a new favorite cam model that one will always go to the top of your order that you have created thus making it a lot of work to reorganize to your specific order.

If possible would like to know if there could be a way to lock the order how you have your favorites cam models setup so when adding in a new favorite cam model it will go to the bottom so that your order wont be disorganized. Or making the favorite order easier to move around without messing up the original order.

**Comment by frankee123** [comment]
Yea, I finally decided to switch from using UWC forever to upgrading to kodi 19 and using Cumination but I don't know why I can't change the order of my favorites like I could in UWC.

**Comment by 12asdfg12** [comment]
In the next version, it will be possible to move a favorite to the bottom of the list.

**Comment by frankee123** [comment]
> In the next version, it will be possible to move a favorite to the bottom of the list.

Ty sir!

**Comment by losthelp815** [comment]
Thanks guys appreciate the moving to the bottom for favorites.
