### ISSUE TITLE
Dobbelina repository 

### ISSUE THREAD

**Issue by saidma** [dobbelina/repository.dobbelina#477]
### Bug reports:

Dobbelina repository not work: Install from repository > could not connect to repository 

###

**Comment by dobbelina** [comment]
Try installing the repository again,
Add source url below into your file manager and install **repository.dobbelina-1.0.3.zip**

https://dobbelina.github.io/

Or download and install directly
https://dobbelina.github.io/repository.dobbelina-1.0.3.zip

**Comment by dobbelina** [comment]
No replies closing.
