### ISSUE TITLE
[Request] Do a one-time search like quicksearch in Youtube 

### ISSUE THREAD

**Issue by DaisyF8** [dobbelina/repository.dobbelina#479]
Only way to do a search is with "Add keyword" ? And after adding you have to click the keyword to show the search.

Can you add a way to search and see results all in one without adding a keyword?

**Comment by dobbelina** [comment]
Not as of now.
I guess what you would like is a quick search feature, similar to the youtube addon.

**Comment by DaisyF8** [comment]
Thanks for explaining.

**Comment by DaisyF8** [comment]
Thanks for implementing.
