### ISSUE TITLE
Pornhub broken?

### ISSUE THREAD

**Issue by gutho877** [dobbelina/repository.dobbelina#48]
Nothing comes up in any of the categories. Anyone else experiencing this issue?

**Comment by gutho877** [comment]
Xhamster is broken for me too now.

**Comment by jdoedev123** [comment]
Weird, make slight change in line 45 of pornhub.py:

	match = re.compile(' class=" js-pop.*?<a href="([^"]+)" title="([^"]+)".*?data-mediumthumb="([^"]+)".*?<var class="duration">([^<]+)</var>(.*?)</div', re.DOTALL).findall(main_block) 

Very subtle change in HTML caused problem with scraping page. Old line started with 3 more characters before class.

**Comment by jdoedev123** [comment]
XHamster made another subtle change in the HTML which broke UWC.
No more <footer> in HTML so change the code to search for </main> instead.
 
Two lines of code to change in xhamster.py. 
Line 50 to fix Video listing:
	match0 = re.compile('<head>(.*?)</head>.*?index-videos.*?>(.*?)</main>', re.DOTALL | re.IGNORECASE).findall(response)
Line 90 to fix Categories:
    match0 = re.compile('<div class="letter-blocks page">(.*?)</main>', re.DOTALL | re.IGNORECASE).findall(cathtml)

**Comment by DJMix-I-Can** [comment]
Fix for Anybunny...
replace line 44 with
match = re.compile(r"<a class='nuyrfe' href='([^']+).*?src='([^']+)' id=\d+ alt='([^']+)'", re.DOTALL | re.IGNORECASE).findall(listhtml)

**Comment by DJMix-I-Can** [comment]
> 
> 
> XHamster made another subtle change in the HTML which broke UWC.
> No more `<footer>` in HTML so change the code to search for `</main>` instead.
> 
> Two lines of code to change in xhamster.py.
> Line 50 to fix Video listing:
> ` match0 = re.compile('<head>(.*?)</head>.*?index-videos.*?>(.*?)</main>', re.DOTALL | re.IGNORECASE).findall(response)`
> Line 90 to fix Categories.
> ` match0 = re.compile('<div class="letter-blocks page">(.*?)</main>', re.DOTALL | re.IGNORECASE).findall(cathtml)`
> 
> Will upload later after a little testing.

This fixed it. I checked the other directories as well. Thanks.

**Comment by jdoedev123** [comment]
Thanks DJMix-I-Can,  your fix for AnyBunny works for me.

**Comment by jdoedev123** [comment]
Pornhub fixed.
[pornhub.py.zip](https://github.com/dobbelina/repository.dobbelina/files/3288456/pornhub.py.zip)

**Comment by jdoedev123** [comment]
XHamster fixed.
[xhamster.py.zip](https://github.com/dobbelina/repository.dobbelina/files/3288458/xhamster.py.zip)

**Comment by gutho877** [comment]
You guys are incredible. Thank you for all your hard work.

**Comment by dobbelina** [comment]
Awesome!

Thanks guys, will update addon soon.

**Comment by dobbelina** [comment]
All fixed, closing thread.
