### ISSUE TITLE
Daftsex Cumination 

### ISSUE THREAD

**Issue by darktones123** [dobbelina/repository.dobbelina#481]
All Links "oh oh, could not find a supported link." Anyone else having this issue?
Thanks

**Comment by crst31** [comment]
I'm getting the same, and "Categories" is empty.

**Comment by darktones123** [comment]
> I'm getting the same, and "Categories" is empty. Search is working though.

Categories has been down for awhile now for me.

**Comment by dobbelina** [comment]
Issue confirmed, thanks for reporting.

**Comment by p8ckachu** [comment]
Was this fixed?
