### ISSUE TITLE
DatoPorn Issues

### ISSUE THREAD

**Issue by darktones123** [dobbelina/repository.dobbelina#483]
# Please fill in below:

- [x] Cumination Bug
- [ ] Ultimate Whitecream Bug

### Bug reports:

I am getting "resolved failed, dato link could not be resolved." All links seem to be affected in Datoporn.

Thanks

### OS environment
Firestick Cumination 1.1.11

**Comment by camilt** [comment]
Seems to be an issue with the site. On all links the player message is: "html5: Video file not found"
