### ISSUE TITLE
Add compress button to Cumination backup favourites page

### ISSUE THREAD

**Issue by Dave-newman** [dobbelina/repository.dobbelina#487]
**Is your feature request related to a problem? Please describe.**
This feature is related to an issue with 32 bit Kodi not been able to recognize compressed backup files, this has been fixed in the 64-bit version of Kodi, but not in the 32-bit version.
This affects all addons running on Kodi 32-bit version, which stopped you from restoring (compressed files) files.

**Describe the solution you'd like**
In the Backup utility addon programme, there is an option button to compress the backup files or not.  
If this button was added to the settings menu of Cumination above Backup favourites, this would give you a choice to compress the backup files or not. This would resolve the issue for this addon and allow you to restore (uncompressed) backup files.

**Comment by ErosVece** [comment]
This will be added in a coming update
