### ISSUE TITLE
Possible bug: Odd Cumination behavior...or is it just me?

### ISSUE THREAD

**Issue by tetzy** [dobbelina/repository.dobbelina#488]
It took me a while to update to the latest version of Cumination. As luck would have it, there was a Linux kernel update on the same day and I'm not sure if what I'm seeing is the result of changes in Linux or in Cumination. 

The Problem:

When viewing new video listings, if I navigate below the first screen of visible results: 

When I add a video to my Favorites menu, the usual 'Video added to the favorites' box opens but then, the program  lags for a second as almost simultaneously another box opens showing the spinning "working" graphic to its right as the program adds the item to the favorites menu. When the boxes go away, the program loses focus and the item I've just added to favorites drops to the bottom of the page from wherever it was originally on the page. 

All in, the lag adds about 1 second to adding entries to the Favorites menu - it isn't much, and it's not really my issue; having to refocus the page every time it happens is the annoyance. The behaviour is new - items were added to the menu immediately before and without that new "working" box.    

The problem only exists within Cumination - I have 32gb of ram, so that isn't the issue.

Any ideas?

I'm running the newest version of Linux Mint on a PC.

**Comment by Gujal00** [comment]
Are you using any skin other than Estuary?

**Comment by tetzy** [comment]
> Are you using any skin other than Estuary?

Yes - I'm using the Confluence skin. I never warmed up to Estuary.

**Comment by Gujal00** [comment]
I think it is skin issue, try with Estuary if you have the same issue

**Comment by tetzy** [comment]
> I think it is skin issue, try with Estuary if you have the same issue

It is. Damn - I think Estuary was a clunky step down from Confluence. Shitty for me.

Thanks for your help.
