### ISSUE TITLE
Cat3Movie is down and out?

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#49]
Cat3Movie source cat3movie.us website is down, perhaps for good. Whois shows:
Domain Status: clientRenewProhibited https://icann.org/epp#clientRenewProhibited
Domain Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Domain Status: clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited
Not good, perhaps a legal dispute shut it down?

**Comment by dobbelina** [comment]
Hi jdoedev123,

I'll remove it.

**Comment by dobbelina** [comment]
Closing thread.
