### ISSUE TITLE
Cumination Site Addition Request

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#490]
With UWC not being developed anymore, can we please add following sites to Cumination:

Javhoho.com
Freevideo.cz
Masalaseen.net

**Comment by imurreflection** [comment]
Dear @m-incognito..can you please look at this request for free video.cz as you initially added this to UWC.

**Comment by imurreflection** [comment]
Dear @12asdfg12 mate. May I request you to please look at the feasibility of this site addition as it appears that the original developer @m-incognito is not available any more. In my personal opinion, I think this is the best site with amazing high quality full length content. Thank you

**Comment by imurreflection** [comment]
Dear Gujal00..can you please look at this request. The only reason I m asking for this addition is that this site is presently on UWC  for which support has ended so if this site goes down,there will be no fix. Thanks

**Comment by Gujal00** [comment]
Sites with no Contact email and DMCA policy will not be added to Cumination. 
Because of this Freevideo.cz wont be added

**Comment by imurreflection** [comment]
@gujal00. 
Oh..that's a bummer...in this case, can you please look at the possibility for javhoho.com...i have checked the site has requisite information you need for its addition.
