### ISSUE TITLE
PornHub Not Working

### ISSUE THREAD

**Issue by Maggio86** [dobbelina/repository.dobbelina#491]
### Bug reports:

All links are not working and getting the error “pornhub link could not be resolved”

### OS environment
Kodi 18.9 and 19

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/

**Comment by dobbelina** [comment]
Issue confirmed, thanks for reporting.
Noticed that xHamster went down as well.

**Comment by Gujal00** [comment]
please check pornhub playback again and report back. There was a fix in ResolveURL for this

**Comment by Maggio86** [comment]
Works now.

**Comment by Gujal00** [comment]
@Maggio86 Please close the issue if it is working for you
