### ISSUE TITLE
Xhamster not loading

### ISSUE THREAD

**Issue by s4ik0s4n** [dobbelina/repository.dobbelina#493]
### Bug reports:

Attempted to open the Xhamster section of Cumination. Kodi attempts to load it, with the spinning wheel going for about 2 minutes, 25 seconds. When it finishes, it shows the categories and search options, but no videos. Selecting an option from the categories produces a similar result. Tried restarting Kodi, my Shield, and clearing the cache to similar results. Other sites work just fine. No bug report to show since no error pops up.

### OS environment
Using a Shield TV

**Comment by tetzy** [comment]
On my end too.

**Comment by dobbelina** [comment]
Issue confirmed, thanks for reporting.
