### ISSUE TITLE
Chaturbate Online Favorites

### ISSUE THREAD

**Issue by TarkusLV** [dobbelina/repository.dobbelina#497]
Didn't see a thread on this, but wanted to thank those responsible for this new feature.  It is a very cool addition!

**Comment by camilt** [comment]
Some features was added as improvements, not as responses to requests. ("Online favorites", "Current hour's top cams" in Chaturbate, "Queen of Queens contest" in Bongacams). Hope someone likes these additions

**Comment by TarkusLV** [comment]
It seems the thumbnail images are never updated, unless you like go into your regular favourites, so they get refreshed there.  Even clearing the local cache doesn't cause them to get updated.  Can that be changed?
