### ISSUE TITLE
StreamXXX.tv 👎🏻

### ISSUE THREAD

**Issue by flapbird1** [dobbelina/repository.dobbelina#499]
### Bug reports:
As per above, website on PC works fine

### OS environment
Android 7, Ubuntu 20.04.2 LTS

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/

**Comment by flapbird1** [comment]
So sorry guys but can't make it work doesn't even open website

Tried Android 7 & Windoze 10

I'll upgrade this later with log

Keep it UP

**Comment by dobbelina** [comment]
@flapbird1 
The fix will be in the next release 1.1.15
