### ISSUE TITLE
Thank you for UWC 

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#5]
Hi, Thank you so much for fixing the much needed issues for UWC. However, kindly note that the issues mentioned in the original issue to kodibae are not completely resolved. If you can fix then I would request you to fix following issues only as of now:

1) Yespornplease still giving ultimate whitecream error.
2) much needed Daftsex is not working
3) hclips under tubes not working.

Thank you so much for fixing porntrex.

I know that this add-on was abandoned for a long time and all issues will take time to get resolved but if you may please kindly look st the above mentioned issue,it would be great. Also, if possible, please provide zip download link to your repo or let me know the source. Thanks again.. Have a nice day !

**Comment by deanogers** [comment]
How can u update 2 1.1.66 as in zip file only says 1.1.65 any help would be great

**Comment by imurreflection** [comment]
Download the file as zip and install using kodi. Since the repo is not installed, you will not b able to update it automatically but manually the file will install and show the latest version.
