### ISSUE TITLE
ParadiseHill 

### ISSUE THREAD

**Issue by Unknown247** [dobbelina/repository.dobbelina#50]
Hello guys and thank you for the hard work fixing the issues with these sites. Paradisehill seems to have the same problem as before. I was able to repair it with your Py file from 5 days ago and it worked great. But tried opening it today and no list just next page tab opens. Thanks

**Comment by dobbelina** [comment]
paradisehill.py from plugin.video.uwc-1.1.80 works.
Here you go:
[paradisehill.zip](https://github.com/dobbelina/repository.dobbelina/files/3293877/paradisehill.zip)
