### ISSUE TITLE
Porn00

### ISSUE THREAD

**Issue by thatguy-cntrl** [dobbelina/repository.dobbelina#500]
### Bug reports:

Titles and thumbnails show up but all the videos fail to stream.

### OS environment
AndroidTV 9 Kodi 19

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/

**Comment by ErosVece** [comment]
Works fine for me with Cumination

**Comment by dobbelina** [comment]
No issue for me either in CN, closing issue.

**Comment by thatguy-cntrl** [comment]
Figured it out. A VPN fixed the issue, so just a problem with my region.
