### ISSUE TITLE
Quality and length filter? Xhamster

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#503]
Change log says it's been added to xhamster context menu but it's not there.please let me know what I m missing?

**Comment by 12asdfg12** [comment]
![image](https://user-images.githubusercontent.com/48175015/116807662-0af33d80-ab3d-11eb-9140-d8db4f31f39f.png)

**Comment by imurreflection** [comment]
Thanks mate..I was looking under main menu. Is it possible to include similar feature for xvideos.com please. If not, please advise and I will close the issue as original concern has been resolved. Thank you

**Comment by 12asdfg12** [comment]
it can also be implemented for xvideos but only for searches and categories

**Comment by imurreflection** [comment]
Please do it mate.it would be great addition has xvideos has vast content

**Comment by imurreflection** [comment]
Thanks for the addition..closing the issue now
