### ISSUE TITLE
Cam4 links not working

### ISSUE THREAD

**Issue by Tyke101** [dobbelina/repository.dobbelina#505]
### 
Recently started getting the error message “oh oh couldn’t find a playable webcam link” on all webcams.
Is this a general fault or just my setup?
If just relevant to me what have I done to cause it?

Kodi 18.9 Nvidia Shield

**Comment by jdoedev123** [comment]
Confirmed.
Cam4 does not work for me in Cumination 1.1.12 in Kodi 18.6 on PopOS 20.04
also Cam4 not working in Cumination 1.1.7 or 1.1.12 in Kodi 19.0 on Android 7.0
also Cam4 not working in Cumination 1.1.12 in Kodi 19.0 on PopOS 20.04
FWIW
Cam4 working in UWC 1.2.46 in Kodi 18.6 on PopOS 20.04

**Comment by ErosVece** [comment]
I heard it will be fixed in Cumination ;)

**Comment by jdoedev123** [comment]
@ErosVece  Thxs
Current github version of Cam4 for Cumination working in Kodi 18.6 and 19.0 on PopOS 20.04
V 1.1.13 Cam4 not working but assume next update will incorporate fix.
