### ISSUE TITLE
Default on Favourites menu change request

### ISSUE THREAD

**Issue by Dave-newman** [dobbelina/repository.dobbelina#506]
In Cumination Favourites, I have been accidentally removing saved Favorites, mostly because "Remove from Favourites" is the default (first on the menu). This does not allow for delays with the internet, remote control etc.

Can this option please be moved lower down the menu, to below "Move Favourite to the bottom" for example? I know this sounds trivial but it so frustrating when your Favourites are deleted and you can't find them again.

Any help with this matter would be very much appreciated

**Comment by ErosVece** [comment]
It's moved down in the next update :)

**Comment by Dave-newman** [comment]
Fantastic, thanks very much

**Comment by Dave-newman** [comment]
Thanks, very much appreciated
