### ISSUE TITLE
Myfreecams not working

### ISSUE THREAD

**Issue by frankee123** [dobbelina/repository.dobbelina#509]
### Bug reports:

Everything is blank when I click on MFC

### OS environment
What OS, Device, version etc

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/

**Comment by dobbelina** [comment]
@frankee123 
Incomplete bugreport, what Kodi version and OS?
Works fine in Kodi 18.9 on Win10

**Comment by onknight** [comment]
working find windows 10 and Android

**Comment by frankee123** [comment]
sorry, I use an android box and kodi 19. When I click on myfreecams no girls show up also when I click on one of them from my favorites that I know is online, it gives me a cumination error.

**Comment by Gujal00** [comment]
@frankee123 if you upgraded from Kodi18 install to Kodi19 on the android box, then there could be issues with incompatible script modules, especially websock module that is required for mfc. Did you do a clean install of Kodi 19 or upgrade from 18?

**Comment by frankee123** [comment]
Yes I did a clean install. This just happened to me randomly starting a few days ago. I have no clue what is wrong. Ty for your response!

**Comment by Gujal00** [comment]
@frankee123 so to investigate further you need to provide full debug log. This issue is specific to you as it works fine on Android 9 with Kodi 19 and log from your device is required

**Comment by frankee123** [comment]
Ty friend. I'm not really savy on how to do that and I don't want to be a bother really, so it's all good. i'll just deal with it. Ty

**Comment by frankee123** [comment]
If I backed up my favorites and keywords for cumination and its the only thing i have on kodi atm, it wouldnt be so bad to uninstall and reinstall kodi 19 then right? I'm thinking that is what I can do?

**Comment by frankee123** [comment]
It randomly started working again for me somehow. Ty for the help though!
