### ISSUE TITLE
XVideoSpanish and YourFreeTube mostly working

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#51]
To avoid too much duplication of effort here are versions of XVideoSpanish And YourFreeTube which are mostly working. Most problems are in playback of the first few videos after maybe 10 videos these sites use DatoPorn, RapidVideo, Openload, etc which mostly work.
Tags also not working in  XVideoSpanish.

[xvideospanish.py.zip](https://github.com/dobbelina/repository.dobbelina/files/3303666/xvideospanish.py.zip)
[yourfreetube.py.zip](https://github.com/dobbelina/repository.dobbelina/files/3303667/yourfreetube.py.zip)

**Comment by dobbelina** [comment]
Awesome, thanks jdoedev123!

Will update soon.

**Comment by 12asdfg12** [comment]
Fixed playback for videos hosted on xvideos-cdn.com and pornhub + added more categories (longest, popular, most viewed)
[xvideospanish.zip](https://github.com/dobbelina/repository.dobbelina/files/3316818/xvideospanish.zip)

**Comment by jdoedev123** [comment]
12asdfg12, thanks for the help. Sometimes it gets frustrating working on   sites which use various playback methods especially buried somewhere in undocumented JSON. Nicely Done

**Comment by 12asdfg12** [comment]
JSON is not a problem, requests which returns JSON are easy to catch in firefox/chrome developer mode, have a look at the picture attached.

![devmode](https://user-images.githubusercontent.com/48175015/59972948-bece2e00-95a0-11e9-89af-1a4fe0cefbb0.png)

**Comment by jdoedev123** [comment]
Yes I know. I use Dev mode but as a long time developer it is not my favorite way to hunt for an undocumented API. A few sites even block Dev mode. But thanks.

**Comment by dobbelina** [comment]
Thanks for the improvement 12asdfg12!

Will update addon.
