### ISSUE TITLE
Daftsex cumination 

### ISSUE THREAD

**Issue by jegfonseca** [dobbelina/repository.dobbelina#512]
### Bug reports:

Please replace this line with a brief summary of your issue 

### OS environment
What OS, Device, version etc

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Hello

Addon cumination 

Dafsrex is not working for me

Why?

Thanks

**Comment by Gujal00** [comment]
Duplicate of #481 
Will be fixed in the next release

**Comment by jegfonseca** [comment]
Thanks you
