### ISSUE TITLE
Pornhub

### ISSUE THREAD

**Issue by cjtharris** [dobbelina/repository.dobbelina#513]
### Bug reports:

Sorry if this has been addressed. I’m new and didn’t see anything as I was looking. Pornhub is not working. It shows the thumbnails but none of the links will work.

### OS environment
Firestick. Kodi version 18.9 

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/

**Comment by imurreflection** [comment]
I checked different links and all are working fine. May be you need to use VPN

**Comment by dobbelina** [comment]
It's working for me to.
