### ISSUE TITLE
Add Filters Request- Pornhub

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#514]
Recently our friendly developer @12asdfg12 enabled filters for xvideos.com. Can I request him to please enable the same filtering options for pornhub as well. Thanks.

**Comment by imurreflection** [comment]
Hi @12asdfg12 ...kindly look at this request. If the addition is not possible, please advise and I will close this issue.

**Comment by imurreflection** [comment]
Take your time and thanks brother

**Comment by 12asdfg12** [comment]
filters added in v1.1.16

**Comment by imurreflection** [comment]
Thanks a lot mate. Is there anyway I can manually add the files?

**Comment by dobbelina** [comment]
@imurreflection 
Edited pornhub.py can be found here:
https://raw.githubusercontent.com/dobbelina/repository.dobbelina/master/plugin.video.cumination/resources/lib/sites/pornhub.py

**Comment by imurreflection** [comment]
Thank you so much @dobbelina and @12asdfg12. This is working just fine. Closing the issue now
