### ISSUE TITLE
Updates not installing  can't Maunaly install on Windows 10 

### ISSUE THREAD

**Issue by onknight** [dobbelina/repository.dobbelina#518]
I'm using version1.1.14 I'm not getting any updates for accumulation
If I try to install manually I got an invalid structure error

**Comment by Gujal00** [comment]
Install the repository first to get automatic updates
`https://github.com/dobbelina/repository.dobbelina/blob/master/repository.dobbelina/repository.dobbelina-1.0.3.zip`

**Comment by onknight** [comment]
Sorry got same error trying to install the Repo Failed do to a invalid Structure Error

**Comment by onknight** [comment]
Got it to install but my Freecams still don't work 
[](https://i.imgur.com/rfTsNOW.jpg)

**Comment by onknight** [comment]
<a href="https://imgur.com/rfTsNOW"><img src="https://i.imgur.com/rfTsNOW.jpg" title="source: imgur.com" /></a>

**Comment by Gujal00** [comment]
post full debug log. It works fine for others

**Comment by dobbelina** [comment]
No log, closing issue.
