### ISSUE TITLE
Czech3x  without working video playback

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#52]
To avoid too much duplication of  effort here are versions of HDZog and Czech3x which are complete except for the most important video playback does not work.

I maybe blocked from further contributions on Czech3x as it blocked my IP for using Dev Tools while visiting the website.

[hdzog.py.zip](https://github.com/dobbelina/repository.dobbelina/files/3303681/hdzog.py.zip)
[czech3x.py.zip](https://github.com/dobbelina/repository.dobbelina/files/3303693/czech3x.py.zip)

**Comment by dobbelina** [comment]
Thanks for the effort jdoedev123.

I will update the addon with these, but keep the "broken" label until somebody
fixes the playback issue.

**Comment by 12asdfg12** [comment]
Hdzog & tpc: applied the fix from WhitecreamDev

[hdzog.zip](https://github.com/dobbelina/repository.dobbelina/files/3363392/hdzog.zip)
[tubepornclassic.zip](https://github.com/dobbelina/repository.dobbelina/files/3363393/tubepornclassic.zip)

**Comment by dobbelina** [comment]
Awesome!

Thanks again 12asdfg12.
Will update addon soon.
