### ISSUE TITLE
One big problem with the new menu

### ISSUE THREAD

**Issue by tetzy** [dobbelina/repository.dobbelina#520]
This is an issue big enough that I consider it a bug:

I've just updated to the latest version of Cumination and have already hit a wall with one of the changes you've implemented: placing "Remove From Favorites" farther down the right click menu.

Here's the thing - content links _expire_. 

The previous system of '_Right-click, delete, right-click, delete_' to clear away expired titles from the Favorites menu is now '_Right-click, navigate to "Remove From Favorites", delete, 'Right-click, navigate to "Remove From Favorites", delete_' adding significant time to what was before a very quick process. 

To make matters worse, when providers upload large numbers of titles from specific sites we'll be faced with removing 80 or 100 expired links from the favorites menu at a time. The newly sorted menu is going to make this a very tedious experience.

I'm hoping you'll consider a switch back to the previous sort - replacing an option that is used all the time with something I've never once bothered using is not an improvement. Better yet, is there any way to give us the option to manually sort the menu?  

Thanks for all you do in keeping the app going, it is very much appreciated.

**Comment by Gujal00** [comment]
Was a requested feature in #506 
Why is this a bug?

**Comment by ErosVece** [comment]
@tetzy Team Cumination can't keep every user happy....an annoyance for one can be a blessing for the other

So, to keep you happy....what do you think of a multiple remove function? Where you'd get a select dialog so you can select multiple favorites, and remove them with one click on a button :)

**Comment by tetzy** [comment]
> So, to keep you happy....what do you think of a multiple remove function? Where you'd get a select dialog so you can select multiple favorites, and remove them with one click on a button :)

Sounds great... Easier yet: how about allowing deletion of favorites by pushing the 'Delete' key on our keyboards?

**Comment by ErosVece** [comment]
That's not possible (I think)... :)
