### ISSUE TITLE
Porndig problems

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#523]
Hi, porndig amateurs and porndig professional sites are crashing Kodi when you try to open them. If possible, kindly fix it or remove them as we have many new sites getting added and many UWC additions are pending.

**Comment by imurreflection** [comment]
Hi @dobbelina. Can you please look at this and confirm if everyone is facing this issue or there is some discrepancy at my end please?.

**Comment by dobbelina** [comment]
@imurreflection 
It is not crashing kodi for me, however the sites are not working.

**Comment by imurreflection** [comment]
Thank @dobbelina...knowing you and our developers, I know all will be okay so closing the issue now
