### ISSUE TITLE
Porn Trex search

### ISSUE THREAD

**Issue by xerel89** [dobbelina/repository.dobbelina#524]
No finding results please fix it

**Comment by dobbelina** [comment]
It works, maybe you are using a search term with no hits.

**Comment by xerel89** [comment]
Yes I have no hits you can fix it?

**Comment by xerel89** [comment]
I search for gabbie carter...

**Comment by dobbelina** [comment]
I get search hits with gabbie carter.
<img width="711" alt="screenshot002" src="https://user-images.githubusercontent.com/46063764/119878866-ebc4b180-bf2a-11eb-99db-cb65fa3920ad.png">

**Comment by ErosVece** [comment]
I <3 Gabbie :)

Pro tip: create a free account on Porntrex, and subscribe to her....log in to Porntrex in Cumination, and you can go to her model page and see every video where she is tagged in.

**Comment by dobbelina** [comment]
No issue, closing thread.
