### ISSUE TITLE
Free porn streams can not load streams

### ISSUE THREAD

**Issue by xerel89** [dobbelina/repository.dobbelina#525]
### Bug reports:

Please replace this line with a brief summary of your issue 

### OS environment
What OS, Device, version etc

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/

**Comment by dobbelina** [comment]
Fixed in next release.
https://github.com/dobbelina/repository.dobbelina/commit/eda512ea13ace8a1f5b69171d61469a42abc4265
