### ISSUE TITLE
Spankbang search not working for all search terms.

### ISSUE THREAD

**Issue by p8ckachu** [dobbelina/repository.dobbelina#532]
### Bug reports:

 Search returns trending videos instead of search results.
 
Android OS, latest version as of this post. 

Search term: Mila monet

**Comment by Gujal00** [comment]
Dont see any issue, working fine
![image](https://i.imgur.com/qzgYrvC.png)

**Comment by jamesonquarters2** [comment]
Do have to say that I have the same issue. Any time I search up anything that isn't specifically a tag I'm guessing it comes up as nothing. I've searched things like Ava Claire and nothing pops up even though I know it's out there. Certain words do go through the search though
