### ISSUE TITLE
New update not Available on Kodi 19

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#533]
Hi @dobbelina. Please know that this recent update is not available on official Kodi 19.1 but the same is available on Unofficial Kodi fork wbmc running 18.9. can you please look into this. Thanks

**Comment by ErosVece** [comment]
I did work for me, must be a @imurreflection issue ;)

**Comment by imurreflection** [comment]
I have updated it manually so closing the issue now
