### ISSUE TITLE
Cam4 link causes freeze in Cumination

### ISSUE THREAD

**Issue by Tyke101** [dobbelina/repository.dobbelina#535]
Cumination freezes for approximately 92 seconds after clicking on any cam link in Cam4.  The link then connects after this time.
If the link is saved as a favourite in both Cumination and Kodi favourites the same freeze happens from within Cumination favourites but the link connects normally using the Kodi favourite link.

### OS environment 
Android Nvidia Shield
 Kodi 19.1 
Cumination 1.1.16

**Comment by Gujal00** [comment]
Seems to be specific to Kodi19.1
Works fine in Kodi 18.9

**Comment by ErosVece** [comment]
Works fine on 19.1 in Windows, but on my Android phone with 19.1 is freezes indeed.
Seems more like a Kodi issue than a Cumination issue
