### ISSUE TITLE
Porn00 and vipporn

### ISSUE THREAD

**Issue by deanogers** [dobbelina/repository.dobbelina#537]
These to sites don’t play movies on kodi 19 for some reason just keeps saying one are more files failed to play play on kodi 18.9

**Comment by imurreflection** [comment]
No such issue observed. Both sites are working fine on Kodi 18.9 and 19. Perhaps you need to use VPN

**Comment by deanogers** [comment]
They work ok on 18.9 but not on 19 everything else works on 19 but these sites just keeps saying videos unable to play check log strange m8 but no worries anyway keep up the good work

**Comment by dobbelina** [comment]
Closing this thread, lacks logfile.
