### ISSUE TITLE
Spankbang Error

### ISSUE THREAD

**Issue by crst31** [dobbelina/repository.dobbelina#539]
Won't open

**Comment by imurreflection** [comment]
Hi @dobbelina and @12asdfg12, may I request you to please look at this request and fix it. It seems it has been forgotten

**Comment by Gujal00** [comment]
What is the issue though? seems to be working fine

**Comment by imurreflection** [comment]
It doesn't open at all. I tried on both 18.9 and 19

**Comment by Tyke101** [comment]
I can confirm that it doesn’t open for me on Kodi 19.0

**Comment by imurreflection** [comment]
@Tyke101....is it working for you on Kodi 18.9? Is am getting 403 Forbidden and it looks like this website is down error.

**Comment by Gujal00** [comment]
repeatedly saying not working without providing debug log is of no use

It works perfectly fine in 19.1
![image](https://i.imgur.com/8cUcb6n.png)

Provide the link for a full debug log (not log snippets) posted into paste.kodi.tv to check why it is not working for you.

Secondly check if the site works for you in a web browser, if not working, it cant work in cumination either.

**Comment by imurreflection** [comment]
Hi Gujal00. The site is working fine on web browser. Here is complete log as required

https://paste.kodi.tv/dovewoculu

**Comment by Gujal00** [comment]
Okay this seems to be specific to Android Platform. I had raised an issue in Kodi forum relating to an identical issue earlier and they are aware and working on it.
https://forum.kodi.tv/showthread.php?tid=363015
If you are brave enough, you can try with the Android Test build of Kodi 20 available on that thread that fixes the issue

**Comment by imurreflection** [comment]
Sure..I will try Android 20 and revert

**Comment by imurreflection** [comment]
Hi Gujal00... I tried Android N Alpha V20 but unable to install Cumination for various errors like:
1) Backsports.ssl,_match_hostname ..This add-on is not compatible with this version of Kodi
2) websocket library- Same error
3) Kodi Six- Same error 
4) The dependency on xbmc python version 2.26.0 could not be satisfied

Please advise what exactly I have to do to get this working

**Comment by imurreflection** [comment]
Here is the log file
https://paste.kodi.tv/usamejavj

**Comment by Gujal00** [comment]
I tested on a fresh install of Kodi 20 test build on my Android phone and it works fine. 
xbmc python 2.26.0 dependency means it is not even matrix compatible, so something messed up in your install.

**Comment by imurreflection** [comment]
Well then I have to wait for next Kodi release..thank you

**Comment by Gujal00** [comment]
@imurreflection 
Can you try with this utils.py file. It has a workaround for OpenSSL1.1.0
It should be copied to Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cumination/resources/lib/ folder
[utils.zip](https://github.com/dobbelina/repository.dobbelina/files/6690757/utils.zip)

I tested this on Kodi 18.9 Windows and on Kodi 19.1 Android

**Comment by imurreflection** [comment]
> @imurreflection
> Can you try with this utils.py file. It has a workaround for OpenSSL1.1.0
> It should be copied to Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cumination/resources/lib/ folder
> [utils.zip](https://github.com/dobbelina/repository.dobbelina/files/6690757/utils.zip)
> 
> I tested this on Kodi 18.9 Windows and on Kodi 19.1 Android
 
Bro, when you said that there is a system limitation, I actually had given hope but this workaround actually works like a charm and my most favorite site is back.  I can thank you enough for this but thank you so much.

**Comment by Gujal00** [comment]
@dobbelina with the release of 1.1.18, I think this issue can be closed

**Comment by omdreamer** [comment]
Spankbang has never worked for me on Apple TV, the workaround listed above is for Android, any suggestions how to fix on ATV?
