### ISSUE TITLE
Sxyprn(yourporn) Issue

### ISSUE THREAD

**Issue by Sameer888** [dobbelina/repository.dobbelina#54]
Hi dobbelina,

Sxyporn videos are working fine in browser but not in addon , Videos are unplayable .Please check the issue ,Thanks

**Comment by 12asdfg12** [comment]
sxyprn.py,  line:158 change cdn4 to cdn5:

old line:
`	videourl = re.compile('''data-vnfo='{".+?":"(.+?)"''', re.DOTALL | re.IGNORECASE).findall(html)[0].replace('\/','/').replace('/cdn/','/cdn4/')`
new line:
`	videourl = re.compile('''data-vnfo='{".+?":"(.+?)"''', re.DOTALL | re.IGNORECASE).findall(html)[0].replace('\/','/').replace('/cdn/','/cdn5/') `

**Comment by Sameer888** [comment]
Thanks 12asdfg12 , you are always helpful 👍

**Comment by dobbelina** [comment]
Fixed, closing issue.
