### ISSUE TITLE
Herexxx issues with video titles using korean text

### ISSUE THREAD

**Issue by steph09** [dobbelina/repository.dobbelina#543]
Found an issue where all videos in herexxx refuse to play giving a 'website is down' error when the video plays fine in a web browser. All videos with english names play fine.

The kodi log gives this error.
>  UnicodeEncodeError: 'ascii' codec can't encode character '\ud3f0' in position 11: ordinal not in range(128)

**Comment by dobbelina** [comment]
@steph09 
Fixed in next release v1.1.18
https://github.com/dobbelina/repository.dobbelina/commit/c380d80d91e283a97a003fbadb2ae1028718825f
