### ISSUE TITLE
AnimeID-Hentai search broken

### ISSUE THREAD

**Issue by DaisyF8** [dobbelina/repository.dobbelina#55]
Search doesn't work in the add-on.

Using <Search> and then <Add keyword> pulls up a keyboard to enter a search term.  So far okay, but when pushing <Done> on the keyboard only a Keyword is created.

Clicking on the keyword opens an empty list.  The website returns results  (tested with working search term "lune"). 

It would be awesome if this could work since AnimeID-Hentai supports searching for anime-studio.

Url for searching is for example :

https://animeidhentai.com/?s=lune

and

https://animeidhentai.com/?s=lune+rex

**Comment by dobbelina** [comment]
Doublepost
