### ISSUE TITLE
vipporns.com not working

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#550]
This site is working fine on web browser but not in our add-on. Complete log is attached. Please look into it

https://paste.kodi.tv/mimapazubi

**Comment by dobbelina** [comment]
Works on Windows Kodi 18.9 Cumination v1.1.17

**Comment by imurreflection** [comment]
It's not working on my Android TV box..

**Comment by imurreflection** [comment]
It has started working again..closing the issue now
