### ISSUE TITLE
Xhamster not working

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#555]
On every link, getting " could not find the supported host" error.
Log is attached
HTTPS://PASTE.KODI.TV/IFUHIJAHUY

**Comment by dobbelina** [comment]
Non existent log, you have to click the save symbol up in the right corner that looks
like a diskette.
Kodi 18.9 on Windows have no issue with Xhamster.

**Comment by imurreflection** [comment]
On Android, there is no such option available. Surprisingly, whenever, I have tried, I am getting log files like this one only. If someone else with Kodi 19 on Android can confirm please

**Comment by Gujal00** [comment]
Cumination 1.1.18 running on Kodi 19.1 Android plays xhamster videos fine

**Comment by imurreflection** [comment]
Thank you @gujal00.. Though, it's not working for me,there is no reason to disbelief you. Closing the issue now.

**Comment by imurreflection** [comment]
Extremely sorry to reopen this issue again but this site is not working even after fresh install. I tried on Kodi 18.9 and 19.1 fresh installs on my Android TV box and Fresh install of Kodi 19.1 on my Android TV.  I know that we don't have any issue on Windows and also on Kodi 19.1 64 bit but I have an Android TV box running 10.1 with 4gb ram and 32 GB ram running 32 bit. On Android 18.9, the site doesn't even show any listings and on 19.1 'could not find supported list" error on every link. Please extend your expertise and let me know what I can do to get this site back.

**Comment by Gujal00** [comment]
@imurreflection post a full debug log properly so that it can be analysed
Every log you log you have posted so far is empty

As I said it works fine on Android 9 aarch64 kodi 19.1

**Comment by imurreflection** [comment]
@gujal00 I am not getting any log for this error. Only the error " could not find supported host' . Please advise what shall I do. I can post a video if required or some screenshots.

**Comment by Gujal00** [comment]
post full debug log, videos are of no use

**Comment by imurreflection** [comment]
Thank you so much for guidance. I enabled debugging,followed your instructions and here is the link I have got HTTPS://PASTE.KODI.TV/EWAFONIGOZ

**Comment by imurreflection** [comment]
Dear @Gujal00.
Thank you so much for guidance. I enabled debugging,followed your instructions and here is the link I have got HTTPS://PASTE.KODI.TV/ULUYOHAWAK

For some reasons, the link above takes to only paste.kodi.tv only which is obviously blank but if we just paste /ULUYOHAWAK, you will get the full log. Kindly have a look and advise

For your convenience, I have also attached the original log available on kodi. Please see the attachment.

[kodi.log](https://github.com/dobbelina/repository.dobbelina/files/6731820/kodi.log)

**Comment by dobbelina** [comment]
Imurreflections log: https://paste.kodi.tv/defujiguqi.kodi

**Comment by Gujal00** [comment]
There is nothing relating to xhamster, or any failures in that log. Did you try accessing xhamster when the debug was running? In cumination setting, cache, clear cache, and then do the debug capture again and try to access xhamster

**Comment by imurreflection** [comment]
Hi Gujal00, I did as you instructed and here is the log it has generated

Https://paste.kodi.tv/izehaxenol

Please use /izehaxenol after paste.kodi.tv to get the log

The old log and this one has xhamster saying csettings manager>requested settings (xhamsterequal) was not found 
Csettings>requested setting(xhamsterlen) wa s not found.
Let me know if you need anything else.

**Comment by Gujal00** [comment]
your log shows you are trying to go to xhamster12.desi
`https://xhamster12.desi/videos/asian-amateur-208-xhn7Vl8`
cumination is coded for xhamster2.com. Have no idea you are going to a different site, and it may not work because resolveurl does not know about xhamster12.desi

**Comment by imurreflection** [comment]
@gujal00... I really have no idea why the site is taking me to xhamster.desi...it was the same link in Cumination working fine earlier. Please advise if this incorrect redirection can be resolved or shall I close this issue?

**Comment by Gujal00** [comment]
I have pushed an update to ResolveURL, see if it is working for you now

**Comment by imurreflection** [comment]
@gujal00.

Thank you so much my friend. This is working fine now. Closing the issue now..best regards
