### ISSUE TITLE
XXX Streams (watch) list videos but doesn't play any of them

### ISSUE THREAD

**Issue by fapbird69** [dobbelina/repository.dobbelina#556]
### Bug reports:

XXX Streams (watch) list videos but doesn't play any of them

### OS environment
MacOS Monterey 12.0 beta
Windoze 10 Pro 20H2

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
In progress, I'll add it up today if new born let me so :D

**Comment by Gujal00** [comment]
No idea who added this site, but wordpress sites like this with no contact information or DMCA policy should not be in Cumination

Anyway the site is not hosting any videos now, so doesnt work in cumination. You can check in the browser that there are no videos hosted on this wordpress site

**Comment by fapbird69** [comment]
thanks!!  Gujal00 a lot for the promt response 

As per https://theporndude.com/1702/xxxstreamseu seem some connection with old xxxstreams.eu 

Please forget this bug and I'm gonna close it now
