### ISSUE TITLE
Spankbang Error again

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#557]
Not sure what's going wrong but spankbang is not working again..please check the log below:
https://paste.kodi.tv/ipuwuzevom

**Comment by Gujal00** [comment]
clear cache in cumination settings and capture the debug log again

**Comment by imurreflection** [comment]
@gujal00. I followed your instructions and recaptured the log with Android debugging enabled. Please see the link:https://paste.kodi.tv/aqagufucot

**Comment by Gujal00** [comment]
Can't see the url being pulled in the debug log, looks like it is coming from cache. Anyway, this works fine on Kodi 19.1 on Android, so again specific to your setup. Cant do much when the error is not visible on the debug log

**Comment by imurreflection** [comment]
@gujal00. All these issues started happening after the new update. I just copied utils.py provided earlier by you in designated folder and the site is working just fine now. However, some prominent sites are not working like beeg,eporner for which I will raise separate issues with proper debugging log later. Thank you for your support.

**Comment by Spanktacular** [comment]
I have the same "too slow to respond" error from spankbang with Kodi 19.1 and current Cumination. It is not isolated to imurreflection's setup.

Android TV stock running Kodi 19.1 and current Cumination.

**Comment by Gujal00** [comment]
As mentioned before it is an issue with Android build of Kodi, the workaround that I did seems to work on 64bit Android, but not on 32bit. Cant do much until Kodi for Android is released with updated OpenSSL

**Comment by imurreflection** [comment]
Thank you.  This is indeed system limitation. Closing the issue now
