### ISSUE TITLE
Bongacams not working

### ISSUE THREAD

**Issue by brokerrnc** [dobbelina/repository.dobbelina#558]
### Bug reports:

Can't get bongacams vids to load, tried on linux, android, and windows boxes

### OS environment
linux mint, 1.1.18

Logfile here: https://paste.kodi.tv/honozipudu.kodi

**Comment by neelrock** [comment]
Same here, it stopped working a few days ago. 
Note it also doesn't work anymore in Cumination addon.
OS: win10 
Kodi: 18.9

Debug log: https://paste.kodi.tv/sobojejime.kodi

**Comment by dobbelina** [comment]
Should be fixed in v1.1.19, closing thread.
