### ISSUE TITLE
Resolve URL issue

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#562]
Hi @Gujal00, xhamster12.desi the update which you pushed to resolve URL is not working. Again, on every link it says could not find the supported link. Also, I am not getting "playing from xhamster12.desi" prompt which I was getting earlier. I checked the resolve URL settings also but could not find xhamster12.desi. also,I checked your repo but I don't see anything in change log..has this update been removed? Can you please check.

**Comment by imurreflection** [comment]
Gujal00. I just found that site is now redirecting to xhamster13...is there anyway I can manually update resolve URL for my own use?

**Comment by Gujal00** [comment]
Check with smr.xxx v2.1.6 and report back if still issues.

**Comment by imurreflection** [comment]
Please advise where I can install smr.xxx v2.1.6 from? Is it available in your repo?

**Comment by Gujal00** [comment]
Tou will get automaatic update if you have dobbelina repo installed.
Auto updates are only checked once every 24 hours, so you may have to go to recently updated tab and from left menu check for updates to initiate a manual check

**Comment by imurreflection** [comment]
I have dobbelina repo but I did not get this update. I am getting could not find this video error on every video. Is there anyway I can manually update this?

**Comment by Gujal00** [comment]
Script modules dont announce when they get updated in Matrix.
Goto Settings -> System -> Addons -> Manage Dependencies
Look for `Adult Resolver SMR Extension` and its version number. It should be `2.1.16`, if not select the addon and select update.

**Comment by imurreflection** [comment]
Thanks for this. I updated the resolver to 2.1.16 and this is working fine. Hope, this stupid site now won't redirect to 14,15,16 etc. Thanks again and closing the issue now.
