### ISSUE TITLE
ipornvideos

### ISSUE THREAD

**Issue by deanogers** [dobbelina/repository.dobbelina#564]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**If it's a site addition request, add url below**

**Comment by darktones123** [comment]
I agree with Deanogers. I only use UWC now for Ipornvideos and sxyprn (yourporn). Its a shame that sxyprn thumbnails are not working. Your help is always appreciated!

**Comment by 12asdfg12** [comment]
no contact information and DMCA policy, will not be added

**Comment by darktones123** [comment]
Why was it okay then for Ultimate Whitecream to have ipornvideos and not for Cumination? 
Thanks

**Comment by 12asdfg12** [comment]
You can read about the reasons here #559
