### ISSUE TITLE
Aag Maal  categories error 

### ISSUE THREAD

**Issue by plsharevme** [dobbelina/repository.dobbelina#567]
### Bug reports:

Aag Maal categories error, please fix it, it contain alot of good stuff.

appreciate you make this addon so great  !!

### OS environment
What OS, Device, version etc

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Any bugreports without logfile will be deleted.

**Comment by dobbelina** [comment]
@plsharevme 
The site has problems with the web server, there are no categories to choose from.
Use search until they fix it.

**Comment by plsharevme** [comment]
> @plsharevme
> The site has problems with the web server, there are no categories to choose from.
> Use search until they fix it.

okay, appreciate your addons so much.
