### ISSUE TITLE
PornTrex search

### ISSUE THREAD

**Issue by EvelK1203** [dobbelina/repository.dobbelina#569]
**Is your feature request related to a problem? Please describe.**

Searching more than 1 word doesn't return expected values. UWC handled this well for PornTrex. Example, search for Sash Grey returns various vids that have Sasha or Grey but not Sasha AND Grey. 
![search](https://user-images.githubusercontent.com/72991316/126051884-084645c3-b744-489c-8517-7b66d8da398b.PNG)

**Describe the solution you'd like**

**If it's a site addition request, add url below**

**Comment by 12asdfg12** [comment]
The results are correct but the order is wrong. In the next version, the sort order will be changed from "latest" to "most relevant".
