### ISSUE TITLE
sxyprn and K18

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#57]
Hi, please check. sxyprn is not working again ...the error again points to cdn5. Nothing happens when you click a link.

k18 has strange issue. When you click on any link a promo video of 9-10 seconds by brazzers is played and then it stops.

**Comment by DJMix-I-Can** [comment]
For sxyprn, change "cdn4" to "cdn6" on line 158

**Comment by imurreflection** [comment]
Thank you so much mate. Can you please check K18 issue also

**Comment by imurreflection** [comment]
Hi DJMix-I-Can, I just changed the line as suggested to cdn6 but unfortunately the videos are still not playing. Getting CCurlfile 404 error, Failed to open source and CvideoPlayer OpeninputStream error.  If its working at your end can you please post the .py file here.

**Comment by DJMix-I-Can** [comment]
> 
> 
> Hi DJMix-I-Can, I just changed the line as suggested to cdn6 but unfortunately the videos are still not playing. Getting CCurlfile 404 error, Failed to open source and CvideoPlayer OpeninputStream error. If its working at your end can you please post the .py file here.


[sxyprn.zip](https://github.com/dobbelina/repository.dobbelina/files/3366386/sxyprn.zip)

**Comment by imurreflection** [comment]
I used your file and replaced it with original one. However, the result was same. Videos are not playing. Please advise.

**Comment by DJMix-I-Can** [comment]
> 
> 
> I used your file and replaced it with original one. However, the result was same. Videos are not playing. Please advise.

You're correct, they changed it again. It's now CDN7. I'm trying to learn Python and tried to add CDN to CDN9, so if they change it again, it would be detected BUT received the following error. "re.IGNORECASE).findall(html)[0].replace('\/','/').replace('/cdn/','/cdn1/','/cdn2/','/cdn3/','/cdn4/','/cdn5/','/cdn6/','/cdn7/','/cdn8/','/cdn9/')
                                            TypeError: replace() takes at most 3 arguments (10 given)"
I know there's a way to write it out so as I won't have to put each argument manually but I'm not even close to having the knowledge to do it. I play with Python once in a blue moon so I could try to learn it. I'm still confused with a lot of stuff but would love to learn it.  Sorry, I couldn't help.

**Comment by imurreflection** [comment]
No mate you have been of great help, even I am learning it and I also found that the site is now using CDN7. I updated the .py file and this is now working fine. Python is slightly complicated but really interesting. Hope, we are able to contribute more in near future. Here is the updated .py file. 
[sxyprn.zip](https://github.com/dobbelina/repository.dobbelina/files/3366508/sxyprn.zip)

**Comment by WhitecreamDev** [comment]
Try something like this (untested):

`@utils.url_dispatcher.register('652', ['url', 'name'], ['download'])
def yourporn_play(url, name, download=None):
    utils.kodilog(url)
    url = url.replace('https://yps.to/','https://sxyprn.com/')
    html = utils.getHtml(url, '')
    videourl = re.compile('''data-vnfo='{".+?":"(.+?)"''', re.DOTALL | re.IGNORECASE).findall(html)[0].replace('\/','/')
    match = re.search('src="(/js/main[^"]+)"', html, re.DOTALL | re.IGNORECASE)
    if match:
        result = match.group(1)
        jsscript = utils.getHtml('https://sxyprn.com%s' % result, url)
        replaceint = re.search(r'tmp\[1\]\+= "(\d+)";', html, re.DOTALL | re.IGNORECASE).group(1)
        videourl.replace('/cdn/', '/cdn%s/' % replaceint)
    else:
        videourl = videourl.replace('/cdn/','/cdn7/')
    videourl='https://sxyprn.com'+videourl
    if download == 1:
        utils.downloadVideo(videourl, name)
    else:
        iconimage = xbmc.getInfoImage("ListItem.Thumb")
        listitem = xbmcgui.ListItem(name, iconImage="DefaultVideo.png", thumbnailImage=iconimage)
        listitem.setInfo('video', {'Title': name, 'Genre': 'Porn'})
        xbmc.Player().play(videourl, listitem)`

**Comment by dobbelina** [comment]
Hi WhitecreamDev,

Thanks for the contribution, however it errors out when i try it?
What about this approach,(from daftsex.py):
`def FindServer(video, vp):
    crazycloud_list = ['13-2','14-2','15-2','16-2','17-2','20-2','13-1','14-1','15-1','16-1','17-1','20-1','13-3','16-3','17-3','20-3','13-4','16-4','13-5','13-6']
    daxab_list = ['11-1','11-2','11-3','11-4','12-1','12-4','12-5','19-1','19-2','21-1','21-2','25-1','25-2','27-1','27-2','29-1','36-1','36-2','38-1','38-2','38-3','43-1','45-1','46-1','47-1','48-1','49-1','49-2','49-3','49-4','49-5','49-6','49-7','50-1','51-1','52-1','53-1','54-1','55-1','56-1','57-1','58-1','59-1','60-1']
    i = 1
    for srv in crazycloud_list:
	server = 'https://psv' + srv + '.crazycloud.ru/videos/'
        vp.progress.update(25 + i, "", "Searching on crazycloud.ru ... " + srv, "")
    	try:
            code = urllib2.urlopen(server + video).getcode()
            if code == 200:
               	return (server + video)
        except:
	    i = i+1
    daxab_list.reverse()
    for srv in daxab_list:
        server = 'https://psv' + srv + '.daxab.com/videos/'
        vp.progress.update(25 + i, "", "Searching on daxab.com ... " + srv, "")
    	try:
            code = urllib2.urlopen(server + video).getcode()
            if code == 200:
               	return (server + video)
        except:
	    i = i+1`
This is above my head unfortunately, but that code loops thru a list of servers....

**Comment by WhitecreamDev** [comment]
Sorry, small mistake. Now it does work :)
That's what you get for doing it out of your head without testing.
So i've edited my post above, and i've tested it.

I'm not a big fan of stuff like 'hammering' a server for a working link. At least built in a few ms wait or something, so you aren't ddosing the server :)
I'd rather figure out in the javascript (or something) how they get to the working videourl.

**Comment by dobbelina** [comment]
Awesome WhitecreamDev, thanks!
Now it works.
Will update addon.
