### ISSUE TITLE
Cant restore my cumination favorites 

### ISSUE THREAD

**Issue by losthelp815** [dobbelina/repository.dobbelina#572]
Having issues trying to restore my backed-up favorites keeps giving me an invalid backup error. Have tried multiple times and nothing works. Have tried Kodi v18 all the way to Kodi 19a. Any help would be appreciated 

Nivida Shield K1 Android

**Comment by ErosVece** [comment]
Try disabling the compressed backup option in the settings.
Manually unpack the backup you have now, and try that file to restore.
