### ISSUE TITLE
Website request 

### ISSUE THREAD

**Issue by dirtman69** [dobbelina/repository.dobbelina#574]
Can you add https://femefun.com please

**Comment by ErosVece** [comment]
Well, this seems like a site with beastiality. and that's illegal in some (most?) countries/states.
So this won't be added.

We can't stop anyone making a custom site plugin for it though (https://github.com/dobbelina/repository.dobbelina/issues/407)

**Comment by dirtman69** [comment]
Ok when I click install custom site it takes me to home folder.

How do I add a site file
