### ISSUE TITLE
Daft sex can not find rharri round and many more 

### ISSUE THREAD

**Issue by xerel89** [dobbelina/repository.dobbelina#576]
### Bug reports:

Please replace this line with a brief summary of your issue 

### OS environment
What OS, Device, version etc

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Any bugreports without logfile will be deleted.

**Comment by Gujal00** [comment]
bug report needs a full debug log without which it cannot be fixed

The search works fine on Windows 10 + Kodi 19.1

**Comment by xerel89** [comment]
I don't get a bug report, just no scenes are displayed

**Comment by Gujal00** [comment]
Yeah you gave same answer 3 months ago
Learn how to create and upload debug log here https://kodi.wiki/view/Log_file

**Comment by dobbelina** [comment]
No log file, closing issue.
