### ISSUE TITLE
Files hosted by Streamtape being blocked?

### ISSUE THREAD

**Issue by tetzy** [dobbelina/repository.dobbelina#577]
For the past 48 hours or so, every file I attempt to download hosted by streamtape gets me the same 7.61mb file of this obnoxious Chinese guy telling me I've attempted to download a streamtape file from a third-party site and to use streamtape instead. 

"Viral Videos Porno" files are particularly hard hit - streamtape must be very popular.

Is there anything that can be done to circumvent this garbage or are we going to lose access to streamtape hosted files?

**Comment by Gujal00** [comment]
@tetzy It was fixed in the ResolveURL update released on 12th Aug. Is this still happening to you?
