### ISSUE TITLE
Beeg not working

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#578]
Nothing happens when you click any link. Here is the debug log
HTTPS://PASTE.KODI.TV/ELITAHEWAJ  

Please paste ELITAHEWAJ manually to get the log

**Comment by dobbelina** [comment]
@imurreflection 
Will be fixed in the next release https://github.com/dobbelina/repository.dobbelina/commit/b4c2897ca4fa8aa4c929dd5215e574b380e9268e
