### ISSUE TITLE
Please fix TubePornClassic

### ISSUE THREAD

**Issue by stevieland58** [dobbelina/repository.dobbelina#579]
Please fix this site, my wrist is begging to heal!

**Comment by dobbelina** [comment]
Site works fine for me on Kodi 18.9 and Windows.

**Comment by stevieland58** [comment]
> Site works fine for me on Kodi 18.9 and Windows.

Categories don't work on Kodi 18.9 Android.

**Comment by dobbelina** [comment]
Categories will be fixed in the next release https://github.com/dobbelina/repository.dobbelina/commit/324eafa08bc33d21a8e0ab27a9babbd7645bbe80

**Comment by stevieland58** [comment]
👏🏼
