### ISSUE TITLE
Javwhore not working.

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#58]
Hi,

The site is working fine on PC and Mobile but in our addon when you click on any video link, it takes you to the quality selection option and then nothing happens. This is the first time I have seen this site going down. I tried finding the cause but I was not able to find javwhores.py under sites. Can you please fix this site as it is the only JAV site we have.

**Comment by DJMix-I-Can** [comment]
It's in the porntrex.py file.

**Comment by LeWaxMar** [comment]
Same issue here.

**Comment by 12asdfg12** [comment]
In the latest version, they encrypted the video urls.
This is the java code  used in Jdownloader to decrypt this urls.
We need somebody, who can convert this 2 functions (decryptHash and calcSeed) from java to python.


```
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;



public class Main{

     public static void main(String []args){
        System.out.println(decryptHash("function/0/http://www.camwhores.tv/get_file/102/98461210780aaa3efce434ff090368ac8ddd48616f/4833000/4833749/4833749.mp4/", "$657253421683940", "16"));
        System.out.println(decryptHash("function/0/https://mangovideo.pw/get_file/7/5c479f750742d5ff9a0f23ac3d551080b8146000a5/18000/18291/18291.mp4/", "$569054218774095", "16"));
        System.out.println(decryptHash("function/0/https://www.javwhores.com/get_file/6/ce8bb6da86198a56f42769801b76c4b4ff0d752a90/43000/43947/43947.mp4/?br=824", "$572446518886012", "16"))
        }


    public static String decryptHash(final String videoUrl, final String licenseCode, final String hashRange) {
        String result = null;
        List<String> videoUrlPart = new ArrayList<String>();
        Collections.addAll(videoUrlPart, videoUrl.split("/"));
        // hash
        String hash = videoUrlPart.get(7).substring(0, 2 * Integer.parseInt(hashRange));
        String nonConvertHash = videoUrlPart.get(7).substring(2 * Integer.parseInt(hashRange));
        String seed = calcSeed(licenseCode, hashRange);
        String[] seedArray = new String[seed.length()];
        for (int i = 0; i < seed.length(); i++) {
            seedArray[i] = seed.substring(i, i + 1);
        }
        if (seed != null && hash != null) {
            for (int k = hash.length() - 1; k >= 0; k--) {
                String[] hashArray = new String[hash.length()];
                for (int i = 0; i < hash.length(); i++) {
                    hashArray[i] = hash.substring(i, i + 1);
                }
                int l = k;
                for (int m = k; m < seedArray.length; m++) {
                    l += Integer.parseInt(seedArray[m]);
                }
                for (; l >= hashArray.length;) {
                    l -= hashArray.length;
                }
                StringBuffer n = new StringBuffer();
                for (int o = 0; o < hashArray.length; o++) {
                    n.append(o == k ? hashArray[l] : o == l ? hashArray[k] : hashArray[o]);
                }
                hash = n.toString();
            }
            videoUrlPart.set(7, hash + nonConvertHash);
            for (String string : videoUrlPart.subList(2, videoUrlPart.size())) {
                if (result == null) {
                    result = string;
                } else {
                    result = result + "/" + string;
                }
            }
        }
        return result;
    }

    public static String calcSeed(final String licenseCode, final String hashRange) {
        StringBuffer fb = new StringBuffer();
        String[] licenseCodeArray = new String[licenseCode.length()];
        for (int i = 0; i < licenseCode.length(); i++) {
            licenseCodeArray[i] = licenseCode.substring(i, i + 1);
        }
        for (String c : licenseCodeArray) {
            if (c.equals("$")) {
                continue;
            }
            int v = Integer.parseInt(c);
            fb.append(v != 0 ? c : "1");
        }
        String f = fb.toString();
        int j = f.length() / 2;
        int k = Integer.parseInt(f.substring(0, j + 1));
        int l = Integer.parseInt(f.substring(j));
        int g = l - k;
        g = Math.abs(g);
        int fi = g;
        g = k - l;
        g = Math.abs(g);
        fi += g;
        fi *= 2;
        String s = String.valueOf(fi);
        String[] fArray = new String[s.length()];
        for (int i = 0; i < s.length(); i++) {
            fArray[i] = s.substring(i, i + 1);
        }
        // f = "" + f;
        int i = Integer.parseInt(hashRange) / 2 + 2;
        StringBuffer m = new StringBuffer();
        for (int g2 = 0; g2 < j + 1; g2++) {
            for (int h = 1; h <= 4; h++) {
                int n = Integer.parseInt(licenseCodeArray[g2 + h]) + Integer.parseInt(fArray[g2]);
                if (n >= i) {
                    n -= i;
                }
                m.append(String.valueOf(n));
            }
        }
        return m.toString();
    }
}

```

The result:


```
http://www.camwhores.tv/get_file/102/0a9848af8fe3cf116409062c03e47aa38ddd48616f/4833000/4833749/4833749.mp4
https://mangovideo.pw/get_file/7/40c9f59f754a23058d3f1552df00a7c7b8146000a5/18000/18291/18291.mp4
https://www.javwhores.com/get_file/6/746f84c96b807b686816a512e9acbdb4ff0d752a90/43000/43947/43947.mp4/?br=824
```

**Comment by WhitecreamDev** [comment]
Converting it is really easy, try it yourself as a challenge.
To learn more about Python and sharpen your skills.
Trust me, it's really rewarding if you'd figure this out yourself.

To give you a start, here's a part of Java and same code as Python

```
public static String calcSeed(final String licenseCode, final String hashRange) {
    StringBuffer fb = new StringBuffer();
    String[] licenseCodeArray = new String[licenseCode.length()];
    for (int i = 0; i < licenseCode.length(); i++) {
        licenseCodeArray[i] = licenseCode.substring(i, i + 1);
    }
    for (String c : licenseCodeArray) {
        if (c.equals("$")) {
            continue;
        }
        int v = Integer.parseInt(c);
        fb.append(v != 0 ? c : "1");
    }
    String f = fb.toString();
    int j = f.length() / 2;



def calcSeed(licenseCode, hashRange):
    licenseCodeArray = list(licenseCode)
    f = licenseCode.replace('$', '').replace('0', '1')
    j = len(f) / 2
```

**Comment by LeWaxMar** [comment]
> Converting it is really easy, try it yourself as a challenge.
> To learn more about Python and sharpen your skills.
> Trust me, it's really rewarding if you'd figure this out yourself.
> 
> To give you a start, here's a part of Java and same code as Python
> 
> ```
> public static String calcSeed(final String licenseCode, final String hashRange) {
>     StringBuffer fb = new StringBuffer();
>     String[] licenseCodeArray = new String[licenseCode.length()];
>     for (int i = 0; i < licenseCode.length(); i++) {
>         licenseCodeArray[i] = licenseCode.substring(i, i + 1);
>     }
>     for (String c : licenseCodeArray) {
>         if (c.equals("$")) {
>             continue;
>         }
>         int v = Integer.parseInt(c);
>         fb.append(v != 0 ? c : "1");
>     }
>     String f = fb.toString();
>     int j = f.length() / 2;
> 
> 
> 
> def calcSeed(licenseCode, hashRange):
>     licenseCodeArray = list(licenseCode)
>     f = licenseCode.replace('$', '').replace('0', '1')
>     j = len(f) / 2
> ```

This code should be added to porntrex.py file?

**Comment by 12asdfg12** [comment]
@WhitecreamDev 
You're right, it was much easier to convert, than I thought when I first saw the code.
here is the converted code:
```

def decryptHash(videoUrl, licenseCode, hashRange):
    result = ''
    videoUrlPart = videoUrl.split('/')
    hash = videoUrlPart[7][:2*int(hashRange)]
    nonConvertHash = videoUrlPart[7][2*int(hashRange):]
    seed = calcSeed(licenseCode, hashRange)
    if seed != '' and hash !='':
        for k in range(len(hash)-1, -1, -1):
            l = k
            for m in range(k,len(hash)):
                l += int(seed[m])
            l = l % len(hash)
            n = ''
            for o in range(0, len(hash)):
                n = n + hash[l] if o == k else n + hash[k] if o == l else n + hash[o]
            hash = n
        videoUrlPart[7] = hash + nonConvertHash
        videoUrlPart.pop(0)
        videoUrlPart.pop(0)        
        result = '/'.join(videoUrlPart)   
    return result        


def calcSeed(licenseCode, hashRange):
    f = licenseCode.replace('$', '').replace('0', '1')
    j = int(len(f) / 2)
    k = int(f[:len(f)-j])
    l = int(f[j:])
    g = abs(l - k)
    fi = 4*g
    i = int(int(hashRange) / 2 + 2)
    m = ''
    for g2 in range (0,j+1):
        for h in range (1,5):
            n =  int(licenseCode[g2 + h]) + int(str(fi)[g2])
            if n>=i:
                n -= i	
            m = m + str(n)
    return m
```

And the updated files for javwhore, mangoporn and speedporn:
[mangoporn.zip](https://github.com/dobbelina/repository.dobbelina/files/3374004/mangoporn.zip)
[porntrex.zip](https://github.com/dobbelina/repository.dobbelina/files/3374005/porntrex.zip)
[speedporn.zip](https://github.com/dobbelina/repository.dobbelina/files/3374006/speedporn.zip)

**Comment by imurreflection** [comment]
Thank you so much friends. I checked and found that the sites are working fine now. You guys are great.

**Comment by dobbelina** [comment]
Thanks 12asdfg12,

Awesome work!
All changes are now in plugin.video.uwc-1.1.87

**Comment by LeWaxMar** [comment]
Thanks for the update!

**Comment by jdoedev123** [comment]
Thanks, 12asdfg12 and WhiteCreamDev, I never could trace where the Java decrypt algorithm came from it just showed up uncommented in JDownloader a couple years ago.

**Comment by jdoedev123** [comment]
Minor point for coders. This algorithm is used in a few different sites, should we move the algorithm up a level and out of the site code? Perhaps in a separate Python file (kvs.py ?) under resources/lib or into the larger utils.py ?
I am testing as kvs.py but am fine with it in utils.py as well.  Not good practice to have redundant code.

**Comment by dobbelina** [comment]
Hi jdoedev123,

I'm not a coder, but it sounds reasonable to do with snippets/algorithms
that are used by many sites.
Reduces redundancy and makes any changes global, instead of having to edit
lots of different site files.
I actually managed to make a small improvement to default.py myself,
The "**If You Have A Website Fix**" banner now opens the default browser
and takes you here when you click on it.
One of these days i'm gonna dedicate some time to learn more python stuff.

**Comment by jdoedev123** [comment]
dobbelina,
Here are versions of 12asdfg12 Python code with the decrypt algorithm moved into it's own file for your next version drop.
Please place the kvs.py file in the lib directory ( resources/lib ).
[kvs.py.zip](https://github.com/dobbelina/repository.dobbelina/files/3389435/kvs.py.zip)

The site code goes in the usual location in the site directory ( resources/lib/sites ).
[mangoporn.py.zip](https://github.com/dobbelina/repository.dobbelina/files/3389436/mangoporn.py.zip)
[porntrex.py.zip](https://github.com/dobbelina/repository.dobbelina/files/3389438/porntrex.py.zip)
[speedporn.py.zip](https://github.com/dobbelina/repository.dobbelina/files/3389439/speedporn.py.zip)

**Comment by dobbelina** [comment]
Thanks jdoedev123!
Awesome as always.
Will incorporate it in the next addon update.
Probably tomorrow as I'm kinda busy elsewhere today.

**Comment by 12asdfg12** [comment]
Good observation  jdoedev123!
1. I modified the function play_from_html from utils.py to detect  and decrypt urls which begins with 'function/0/'
Now play_from_html or play_from_site_link functions can be used to play this encrypted url's.
2. I added the posibility to add accounts in uwc setings for porntrex and javwhore, for playing private videos.
[resources.zip](https://github.com/dobbelina/repository.dobbelina/files/3389702/resources.zip)

**Comment by jdoedev123** [comment]
No problem, good solution 12asdfg12. It felt a bit strange, in my professional life, I usually write Alpha and Beta code and someone else does the code cleanup and refactoring. But my buddy that usually does that now works for Google full time.

**Comment by imurreflection** [comment]
@12asdfg12 ...I heard somewhere you saying that you are not a developer? No sir, you are much more than that. The feature you have incorporated for adding logon information to view private videos hasn't been implemented by anyone so far and it's working flawlessly. May I request you to kindly consider adding those jav sites mentioned in my other thread. Have a blissful day !!!
