### ISSUE TITLE
Beeg Search

### ISSUE THREAD

**Issue by Kodionpi** [dobbelina/repository.dobbelina#586]
Is it possible to get a search function for beeg? Thanks in advance!

**Comment by Gujal00** [comment]
There is no generic search on beeg site. the only search available on site is for profiles

**Comment by imurreflection** [comment]
@gujal00. I just checked the site on my mobile browser and found that Search function is available for any keywords and it's working just fine
 Please advise if you need screenshot

**Comment by imurreflection** [comment]
Hi @dobbelina..search function is available on this site and it was earlier informed by @gujal00 that it would be added soon. Can you please look into this and re-open this issue?
