### ISSUE TITLE
Beeg is broken again

### ISSUE THREAD

**Issue by Kodionpi** [dobbelina/repository.dobbelina#589]
### Bug reports:

Beeg is not working at all

### OS environment
Libreelec, Raspberry Pi 2Model b

[kodi.log](https://github.com/dobbelina/repository.dobbelina/files/7094668/kodi.log)

**Comment by Gujal00** [comment]
Python 2.7 Kodi 18.9 issue.

**Comment by brainwaster** [comment]
Beeg now plays but the videos dont fully play. For exsmple if a vid is 40 monsit will play about 11 mins of it, unless all the video lengths in the title are being reported incorrectly

I'm running Libreelec 9.2.6 (Kodi 18.9)

**Comment by 12asdfg12** [comment]
Some videos are incomplete on the website.
In the next version, the start and end times of the video will be added to the names of incomplete videos.
