### ISSUE TITLE
ParadiseHill

### ISSUE THREAD

**Issue by tarapiatapioca** [dobbelina/repository.dobbelina#59]
ParadiseHill is empty on version 1.1.85

**Comment by imurreflection** [comment]
Hi, I checked and found that in latest version 1.1.86, the site is working fine. However, only 1 link can be seen with search not working. However, that link is playable.

**Comment by dobbelina** [comment]
ParadiseHill marked broken.

**Comment by tarapiatapioca** [comment]
Thanks

**Comment by 12asdfg12** [comment]
[paradisehill.zip](https://github.com/dobbelina/repository.dobbelina/files/3393001/paradisehill.zip)

**Comment by tarapiatapioca** [comment]
> [paradisehill.zip](https://github.com/dobbelina/repository.dobbelina/files/3393001/paradisehill.zip)

TY,  it works perfectly

**Comment by dobbelina** [comment]
Thanks 12asdfg12!

Will use for next update of the addon.

**Comment by dobbelina** [comment]
closing issue.
