### ISSUE TITLE
Porntrex thumbails not matching the file name

### ISSUE THREAD

**Issue by tetzy** [dobbelina/repository.dobbelina#591]
For the past few days, Porntrex thumbnails have not matched the title name - see below:

![Screenshot from 2021-09-03 00-40-13](https://user-images.githubusercontent.com/59111079/131961989-9d743420-41ba-4d24-9ee9-348a00ff8961.jpg)

I'm not sure if this is an issue for every filename/thumbnail, but the error seems to be pretty widespread. Is this a Porntrex issue, or something that can be fixed in Cumination?

**Comment by seitman** [comment]
Same here. Thumbs on porntrex site are working fine, so probably there is a hick up somewhere in Cumination

**Comment by dobbelina** [comment]
Will be fixed in the next release https://github.com/dobbelina/repository.dobbelina/commit/6dda8bb74548ec5a7e2775bd695e1210303dbd7b
