### ISSUE TITLE
Site Addition Request- javhoho.com

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#592]
Please add this site
It is present in uwc and it has DMCA and contact information.

**Comment by dobbelina** [comment]
Will be in next release https://github.com/dobbelina/repository.dobbelina/commit/e8265854a31b6714ebc8967dc53488772c2dea05

**Comment by imurreflection** [comment]
Thank you for the addition. Waiting for the update. Closing the issue now.
