### ISSUE TITLE
Pornhub search

### ISSUE THREAD

**Issue by EvelK1203** [dobbelina/repository.dobbelina#593]
Pornhub searches are pretty random and don't match the same search done in a web browser. Searching 2 words strung together like "sashagrey" works for some searche3s but overall there is something strange with the search returns in the addon. I know it sounds vague but the search returns are pretty vague! :)

**Comment by 12asdfg12** [comment]
Change the sort order to most relevant in context menu:

![image](https://user-images.githubusercontent.com/48175015/132227164-3f94e709-5e2b-46e9-b1fb-f180b644859b.png)

**Comment by EvelK1203** [comment]
Perfect! Thanks
