### ISSUE TITLE
No Next Page Available- Viralvideosporno

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#594]
On the web browser, we can see 'Next' page in "Channels' categories example channel 'Blacked' has more than 10 pages but in our add-on, we can only see 1 page with 12 video and this is applicable for all 232 channels. Please fix this.
  
Also, just observed that search function also works in a similar manner with no next page and most search keywords example young,sexmex etc returning no results but the site has lots.

**Comment by dobbelina** [comment]
Will be fixed in the next release https://github.com/dobbelina/repository.dobbelina/commit/8ef76d3f71c9bcc01eefe0d5804ebb218d5de1a9
