### ISSUE TITLE
Playback Failed- vipporns

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#595]
Getting this error on every video. Log is attached.
https://paste.kodi.tv/gugerekado

**Comment by Gujal00** [comment]
may have been temporary issue on site. plays fine now

**Comment by imurreflection** [comment]
@gujal00. Just checked 5 videos and none of them played. Do you want another log for this?

**Comment by imurreflection** [comment]
Checked again..it's working now. Closing the issue now.
