### ISSUE TITLE
Site Request: Erome.com

### ISSUE THREAD

**Issue by Nash10se** [dobbelina/repository.dobbelina#596]
Site request: 
https://www.erome.com

DMCA:
https://www.erome.com/s/report

Contact:
https://www.erome.com/s/contact

Also, I tried to create a custom site. I downloaded the "crazyshit.com" zip file, and then went through all 4 files and replaced every mention of "crazyshit" or "Crazyshit" with "erome" or "Erome," and edited the filenames and such.  Trid to install it from inside Cumination, and got a "installation cancelled or invalid file" error. So if simply replacing "crazyshit" throughout the py file isn't sufficient, I have no idea how to create a custom channel. Any additional clues?

**Comment by dobbelina** [comment]
Will be in the next v1.1.38 release https://github.com/dobbelina/repository.dobbelina/commit/c72a02a8462dbc50927ca4f83c57c1484215a0fd
