### ISSUE TITLE
Site Request: www.herzogvideos.com & www.erogarga.com

### ISSUE THREAD

**Issue by neptunus123** [dobbelina/repository.dobbelina#597]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**If it's a site addition request, add url below**
www.herzogvideos.com
www.erogarga.com

**Comment by dobbelina** [comment]
Will be added in the next release https://github.com/dobbelina/repository.dobbelina/commit/366df8ec49d2ad9ffc680df7fe4d9a784f158310

**Comment by neptunus123** [comment]
I tried the erogarga.py from the custom site add menu. It automatically disables due to error: erogarga

Can you please verify it?

**Comment by 12asdfg12** [comment]
erogarga.py is not a custom site, it cannot be added to the custom sites.
Erogarga will be added in the next release.
