### ISSUE TITLE
More thumbnail mismatches 

### ISSUE THREAD

**Issue by tetzy** [dobbelina/repository.dobbelina#598]
Firstly, thank you for fixing the PornTrex thumbnail problem - it's nice to not have it working again. The problem seems to have spread,  thumbnails aren't matching the titles at "Viral Videos Porno" now.

Thanks.

**Comment by 12asdfg12** [comment]
looks ok to me. can you give an example?

**Comment by frankee123** [comment]
I also see that the view order which I have always had by newest is all out of sorts.

**Comment by frankee123** [comment]
Sorry, the order may actually be from spankbang and not porntrex.
