### ISSUE TITLE
Can’t update 

### ISSUE THREAD

**Issue by deanogers** [dobbelina/repository.dobbelina#6]
It won’t update to 1.1.66 as when you click update only brings up 1.1.65 can you help

**Comment by Sameer888** [comment]
Download the zip file first go to install zip file and then go to download folder were yu have that zip file then click on zip file your addon is updated simple

**Comment by jdoedev123** [comment]
Update does not work because this plugin is not in a standard kodi repository which kodi  can check for updates but instead in a GitHub depository more commonly used by code developers. It is still fairly easy to install manually if you follow Sameer's instructions above.

**Comment by deanogers** [comment]
I have tried that still says 1.1.65 in zip
