### ISSUE TITLE
Pornsland not working

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#60]
Hi, the site works fine on PC and Mobile browser but in our add-on same issue as javwhore had it. When you click,it takes you to the quality selection page but then nothing happens. Error says ccurl error 22. They also have a banner on their website saying that they have a new site 'Porner.tv'. I am not sure if site not working issue is linked with it. I checked and found that both sites are running parallel without any issue. Kindly have a look

**Comment by imurreflection** [comment]
I have found that the .py file from version 1.1.80 is working fine for this site. I manually updated it and it has no issue. Kindly update the addon.
[pornsland.zip](https://github.com/dobbelina/repository.dobbelina/files/3375817/pornsland.zip)

**Comment by imurreflection** [comment]
Hi Dobbelina, with so many changes on the addon, sometimes its troublesome collating. I have made all the changes and updated UWC is attached. These changes include - Fixes by 12asdfg12 and Whitecreamdev for javwhore,mangoporn and speedporn. Fix by DJMIX I can for sxyprn for change in content delivery network to 7 and pornsland working py file from the version 1.1.80. 
[plugin.video.uwc.zip](https://github.com/dobbelina/repository.dobbelina/files/3375848/plugin.video.uwc.zip)
Hope this helps.

**Comment by dobbelina** [comment]
Hi imurreflection,

Thanks for the help!
All changes is now in plugin.video.uwc-1.1.87

**Comment by dobbelina** [comment]
Closing issue.
