### ISSUE TITLE
Netflixporno can not load movie's

### ISSUE THREAD

**Issue by xerel89** [dobbelina/repository.dobbelina#601]
### Bug reports:

Please replace this line with a brief summary of your issue 

### OS environment
What OS, Device, version etc

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Any bugreports without logfile will be deleted.

**Comment by dobbelina** [comment]
Works on Windows kodi 18.9

**Comment by dobbelina** [comment]
No logfile, closing issue.
