### ISSUE TITLE
Site Addition Request sextb.net

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#603]
Hi,

Please add sextb.net. This is an excellent Jav site with great content in latest and uncensored categories. The site also has DMCA and Contact Information.

**Comment by ErosVece** [comment]
Team Cumination started with this, the beginning is done. Uncensored videos in the main site menu, and Censored in a subfolder.
Categories and more are coming in the future.

**Comment by imurreflection** [comment]
@erosvece..may I know of this is available in the latest release or will be released later?

**Comment by ErosVece** [comment]
Soon, check the latest commits.....or when a new version is pushed and Kodi updates itself

**Comment by imurreflection** [comment]
Thank you for the addition. Closing the request now.
