### ISSUE TITLE
Herexxx & Cambro won't load, Says site too slow.

### ISSUE THREAD

**Issue by steph09** [dobbelina/repository.dobbelina#610]
### Bug reports:

When I select Herexxx or Cambro it won't load the content & instead comes up with an error notification saying 'It looks like this website is too slow'.

### OS environment

Kodi 19 On Windows 10.

**Comment by dobbelina** [comment]
Works for me on both kodi 18.9 & 10 on my Windows rig.

**Comment by steph09** [comment]
Full log, I think.
https://paste.kodi.tv/omevesukay.kodi
