### ISSUE TITLE
Bubba Porn fix

### ISSUE THREAD

**Issue by DJMix-I-Can** [dobbelina/repository.dobbelina#62]

**Comment by DJMix-I-Can** [comment]
Here's a partial fix for Bubba Porn. The thumbnails (img) wasn't showing up on the main page and through out some directories. Categories loads up but without thumbnails, I believe the image file path is "data-src=" for the image but I couldn't figure it out on how to code it, as I'm still trying to learn python. I know this is an easy fix for a more experienced coder.   For those with advanced experience in coding,  could you refer a layman's term Python coding book or website. I've come across a couple of sites but they usually assume you know what certain codes means. For ex: after image source, what does the following mean, <img src="([^"]+)"[^<]+<[^"]+"([^"]+)">([^<]+)<'. I believe my problem is in interpreting line 77. When I add "data-" before src in line 77 like line 44, I lose the category directory. Thanks....
[bubbaporn.zip](https://github.com/dobbelina/repository.dobbelina/files/3388546/bubbaporn.zip)

**Comment by jdoedev123** [comment]
What you really want to start with is a tutorial on Regular Expressions aka RegEx.  That is the basis for most of the simpler updates.  Google "Python RegEx" gives you a good head start. That was my intro to the simpler fixes on UWC.

**Comment by DJMix-I-Can** [comment]
Thanks jdoedev123, that's exactly what I was reading on about two hours ago.

**Comment by jdoedev123** [comment]
So If you look at "view page source" you will see it includes sections something like:

`</div>
--
  | <div class="wrap-box-escena">
  | <div class="box-escena">
  |  
  |  
  |  
  | <a            href="/video/big-booty-slut-rides-different-kinds-of-dildos/"
  | data-stats-video-id="371298"
  | data-stats-video-name="Big booty slut rides different kinds of dildos"
  | data-stats-video-category=""
  | data-stats-list-name="Index"
  | data-stats-list-pos = "3">
  | <img
  | class="lazy"
  | src="/assets/images/loading-placeholder.gif"
  | data-src="https://pics.serviporno.com/thumbs/5/3/d/0/c/53d0c33ade0b65fefb41190fb8fa65c23b12daab.mp4/53d0c33ade0b65fefb41190fb8fa65c23b12daab.mp4-14.jpg"
  | alt="Big booty slut rides different kinds of dildos"
  | id='53d0c33ade0b65fefb41190fb8fa65c23b12daab.mp4'
  | class="thumbs-changer"
  | height="150px" width="175px" border=0 />
  | </a>
  |  
  | <h4><a href="/video/big-booty-slut-rides-different-kinds-of-dildos/">Big booty slut rides different kinds of dildos</a></h4>
  | <div class="duracion">05:00 min</div>
  |  
  | <span class="votar-escena"><small class="sprite ico-votar-escena"></small>82.00%</span>
  |  
  | <div class="clear"></div>
  | </div>
  | </div>
`

Lines 44 and 45 try to match parts to the variables (thumb videourl name duration)

`    match = re.compile('class="box-escena".+?data-src="([^"]+)".+?href="([^"]+)">([^<]+)<.+?duracion">([^<]+)<', re.DOTALL | re.IGNORECASE).findall(listhtml)
    for thumb, videourl, name, duration in match:`

As you can see it is trying to match the sections in parentheses () to variables  with the RegEx code . The rest is just helping to identify what to look for before and after and what to skip i.e. .+?

**Comment by dobbelina** [comment]
Congratulations to your first fix and thank you DJMix-I-Can!
I will incorporate it next time we update the addon.

**Comment by DJMix-I-Can** [comment]
> 
> 
> Congratulations to your first fix and thank you DJMix-I-Can!
> I will incorporate it next time we update the addon.

Thanks dobbelina but it's not a complete fix. Categories isn't showing images but are able to go into the directory.

**Comment by DJMix-I-Can** [comment]
> 
> 
> Congratulations to your first fix and thank you DJMix-I-Can!
> I will incorporate it next time we update the addon.

Thanks dobbelina, it wasn't completely fixed but after reading what @jdoedev123 sent me, I took another look at the code. Him telling me what .+? was helped me figure it out. So NOW Bubba Porn is fixed, everything is working. Thanks for your time. 
[bubbaporn.zip](https://github.com/dobbelina/repository.dobbelina/files/3390159/bubbaporn.zip)
jdoedev123

**Comment by dobbelina** [comment]
Thanks DJMix-I-Can,

I updated the addon with your final fix.
