### ISSUE TITLE
Set custom config or favorites path?

### ISSUE THREAD

**Issue by TarkusLV** [dobbelina/repository.dobbelina#622]
Would it be possible to set a custom path for either the config or at least the favorites file?  That way you could have the same config (or favorites) shared across multiple devices.  Super Favorites allows you to set a custom path, and it's nice being able to have the same Super Favorites across multiple devices, and if you edit it on one device, any changes show up everywhere.

**Comment by dobbelina** [comment]
Will be in the next 1.1.46 release https://github.com/dobbelina/repository.dobbelina/commit/c647112d837c193eafe88801bfbb019e6b1df1fa

**Comment by TarkusLV** [comment]
Awesome!  You guys rock!
