### ISSUE TITLE
Beeg play all parts

### ISSUE THREAD

**Issue by ginofalaci** [dobbelina/repository.dobbelina#624]
Hi, is it possible to make Beeg an read all part option like for ParadiseHill please?

**Comment by ginofalaci** [comment]
? Did you had the time to take a look? You can do something?

**Comment by ginofalaci** [comment]
What is wrong in my question that I can’t get any answer?

**Comment by ErosVece** [comment]
There is nothing wrong with your question.
This is a hobby for us, so people will or will not get an answer.
We all have a personal life, day jobs and much more....keeping up with every request or question isn't our top priority.

Answering your question, I would be possible to do add that, maybe a team member has time to do this....I can't say for sure. Like I said, this is a hobby for us.....if you want something done quickly, learn Python (https://www.sololearn.com/learning/1073) and fix it yourself and commit it here. Most of us started like that (we wanted something added/changed, so we learned how)

**Comment by ginofalaci** [comment]
> There is nothing wrong with your question. This is a hobby for us, so people will or will not get an answer. We all have a personal life, day jobs and much more....keeping up with every request or question isn't our top priority.
> 
Oh really? I was sure you were earning billions, sorry, I receive a a lot of answer concerning some adds, so i was wondering why this one was not considered.

**Comment by ginofalaci** [comment]
> Answering your question, I would be possible to do add that, maybe a team member has time to do this....I can't say for sure. Like I said, this is a hobby for us.....if you want something done quickly, learn Python (https://www.sololearn.com/learning/1073 or https://www.sololearn.com/learning/1157) and fix it yourself and commit it here. Most of us started like that (we wanted something added/changed, so we learned how)
> 
Sure, im learning, i will, thanks

**Comment by ErosVece** [comment]
This will be added in a coming update.

**Comment by ginofalaci** [comment]
Thanks,
