### ISSUE TITLE
Site perverzija.com

### ISSUE THREAD

**Issue by saidma** [dobbelina/repository.dobbelina#625]
Please add perverzija.com

**Comment by dobbelina** [comment]
Will be in the next release https://github.com/dobbelina/repository.dobbelina/commit/abe341d6ce7d83fdd529db8f72c21fde9faed813

**Comment by saidma** [comment]
> Will be in the next release [abe341d](https://github.com/dobbelina/repository.dobbelina/commit/abe341d6ce7d83fdd529db8f72c21fde9faed813)

It is possible to add the option lookup stars, studio and tags? thanks for the great job.

**Comment by ErosVece** [comment]
Tags is added, maybe stars and studios in an later update.
