### ISSUE TITLE
HQPorner fixes for older links

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#63]
HQPorner does not play the videos for many older (2-3 years) links. I made some changes to the rarely used older code for flyflv.com and added some new code for hqwo.cc which fixed the problem.

[hqporner.py.zip](https://github.com/dobbelina/repository.dobbelina/files/3389446/hqporner.py.zip)

**Comment by dobbelina** [comment]
Thanks jdoedev123!
Awesome as always.
Will incorporate it in the next addon update.

**Comment by dobbelina** [comment]
Added to addon, closing issue.
