### ISSUE TITLE
Request Uflash

### ISSUE THREAD

**Issue by brainwaster** [dobbelina/repository.dobbelina#632]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**If it's a site addition request, add url below**

http://www.uflash.tv/

**Comment by Buddha2400** [comment]
Yes please add Uflash.

**Comment by dobbelina** [comment]
Will be in the 1.1.34 release https://github.com/dobbelina/repository.dobbelina/commit/f562093560465a5c00fbcbfb00fb85c6bbaca084

**Comment by brainwaster** [comment]
Cheers
