### ISSUE TITLE
Viralvideosporno not working

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#634]
Getting "Playback Failed' on every link. Log is attached
https://paste.kodi.tv/qogihexuze

**Comment by Gujal00** [comment]
May be user specific issue. The site uses doodstream and in some regions they have enabled captcha

**Comment by imurreflection** [comment]
This indeed seems to be a region specific issue as after disabling VPN, links are playing fine. Thank you for your help. Closing the issue now
