### ISSUE TITLE
JAV Sites

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#64]
Hi, there are some extremely high quality uncensored JAV sites. Request our developers to have a look at them as one of the very skilled developer says that these sites are using some kind of proprietary streaming which is not possible with Kodi. These sites are:

Javhihi.me
Javbuz.com
Jav789.com

Please try to add these niche sites

**Comment by 12asdfg12** [comment]
I have looked at these sites, i don't know if the streams can be played in kodi or not, but the video links are too well protected, unfortunately I have no solution for any of them, maybe someone else.

**Comment by imurreflection** [comment]
Thank you so much for looking at at. @Whitecreamdev sir, is it possible for you to look at these sites and provide us any learning opportunities.

**Comment by imurreflection** [comment]
@WhitecreamDev, a simple yes or no could have sufficed the purpose. Thank you for your support. Closing the issue.
