### ISSUE TITLE
Add option in settings to change content type to "TVShows"

### ISSUE THREAD

**Issue by p8ckachu** [dobbelina/repository.dobbelina#642]
Helps with picking viewtypes for some skins.

**Comment by DJMix-I-Can** [comment]
I've modified my Acrtic Zypher Skin in Matrix. I use the square wall. Every time there's an update, I modify Cuminations default.py file on line 38. I change the "content = 'movies' to 'addons'.  This enables me to change everything to the skins square wall setting. Yes it's tedious especially if you're not familiar with making changes. I have to two NVIDIA Shields & always make my changes on my Windows 7 laptop. I have everything connected to my network.

**Comment by p8ckachu** [comment]
I'll try looking for that setting. I prefer the Eminence skin and for some reason the labels in "Icon" mode only show when content type is set to "tv shows".

I thought this would be a quick easy change, surprised this request has been ignored for so long.

**Comment by DJMix-I-Can** [comment]
I'm not sure If I'm understanding your issue. I use a portable Kodi on my laptop for testing purposes. I installed the Eminence skin & set the view to icon. The labels are showing. Another thing you could try which I forgot, is going into the Cumination settings, "general", on the right hand side, scroll down to "set content type", change it from movies to videos. See if that helps. If it doesn't, post a picture of what you're trying to achieve.
![IconView](https://user-images.githubusercontent.com/35236592/156869048-2f1da997-6b29-4639-9e6a-810d85af977e.jpg)
.
