### ISSUE TITLE
Add  full movie option on perverzija.com

### ISSUE THREAD

**Issue by jp194978** [dobbelina/repository.dobbelina#644]
Is it posible that you could add the FULL MOVIE  option on  perverzija, thank you

**Comment by dobbelina** [comment]
Will be in the next release https://github.com/dobbelina/repository.dobbelina/commit/64efd2cfccd8ab58872c605b9f3f5a35c188b1f1

**Comment by jp194978** [comment]
Thanks....

**Comment by jp194978** [comment]
Thank you
