### ISSUE TITLE
Myfreecams Not Working in cumination

### ISSUE THREAD

**Issue by losthelp815** [dobbelina/repository.dobbelina#645]
Unable to use Kodi on multiple versions of cumination not working with Myfreecams my main version Kodi 18.0 Leia is not working with allowing stream to be watched Also not working with Kodi 19.3 Matrix also not working. Has been giving error. Couldn't find a playable webcam link. Error has been happening since 11/16/2021 

Windows 7 PC
Kodi 18.0 Leia

**Comment by onknight** [comment]
Confirmed  Same problem

**Comment by dobbelina** [comment]
Fixed in the latest release version 1.1.28

**Comment by losthelp815** [comment]
Thanks, guys it working flawless appreciate such a fast turn around MFC is life thank you again.

**Comment by onknight** [comment]
MFC Great as long don't have to pay the bitchie models lol
