### ISSUE TITLE
Sextb.net

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#648]
Thanks for adding this site. May I request you to please add search function on it please. I know you have mentioned that categories etc would be added later but search is a very basic but important feature.

**Comment by dobbelina** [comment]
Will be in the next release https://github.com/dobbelina/repository.dobbelina/commit/67a08fdcd138d9d436ebe911d7f883a408b7a62f

**Comment by imurreflection** [comment]
Thanks for this. Closing the issue now.
