### ISSUE TITLE
Location for Favorites context menu?

### ISSUE THREAD

**Issue by TarkusLV** [dobbelina/repository.dobbelina#649]
Can you please tell me where the order is stored for the Favorites context menu?  I would like to move "Delete" back to the top.  I get why it was moved down, but I want to move it back up for my own personal use.

Thanks.

**Comment by ErosVece** [comment]
https://github.com/dobbelina/repository.dobbelina/blob/master/plugin.video.cumination/resources/lib/basics.py#L190

Move this line up, to line149 (before the 'if fav' line).

**Comment by TarkusLV** [comment]
Thank you, that worked perfectly!
