### ISSUE TITLE
Streamate doesn't play cams

### ISSUE THREAD

**Issue by DJMix-I-Can** [dobbelina/repository.dobbelina#65]
As the title states, cams won't play. I tried looking into it but will need the experts help on it. The error I was getting was WebSocketBadStatusException: Handshake status 502
I believe the problem lies under line 74 PlayVid,

The following info is from a streamate cammer, https://streamate.com/cam/LamiaLive/ 
It gives me the following information when I inspect element, console, requests & headers.
https://sea1b-ls.naiadsystems.com/sea1b-gateway-3/8100/socket.io/?performerid=57845765&sserver=72031&streamid=7248569373&sakey=&sessiontype=preview&perfdiscountid=0&minduration=0&goldshowid=0&version=7&referrer=hybrid.client.7.14.4/avchat.swf&usertype=false&lang=en&EIO=3&transport=websocket

This link (which is the javascript I believe) comes from line 75 https://streamate.com/ajax/config/?name=LamiaLive&sakey=&sk=streamate.com&userid=0&version=7.14.4&ajax=1

Now on line 78, host = data[liveservices][host] + "/socket.io/" + performerID + "&EIO=3&transport=websocket
doesn't match with the javascript from that cammer, as for the liveservices & host. What matches is now under stream & nodeHost. There is more info after performerid but don't know if that was there prior to them changing it. This is my first time looking at it.

I also think that line 82 is now 80/live or 80/live/s:, not sure. Currently it's 40/live.

I hope this makes sense to you guys, sorry I sound like a broken record but I'm still trying to learn.
Hopefully, the info I provided (if it's even correct) saves you time from looking into it.
Thanks again.

**Comment by jdoedev123** [comment]
Never looked at this before either my quick 2 cents:
I get (for a random performer Morena18xx )
If I manually do lines 75 and 76 and request: https://streamate.com/ajax/config/?name=Morena18xx&sakey=&sk=streamate.com&userid=0&version=2.2.0&ajax=1

JSON response:
{"liveservices":{"retryCount":5,"retryInterval":30000,"host":"wss:\/\/sea1c-ls.naiadsystems.com\/sea1c-hub-api\/8101"},"user":{"id":false,"type":false,"nickname":false,"status":false,"nonpremium":false,"sakey":"","stashUser":false,"limit":"","isStashLimit":false,"isNonBillableUser":false,"redirectToConfirm":false,"cpsUserId":null,"cpsNumbers":[]},"performer":{"id":"48510112","nickname":"Morena18xx","biopicThumb":"\/\/m2.nsimg.net\/biopic\/200x150\/48510112","biopicFull":"\/\/m1.nsimg.net\/biopic\/original4x3\/48510112","avgrating":"498","modelrating":0,"favorite":false,"cam2CamAvailable":false,"hasPaidVideos":false},"rate":{"blocksessions":{"resumed":[],"premium":[],"exclusive":[]},"currency":"$","prebill":false,"goldPrebill":false,"descriptor":"","taxPercentage":0,"feePercentage":0,"feeType":"","feeAppliesTo":"","exclusive":"5.49","premium":"4.49"},"stream":{"serverId":"80651","streamId":"7249021456","nodeHost":"wss:\/\/sea1c-ls.naiadsystems.com\/sea1c-gateway-5\/8100","nodeHostVer":2,"janusEndpoint":"sea1c-ls.naiadsystems.com\/sea1c-webrtc-ls\/8154"},"links":{"login":"https:\/\/www.streamate.com\/login.php","forgot":"https:\/\/\/resetpw.php","confirm":"https:\/\/\/flash\/confirm.php?pid=48510112","support":"https:\/\/\/contactsupport.php","account":"https:\/\/\/mymanage.php?expand=limits","updatePayment":"https:\/\/\/update\/","browse":"https:\/\/\/","join":"https:\/\/streamate.com\/signup\/","upgrade":"https:\/\/streamate.com\/upgrade\/"},"site":{"name":"Streamate","domainActive":"www.streamate.com","supportEmail":"supportteam@streamate.com","tdsname":"","defaultGold":5,"backgroundColor":"#ffffff","primaryColor":"#3399cc","logLevel":3,"termsAddress":".cnI ,ygolonhceT FCI <br>80512 xoB OP<br>11189 AW ,elttaeS<br>ASU","euroTermsAddress":".V.B UE hceT FCI<br>RB 1011 ,57 gewgrebskaaH<br>sdnalrehteN ,madretsmA","referrerId":0,"site":1,"googleAnalyticsId":null,"whitelabelDomain":"streamate.com"}}

Looking at actual communications with website the websocket request is:
wss://sea1c-ls.naiadsystems.com/sea1c-gateway-5/8100/socket.io/?performerid=48510112&sserver=80651&streamid=7249021456&sakey=&sessiontype=preview&perfdiscountid=0&minduration=0&goldshowid=0&version=7&referrer=hybrid.client.7.14.4%2Favchat.swf&usertype=false&lang=en&EIO=3&transport=websocket

All the information to construct the above WebSocket request is in the JSON but the current line 78 does not use the use the serverId=sserver and the streamId . Will adding these items fix it? Someone should give it a try.

**Comment by 12asdfg12** [comment]
This version works for me, which is odd because it's the version from uwc-1.1.87, with tabs converted to spaces.
Can someone confirm if it's working ?
[streamate.zip](https://github.com/dobbelina/repository.dobbelina/files/3392677/streamate.zip)

**Comment by DJMix-I-Can** [comment]
> 
> 
> This version works for me, which is odd because it's the version from uwc-1.1.87, with tabs converted to spaces.
> Can someone confirm if it's working ?
> [streamate.zip](https://github.com/dobbelina/repository.dobbelina/files/3392677/streamate.zip)

This is working. I compared this to 1.1.85 & 1.1.86, nothing has changed. I don't know what happened to my file then.... Thanks

**Comment by jdoedev123** [comment]
Hmmm maybe which just randomly picked cams which were in private or offline?
Or they could be in the middle of an API update. Sometimes when a website is updating they accidentally break their own old code and  either switch back or make exception after complaints. 
For me I just noticed nothing happens with a double click but a right click and "Play" seems to try to play but no video plays.
I would give this site a few days to settle it's API.

**Comment by dobbelina** [comment]
Very odd?
Either way I'll update with 12asdfg12's file as it's working.

**Comment by DJMix-I-Can** [comment]
Yup it was...Thanks guys, I'll close this. BTW dobbelina, Bubba Porn is now completely fixed, I added the file to the open ticket.
