### ISSUE TITLE
Xmoviesforyou search broken

### ISSUE THREAD

**Issue by xerel89** [dobbelina/repository.dobbelina#651]
### Bug reports:

Please replace this line with a brief summary of your issue 

### OS environment
What OS, Device, version etc

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Any bugreports without logfile will be deleted.

Hello I don't get a result when ivh search for April Olsen at xmoviesforyou, he always jumps back to search and I don't get an error message either, can I reset it somehow?

**Comment by dobbelina** [comment]
Confirmed, search doesn't work.

**Comment by 12asdfg12** [comment]
website error, if you keep trying, it will work eventually 
![image](https://user-images.githubusercontent.com/48175015/143859187-8360f542-56dd-417b-a1f2-c9454aa52d6f.png)

**Comment by dobbelina** [comment]
Confirmed, if you try a few times it works .
Closing issue
