### ISSUE TITLE
xfreehd search results pagination not working

### ISSUE THREAD

**Issue by vardevmisc** [dobbelina/repository.dobbelina#652]
### Bug reports:

xfreehd search results pagination not working

### OS environment
Windows, AndroidTV 

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/:
https://paste.kodi.tv/turaqeramu.kodi

**Comment by dobbelina** [comment]
Will be fixed in the next release https://github.com/dobbelina/repository.dobbelina/commit/b9bea603a693ffbf35bf2e1c4274ce48e334d9a6
