### ISSUE TITLE
PornTrex default load broken?

### ISSUE THREAD

**Issue by tetzy** [dobbelina/repository.dobbelina#655]
When I open PornTrex I'm seeing only 1 result using the default sort:

![Screenshot from 2021-12-10 00-38-13](https://user-images.githubusercontent.com/59111079/145538788-2b241045-f8fe-458a-ae9e-fa38aedabd1e.png)

Any ideas? - There wasn't an error, the page simply didn't load properly. My logfile is here:  https://paste.kodi.tv/igigucuqox

**Comment by dobbelina** [comment]
Maybe you activated some filter?
Click "M" on your keyboard to load the side panel, see screenshot below:
![bild](https://user-images.githubusercontent.com/46063764/145644367-26aab79c-dbce-48a2-9489-b229c832863e.png)

**Comment by tetzy** [comment]
This is weird - I loaded PornTrex tonight and all is well again... 

Thanks anyway.
