### ISSUE TITLE
Daftsex wont play videos

### ISSUE THREAD

**Issue by needsomehelpplease** [dobbelina/repository.dobbelina#656]
On my HP pc. i have tried installing the daxab extension but the site still does not play any of the videos. and not any other browser does either.  It says ''waiting for daxab.com when it's loading, then after a while this comes up.

![DAF](https://user-images.githubusercontent.com/96019091/145723676-abcf5df9-636c-4816-b749-e58f4b360891.png)

**Comment by needsomehelpplease** [comment]
it works when i use my 5g browsing on my phone though. dont know why

**Comment by ErosVece** [comment]
I just tried 2 videos with latest Cumination, on a Win11 laptop with Kodi 19.3.
And they played fine here.

**Comment by dobbelina** [comment]
Works for me to, closing thread.
