### ISSUE TITLE
Site Addition Request- Supjav

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#657]
Please add https://supjav.com/
This is probably the best Japanese porn site with biggest collection of Reducing Mosaic and Uncensored videos. The site has contact information also.

**Comment by imurreflection** [comment]
Kindly advise if the addition is not possible and I will close the issue

**Comment by dobbelina** [comment]
Will be in the next release https://github.com/dobbelina/repository.dobbelina/commit/abab7af156c8ead2845c6f60e95a35f15090f3e9

**Comment by imurreflection** [comment]
Thank you for the addition. Closing the issue now.
