### ISSUE TITLE
Pornhub

### ISSUE THREAD

**Issue by EvelK1203** [dobbelina/repository.dobbelina#660]
A couple issues with Pornhub.

1. Category list is blank, verified on both Android and Windows. Kodi 19.3
2. This one is random, videos will occasionally start somewhere not at the start. If this happens you can't seek and the stream eventually stops. Restarting the video usually is ok but as this seems to be a random thing something it needs a 3rd time to play correctly.

no errors occur for either issue

**Comment by dobbelina** [comment]
Will be fixed in the next release https://github.com/dobbelina/repository.dobbelina/commit/f2a9de6edbd250f13c4da9f1d496ab55da677b1d
