### ISSUE TITLE
Site Request Please - https://www.eroticage.net/

### ISSUE THREAD

**Issue by maxpro59** [dobbelina/repository.dobbelina#661]
It was also on Ultimate Whitecream and I liked it a lot.

https://www.eroticage.net/

Really hope this can be added, thanks in advance!!

**Comment by dobbelina** [comment]
Will be in the next release https://github.com/dobbelina/repository.dobbelina/commit/1aa605b2f09b481d692bfb2c83a606627c027a93

**Comment by maxpro59** [comment]
Thank you very much!
