### ISSUE TITLE
Site Addition Request- palimas and pornvid69

### ISSUE THREAD

**Issue by NIGHTRIDERSPIRIT** [dobbelina/repository.dobbelina#663]
**Site request:**
https://palimas.org/

Functions to add: 
Search
Categories
Pornstars
Channels

DMCA:
https://palimas.org/dmca

Contact:
https://palimas.org/contact

**Site request:**
https://pornvid69.com/

Functions to add: 
Search
Categories
Pornstars
Tags

DMCA:
https://pornvid69.com/dmca/

Contact:
https://pornvid69.com/contact/

Also there is a problem with video playback in perverzija which is already present in cumination.
Cannot forward or skip to a time on the video in perverzija.
This problem is not seen on perverzija website.

**Comment by dobbelina** [comment]
Will be in the next release https://github.com/dobbelina/repository.dobbelina/commit/69a7c32b8fa6840a5c4bbf6e4db089b765ed8717
