### ISSUE TITLE
Aagmaal.com not working

### ISSUE THREAD

**Issue by cg8440** [dobbelina/repository.dobbelina#664]
Can’t open the website aagmaal.com

**Comment by Gujal00** [comment]
domain changed. Fix will be in the next release

**Comment by cg8440** [comment]
> domain changed. Fix will be in the next release [dee24a3](https://github.com/dobbelina/repository.dobbelina/commit/dee24a36c64517ca06f43235076a4c00f9e64fd7)


Thank You!
