### ISSUE TITLE
Site request - Motherless.com

### ISSUE THREAD

**Issue by EvelK1203** [dobbelina/repository.dobbelina#666]
This site is in a few other addons but those seem to be abandoned. Would be nice to see it in a maintained addon.

www.motherless.com

Thanks

**Comment by Devonweber19** [comment]
Definitely agree was going to request the same site 😂😂

**Comment by Gujal00** [comment]
Avail;able as a custom site now.
[motherless.zip](https://github.com/dobbelina/repository.dobbelina/files/8840204/motherless.zip)

_Originally posted by @dobbelina in https://github.com/dobbelina/repository.dobbelina/issues/407#issuecomment-1146847664_

This issue can be closed @dobbelina
