### ISSUE TITLE
ResolveUrl not opening link

### ISSUE THREAD

**Issue by jayger1217** [dobbelina/repository.dobbelina#67]
Multiple sites, ResolveUrl not working with gounlimited as a source

**Comment by jdoedev123** [comment]
Can you be more specific. 
Quick spot check in Xtheatre worked with UWC vers 1.1.89
and ResolveURL version 5.0.33
Played a gounlimited.to  URL

**Comment by dobbelina** [comment]
Works for me to.
However sometimes they can time-out, and you have to try again before
they start playing.
Probably a server load issue.

**Comment by jdoedev123** [comment]
I also noticed an intermittent time out issue but the URL was valid. I grabbed the URL from the JSON served out by Kodi and it was a valid gounlimited URL which was playable.

**Comment by DJMix-I-Can** [comment]
Gounlimited also worked for me. It takes about 20 seconds to load but it works.
