### ISSUE TITLE
CUMINATION - JAV Moe

### ISSUE THREAD

**Issue by Xevo6** [dobbelina/repository.dobbelina#670]
JAV Moe site appears on Cumination sites list, and lists videos available - however, none of them actually play when selected.

Would like to be able to access working videos on this site.

Thanks

**Comment by dobbelina** [comment]
Will be fixed in the next release https://github.com/dobbelina/repository.dobbelina/commit/23b87f641bb81af1777ff831dcf4816e9d280b3e
