### ISSUE TITLE
unable to download from perverzija

### ISSUE THREAD

**Issue by joselbcn36** [dobbelina/repository.dobbelina#673]
### Bug reports:

Please replace this line with a brief summary of your issue 

### OS environment
What OS, Device, version etc

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Any bugreports without logfile will be deleted.

**Comment by joselbcn36** [comment]
Hi, I have tried to download videos from perverzyja, and was able to download with the integrated option...Also have tried with youtube-dl addon, and it reports that can determinate the file size

**Comment by Gujal00** [comment]
perverzija uses __HLS streams__ and those __can not be downloaded__ using the downloader in cumination.

**Comment by dobbelina** [comment]
On windows this works https://github.com/dobbelina/repository.dobbelina/issues/368
