### ISSUE TITLE
daftsex playlist videos doesn't open.

### ISSUE THREAD

**Issue by zenoave** [dobbelina/repository.dobbelina#674]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**If it's a site addition request, add url below**

**Comment by dobbelina** [comment]
Can't help you without a logfile as under Windows it works fine.
Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/

**Comment by dobbelina** [comment]
No log, closing issue.
