### ISSUE TITLE
Sextb only showing 2 links for streaming

### ISSUE THREAD

**Issue by crst31** [dobbelina/repository.dobbelina#675]
Checked the site and there's at least 4-5 links available. Tried the other links on the site and their working. The other links just don't show up on cumination

My device - Shield (Kodi 19)

**Comment by Gujal00** [comment]
Cumination will only show the links that it can resolve.

**Comment by crst31** [comment]
It was showing 4 links last week. Tried it this week and it was only showing 2. It's not showing the "dood" and "streambox" links anymore.

**Comment by dobbelina** [comment]
Will be improved in the next release https://github.com/dobbelina/repository.dobbelina/commit/49eb1cdc6888741e6d201818e4966142f57eb7cf
