### ISSUE TITLE
Site Addition Request- https://roshy.tv/

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#677]
Please add. This is the only site dedicated to Japanese Decensored porn only. The site has contact information also

**Comment by DJMix-I-Can** [comment]
Has contact information BUT no DMCA information.

**Comment by imurreflection** [comment]
@DJMix-I-Can

Contact information is used for DMCA Takedown requests also.

**Comment by imurreflection** [comment]
Hello everyone, if the addition is not possible, let me know and I will close the issue as initial request was raised almost 3 months ago.
