### ISSUE TITLE
ElReyX is down

### ISSUE THREAD

**Issue by tetzy** [dobbelina/repository.dobbelina#678]
For the past 48hrs ElReyX has not been loading. Cumination initially reports that the website is too slow, but then gives the following error:

![Screenshot from 2022-01-17 01-09-06](https://user-images.githubusercontent.com/59111079/149732515-528bfbf0-5493-45ad-a560-4283678e2850.png)

Any help would be greatly appreciated. 
Thanks.

**Comment by Gujal00** [comment]
Cumination is giving you the correct message. Have a look browsing to elreyx on your browser and see if it works

**Comment by tetzy** [comment]
The website gives me a "Error 522 Connection timed out".

Is elreyX working on your end or am I being blocked?

**Comment by dobbelina** [comment]
The website is down for everyone https://www.isitdownrightnow.com/elreyx.co.html

**Comment by tetzy** [comment]
...aaand the site is back working as usual. 

Thanks for your time.
