### ISSUE TITLE
Whitecream Download Folder error

### ISSUE THREAD

**Issue by dobbelina** [dobbelina/repository.dobbelina#68]
Hi all!

I noticed when you configure a Download Folder in the settings, that you
can't open it, it errors out.
I assume it's line 171 in default.py that wont cooperate.
`xbmc.executebuiltin('ActivateWindow(Videos, ' + url + ')')`
Lines 53-55 & 169-171 are of interest.
<img width="260" alt="screenshot000" src="https://user-images.githubusercontent.com/46063764/61588534-7ef96700-ab9d-11e9-827e-6842e922edba.png">

**Comment by dobbelina** [comment]
Ok, think i found a fix.
If i add this above line 171 it works:
`xbmc.executebuiltin('Dialog.Close(busydialog)')`

Can somebody please reproduce and give some feedback.

**Comment by imurreflection** [comment]
There are two ways for setting up download location folder. 1st through add-on itself like the one you have mentioned and secondly through add-on setting. They both are working fine for me.

**Comment by dobbelina** [comment]
Setting up the download location folder is not a problem.
The problem occurs when i click on it,(Whitecream Download Folder).
I get the error signal and nothing happens.
I'm on Windows btw.

**Comment by imurreflection** [comment]
I m not sure about windows but on Android box km9 pro, I don't see any issue with download folder both options. When inside add-on, I click on download folder, it takes me to all downloaded files. I m on Kodi 17.6.

**Comment by DJMix-I-Can** [comment]
> 
> 
> Ok, think i found a fix.
> If i add this above line 171 it works:
> `xbmc.executebuiltin('Dialog.Close(busydialog)')`
> 
> Can somebody please reproduce and give some feedback.

I can confirm that in Leia, the download folder doesn't work. In Krypton or SPMC it does. I checked on a Windows 7 64-Bit Laptop, Windows 7 64-Bit Desktop, Nvidia Shield and Android phone.  As for adding that line, it does make it work in Leia. My concern was if inserting that line would break the download folder under Krypton.  I tried it and it still works.  The only thing I don't like,  let's say you click on the download folder and decide to not select a file. Clicking on back should throw you back into UWC directory but it doesn't. It goes to the previous folder of your download path and so on. So for example, on my Windows Laptop, this would be my download path C:\Users\DJMix-I-Can\Downloads\MP3s\Serato Mixes. If I click back, it would go MP3s, click back again and now I'm in Downloads, click back and now I'm in DJMix-I-Can, etc... It shouldn't be like that, it should throw us back into the UWC directory of where we select the download folder.  Hope that helps...

**Comment by dobbelina** [comment]
Thanks DJMix-I-Can for your thorough answer.
Definitively a Leia bug then.
Unless somebody comes up with a better fix, where the back button takes you back
to the addon, I will incorporate it in the v1.1.90 release.
Final fix above line 171:

```
    xbmc.executebuiltin('Dialog.Close(busydialog)')
    xbmc.sleep(100)
```
