### ISSUE TITLE
No Thumbnails Familypornhd

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#680]
Hi, Familypornhd doesn't have any thumbnails..kindly fix it

**Comment by dobbelina** [comment]
Thumbnails work for me on both kodi18.9 And 19 on Windows.
Links do not play though on kodi 18.9

**Comment by imurreflection** [comment]
No issues with playback on Android TV Box 19.3 but still there are no thumbnails..can someone else confirm on Android 19.3?

**Comment by imurreflection** [comment]
Hi @12asdfg12 can you please confirm if thumbnails works for you on Android?

**Comment by 12asdfg12** [comment]
I don't have android with kodi, no problems on windows and linux.

**Comment by imurreflection** [comment]
Oh..thanks mate..@gujal007..can you please confirm as you have Android devices.

**Comment by Gujal00** [comment]
Nope, I test on Windows, Linux and CoreElec only

**Comment by imurreflection** [comment]
Ah..seems like issue at my end. Thanks to everyone for their time. Closing the issue now.
