### ISSUE TITLE
Some issues on hpjav site

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#681]
Hi,

Thanks for the addition. However, the site has some issues.

1) Doesn't have any thumbnails
2) site main page shows only three pages but the main site has 4128 pages
3) kindly include all sections like movies, uncensored, Reducing Mosaic, Chinese etc to get all content
 4) A search with the keyword "Chinese" returned with only 24 returns with no next page whereas inbuilt section "Chinese" has more than 1000 pages. 

Please take a look at above issue and fix them.

**Comment by 12asdfg12** [comment]
1. will  be fixed in the next release
2.  the 'hot' section contains only 3 pages
3. in the next release
4. you are comparing different things (chinese content vs videos with chinese subtitles)

**Comment by imurreflection** [comment]
On the home page, if you click category, you can see "China Porn" on number 3. However, in our addon, this is missing completely. Moreover, our addon shows more than 700 categories but on website, the category has only 12 sub categories.

**Comment by 12asdfg12** [comment]
I can't see any "china porn" category on https://hpjav.tv/

**Comment by imurreflection** [comment]
My apologies. I was looking at somewhere else..
