### ISSUE TITLE
JAVMoe site

### ISSUE THREAD

**Issue by Xevo6** [dobbelina/repository.dobbelina#684]
Have commented before on the above site and you did improve it when you updated (had no working links from home page)
Links do now occasionally work.
However, very high percentage of links do not work (70 - 80%)   If possible, would like more working links available.

**Comment by dobbelina** [comment]
Will be improved in the next release https://github.com/dobbelina/repository.dobbelina/commit/d9b3da54ba0680275c95e9442dc072a1280b9a9a
