### ISSUE TITLE
Paradise Hill videos don't play

### ISSUE THREAD

**Issue by durangorob** [dobbelina/repository.dobbelina#686]
The movies on Paradise Hill used to play with no problems, but for a very long time now when I try to play  any of them, they start and only play for few seconds then stop. I'll do a stop/start on the play button then they will play again for only a few seconds.  I do not understand this as I can play videos on other sites in the list .   Can you please look into to this and see if you can fix it.

durangorob

**Comment by 12asdfg12** [comment]
Sounds like you have a bad connection with the website, this can not be fixed from the addon.
