### ISSUE TITLE
Contribution support

### ISSUE THREAD

**Issue by withoutprefix** [dobbelina/repository.dobbelina#687]
Hi,

i would like to contribute but i have a question about testing my changes.
i`ve set my local dev env and i am able to make code changes but i am not sure how i can test / debug my changes.
(i can zip and install it but i wonder what is the best way to test it locally)

i am using ubuntu and intelij IDE.

Thanks

**Comment by Gujal00** [comment]
The simplest way is to delete the plugin.video.cumination folder in ~/.kodi/addons/ folder and create a symbolic link with the name as plugin.video.cumination pointing to your dev folder. Once done inside kodi goto addon information and disable auto updates.
Now as long as you keep your dev folder up to date with git and then make any fixes on your dev folder they will be available inside kodi immediately.

**Comment by withoutprefix** [comment]
Thanks a lot
I'll check it
