### ISSUE TITLE
Xhamster has no videos

### ISSUE THREAD

**Issue by jeajesper** [dobbelina/repository.dobbelina#689]
### Bug reports:

There is no videos when opening Xhamster

### OS environment
LibreElec Kodi, Kodi for Windows and Android TV Kodi

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Any bugreports without logfile will be deleted.

**Comment by dobbelina** [comment]
Will be fixed in the next release https://github.com/dobbelina/repository.dobbelina/commit/2c1af2f5165ef3a31551902dad9e348a1b820bc3

**Comment by dobbelina** [comment]
Thumbnail doesn't match video, it's for the video ahead.

**Comment by dobbelina** [comment]
Will be fixed in the 1.1.34 release https://github.com/dobbelina/repository.dobbelina/commit/9f7373a447cfb0a89a215d799226dcdb74146004
