### ISSUE TITLE
how to have ultimate whitecream on kodi 19...??

### ISSUE THREAD

**Issue by p060477** [dobbelina/repository.dobbelina#691]
how to have ultimate whitecream on kodi 19...??

**Comment by dobbelina** [comment]
You can't, it's not Python 3 compatible.
https://iwf1.com/what-to-do-kodi-19-dropped-support-for-python-version-2-below

**Comment by p060477** [comment]
is there a chance to have it in the future..??..i mean will be updated to be compatible with phy.3 ?
thxs so much
:)

**Comment by dobbelina** [comment]
No, Cumination is the successor of UWC, UWC will not be worked on any more.

**Comment by p060477** [comment]
thxs so much, so i think it should be better clarify it on yr github page dedicated...
i mean here...
https://github.com/dobbelina/repository.dobbelina

;)

thxs so much again
:)
