### ISSUE TITLE
Site request

### ISSUE THREAD

**Issue by firetrap71** [dobbelina/repository.dobbelina#695]
Any chance you could add Bigo or Liveme live streaming addons or any live streming https://www.bigo.tv or https://www.liveme.com thanks

**Comment by DJMix-I-Can** [comment]
This doesn't make sense. Why don't you just download their app?? BTW These two sites don't provide DMCA contact information. Just do you within their app.....

**Comment by Gujal00** [comment]
These are social streaming sites. Are they even relevant to cumination? @dobbelina

**Comment by dobbelina** [comment]
@Gujal00 
No, these does not seem relevant to cumination, closing topic.
