### ISSUE TITLE
Increase load speed

### ISSUE THREAD

**Issue by Buddha2400** [dobbelina/repository.dobbelina#698]
Is it possible to increase the loading speeds of videos and cam feeds. Close to what you would get if you was on a computer, phone, and or tablet. Chaturbate especially needs that load increase. Loading the into cams is slow, going into online favorites is slow. Even loading into the different categories this slow for Chaturbate.

**Comment by 12asdfg12** [comment]
On what device is slow?
Chaturbate may be slower than other sites because no caching is used and every time you access a menu the addon downloads a web page.

**Comment by Buddha2400** [comment]
OK I get that but still is there a way to help it load a little bit faster. Because just to load my online favorites in chaturbate takes 2 to 3 minutes. And I’m using both a fire stick and a android TV box.

**Comment by 12asdfg12** [comment]
Are you sure you have the latest version?
There was a problem with loading online favorites but it was fixed a few versions ago.
On an android box running Coreelec, online favorites open in about 2 seconds.

**Comment by Buddha2400** [comment]
The android box I’m using is an Ematic Jetstream Agt418 running Android pie I have looked up what you were talking about and there is no easy way to install that. Is there an easier way?

**Comment by 12asdfg12** [comment]
By the latest version, I meant the latest version of Cumination, the slow loading problem of online favorites has been fixed in version 1.1.26, the current version is 1.1.33.

**Comment by Buddha2400** [comment]
Yes I’m on the current version 1.1.3.3.

**Comment by Buddha2400** [comment]
Now I did a test of opening online favorites the first I opened it by going straight to it. It took 
1:m 31:s 23:ms Just to load 50 favorite cams that were online. Now with the second I had added online favorites to my Kodi favorites. And it took 
1:m 25:s 91:ms. 
![7B0D1E3A-A9B8-4F58-864E-C599BAB83935](https://user-images.githubusercontent.com/33353171/153015965-8eb748c5-7e61-4c0a-8fb3-8e0b44326ced.png)
![2B4EE56E-2054-44C0-A2CA-ED1E970A59DA](https://user-images.githubusercontent.com/33353171/153015966-dc59a5d4-c7a2-4bfc-8e22-74d98e2a8bd3.png)

**Comment by DJMix-I-Can** [comment]
I personally have 85 Chaturbate & different misc. Webcam favorites. I only have these cam sites & everything loads in 9 seconds. Yes, I timed it as well as you did. I'm using an Nvidia Shield & the latest versions of Kodi & Cumination. Check you network.
