### ISSUE TITLE
Site Addition Request- A Question Please

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#699]
Hi.. I know that dear @12asdfg12 has mentioned that sxyprn.com cannot be added as it is using Anti Bot protection and I have no question on his expertise but just want to know that this site at present is available in our old UWC and it's working fine but thumbnails are missing. I just tried two videos from UWC and they played fine.

Now, may I please ask why this site cannot be added to cumination..is it because it's not Kodi 19 compatible. Can we possibly look again to see if this can be added as this is indeed best.  The site is using ,streamtape,upvideo,highload etc which are resolving fine through resolveurl. Only doodstream links are not playable but we can disable it in UWC settings. Perhaps @gujal00 can check the compatibility with resolveurl. 

Also, if possible, please advise where should we look for the information that site is using "Anti-Bot Protection" so that if there is any change in the future, i  can intimate you.

Regards.

**Comment by 12asdfg12** [comment]
This is what i get when i try to access the site.

![image](https://user-images.githubusercontent.com/48175015/152674775-d90898cd-0823-42a3-9058-4a0649b72048.png)

If is working for you in UWC, then the cloudflare protection is may be a regional thing

**Comment by imurreflection** [comment]
Thank you my friend. I can access this site without any issue as a matter of fact, I just checked more than 15 videos and all are working fine.so perhaps it could be a regional blockage at your end. In that case, is it a possibility that this site can be added by someone else? Perhaps  @gujal00 can provide his input here.

**Comment by imurreflection** [comment]
![IMG_20220206_154558_263](https://user-images.githubusercontent.com/30263396/152676392-afd1fc90-6f4d-431f-9956-8395d63788ac.jpg)

**Comment by imurreflection** [comment]
![Screenshot_2022-02-06-16-13-02-15_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/30263396/152677191-412add9e-5da4-4410-85e8-516e4b3ef732.jpg)

**Comment by imurreflection** [comment]
Upon further research, I found the information above. Please see if this site can be added now

**Comment by Gujal00** [comment]
Added in https://github.com/dobbelina/repository.dobbelina/commit/421f5ad621259c759dfca5205452a54c6fad998d

**Comment by imurreflection** [comment]
Thank you. Closing the issue now
