### ISSUE TITLE
Porntrex thumbnail images stopped loading.

### ISSUE THREAD

**Issue by lukehansford** [dobbelina/repository.dobbelina#7]
All the thumbnail images for every video have stopped loading.

Can this be fixed?

**Comment by jdoedev123** [comment]
Proposed PornTrex fix for missing images.
[porntrex.py.zip](https://github.com/dobbelina/repository.dobbelina/files/2843969/porntrex.py.zip)

**Comment by imurreflection** [comment]
Mate, can you please upload the zip file with this fix

**Comment by dobbelina** [comment]
Thanks for the fix jdoedev123,

Will update the addon.
