### ISSUE TITLE
download from porntrex impossible

### ISSUE THREAD

**Issue by lucapicchio** [dobbelina/repository.dobbelina#70]
Hello
from 1.1.89 the download from porntrex site its no possible (start playback)
thanx

**Comment by jdoedev123** [comment]
Looks like the code to download was lost when the ability to play private videos was added.

**Comment by 12asdfg12** [comment]
My mistake, i forgot the 'download' parameter. Replace line 191 from porntrex.py:
`    vp = utils.VideoPlayer(name) #, download=download, direct_regex="video\S+url\d*:\s*'([^']+)'")`
with:
`    vp = utils.VideoPlayer(name, download=download)`

**Comment by lucapicchio** [comment]
Great!! Works perfectly!
Thank you so much!

**Comment by dobbelina** [comment]
Excellent 12asdfg12!
Fix added to 1.1.90, closing issue.
