### ISSUE TITLE
Search Function not working Xmoviesforyou.

### ISSUE THREAD

**Issue by joxdfrt** [dobbelina/repository.dobbelina#700]
### Bug reports:

Please replace this line with a brief summary of your issue 

### OS environment
What OS, Device, version etc

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Any bugreports without logfile will be deleted.

**Comment by joxdfrt** [comment]
Search function not working on Xmoviesforyou just getting Cumination error.

**Comment by 12asdfg12** [comment]
Website error, the site sometimes returns the error "500 Internal Server Error". 
Try again and it will work eventually.

**Comment by joxdfrt** [comment]
Will give it a try thanks 😊
