### ISSUE TITLE
Xxxstreams.org

### ISSUE THREAD

**Issue by joxdfrt** [dobbelina/repository.dobbelina#701]
### Bug reports:

Although the site opens the filehost needs changing k2s videos are stopping after 30 seconds. 

### OS environment
What OS, Device, version etc

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Any bugreports without logfile will be deleted.

**Comment by DJMix-I-Can** [comment]
This has nothing to do with Cumination. What Cumination did was pass the link to the ResolveURL in order to play it. It's failing to resolve with ResolveURL.  Cumination did it's job.

**Comment by Gujal00** [comment]
k2s are a premium hoster and only allow 30 seconds of playback for free users
