### ISSUE TITLE
Xxxstreams.eu/

### ISSUE THREAD

**Issue by joxdfrt** [dobbelina/repository.dobbelina#702]
### 
After several attempts the site will not load saying they site is down.  Followed 

### OS environment
What OS, Device, version etc

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Any bugreports without logfile will be deleted.

**Comment by DJMix-I-Can** [comment]
That's because the site is dead. It gets redirected to http://ww12.xxxstreams.me/ Dead site

**Comment by dobbelina** [comment]
Will be removed in the next release.
