### ISSUE TITLE
Log Files 

### ISSUE THREAD

**Issue by onknight** [dobbelina/repository.dobbelina#703]
I want to report a bug but I need to know where I can find the log file
So someone could tell me where to look that would be helpful

**Comment by imurreflection** [comment]
For which platform?

**Comment by onknight** [comment]
Windows

**Comment by imurreflection** [comment]
This is for windows
https://howtomediacenter.com/en/how-to-check-kodi-log-file/

**Comment by imurreflection** [comment]
@joxdfrt this is for Firestick

https://gameinpost.com/check-the-log-for-more-information-kodi/

**Comment by joxdfrt** [comment]
Thank you for that information I went into indigo and deleted cache packages and thumbnails. I then preceded to url resolver which had Orphaned next to it I clicked on update but it stayed at that status so no idea what next.

**Comment by onknight** [comment]
Thanks

**Comment by imurreflection** [comment]
@joxdfrt all you need to do is download "Log Viewer' from Kodi Repository. Please search Google to find how to install Kodi Repo. Once installed, you should be able to View the log directly on the screen. Another addon " Kodi log Uploader' will give you the paste.kodi link which you can post here to get support from our friendly developers.
