### ISSUE TITLE
Cam Soda Not working 

### ISSUE THREAD

**Issue by onknight** [dobbelina/repository.dobbelina#704]
### Bug reports:

Please replace this line with a brief summary of your issue 

### Windows 11
Kodi 19.3

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Any bugreports without logfile will be deleted.

Logfile: https://paste.kodi.tv/ekifocexum.kodi
(Edited by Dobbelina)

**Comment by onknight** [comment]
As I said  when click link in Cam Soda part of the idea  
It searches for the model

I get the Following Error : 
One or more items failed to play check the log for more information about this message

**Comment by dobbelina** [comment]
Will be fixed in the next 1.1.34 release https://github.com/dobbelina/repository.dobbelina/commit/7f7ce8a4f5471b1dcabbae9fca29560e524d08cb
