### ISSUE TITLE
Download Tip For Windows Users

### ISSUE THREAD

**Issue by dobbelina** [dobbelina/repository.dobbelina#71]
# FFmpeg Recorder

I got bored testing different addons in regard to downloading videos, as none of them seems to work the way i want.

so i decided to make use of ffmpeg configured as an external player.

By doing that it will be avaliable for all addons that has playable links, and the download for most part goes on in the background, so i can continue to use kodi while it is ongoing.

You can even start multiple downloads at the same time if you wish, depending on what source you use.

Added option is now that you can watch while you are downloading, this is especially useful on livestreams.

This is done thru a "pipe", so no extra bandwith is being consumed.

So here's how i do it:

Download ffmpeg from here: https://ffmpeg.org/download.html

It's a zip archive, so no installation required, just extract ffmpeg.exe & ffplay.exe to a location of your choice.

They both have to be in the same folder.

For this purpose i have made a custom program to simplify, called FFMPEG_Recorder.exe that you can find a link to at the bottom.

Download it and put in the same folder as ffmpeg.exe,
or some other permanent location from where it will work as a "dummy player" before running it.

Now start FFMPEG_Recorder.exe, and point to the location of ffmpeg.exe, 
after that you will be prompted for a download location for the videos.

After execution, 2 xml files will be created in the same folder as FFMPEG_Recorder.exe, 
that is playercorefactory.xml & playercorefactory2.xml.

Copy those to the %APPDATA%\Kodi\userdata\ folder.

On the desktop a shortcut will be created called "FFMPEG_Recorder Default Change" that 
toggles between the 2 xml files, making FFMPEG_Recorder.exe default player.

This is necessary, as **some addons don't respect the "Play using.." context menu** 
and will revert to the default player, and others wont display a context menu at all.

Press "Q" to stop an ongoing recording/download.

Default container format is mp4, but you can change it by editing the Options 

section in ffmpeg.ini to any of the formats supported by ffmpeg, and there are plenty.

In the Options section you can also edit the timestamp switch to off, 
if you don't like it in the view window.

Recorded video don't have a timestamp.

Delete ffmpeg.ini to restart setup.

Created in Autohotkey

Download here: https://github.com/dobbelina/Playground/releases/download/v1.4-Windows/FFMPEG_Recorder-v1.4.zip

**Comment by 12asdfg12** [comment]
Fix for download not working:
[download.zip](https://github.com/dobbelina/repository.dobbelina/files/3437962/download.zip)

**Comment by jdoedev123** [comment]
Thanks 12asdfg12 we all have been running fast and loose with "fixing" playback but not testing download.   
As seen above dobbelina does not use conventional download on a PC and I run Linux with my own custom code on my NAS to download independently. We sometimes forget most users use what is provided in conventional Kodi.

**Comment by 12asdfg12** [comment]
You are right, I have never downloaded anything from kodi, so I never tested if downloading works
But the download functionality is implemented in uwc, it would be a pity not to be available for certain sites

**Comment by dobbelina** [comment]
Thanks 12asdfg12 for all the download fixes!

Will incorporate in next update.

**Comment by Gitbone94** [comment]
Hi. I tried this but I have Kodi in my J: drive instead of C: drive. Running that little file from my desktop fails because it can't find Kodi on C:    I tried to edit the program but you must have compiled that part to be hidden.  In the same way you prompted for the download folder can you please prompt for Kodi.exe location?
