### ISSUE TITLE
Xmoviesforyou.com

### ISSUE THREAD

**Issue by joxdfrt** [dobbelina/repository.dobbelina#710]
### Bug reports:

Search function is not working tried this multiple times and getting connection error 

### OS environment
Firetv 4K Stick. 

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Any bugreports without logfile will be deleted.

**Comment by DJMix-I-Can** [comment]
The search function works but unfortunately, it's a hit or miss depending on the keyword. They're also using Cloudflare which causes issues. For example, click on this search function https://xmoviesforyou.com/?s=breasts on a laptop of phone. Now go to the site in Cumination & do a search for "breasts" Do you get the same results as on your laptop or phone? If so, it's working.

**Comment by Gujal00** [comment]
Cant replicate issue. Please provide full debug log

**Comment by dobbelina** [comment]
No log, closing issue.
