### ISSUE TITLE
Xtheatre

### ISSUE THREAD

**Issue by deanogers** [dobbelina/repository.dobbelina#712]
Search function doesn’t seem to work can u take a look thanks for the hard work

**Comment by DJMix-I-Can** [comment]
The search function does work. Go to the website https://pornxtheatre.com & make the same search of the keywords that are failing in the Cumination addon.. It would either work or fail. There is nothing that they could do if the site is inconsistent. The site uses selective searches or their site is inconsistent. For example, go to your phone or laptop. Go to the website https://pornxtheatre.com. Go to "their" search function & type in the keyword "breasts". Now, do the same keyword search in the Cumination addon. If you get the same results, then it's working.
