### ISSUE TITLE
Supjav (Issue #690)

### ISSUE THREAD

**Issue by butterflytwist** [dobbelina/repository.dobbelina#716]
Seem to be having issues with supjav again.

Log: https://paste.kodi.tv/ehefeqibuf.kodi

Any assistance is appreciated. 

Thank you

**Comment by Gujal00** [comment]
The log is not a debug log so not much information there.
Anyway from the error it looks like restriction by your ISP/location
Works fine otherwise
![image](https://i.imgur.com/qhsxLJG.png)

**Comment by butterflytwist** [comment]
I don't know if this is the debug log but would you check this and let me know if it is? Appreciate your assistance again~

https://paste.kodi.tv/eteceyigum.kodi

**Comment by butterflytwist** [comment]
If it makes a difference, I can access supjav through a web browser on the same device. Just not through the addon. I also noticed a red asterisk next to supjav in the sites list.

**Comment by DJMix-I-Can** [comment]
So thought I'd try to help, I personally don't use SupJav Since @butterflytwist didn't state what the actual problem was. I'm going to assume that you can't play the video from any of the sources. I couldn't either with my Android device. It does play on my Windows laptop but did notice that the website is using Cloudflare. Thought I'd try with the VPN enabled. It still wouldn't play. I tried to paste my debug log on Pastebin but they're Smart Filters is starting to be a pain in the ass. This is my debug log as soon as I click on SupJav via ControlC.com. https://controlc.com/74aa2ffd

**Comment by Gujal00** [comment]
` urllib.error.HTTPError: HTTP Error 403: Forbidden` in the log means cloudflare is blocking you in your location. It will work on a browser, but web scraping through python will fail

**Comment by butterflytwist** [comment]
> So thought I'd try to help, I personally don't use SupJav. Since @butterflytwist didn't state what the actual problem was. I'm going to assume that you can't play the video from any of the sources. I couldn't either with my Android device. It does play on my Windows laptop & noticed that the website is using Cloudflare. Thought I'd try with the VPN enabled. It still wouldn't play. I tried to paste my debug log on Pastebin but their Smart Filters is starting to be a pain in the ass. This is my debug log from as soon as I click on SupJav. https://controlc.com/74aa2ffd

Hello appreciate your response. Sorry I should have mentioned it in the subject. I tried to reopen a previous issue but it wouldn't let me so I added Issue #690 to the post. I was having an error where it was telling me the website was down. Thank you for testing it. At least now I know I'm not the only Android user having the issue.

**Comment by butterflytwist** [comment]
> ` urllib.error.HTTPError: HTTP Error 403: Forbidden` in the log means cloudflare is blocking you in your location. It will work on a browser, but web scraping through python will fail

Do you know if there is any work around to get it working? It was working fine for around 2 weeks and the issue began again. Seeing that @DJMix-I-Can is able to access via Windows app and not on Android sounds like it may be an issue with the Android version of Kodi? Any suggestions are appreciate.

Thank you both~

**Comment by DJMix-I-Can** [comment]
@butterflytwist It probably worked two weeks ago because they weren't using Cloudflare as of yet. I didn't use Kodi within windows. I was using my Windows 7 laptop via the Firefox browser. I have a Firefox extension called Detect Cloudflare. It will tell me if a certain website is using Cloudflare.

**Comment by Gujal00** [comment]
Actually at what stage does it fail. Is it able to list the videos and fail when you try to play?
Or is it not listing the videos at all

**Comment by DJMix-I-Can** [comment]
It does list the directory, you have the list. It fails once you click for
play.

**Comment by Gujal00** [comment]
okay, found the issue with playback, there will be an update from @dobbelina later

**Comment by dobbelina** [comment]
Fix will be in the next update https://github.com/dobbelina/repository.dobbelina/commit/2e22be1a88c7be0ee691064455757a881cd74e8d

**Comment by butterflytwist** [comment]
> Actually at what stage does it fail. Is it able to list the videos and fail when you try to play? Or is it not listing the videos at all

For me it doesn't load the directory. I get a website is down prompt.

**Comment by Gujal00** [comment]
> For me it doesn't load the directory. I get a website is down prompt.

In which case it is probably cloudflare ddos protection in your location. Cant do much about it.
