### ISSUE TITLE
Beeg.com hopeless

### ISSUE THREAD

**Issue by sniffer54** [dobbelina/repository.dobbelina#718]
This only ever works after you update for about one day.  Then none of the videos can be played. “Cumination error - check the log for info” message every bloody time.

One of the best sites WHEN IT WORKS which is once in a blue moon!

help please?

**Comment by dobbelina** [comment]
Will be fixed in the next release https://github.com/dobbelina/repository.dobbelina/commit/b431ef9954a485fafdf9975060c4d1e0cb3d1aba

**Comment by sniffer54** [comment]
The next release happens when??
I bet that works for five minutes and then the videos won’t play after
that? Why would it be any different from your previous 6-7 updates?

**Comment by dobbelina** [comment]
> Why does it always bugger up as soon as you fix it every time?
Because of changes being made by beeg.com on a regular basis.
If you have an issue with that i'd suggest you contact them.
Or even better, create a selfpatching scraper and give us a pull request.

**Comment by sniffer54** [comment]
Ok - if I knew what your last sentence even meant then I would certainly do
that.

Thanks for your reply anyway.
