### ISSUE TITLE
Bitporno

### ISSUE THREAD

**Issue by joxdfrt** [dobbelina/repository.dobbelina#720]
### Bug reports:

Search function not Working. 

### OS environment
Firetv Leia 18.5 

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Any bugreports without logfile will be deleted.

**Comment by DJMix-I-Can** [comment]
Search function is working fine on Android & Matrix 19.4. Compared the results to their website & they matched.

**Comment by joxdfrt** [comment]
I checked on my second firetv which is using 19.3 yes search function working but not playing files like ftvgirls for example seems to play other stuff. If someone could double check ftvgirls.

**Comment by DJMix-I-Can** [comment]
Now, none of the videos play, it was playing the other day. 
The log gives this error.
2022-03-11 15:03:38.130 T:4104    ERROR <general>: GetDirectory - Error getting /m3u8/a5a57fc4a2ac55f5fbc9b9e0bc9575ed/H06JG6FC1W/
2022-03-11 15:03:38.143 T:4104    ERROR <general>: Skipped 1 duplicate messages..
2022-03-11 15:03:38.143 T:4104    ERROR <general>: CVideoPlayer::OpenInputStream - error opening [/m3u8/a5a57fc4a2ac55f5fbc9b9e0bc9575ed/H06JG6FC1W/playlist.m3u8]

**Comment by Gujal00** [comment]
SIte gone behind DDOS Guard with Hcaptcha, cant be fixed for now. Have to wait and see if they remove captcha

**Comment by joxdfrt** [comment]
Thanks for trying don’t understand these sites doing this. One can only hope they remove captcha only other place that does ftvgirls is ipornovideos but that’s on ultimate white cream and not updated, Anyone know where else

**Comment by DJMix-I-Can** [comment]
@Gujal00 If I may pick your brain. I'm trying to learn Python & need to spend more time with Regex. There are certain changes I could detect but for example, this issue. How did you determine that the site is behind DDOS guard with captcha? When I go to the site in Firefox or Chrome, I don't see any Captcha. I've also checked behind the scenes as in viewing the source & going into F12 developer options. I'm going to look into more regardless but thought I'd ask. Thanks for your time.

**Comment by Gujal00** [comment]
@DJMix-I-Can Most probably it is location dependent. May be for you it doesn't activate DDOS Guard. This is what I see in browser
![image](https://i.imgur.com/HaA3PxA.png)

**Comment by DJMix-I-Can** [comment]
I don't get that at all when I check through by browser. That is why it throws me off. Regardless, since I don't encounter the DDOS or captcha issue what would be the issue? I'm in the US , East coast. I have also entered Google DNS on my router & static IP address on my Nvidia Shield. Just a troubleshooting FYi info. Thanks for replying..

**Comment by Gujal00** [comment]
They have now removed captcha, and wokring, fix for ftvgirls playback will be in next release

**Comment by dobbelina** [comment]
Will be fixed in the next 1.1.37 release https://github.com/dobbelina/repository.dobbelina/commit/8629e8a20fef20718d7d47e8d56f5275221888ac

**Comment by DJMix-I-Can** [comment]
I just tried the Bitporno fix & it's not working on my end. I don't get the DDOS or capcha on the browser but do notice that they're using Cloudflare.

**Comment by Gujal00** [comment]
@DJMix-I-Can the bitporno fix for ftvgirls playback is in utils.py file, did you update it in your test?

**Comment by DJMix-I-Can** [comment]
> @DJMix-I-Can the bitporno fix for ftvgirls playback is in utils.py file, did you update it in your test?

You are correct, I missed that file. It's working. Thanks..

**Comment by arzezio7** [comment]
What happened to site now? They shut down it because It's now being redirected to bongacams
