### ISSUE TITLE
how to: Add Lesbian PornVideos...

### ISSUE THREAD

**Issue by p060477** [dobbelina/repository.dobbelina#722]
hi, you say you have added it , i've yr latest 1.1.35 and i've also updated..but..i do not see that site added...what's my fault?'..
thxs in adv
cheers

**Comment by dobbelina** [comment]
Will be in the next 1.1.36 update https://github.com/dobbelina/repository.dobbelina/commit/a6647db250d971e94f8586c698bfa5abc23cd865
Will be released tomorrow 13/3
