### ISSUE TITLE
Streaming Issue, Kodi 19.3 and 19.4 Matrix on Nvidia Shield

### ISSUE THREAD

**Issue by DaveyK100** [dobbelina/repository.dobbelina#724]
### Bug reports:

There seems to be issues streaming a lot of the sites using Kodi 19.3 and 19.4 Matrix on Nvidia shield running Android 11.
I have tested this with Eporner and on the Android version of Kodi nothing plays but on the Windows version it plays everything fine.

I have jumped back to Kodi 18 Leia and it seems to work fine on that, Apart from any new sites that get added like perverzija. Which won't work on Kodi 18.0.

I have attached the debug logs for both Windows and Android.

Many Thanks.

### OS environment
Windows 11 and Nvidia Shield running Android 11.

Log files are below.

Windows 
https://paste.kodi.tv/zoreniqejo.kodi

Nvidia Shield running Android 11

https://paste.kodi.tv/opasisozuq.kodi

**Comment by Gujal00** [comment]
Android 11 on nVidia Shield is buggy and they have been patching it frequently, just ensure that you are on the latest patch. From the log all I can say is Kodi FFMPEG has trouble handling mp4 streams when running on Android 11 and the addon such as cumination has no control over it. I test on my Android 9 device and there it works perfectly with kodi 19.4

One additional thing that you can try is using this advancedsettings.xml which may or may not improve things
```xml
<advancedsettings>
	<cache>
		<buffermode>2</buffermode>
		<memorysize>314572800</memorysize>
		<readfactor>8</readfactor>
	</cache>
	<network>
		<disablehttp2>true</disablehttp2> 
	</network>
</advancedsettings>
```

**Comment by DJMix-I-Can** [comment]
As @DaveyK100 I tested it on my Windows laptop & it works. On my Nvidia Shield it doesn't. I noticed on his log that he has also updated to Android 11. I'm on Android 11 Experience version 9.0.2(33.1.0.301)
I also tested it on a different Android device.
This is my debug log from a fresh install on my Samsung phone Android 12 using Kodi 19.3. Eporner does work.
https://paste.kodi.tv/uvonobonaf.kodi

This is my Nvidia Shield Android 11 Experience 9.0.2 with the Hotfixes installed.  Kodi 19.4 fresh install without AdvancedSettings.xml file. I clicked on a video and the busy spinner wheel just kept spinning. Went to throw out the trash, came back and it was still spinning. You could see the 17minute gap in the log. When I click back, it stops but won't be able to get anything else if I select a different video. The whole process screws Kodi up & can't exit correctly. I have to force exit.
https://paste.kodi.tv/yitamafoji.kodi

My original build already had the advancedsettings.xml file & it didn't work but didn't try it on a fresh install.
This is the same shield, same info as above but with the Advancedsettings.xml file.  It doesn't work.
https://paste.kodi.tv/howijonaba.kodi

I also think it's part of the Nvidia Shield Android 11 roll out. Too many bugs.

**Comment by Gujal00** [comment]
@DJMix-I-Can your advancedsettings.xml doesnt have the one important thing that could fix the issue
```xml
	<network>
		<disablehttp2>true</disablehttp2> 
	</network>
```
Please include that and test again if it improves

**Comment by DJMix-I-Can** [comment]
> @DJMix-I-Can your advancedsettings.xml doesnt have the one important thing that could fix the issue
> 
> ```
> 	<network>
> 		<disablehttp2>true</disablehttp2> 
> 	</network>
> ```
> 
> Please include that and test again if it improves

I added disablehttp2 in the advancedsettings.xml file. The video files that weren't playing, are now playing without a hiccup. There are some videos that throw this up, 
![Eporner](https://user-images.githubusercontent.com/35236592/158086148-7019b767-55c5-41c6-a188-2721a34f819e.jpg)
but I guess it's better than nothing. I don't personally use Eporner but thought I'd try some troubleshooting since I also have the Shield. Thanks for your help @Gujal00 Time for some reading on http2, lol

**Comment by Gujal00** [comment]
Kodi 19.x tries to use http2 if exposed by the OS by default and it causes issues with certain sites such as drive.google,.com
So the safest bet is to disable http2 in advanced settings and the problem goes away.

**Comment by DaveyK100** [comment]
Thanks @Gujal00 @DJMix-I-Can  I shall give that a try, and will let you know. All hotfixes have been applied so far. So will try advanced settings hopefully Nvidia will fix this eventually.

**Comment by DaveyK100** [comment]
Thanks @Gujal00 @DJMix-I-Can  I can confirm the AdvancedSettings.xml works a treat.
