### ISSUE TITLE
Site Request: playvids

### ISSUE THREAD

**Issue by DaveyK100** [dobbelina/repository.dobbelina#725]
https://www.playvids.com/

**Comment by fgroul** [comment]
Rub theduck

**Comment by fgroul** [comment]
Porno

**Comment by DaveyK100** [comment]
> https://www.playvids.com/

Hi is this something that been added or is it a tricky one :-)

**Comment by dobbelina** [comment]
Will be in the next 1.1.46 release https://github.com/dobbelina/repository.dobbelina/commit/6175e9fefee1d761c3eaf20d1e2a091e5f03777e
