### ISSUE TITLE
XNXX shows only a few entries

### ISSUE THREAD

**Issue by Kodionpi** [dobbelina/repository.dobbelina#726]
### Bug reports:

Instead of a longer list, only 2-5 videos are displayed per page.
+ the main page offers only 5 pages

### OS environment
Libreelec 10.0.2  Kodi 19.4 ,  Raspberry pi 2b

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Any bugreports without logfile will be deleted.

**Comment by Buddha2400** [comment]
Bug reports:

The same here even when you do a search it combines straight, gay, and transgender categories into one rseach esult 

OS environment

SDMC Jetstream AGT418 with Android 9.0.0 API level 28, kernel: Linux ARM 32-bit version 4.9.113, Kodi 19.4

Logfile with debugging enabled can be uploaded here: http://paste.kodi.tv/voqenaqoju
Any bugreports without logfile will be deleted.

**Comment by dobbelina** [comment]
Will be fixed in the next 1.1.37 release https://github.com/dobbelina/repository.dobbelina/commit/c58d8a18d6d395659881244b7206a82fbfdc66b0

**Comment by p060477** [comment]
also the navigation ahed in the pages 
even if showed for ex:120 pages 
when you try to go ahead the 8th page you are put back on the previous 7th...

**Comment by DJMix-I-Can** [comment]
I just tested this fix.  I hit next up till page 20 & it didn't repeat any previous page.

**Comment by p060477** [comment]
how to test this fix...??

**Comment by DJMix-I-Can** [comment]
@dobbelina provided the fix here https://github.com/dobbelina/repository.dobbelina/commit/c58d8a18d6d395659881244b7206a82fbfdc66b0 What ever is in red is what has been removed & replaced with whats in green.  I have my devices (2 shields, 3 computers & 2 phones) networked. I could make the changes via my laptop or phone. On Android, you would need to go to Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cumination/resources/lib/sites & modify the eporner.py file. If you're on Windows, you would go to C:\Users\"YOUR LOG IN NAME"\AppData\Roaming\Kodi\addons\plugin.video.cumination\resources\lib\sites   In either system, you have to make sure that hidden files is showing. If you're not familiar on how to do this, unfortunately you're going to have to wait for the update.

**Comment by p060477** [comment]
why you write eporner.py...??...

**Comment by DJMix-I-Can** [comment]
> why you write eporner.py...??...

My bad, I still had yesteredays eporner issues in my head. I corrected it, it's the xnxx.py file. Thanks.

**Comment by p060477** [comment]
you are welcome
i've done this following yr isntructions..but now the add on do not start at all...what's my fault..??
[xnxx.txt](https://github.com/dobbelina/repository.dobbelina/files/8248924/xnxx.txt)
i've attached the file here to have yr opinion..obviously i've changed to attach it here the extension from py to txt...
thxs in adv
cheers

**Comment by DJMix-I-Can** [comment]
> you are welcome i've done this following yr isntructions..but now the add on do not start at all...what's my fault..?? [xnxx.txt](https://github.com/dobbelina/repository.dobbelina/files/8248924/xnxx.txt) i've attached the file here to have yr opinion..obviously i've changed to attach it here the extension from py to txt... thxs in adv cheers

Look at this line, " hdr = utils.base_hdrs" It has an extra space. Click behind hdr & go back one & save.

**Comment by p060477** [comment]
apologize me...:
this is what is green in the fix file:
    hdr = utils.base_hdrs
...how have i to modify mine...??...i've only copy-attached the green one from the fix...
thxs again for yr kind helping
cheers

**Comment by DJMix-I-Can** [comment]
Ok, look at this pic. You see how the first line is not lined up with the second line. Click on that line that I mentioned & click backspace. It should be lined up with the second line
![XNXXSpace](https://user-images.githubusercontent.com/35236592/158276502-3a770570-96ca-4fba-8514-ea90a5bf749f.jpg)
.

**Comment by DJMix-I-Can** [comment]
> Ok, look at this pic. You see how the first line is not lined up with the second line. Click on that line that I mentioned & click backspace. It should be lined up with the second line ![XNXXSpace](https://user-images.githubusercontent.com/35236592/158276502-3a770570-96ca-4fba-8514-ea90a5bf749f.jpg) .

It should be like this.
![XNXXCorrect](https://user-images.githubusercontent.com/35236592/158276765-61bfd413-d044-43e6-b69f-2f9c57c24b01.jpg)

**Comment by p060477** [comment]
thxs again for yr kind helping
done...but still unable to start the add on...:
[xnxx.txt](https://github.com/dobbelina/repository.dobbelina/files/8249041/xnxx.txt)
...maybe i've done another mistake...?.. :(
thxs so much
cheers

**Comment by p060477** [comment]
this is the kodi log error..
consider that i've it -portable- so i have to go inside the portable_data folder then addons and so on...

Error Type: <class 'Exception'>
                                                   Error Contents: Error: <function Main at 0x0000024A8609DCA0> already registered as xnxx.Main
                                                   Traceback (most recent call last):
                                                     File "O:\Kodi-19.1_Guruhitech\Kodi\portable_data\addons\plugin.video.cumination\default.py", line 33, in <module>
                                                       from resources.lib.sites import *  # noqa
                                                     File "O:\Kodi-19.1_Guruhitech\Kodi\portable_data\addons\plugin.video.cumination\resources\lib\sites\xnxxnew.py", line 29, in <module>
                                                       def Main():
                                                     File "O:\Kodi-19.1_Guruhitech\Kodi\portable_data\addons\plugin.video.cumination\resources\lib\adultsite.py", line 41, in dec
                                                       func = super_register(f)
                                                     File "O:\Kodi-19.1_Guruhitech\Kodi\portable_data\addons\plugin.video.cumination\resources\lib\url_dispatcher.py", line 54, in decorator
                                                       raise Exception(message)
                                                   Exception: Error: <function Main at 0x0000024A8609DCA0> already registered as xnxx.Main
                                                   -->End of Python script error report<--

**Comment by DJMix-I-Can** [comment]
Ok, I tested your file & it's working. What I think you did was create a backup of XNXX.py file within that sites folder. Remove the backup & just use the one that you modified (the working one). Once you do that, close Kodi & restart.

**Comment by p060477** [comment]
Goal!
You are a genious!
how you ahve been able to do this:ù
" I hit next up till page 20"...:
now at the bottom of the page i've only:
-next page-
i mean that now with the fix  i really do not see the number of the pages..
so how you ahve been able to skip to page 20...??
maybe you have count them by your own without having the number clearly written on the add on pages..??
and you suggest also to modify the changelog.txt file with the info about the 1.1.37 vers?
thxs so much again indeed!
you have been so kind, helpful and patienceable too
cheers
:)

**Comment by DJMix-I-Can** [comment]
You don't get how many pages there are in the next button. I just clicked next, page loaded, click next, page loaded, click next etc.etc. If it's repetitive you would see the same images. That's how I knew. Don't modify the changelog.txt. That's just telling you what the new update has fixed or added to Cumination. Glad to hear it worked out for you. Hey, I'm still learning Python, I'm not a dev at all. The same way you're trying to learn is how I learned what I know. So, paying it forward,  if I can...
Be well...

**Comment by p060477** [comment]
i really wish you all the best
because you deserve it
cheers!

**Comment by DJMix-I-Can** [comment]
> i really wish you all the best because you deserve it cheers!

Thank you. As you as well.

**Comment by Gujal00** [comment]
@DJMix-I-Can @p060477 
Why go through all this pain. When @dobbelina committed the change all you had to do was to get the new file from the git
https://github.com/dobbelina/repository.dobbelina/blob/master/plugin.video.cumination/resources/lib/sites/xnxx.py
and replace it in your install

**Comment by DJMix-I-Can** [comment]
@Gujal00 I understand where you're coming from but in order to learn from the pain, you need to learn how to do it manually. If he/she did what you suggested, they wouldn't learn. I know I didn't when I was learning. I need to see what was going on in the background in order for it to work. I'm learning the hard way as @p060477 might be as well.  Personally, I need to see why certain situations didn't work. Trial & error.

**Comment by Buddha2400** [comment]
@DJMix-I-Can I don't have a knack for programming but what would be the best way to add Quality selection? If you only wanna pull up one type of resolution. And how to keep your search results in one category only ie: straight and not a mash up of the three categories?

**Comment by p060477** [comment]
> @Gujal00 I understand where you're coming from but in order to learn from the pain, you need to learn how to do it manually. If he/she did what you suggested, they wouldn't learn. I know I didn't when I was learning. I need to see what was going on in the background in order for it to work. I'm learning the hard way as @p060477 might be as well. Personally, I need to see why certain situations didn't work. Trial & error.

i totally agree with my very helpfull and patienceable friend DJ-Mix-I-Can,
and to enforce the concept he did not give me a fish...but he taught me how to fishing...
infact what you do Guja is not helpfull and i demostrate with this:
https://github.com/dobbelina/repository.dobbelina/blob/master/plugin.video.cumination/resources/lib/sites/xnxx.py
this link that you have put here and that leads to the new .py file that will be in the nex 1.1.37
how the hell has been discovered..??...
i mean at least explain how you have goit it...
the detailed passages...because it is not really intuitive at all....
the best way to help others is really not showing them how you are skilled in something...but it is to low you down to the ground of the person who needs help...
think of it....
anyway i really wish you all the best too
cheers
