### ISSUE TITLE
https://bestjavs.com

### ISSUE THREAD

**Issue by jegfonseca** [dobbelina/repository.dobbelina#727]
### Bug reports:

Please replace this line with a brief summary of your issue 

### OS environment
What OS, Device, version etc

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Any bugreports without logfile will be deleted.
Good afternoon

could you add the site https://bestjavs.com?

Thanks

**Comment by Gujal00** [comment]
The site hasnt been updated in a while, the hosters they use such as Gounlimited and rapidvideo are long gone. Dont see value in adding this site

**Comment by jegfonseca** [comment]
Thanks
