### ISSUE TITLE
Can you add https://en.avple.tv/

### ISSUE THREAD

**Issue by jhumroo786** [dobbelina/repository.dobbelina#729]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**If it's a site addition request, add url below**
Original Site Link: https://avple.tv/
English Site:
https://en.avple.
Contact : contact@avple.tv
DMCA: https://en.avple.tv/dcma
Thanks in Advance.

**Comment by dobbelina** [comment]
Will be in the next 1.1.38 update https://github.com/dobbelina/repository.dobbelina/commit/fef164536494d065584ceea7dfd39f4cb93246cc

**Comment by jhumroo786** [comment]
Thank you fellas..it's working good. Closing the issue
