### ISSUE TITLE
Can you add https://aagmaal.com/?

### ISSUE THREAD

**Issue by disha9551** [dobbelina/repository.dobbelina#731]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**If it's a site addition request, add url below**

**Comment by dobbelina** [comment]
There's a pull request made that still needs some fixing https://github.com/dobbelina/repository.dobbelina/pull/730

**Comment by dobbelina** [comment]
There's a pull request made that still needs some fixing https://github.com/dobbelina/repository.dobbelina/pull/730
