### ISSUE TITLE
Webcamshows 

### ISSUE THREAD

**Issue by joxdfrt** [dobbelina/repository.dobbelina#732]
### Bug reports:

Search Function not Working for webcam Shows.
What OS, Device, version etc
Fire Tv Matrix 19.3

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Any bugreports without logfile will be deleted.

**Comment by DJMix-I-Can** [comment]
Just tested it on my Shield, Android 11, Kodi 19.4 & Cumination 1.1.37. I searched for three different names & they showed up.

**Comment by joxdfrt** [comment]
That’s strange then only installed latest Kodi version yesterday on my Firetv. Currently running Matrix 19.3 I have Cumination and iplayer as my only Addons. Is there anything else I need. All other sites work with search.

**Comment by DJMix-I-Can** [comment]
Hey @joxdfrt The latest version of Kodi is 19.4 not 19.3. I noticed you've had search issues with Bitporno as well. What you could try is using a VPN to see if it works. If it works with a VPN, then it's a location dependent issue as in Bitporno.

**Comment by joxdfrt** [comment]
Sorted it yes I do use a vpn express vpn. I changed the country to USA from uk and it worked. Much appreciated.

**Comment by DJMix-I-Can** [comment]
Good to hear..
