### ISSUE TITLE
New site japanese

### ISSUE THREAD

**Issue by jegfonseca** [dobbelina/repository.dobbelina#733]
### Bug reports:

Hello

Could you add the site www.javfull.net ?

Thanks

### OS environment
What OS, Device, version etc

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Any bugreports without logfile will be deleted.

**Comment by DJMix-I-Can** [comment]
As they mentioned before.
[That website does not have any Contact or DMCA information.](https://github.com/dobbelina/repository.dobbelina/issues/723#issuecomment-1065965928)

**Comment by jegfonseca** [comment]
Thanks
