### ISSUE TITLE
Categories in XNXX don't work

### ISSUE THREAD

**Issue by stevieland58** [dobbelina/repository.dobbelina#734]
👍🏼

### Bug reports:

Categories in XNXX don't work, so when you get a chance... can't have my wrist healing and retuning to work.

👍🏼

### OS environment
What OS, Device, version etc

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Any bugreports without logfile will be deleted.

**Comment by DJMix-I-Can** [comment]
I'm using Android, Kodi 19.4 & Cumination 1.1.37. Categories directory does load. I went into 4 categories & they all loaded. They also played.

**Comment by dobbelina** [comment]
I get an error to, log snippet https://paste.kodi.tv/adolidumec.kodi

**Comment by DJMix-I-Can** [comment]
@dobbelina Question, If I recall wasn't Cumination created because Kodi Matix was moving to Python 3? If so, should there be any support for those that are still on Leia? I have a portable Kodi Leia installation & categories didn't load for me as well.

**Comment by dobbelina** [comment]
@DJMix-I-Can you are right, That is why Cumination was created.
@stevieland58 needs to update kodi.

**Comment by dobbelina** [comment]
Will be fixed in the next 1.1.39 update https://github.com/dobbelina/repository.dobbelina/commit/9649dd1469560faba5cc9100cab116ec3aea089a

**Comment by stevieland58** [comment]
Thanks bruh 😎
