### ISSUE TITLE
Chaturbate Webcams Transsexual portal does not work

### ISSUE THREAD

**Issue by scorsese50** [dobbelina/repository.dobbelina#737]
### Bug reports:

Please replace this line with a brief summary of your issue 

### OS environment
What OS, Device, version etc

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Any bugreports without logfile will be deleted.

**Comment by dobbelina** [comment]
Thanks @DJMix-I-Can for the fix.
Will be in the next 1.1.39 update https://github.com/dobbelina/repository.dobbelina/commit/1a4d0c4955dcecded85ee0c9e721e231e644aedf
