### ISSUE TITLE
Came soda is not working 

### ISSUE THREAD

**Issue by Highway1409** [dobbelina/repository.dobbelina#741]
### Bug reports:

Please replace this line with a brief summary of your issue 

### OS environment
What OS, Device, version etc

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Any bugreports without logfile will be deleted.

**Comment by Highway1409** [comment]
Not pulling up

**Comment by DJMix-I-Can** [comment]
Cam Soda is working on Android & Kodi 19.4. You should provide more details as the template requested.
OS environment

What OS, Device, version etc

**Comment by dobbelina** [comment]
@Highway1409 
1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

**Comment by dobbelina** [comment]
Incomplete bug report, closing.
