### ISSUE TITLE
Xxxstreams.org

### ISSUE THREAD

**Issue by joxdfrt** [dobbelina/repository.dobbelina#743]
### Bug reports:

Showing Cumination Error when searching won’t load video. Also the filehost k2s when it does work only shows video for 30 secs can this not be changed.
### OS environment
What OS, Device, version etc
Firetv 4k Matrix 19.3

Logfile with debugging enabled can be uploaded here: https://paste.kodi.tv/
Any bugreports without logfile will be deleted.

**Comment by Gujal00** [comment]
It was already answered in the issue you raised earlier #701 
Why raise the same issue again?

**Comment by dobbelina** [comment]
Closing issue.
