### ISSUE TITLE
Add this please : https://beemtube.com/

### ISSUE THREAD

**Issue by jhumroo786** [dobbelina/repository.dobbelina#747]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**If it's a site addition request, add url below**
Sites with no DMCA information will not be added

Contact: https://beemtube.com/contact
DMCA: https://beemtube.com/static/dmca

Hope for the addition. Thanks

**Comment by dobbelina** [comment]
Will be added in the next 1.1.40 release https://github.com/dobbelina/repository.dobbelina/commit/efc5c871803950b17a20c2f91aff42d0ceca9ba9

**Comment by jhumroo786** [comment]
Arigato Madame, Arrivederci
