### ISSUE TITLE
Avple not working

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#751]
Here is the log:
https://paste.kodi.tv/ohajecafuj

**Comment by dobbelina** [comment]
Will be fixed in the next 1.1.40 version https://github.com/dobbelina/repository.dobbelina/commit/22aec7ba6430b8d7bce0d7043fee2f8e5226ded4

**Comment by DJMix-I-Can** [comment]
> Will be fixed in the next 1.1.40 version [22aec7b](https://github.com/dobbelina/repository.dobbelina/commit/22aec7ba6430b8d7bce0d7043fee2f8e5226ded4)

@dobbelina What's up Dobbelina, can you double check on that new site Beemtube. Next page is not working, thought I'd mention it before releasing it. Thanks, be well.

**Comment by dobbelina** [comment]
@DJMix-I-Can thanks for the heads up!
@12asdfg12 can you have a look?

**Comment by 12asdfg12** [comment]
Next page works for me, did you update utils.py?

**Comment by dobbelina** [comment]
> Next page works for me, did you update utils.py?

@DJMix-I-Can I was just gonna say that, it works for me with the modified utils.py

**Comment by DJMix-I-Can** [comment]
@dobbelina @12asdfg12 My apologies, I missed updating that utils.py file.  It's working. Thanks..

**Comment by imurreflection** [comment]
Just realised that avple fix works on the first page only. If you click any Tag, you will not find any results. 
It is mainly because english version of the site works only on first page and may be on very few tags. When we change the site url to avple.com instead of en.avple.com, everything works fine. I edited the .py file and there is no issue in playback. Please check and if you deem fit, incorporate. Thanks

**Comment by dobbelina** [comment]
@imurreflection that's a good idea, https://github.com/dobbelina/repository.dobbelina/commit/f073c2e34ade661acad15cb2ada84274eee2661d
