### ISSUE TITLE
Can you Add goodporn.to site?

### ISSUE THREAD

**Issue by Napster955** [dobbelina/repository.dobbelina#754]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**If it's a site addition request, add url below**
Sites with no DMCA information will not be added

Site: https://goodporn.to/

**Comment by imurreflection** [comment]
Helping the OP as he may not be aware of Contact and DMCA requirement

DMCA: https://goodporn.to/dmca/
Contact: clicking "support" link takes you directly to contact form

**Comment by dobbelina** [comment]
Will be in the next 1.1.41 release https://github.com/dobbelina/repository.dobbelina/commit/36607378c80a98af93157429581bde53158bcd3f
