### ISSUE TITLE
Vidoz8 not working

### ISSUE THREAD

**Issue by neptunus123** [dobbelina/repository.dobbelina#755]
### Bug reports:

Vidoz 8 site is not working.

### OS environment
What OS, Device, version etc

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.

**Comment by DJMix-I-Can** [comment]
It's working on Android. Studios, tags, search, pagination & video playback are functioning.

**Comment by dobbelina** [comment]
Working on windows to.
Closing issue, logfile missing.
