### ISSUE TITLE
Paradies Hill search no hits

### ISSUE THREAD

**Issue by xerel89** [dobbelina/repository.dobbelina#756]
### Bug reports:

No search hits on this site

### OS environment
What OS, Device, version etc

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.

**Comment by xerel89** [comment]
Ok I got not search hits for pornstars...

**Comment by DJMix-I-Can** [comment]
I did get results when I searched pornstars. Any chance you're using a VPN? A debug log should also shed some light.

**Comment by xerel89** [comment]
I can make a debug log later and I don't use a VPN
