### ISSUE TITLE
netflixporn

### ISSUE THREAD

**Issue by demex2008** [dobbelina/repository.dobbelina#757]
hello can you fix the Site netflixporn
mfg.

**Comment by dobbelina** [comment]
A fix will be in the next release 1.1.41 https://github.com/dobbelina/repository.dobbelina/commit/681ca0542f28bdbeb5b0b0e8cbb93f1b108d7abb

**Comment by Bigdane14** [comment]
It's still messed up netflixporn and speedporn

**Comment by Bigdane14** [comment]
> hello can you fix the Site netflixporn
> 
> mfg.
> 
> 

Please

**Comment by dobbelina** [comment]
> It's still messed up netflixporn and speedporn

Fix hasn't been published yet.
Did you apply the fix manually?
Fix works for me.

**Comment by Bigdane14** [comment]
> > It's still messed up netflixporn and speedporn
> 
> 
> 
> Fix hasn't been published yet.
> 
> Did you apply the fix manually?
> 
> Fix works for me.

How do I?

**Comment by dobbelina** [comment]
Wait for version 1.1.41 that will be released on Sunday.
