### ISSUE TITLE
Sextb and daftsex

### ISSUE THREAD

**Issue by jegfonseca** [dobbelina/repository.dobbelina#763]
### Bug reports:

Good morning

Daftsex and sextb is not working on kodi matrix
IT is not open videos
Thanks 

### OS environment
What OS, Device, version etc

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.

**Comment by dobbelina** [comment]
Both sites work for me on windows, please provide a logfile.

**Comment by DJMix-I-Can** [comment]
Also working on Android.
Tested Sextb Amateur, Censored, Uncensored Leak, Refucing Mosaic, Subtitle, Genres, Actress & Studios. All the directories loaded and the videos played.

Tested Daftsex & categories. Everything loaded & videos played as well.

As Dobbelina suggested, provide a debug log file.

**Comment by jegfonseca** [comment]
Ok

Thanks

**Comment by dobbelina** [comment]
No log file closing issue.
