### ISSUE TITLE
pornkinox

### ISSUE THREAD

**Issue by houseman100** [dobbelina/repository.dobbelina#765]
Site dont Play Videos pls can you fix it

**Comment by DJMix-I-Can** [comment]
Same as well with Android. As I'm still learning Python and can help with what I can.  I'll take a crack at this, if I'm wrong. I know the devs will correct me. I believe the video links are now behind the keeplinks captcha.

**Comment by dobbelina** [comment]
Will be fixed in the next release 1.1.43 https://github.com/dobbelina/repository.dobbelina/commit/0065979206ce3dba13c8f85dced1815644a2e2aa
