### ISSUE TITLE
Can you please add ghettotube.com

### ISSUE THREAD

**Issue by Kaveon2022** [dobbelina/repository.dobbelina#766]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**If it's a site addition request, add url below**
Sites with no DMCA information will not be added
https://ghettotube.com
DMCA
https://ghettotube.com/dmca/

**Comment by dobbelina** [comment]
Will be in the next update https://github.com/dobbelina/repository.dobbelina/commit/d7284bf98d17a7c14cd678652d1ed5c31d95fd20
