### ISSUE TITLE
 script.module.six version 0.0.0 could not be satisfied

### ISSUE THREAD

**Issue by rogerwee** [dobbelina/repository.dobbelina#767]
### Bug reports:

I am trying to install cumination repo, during install it would show the dependency on script.module.six version 0.0.0 could not be satisfied, can anyone assist? currently using kodi 19.3 Thanks

**Comment by dobbelina** [comment]
Try installing the script module from zip file http://mirrors.kodi.tv/addons/matrix/script.module.six/script.module.six-1.15.0+matrix.1.zip

**Comment by antoniosobarzo** [comment]
Exactly the same thing happens to me, I cannot install the plugin. Alpha appears script.module.js2py version 0.0.0 cannot be satisfied and I have tried to install other modules that have been recommended but nothing works, I really don't know what to do anymore I just don't think I will be able to continue using Kodi on mac

**Comment by antoniosobarzo** [comment]
http://mirrors.kodi.tv/addons/matrix/script.module.six/script.module.six-1.15.0+matrix.1.zip.     this  zip don't work
