### ISSUE TITLE
FREEOMOVIE

### ISSUE THREAD

**Issue by Scharnhorst1939** [dobbelina/repository.dobbelina#768]
Hello,
There is a Problem on xbox with Freeomovie. Everytime come error when Start watch.
Please help

**Comment by dobbelina** [comment]
1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

**Comment by dobbelina** [comment]
No log file closing issue.
