### ISSUE TITLE
Pornwild.com

### ISSUE THREAD

**Issue by xerel89** [dobbelina/repository.dobbelina#769]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Please add pornwild 
https://pornwild.com/de/2257/
Sites with no DMCA information will not be added

**Comment by dobbelina** [comment]
Will be in the next 1.1.42 release https://github.com/dobbelina/repository.dobbelina/commit/28dbac7ec0ee1b0152fc8faac48d15f13551659e
