### ISSUE TITLE
Porn00 not working .... quick fix

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#77]
Porn00 is not listing properly.  A simple fix is to slightly change the RegEx in line 60 of the file hdporn.py where the Porn00 code is located:
`match = re.compile('<h2>\s+<a title="([^"]+)".*?href="([^"]+)".*?src="([^"]+)" class="attachment-primary-post-thumbnail', re.DOTALL | re.IGNORECASE).findall(listhtml)`        

(A more general  .*? is substituted for the original space " " before the href to skip unneeded HTML. )

**Comment by dobbelina** [comment]
Beautiful, thanks jdoedev123!

Will incorporate in next update.

**Comment by dobbelina** [comment]
It broke again.

**Comment by jdoedev123** [comment]
Not quite working yet. Fixed video list with change another change to line 60:
        match = re.compile('<div class="image">.*?<a title="([^"]+)".*?href="([^"]+)".*?src="([^"]+)" class="attachment-', re.DOTALL | re.IGNORECASE).findall(listhtml)

Fixed Pagination with a more complicated fix.
Video playback not working in Porn00.
Video playback also (mostly) not working in PornAQ

**Comment by dobbelina** [comment]
Thanks for you effort jdoedev123!

I'll look forward to the finished product once you are done.

**Comment by jdoedev123** [comment]
This is not complete. Listings and pagination work but the critical playback does not for Porn00. Playback also a problem in the PornAQ code in the same file.
[hdporn.py.zip](https://github.com/dobbelina/repository.dobbelina/files/3572518/hdporn.py.zip)

**Comment by 12asdfg12** [comment]
fixed
[hdporn.zip](https://github.com/dobbelina/repository.dobbelina/files/3575668/hdporn.zip)

**Comment by dobbelina** [comment]
Thumbs up for you 12asdfg12!

**Comment by jdoedev123** [comment]
Well done 12asdfg12. I like how you seperated the playback code for Porn00 and PornAQ, it was getting confusing.
