### ISSUE TITLE
xvideos pagination failure

### ISSUE THREAD

**Issue by hiller8** [dobbelina/repository.dobbelina#771]
### Bug reports:

in the 'tags' section you can choose whatever subsection you want
then you get the list with videos and at the bottom it shows how many pages this subsection has
if you continue to the second page you get exactly the same list of videos like on the first page
if you continue to further pages the behavior is the same
indeed you are on the x-th page, if you want to go back, you have go through all the pages until you reach the beginning

in rare cases i witnessed this in the 'categories' section too

### OS environment
H96 Pro+ (3MB), Kodi 18.9, CoreELEC 9.2.8, Cumination 1.1.41
no error message, hence no log-file

**Comment by dobbelina** [comment]
Issue confirmed, thanks for reporting.
