### ISSUE TITLE
Free porn streams site: can’t search

### ISSUE THREAD

**Issue by bodyjar4** [dobbelina/repository.dobbelina#772]
Hello. Completely new to this and not certain if I am following protocol correctly. Apologies if not. I wanted to report an issue - For the “free porn streams” site, there is no option to view page 2 and beyond after page 1 (the first page you see when you select the site).  Also, when pressing search, no key words entered ever identify a hit, even if the key word is located in one of the titles visible from the first page. Not sure if this is a big, all the sites seem to work a bit differently so I am still trying to figure it out. Will supply more details as needed.

**Comment by dobbelina** [comment]
Issue confirmed, thanks for reporting.

**Comment by dobbelina** [comment]
Will be fixed in the next release 1.1.43 https://github.com/dobbelina/repository.dobbelina/commit/0065979206ce3dba13c8f85dced1815644a2e2aa
