### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by me30122** [dobbelina/repository.dobbelina#773]
### Bug reports:

So many sites not working. For eg : if you go in aagmaal and open video it will give you error. Same happens to some other sites also.

### OS environment
Amazon fire cube

**Comment by dobbelina** [comment]
"Not working" is not sufficient for a bug report, logfile also missing.
Deleting.

**Comment by Gujal00** [comment]
@me30122
Depends on your location. If a site is not working in cumination, check if it is working on your browser. If you are in India, for e.g, there is lot of ISP blocking and the addon cant do anything about it
