### ISSUE TITLE
Cumination - Chaturbate Catagories

### ISSUE THREAD

**Issue by flhthemi** [dobbelina/repository.dobbelina#775]
### Bug reports:
Chaturbate catagories Female/18-21 Female Cams/more
Seems female Tags has issues too
When trying to open them Kodi just locks up with a busy screen and has to be force closed.

### OS environment
Windows 10 PC
Kodi 19.4 Nightly
Current version of Cumination

[kodi.log](https://github.com/dobbelina/repository.dobbelina/files/8732449/kodi.log)

**Comment by scorsese50** [comment]
I am having same issue on all categories.

**Comment by flhthemi** [comment]
> I am having same issue on all categories.

My favorites that were saved from Chaturbate work but I suppose that's because they are direct links. I could only confirm those I mentioned in my bug report. I.m sure there are a lot more I just didn't have time to keep restarting Kodi to test each one. It's probably due to some change at Chaturbate.

**Comment by scorsese50** [comment]
Yes the favorites work for me too.

**Comment by dobbelina** [comment]
Will be a fix for chaturbate in the next release https://github.com/dobbelina/repository.dobbelina/commit/b46b1a41dab735ff0394e030a64380c55cbde9ff

**Comment by milleniaxx** [comment]
Chaturbate still not working for me, I reinstalled and no luck

**Comment by scorsese50** [comment]
They say it will be fixed in the next update.
