### ISSUE TITLE
ElReyX and others sites don't work in Cumination

### ISSUE THREAD

**Issue by Norwegian11** [dobbelina/repository.dobbelina#776]
Getting "error" messages when I try to play something from both ElReyx and XMoviesforyou in the Cumination app. Been like this for almost 2 weeks.
F.ex HqPorner and Eporner works, but I miss tjose others, that normally gets updated with content several times a day..
Please help..

**Comment by dobbelina** [comment]
Both ElReyx & XMoviesforyou works under windows, so you need to provide a logfile to pinpoint the issue.
1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

**Comment by Norwegian11** [comment]
Only works under windows?
All my units are Android based..Mobile, Android TV and Android box...

fre. 20. mai 2022, 08:03 skrev dobbelina ***@***.***>:

**Comment by dobbelina** [comment]
Deleting, no logfile provided.

**Comment by Norwegian11** [comment]
I provided a url with logfile. Seriously?


lør. 21. mai 2022, 08:14 skrev dobbelina ***@***.***>:

**Comment by Norwegian11** [comment]
https://paste.kodi.tv/esotinuhat

fre. 20. mai 2022, 08:03 skrev dobbelina ***@***.***>:

**Comment by 12asdfg12** [comment]
You have an error in the log file from resolve.url, try to reinstall the script.module.resolveurl and script.module.resolveurl.xxx addons.

**Comment by Norwegian11** [comment]
Have tried that. Still not working. When I use HQPorner, I get the videos.
But not from the sites that offer several hosts..


søn. 22. mai 2022, 13:59 skrev 12asdfg12 ***@***.***>:

**Comment by 12asdfg12** [comment]
In the log file, the ResolveURL version is 5.1.64, and the latest version is 5.1.68. Make sure you have the latest version.

HQPorner uses an internal video host and does not use the script.module.resolveurl plugin, so it works.
Other sites that use external video hosts do not work without ResolveURL .
You should resolve the issue with ResolveURL, Cumination is working fine.

**Comment by Norwegian11** [comment]
Ok...I will try again.
It was working fine until 1,5 weeks ago..
Thanks for the support. I appreciate that.

søn. 22. mai 2022, 21:24 skrev 12asdfg12 ***@***.***>:

**Comment by Norwegian11** [comment]
https://paste.kodi.tv/esotinuhat

fre. 20. mai 2022, 10:14 skrev Min Mail ***@***.***>:
