### ISSUE TITLE
Site addition request www2.javhdporn.net

### ISSUE THREAD

**Issue by jegfonseca** [dobbelina/repository.dobbelina#779]
Hello

Could you add a new sites ?

https://www2.javhdporn.net

https://www2.javhdporn.net

Have a good day

Thanks

**Comment by jegfonseca** [comment]
> Hello
> 
> Could you add a new sites ?
> 
> https://www2.javhdporn.net
> 
> https://www2.javhdporn.net
> 
> Have a good day
> 
> Thanks

Please respond me

Thanks

**Comment by dobbelina** [comment]
Will be in the next 1.1.50 release https://github.com/dobbelina/repository.dobbelina/commit/41610d393f4977f971caafcc60047f96cf72634b

**Comment by jegfonseca** [comment]
Thanks
