### ISSUE TITLE
Back ups 

### ISSUE THREAD

**Issue by xyz236** [dobbelina/repository.dobbelina#78]
On Leila back up favorites and keywords does not work. It will say you backed it up but if you clear it and try to restore your favorites or keywords you will be promoted “invalid back up”

**Comment by Sameer888** [comment]
Always save your backup manually its easy: 

Go to
 Internalstorage/Android/org.xbmc.kodi/files/kodi/userdata/addon_data/   you will see plugin.program.super.favourites & plugin.video.uwc

Copy both to any folder on Mmc and save it and do viceversa when ever you want your backup

Its simple

**Comment by xyz236** [comment]
I tried your method it works but not as convenient as it was on the add on, this stopped working when I went from 17.6 to 18.2 hopefully dobbelina can fix this. Thanks for the advice.

**Comment by 12asdfg12** [comment]
I tested the backup/clear/restore functions in Kodi versions 17.6, 18.2 (windows) and 18.3 (linux), and it works. Maybe you tried to restore the favorites in keywords or keywords in favorites.
You can open the backup files in winrar and check the content, the backup is just a compressed textfile.
Or check the logfile for errors.

**Comment by DJMix-I-Can** [comment]
I remember when Leia first came out, any type of backup(zipping) that was installed on Android did not work. It worked on windows but not Android. I recall reading on a Kodi forum that when Leia was being developed, they didn't have a dedicated Android developer to assist on Leia, hence the problems. Is it true? Maybe. When Leia first came out is when I started having back up & restore problems on Android, not on Windows though. This is when UWC backup and restore started failing on my Android devices. I wound up getting used to backing up my file manually like Sameeer888 suggested. I became so used to just backing it up manually that I didn't even retry after the Leia updates. Reading this made me try it again and as for me, it works on both Windows and NOW on two of my Android devices (phone & Nvidia Shield).  I'm using the 1.1.91 and on Leia 18.3. It could be the problem still persists on 18.2.

**Comment by xyz236** [comment]
Yes it’s failing to back up on Android devices I tried two separate android devices both say “invalid  back up file” and has failed on me with 18.2 as well as 18.3 hopefully soon there will be fix. Thanks for the feedback guys.

**Comment by DJMix-I-Can** [comment]
Honestly, it's not UWC, it's working the way it's suppose to work.  Have you tried uninstalling UWC completely, also make sure the folder is not under userdata, addon_data and delete the plugin.video.uwc folder that's in there. Reinstall UWC and see if you get any dependency errors.

**Comment by xyz236** [comment]
No I have not tried that yet I will give it shot when I get home.fingers crossed.

**Comment by DJMix-I-Can** [comment]
Just make sure you manually back up your favorites and keywords before deleting it. You don't want to loose all of your info...
