### ISSUE TITLE
Playback error for jav guru 

### ISSUE THREAD

**Issue by nikitronica** [dobbelina/repository.dobbelina#780]
### Bug reports:

Please fix the playback error for JAV GURU, thank you.

### OS environment
What OS, Device, version etc

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.

**Comment by dobbelina** [comment]
Works for me with "Stream FE & Stream ST" option.
No logfile provided.

**Comment by Gujal00** [comment]
Stream DD should also work
Stream SB and Stream VO will work once updated ResolveURL is released.

**Comment by nikitronica** [comment]
Works again after updated the ResolvedURL.

thanks.
