### ISSUE TITLE
Viral Videos Porno stopped working

### ISSUE THREAD

**Issue by tetzy** [dobbelina/repository.dobbelina#781]
Cumination no longer downloads or plays files from Viral Videos Porno.

Log file here:

https://paste.kodi.tv/fatumabono

**Comment by dobbelina** [comment]
New clips seems to play well from doodstream, older clips and movies don't play at all.

**Comment by Gujal00** [comment]
Correct, the older clips and movies mostly have only download option from premium hosters. If you have debrid account and enabled universal resolvers in settings and if the premium hoster is supported by your debrid provider, then it will play using that.
Check the web site if in doubt.
