### ISSUE TITLE
Cumination

### ISSUE THREAD

**Issue by gayala27** [dobbelina/repository.dobbelina#784]
### Bug reports:

Freeomovies and NetflixPorn not working. 
OS Android. TV Box

### OS environment
What OS, Device, version etc

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

http://paste.kodi.tv/owibaqewiz
http://paste.ubuntu.com/p/W8mncQHTvF

Any bugreports without logfile will be deleted.

**Comment by Gujal00** [comment]
From your log
```
INFO <general>: CAddonMgr::FindAddons: script.module.resolveurl v5.1.68 installed
INFO <general>: CAddonMgr::FindAddons: script.module.resolveurl.xxx v2.1.17 installed
```
Those two wont work together
You have resolveurl repo installed yet the origin repo for resolveurl and resolveurl.xxx are some other repos feeding you incompatible versions
```
ADDONS: update check: addonID = repository.resolveurl / Origin = repository.resolveurl / Version = 1.0.0
ADDONS: update check: addonID = script.module.resolveurl / Origin = repository.doomzday / Version = 5.1.68
ADDONS: update check: addonID = script.module.resolveurl.xxx / Origin = repository.DejaVu / Version = 2.1.17
```
Update the two addons from resolveurl repo and your problem will be solved
