### ISSUE TITLE
Motherless Site addition

### ISSUE THREAD

**Issue by DJMix-I-Can** [dobbelina/repository.dobbelina#786]
What's up guys.... I've been playing with this site for a while. As some of you are aware, I'm trying to learn Python but I've been getting busy and not having much time to mess with it much. I picked some of the coding from a defunct addon & noticed this has been a request as well. As of right now, the directory loads, pagination works & the videos play. My issues are with Being Watched Now, it doesn't refresh when I click on Refresh Page. In Galleries, directories load correctly but when I click on either directory, they're all the same listing. The same with the Groups directory. The search function is a hit or miss & believe pagination doesn't work.  I did not set this up as an import for a custom site. Hopefully someone can correct this. Thanks
[motherless.zip](https://github.com/dobbelina/repository.dobbelina/files/8810538/motherless.zip)
.

**Comment by 12asdfg12** [comment]
[motherless.zip](https://github.com/dobbelina/repository.dobbelina/files/8840204/motherless.zip)

Fixed and created a custom site.

**Comment by DJMix-I-Can** [comment]
> Fixed and created a custom site.

Thanks @12asdfg12 I appreciate it.
