### ISSUE TITLE
small fix for beeg

### ISSUE THREAD

**Issue by 12asdfg12** [dobbelina/repository.dobbelina#79]
fixed categories with space in names
[beeg.zip](https://github.com/dobbelina/repository.dobbelina/files/3478058/beeg.zip)

vidz7 can be removed, the website is gone.
hdpornz.py file is present in the archive, but not in default.py, it must be added again

**Comment by DJMix-I-Can** [comment]
Hey @12asdfg12 I just dumped the file into the sites folder and it's not working. No main or categories list...

**Comment by 12asdfg12** [comment]
Right, an old bug, I thought i fix it already, don't work unless the version is saved in the settings.
Try this:
[beeg.zip](https://github.com/dobbelina/repository.dobbelina/files/3478520/beeg.zip)

**Comment by DJMix-I-Can** [comment]
That worked.... A heads up though, I don't usually use that site but when you search using more than one word ex:big breasts, it doesn't search. It would only search single words. The website actually gives you their suggestions when you start typing.  So, in case someone mentions that the search function doesn't work, it partially does but only for single word searches.

**Comment by dobbelina** [comment]
Thanks 12asdfg12,

vidz7 will be replaced with Hdpornz in next update.

**Comment by 12asdfg12** [comment]
Search on beeg works only with predefined keywords, if you are searching for something different it will not return anything, this is normal and cannot be fixed in uwc

**Comment by dobbelina** [comment]
Seems like beeg changed something again, it's empty again.

**Comment by 12asdfg12** [comment]
Fixed and improved version (added quality selector,  quality not limited to 720p, added channels, and video duration)
[beeg.zip](https://github.com/dobbelina/repository.dobbelina/files/3530582/beeg.zip)

**Comment by 12asdfg12** [comment]
+ fix for porndig
[porndig.zip](https://github.com/dobbelina/repository.dobbelina/files/3530601/porndig.zip)

**Comment by dobbelina** [comment]
Thanks 12asdfg12,

Awesome!
