### ISSUE TITLE
JAV Moe playback - Cumination

### ISSUE THREAD

**Issue by Xevo666** [dobbelina/repository.dobbelina#790]
Very high percentage of links on this site do not connect/playback.

Would be good if they did !!!

**Comment by Gujal00** [comment]
Would be helpful if you can provide a debug log

**Comment by dobbelina** [comment]
A fix has been provided, will be in the next 1.1.45 release https://github.com/dobbelina/repository.dobbelina/commit/b24e2eee7d18c87a08601045c7631b936c02455c
