### ISSUE TITLE
Paradisehills not displaying properly

### ISSUE THREAD

**Issue by Zee346** [dobbelina/repository.dobbelina#791]
when using Paradisehills, it displays a limited number on the initial screen.  Searching using keywords and/or categories only returns a limited number, and the titles do not match the pictures shown.  The search function still works correctly, and the website is still functioning correctly as well.  Hope you can fix this..

**Comment by dobbelina** [comment]
A fix has been provided, will be in the next 1.1.45 release https://github.com/dobbelina/repository.dobbelina/commit/8ba4f53705ab52f27fcd4f2c33f92b5523b64262
