### ISSUE TITLE
Delete Cookie file button

### ISSUE THREAD

**Issue by EvelK1203** [dobbelina/repository.dobbelina#793]
Is if possible to add  a feature that will easily allow deletion of the cumination cookie file? Maybe something similar to the clear local cache?

Reason for asking is some sites will change the default viewing genre, Xvideos and XNXX I've noticed but there might be others. Only way to fix is to delete the cookies.lwp file.

Thanks

**Comment by dobbelina** [comment]
A fix has been provided, will be in the next 1.1.45 release https://github.com/dobbelina/repository.dobbelina/commit/305bac67c04b97440d2b5927e6511757d8445b1b
