### ISSUE TITLE
I've tried everything possible, if anybody has any ideas what is the problem with my kodi freezing help me please?

### ISSUE THREAD

**Issue by frankee123** [dobbelina/repository.dobbelina#796]
This isn't something I can make a log file for, what happens when I'm trying to play most videos or scenes from Cumination, the file tries to play as I see the circle in the middle start spinning and it will say the title of the video on top right I'm trying to play. The issue is, that is as far as it will go and nothing ends up playing. I literally have no choice but to manually close out Kodi and open it again. It is happening on Spankbang which is one app I really enjoy, as well as many others like Camwhoresbay, and SxyPrn. The only one that seems to work all the time for me is PornTrex and any cam girls from MFC and Chaturbate. I have tried uninstalling Cumination and reinstalling. I have also tried doing the same to kodi. I even thought maybe it was the new kodi 19.4 for some reason so I currently went back to 19.3, but it still is happening. I cannot think of as to why the freezing is happening, but I can't take it anymore. I am using a new 4k android box as well so I really am lost. If anybody has any ideas at all, it would greatly be appreciated. I tried to report this as an issue weeks ago, but simply cannoy since it is freezing my kodi altogether and I was not able to provide the needed details. Ty

**Comment by 12asdfg12** [comment]
If your Kodi is frozen and you need to restart it, a new log file is created and will not contain any useful information.
But in this case, the previous log file is available as kodi.old.log which contains all the information before the crash.
So you need to share kodi.old.log instead of kodi.log
Read more here: https://kodi.wiki/view/Log_file
Also, you may check how these sites work on your device in a web browser.

**Comment by frankee123** [comment]
Ty so much for the response. I'm kind of confused at how to do what you post, but I will try to figure it out and post it at some point. Ty again.

**Comment by frankee123** [comment]
So what I did was I clicked on a vid from spankbang that did the usual thing where it tried to play it but didn't. I then hit cancel and went right to upload kodi log. I don't see anywhere for the old kodi log though sorry. I'm not sure if this shows anything but here it is anyway. http://paste.kodi.tv/esilofobas

**Comment by frankee123** [comment]
What happens after I hit cancel on something that does not play like I posted from above, is if I go to try to hit on anything else and play any other thing (even if it works like a camgirl or a scene from porntrex) that is when Kodi freezes. All I have been trying to is play vids from spankbang etc that have not been working, and I have to restart kodi when I do since after trying, nothing works and it will freeze up.

**Comment by frankee123** [comment]
I think I finally got the old kodi log to work. So After I manually closed out kodi after trying to play a scene from SpankBang, hopefully this will show something? https://paste.kodi.tv/deqekewifi

**Comment by Gujal00** [comment]
Need a Log with `DEBUG` turned on

**Comment by frankee123** [comment]
But doesn't that not work if I have to close kodi? I made a thread few weeks ago and they said there wasn't anything to show since I closed kodi manually. I will stil ltry this and see what happens though. Sorry, I am not good with this kind of thing. I really appreciate the help and info guys.

**Comment by frankee123** [comment]
> Need a Log with `DEBUG` turned on

So friend, I just turned debug on, tried to play one scene from spankbang which never loaded. So I had to manually quit kodi and reopen. So hopefully this old kodi log is what you need? https://paste.kodi.tv/uwisukadod

**Comment by Gujal00** [comment]
The issue seems to point to Kodi Videoplayer (FFMPEG),
```
DEBUG <general>: CurlFile::Open(0x794693c430) https://vdownload-2.sb-cd.com/1/1/11677126-1080p.mp4?secure=LSRPlVJ__NRBHdEx8sgTAg,1655730801&m=2&d=4&_tid=11677126

DEBUG <general>: CFileCache::Open - <https://vdownload-2.sb-cd.com/1/1/11677126-1080p.mp4?secure=LSRPlVJ__NRBHdEx8sgTAg,1655730801&m=2&d=4&_tid=11677126> using double memory cache each sized 10485760 bytes

INFO <general>: Creating Demuxer
DEBUG <general>: Open - probing detected format [mov,mp4,m4a,3gp,3g2,mj2]
DEBUG <general>: ffmpeg[0x79d68c9f30X]: [mov,mp4,m4a,3gp,3g2,mj2] reached eof, corrupted STCO atom
ERROR <general>: ffmpeg[0x79d68c9f30X]: [mov,mp4,m4a,3gp,3g2,mj2] error reading header
ERROR <general>: Open - Error, could not open file https://vdownload-2.sb-cd.com/1/1/11677126-1080p.mp4?secure=LSRPlVJ__NRBHdEx8sgTAg,1655730801&m=2&d=4&_tid=11677126
ERROR <general>: OpenDemuxStream - Error creating demuxer
```
Don't see any way to fix it in the addon. Only thing I can suggest is to upgrade Kodi to 19.4. It is not available in Google Playstore and is available only from Kodi
`http://mirrors.kodi.tv/releases/android/arm64-v8a/kodi-19.4-Matrix-arm64-v8a.apk`

**Comment by frankee123** [comment]
Ty friend, but I actually started with that same 19.4 kodi you have listed. When nothing else worked I uninstalled it and went back to 19.3 I really don't know if I should even bother going to 19.4 or not again, but I guess it couldn't hurt? Ty for the help.

**Comment by frankee123** [comment]
So I just upgraded again to 19.4 and sadly same thing. I'm at a loss at this point. Very frustrating!

**Comment by frankee123** [comment]
Thank you so much for the help, I am just having no luck finding where this advancedsettings.xml file is right now. I went into my file browser on my android box...clicked android....data....org.xbmc.kodi.....files.....but there is nothing in there? Isn't that where the advancedsettings.xml file should be to change what you are telling me?

**Comment by frankee123** [comment]
I tried so many different things. I even tried downloading the open wizard kodi program but it only lets me change the readfactor number to 8 like you posted above. It won't let me select 0 for the buffer mode and I don't see the network in there to change disablehttp2 to true like you have...I'm burnt out lol. I will have to wait to get your help again please. Ty

**Comment by Gujal00** [comment]
The path is
`Android`->`data`->`org.xbmc.kodi`->`files`->`.kodi`->`userdata`
`.kodi` wont be visible unless display hidden files options is set correctly

The easier way to do this is from within kodi itself. create the `advancedsettings.xml` file in your pc and put on a usb flash drive. Plug in the usb flash drive on to your shield.
Start Kodi, go to gear wheel - file manager
There it will show you `profile directory` which is the folder where advancedsettings.xml needs to be copied. so select profile directory on one side and usb drive on the other side, select the file and copy

**Comment by frankee123** [comment]
I F*cking love you bro! It worked! Thank you so much. doing that from within Kodi worked and thank you for making it easy to understand and for all for your help and trouble!!!
