### ISSUE TITLE
new site add

### ISSUE THREAD

**Issue by sagg13** [dobbelina/repository.dobbelina#797]
can you add a new sites ?

https://www.amateur.tv/

Thanks

**Comment by Gujal00** [comment]
This site can't be done as it delivers the streams over websocket and kodi cannot play websocket streams

**Comment by dobbelina** [comment]
Will be in the next release 1.1.47 https://github.com/dobbelina/repository.dobbelina/commit/da3da83deec8b39cb910a434c89647d34d17c0db
