### ISSUE TITLE
Custom SMB folder for Favorites crashes Cumination

### ISSUE THREAD

**Issue by TarkusLV** [dobbelina/repository.dobbelina#798]
### Bug reports:

I set up a custom folder with a copy of my favorites.db on an SMB location, and Cumination crashes immediately when trying to open it.  There is no problem navigating to the folder from the Settings prompt. 

On the native Windows 11 computer containing the folder, it too crashes when using the local network address, but works fine if I use the direct drive path.  So it seems to be an issue with SMB paths.

### OS environment
Fire TV 4K Max & Windows 11

https://paste.kodi.tv/anagafonic

**Comment by Gujal00** [comment]
SQLite3 is embedded-only database so it does not have network connection capabilities. You will need to somehow mount the remote filesystem.

So it has to be mounted as a drive for sqlite3 to function, it cannot handle URI paths such as smb://

**Comment by Gujal00** [comment]
Yes Kodi can because it is a c++ app and use mysql database which is network capable
Addons are python based and use sqlite which only understands local paths

**Comment by TarkusLV** [comment]
> Perhaps a long shot, but it seems you can create symbolic links in the Android system https://stackoverflow.com/questions/41384370/is-it-possible-to-create-a-symbolic-link-on-android

Thanks, I'll have a look!
