### ISSUE TITLE
chaturbate not working

### ISSUE THREAD

**Issue by stemei2013** [dobbelina/repository.dobbelina#8]
just saw that chaturbate isnt working. the thumbnails are loading but videos wont play...

thanks

**Comment by jdoedev123** [comment]
Chaturbate in version 1.1.66 still working on my PC and Android.

**Comment by stemei2013** [comment]
just tried it again, 1.66 running and I keep getting an UltimateWhitecream error as soon as I try to open any chaturbate stream....strange
