### ISSUE TITLE
www.sxyprn.net/

### ISSUE THREAD

**Issue by joxdfrt** [dobbelina/repository.dobbelina#801]
![B2E45215-2318-4B5F-92EC-72088326949A](https://user-images.githubusercontent.com/61237563/174780099-9d14cfdc-8bdf-4d85-9f83-f2907a722749.png)
### Bug 

Videos not playing after search functioned performed. 

Matrix 19.4
Firetv 4k.

### OS environment
What OS, Device, version etc

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.

**Comment by DJMix-I-Can** [comment]
I did 6 different searches, all the videos played. I'm on the Nvidia Shield, Kodi 19.4. 
You also didn't provide a debug file.

OS environment

What OS, Device, version etc

    Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
    Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
    Restart Kodi (Important)
    Go into Cumination and open the site (wait for the error message)
    Come out of cumination
    Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
    launch Kodi Logfile uploader and upload your log. This will give you a url
    provide the url from step 7 here

Any bugreports without logfile will be deleted.

**Comment by joxdfrt** [comment]
If someone wants to tell me how to do a debug file I will. I only have Kodi installed on my Firetv stick I scanned the QR code after following the above instructions. I’ve done numerous searches and none played other sites are working.

**Comment by Gujal00** [comment]
Follow the instructions above correctly to generate DEBUG log, the log above does not contain any DEBUG information during playback, so looks like you missed step 3

**Comment by joxdfrt** [comment]
Followed all the instructions to do the debug log aplogies if wrong I’m no expert. 

https://paste.kodi.tv/ogivokisuc

**Comment by Gujal00** [comment]
Yes that debug log was helpful in locating the issue. Will be fixed in the next release

**Comment by joxdfrt** [comment]
Is this getting fixed in the next update still getting no videos being played. Thanks.

**Comment by dobbelina** [comment]
Is now fixed, closing.
