### ISSUE TITLE
Daftsex

### ISSUE THREAD

**Issue by Tyke101** [dobbelina/repository.dobbelina#802]
All videos on Daftsex freeze Kodi after playing for a few seconds.  There is no error message.  The only way to continue if to force close Kodi.
Using Nvidia Shield Kodi 19.4.
I don’t know whether a logfile will show anything in these circumstances but here it is:
https://paste.kodi.tv/osomigadin

**Comment by Tyke101** [comment]
Thank you for the info.  Do I put that xml file in the Kodi profile
directory?

**Comment by Gujal00** [comment]
Correct put it inside profile directory and restart kodi
