### ISSUE TITLE
Site Addition Request www.camwhores.tv

### ISSUE THREAD

**Issue by marsrover1-ops** [dobbelina/repository.dobbelina#805]
Wondering if you could add Camwhores.tv to the list? I know most content is private, but there are some good public videos available.
https://www.camwhores.tv/

https://camwhores.tv/dmca/

or at the very least provide the zip file so that we could add it as a custom site.
Thanks,

**Comment by marsrover1-ops** [comment]
I was able to create my own custom site for this site. Only issue is that the search results are either random or oldest to newest. Can you offer any insight on how to get the search results to show newest to oldest? Thanks

**Comment by 12asdfg12** [comment]
What search URL are you using?
https://www.camwhores.tv/search/XXXXXX/ returns the results in the newest to oldest order

**Comment by marsrover1-ops** [comment]
I need to reopen this site request. What I developed was working for awhile, but now getting an error. From reviewing the error log, it looks like there is a discrepancy with your main code. So not sure if you changed something or not, but the site won't load anymore. As soon as I can, I will post the error log.

**Comment by 12asdfg12** [comment]
Post the code for your custom site and the log file.

**Comment by marsrover1-ops** [comment]
Not sure what was actually causing the issue, but the site is working again. Thanks
