### ISSUE TITLE
JAVwhores not loading videos

### ISSUE THREAD

**Issue by s4ik0s4n** [dobbelina/repository.dobbelina#81]
I've been using is add-on since before dobbelina tookover development. For around the last week or so, whenever I try to load a long video in JAVWhores, the video appears to be play, then just stops and goes back to the selection screen. I've tried this with multiple videos on each level of quality. Shorter videos will play, and if im patient enough and keep selecting the same video, sometimes longer videos will play. I even upgraded from using a Firestick to a Shield TV with no difference. Is this an issue with the website, Kodi, the add-on, or my settings? I've tried it both logged in and logged out of a JAVWhores account. If this isn't an issue anybody else is experiencing, feel free to close the issue.

**Comment by jdoedev123** [comment]
How long do the videos play? I assume most of us don't normally test if a video plays all the way through, but we need a time frame to test.

**Comment by jdoedev123** [comment]
A quick check. Short video (~11min) played but longer (~120min) would not play. Checking the kodi logs the longer video URL is valid but times out before playback.

**Comment by s4ik0s4n** [comment]
Yeah, sorry about the late reply. Im at work right now, but I figured I'd ask before I got home. I didn't think I'd get a reply this quickly. So, it's an issue of it timing out before the video plays? Is there a way to increase the time before timeout? Im not going with python or any real coding for that matter.

**Comment by jdoedev123** [comment]
Will check later just doing quick diagnosis. 
About ~50 second delay for VLC to play URL so a much longer delay.

**Comment by 12asdfg12** [comment]
This is not an addon issue, the same thing is happening on a web page, it takes a long time to play long videos.
I think the same issue is described here:
https://forum.kodi.tv/showthread.php?tid=129482

**Comment by s4ik0s4n** [comment]
Would something like Real Debrid help with this issue? Im not quite sure where the videos are hosted for the PornTrex network, but if it's in one of the hosts that Real Debrid works with, it might help. I know Real Debrid is a paid service, but it would still be nice to watch videos on this website again.

**Comment by 12asdfg12** [comment]
These are direct links, real debrid doesn't help. Most of the links works for me, but for the longer links i have to wait more to start. Only the very long links don't start in 30 sec and times out.
