### ISSUE TITLE
Free Porn Streams site - Videos stop playing after 60 seconds

### ISSUE THREAD

**Issue by bodyjar4** [dobbelina/repository.dobbelina#810]
Hello. Most videos (recently added or older) will stop playing at about the 1 minute mark. This includes videos that would previously play for longer. I have tried fast forwarding to later parts of the video and also letting the video play from the beginning with no interruptions but they always stop at around the 1 minute mark (so if i try fast forwarding to the 2 minute mark, the video will simply stop playing). I recall this issue occurring previously, but it seemed to resolve itself after a day or so. The current issue has been ongoing for 3-4 days. This is my favorite site to use so I notice when things go wrong, haha. 

I am happy to provide any further details as needed. I am not receiving any error message after the 60 seconds - The videos simply stop playing as if the whole video was viewed. 

Thanks for all the work you are doing.

**Comment by dobbelina** [comment]
k2s are a premium hoster and only allow 30 seconds of playback for free users
The videos on that site are only uploaded to k2s, they make money by getting users to pay for k2s subscription
https://github.com/dobbelina/repository.dobbelina/issues/442

**Comment by joxdfrt** [comment]
Often thought that myself too, well is it worth keeping the site live then can it not be deleted pretty pointless otherwise.

**Comment by Gujal00** [comment]
yeah it wasn't like this when it was originally added. Now with them only using k2s, it is better that the site is removed from cumination

**Comment by bodyjar4** [comment]
Thank you for the responses and clarification. That's a shame since this site has a variety of videos that other sites don't seem to have (specifically POV FemDom which I can't seem to locate in abundance on the other sites unless someone has any recommendations). And also the search function is fantastic.

**Comment by dobbelina** [comment]
pornkinox.to is also only using k2s.
I think I'll remove both before next release.

**Comment by joxdfrt** [comment]
Thanks
