### ISSUE TITLE
Auto Update?

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#811]
Dear @dobbelina.. cumination is not getting updated automatically for a long time now. I had to download 1.1.48 file manually as i did for last version also. I tried uninstalling your repository and reinstalled 1.0.3 from your git link, still not getting .48 version. The version we have is 1.1.47 only.

Can you please check?

**Comment by dobbelina** [comment]
Works for me.
Do you have "Auto updates" enabled?
<img width="500" alt="screenshot00000" src="https://user-images.githubusercontent.com/46063764/178155917-bfe35737-1f48-44a8-8a68-8252a1dccb70.png">
?

**Comment by imurreflection** [comment]
Yes, it's already enabled

**Comment by joxdfrt** [comment]
Mine updated fine today

**Comment by dobbelina** [comment]
Seems your install is screwed somehow, try https://www.google.com/search?q=kodi+addons+update+problem+-failed

**Comment by imurreflection** [comment]
Ah..it means i have to reinstall Kodi again. Thank you for responding. Closing the issue now

**Comment by dobbelina** [comment]
Wait with that, try to delete/rename the AddonsXX.db file in the profile directory first,(profile/Database)
If you rename the file/s, just rename the extension like AddonsXX.bak
Then restart kodi
