### ISSUE TITLE
Cumination List/Playback Issues

### ISSUE THREAD

**Issue by abefroman69** [dobbelina/repository.dobbelina#813]
Hello,

The following sites are having playback issues on Kodi 19 on Nvidia Shield Android TV:
Porn00, PornTrex, HQPorner

StreamXXX has a directory issue that only shows the date but doesn't allow individual videos to be selected.

Thank you

**Comment by DJMix-I-Can** [comment]
StreamXXX doesn't have a directory issue on my end. Played three videos without a problem.
Porntrex & HQPorner played without issues as well.
Porn00 did play one video but then kept failing on a handful of videos. The log showed multiple
ERROR <general>: CCurlFile::Stat - Failed: HTTP response code said error(22) &
ERROR <general>: CCurlFile::Open failed with code 410 
errors. On Nvidia Shield & Kodi 19.4

**Comment by abefroman69** [comment]
PornTrex and HQPorner both appear to be working again.

Porn00 is still having the playback issue.

I also checked and Stream XXX Still doesn't list videos, Only dates with no apparent way to select individual videos.
![20220711_211258](https://user-images.githubusercontent.com/20526483/178394203-4e4f4ab5-e4e8-4bf9-8870-5384d30fbdb3.jpg)

**Comment by DJMix-I-Can** [comment]
I now see what you're talking about. You're skin view is different from mine. I went to the website via my browser & saw that it's a another directory within the main directory. There are multiple video links of different movies.... This what I see, hence why I said it's working
![screenshot00000](https://user-images.githubusercontent.com/35236592/178601329-ad9d8f47-85d9-4076-8db2-954e211db866.png)
.

**Comment by abefroman69** [comment]
Yes but if you click on one of them it only plays a random video from that day.  There is no way o select the actual video.  It seems to be taking the actual individual video links and putting them in the description on the left.  Is there any way to fix it?

**Comment by dobbelina** [comment]
Will be fixed in the next 1.1.49 release https://github.com/dobbelina/repository.dobbelina/commit/d66ce15dec7895d824598d90d6a0d3108ef380c2
