### ISSUE TITLE
VIP Porns resolution issue

### ISSUE THREAD

**Issue by Kaveon2022** [dobbelina/repository.dobbelina#817]
Stated resolution of videos is ignored... All videos default to SD definition (540p). Even when picking, for example, 4k or 60fps videos from the categories section they either don't work or default to SD definition. Your help would be much appreciated in this issue. Thanks.

**Comment by Gujal00** [comment]
The site is serving only SD streams. If you can find a video on the site playing at a higher quality on web browser then let know the url

**Comment by Kaveon2022** [comment]
Ok thanks for taking the time to reply.
