### ISSUE TITLE
HQPorner pagination not working

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#82]
Pagination is not working in HQPorner. The first page displays correctly, but second page is incorrect. No ability to continue beyond. 
Testing fix on line 51 of hqporner.py:
        nextp=re.compile('<a href="([^"]+)" class="button mobile-pagi pagi-btn">Next</a>', re.DOTALL | re.IGNORECASE).findall(link)

**Comment by dobbelina** [comment]
Thanks for you effort jdoedev123!

When you have a complete fix for this and other sites, i really appreciate if you could
attach zipped py files, thanks.
![bild](https://user-images.githubusercontent.com/46063764/64148110-b73dc780-ce22-11e9-889b-e6ecdfbed6e5.png)

**Comment by jdoedev123** [comment]
Usually I wait until I do some testing before uploading. This passed initial tests.
[hqporner.py.zip](https://github.com/dobbelina/repository.dobbelina/files/3572498/hqporner.py.zip)

**Comment by dobbelina** [comment]
Thanks jdoedev123,

Will include in next update.
