### ISSUE TITLE
Site addition request: Nonk Tube https://www.nonktube.com/

### ISSUE THREAD

**Issue by mmhappy1971** [dobbelina/repository.dobbelina#823]
Site: https://www.nonktube.com/

Contact: https://www.nonktube.com/feedback

DMCA information: https://www.nonktube.com/static/dmca

**Comment by dobbelina** [comment]
A fix will be in the next 1.1.52 release https://github.com/dobbelina/repository.dobbelina/commit/6cb978c0e6e9e67dd6c38ff25d400334cda79fe1
I will release it tomorrow.

**Comment by mmhappy1971** [comment]
Thank you!
