### ISSUE TITLE
Site addition request: TNAflix https://tnaflix.com/

### ISSUE THREAD

**Issue by mmhappy1971** [dobbelina/repository.dobbelina#824]
Site: https://tnaflix.com/

DMCA information: https://tnaflix.com/dmca

**Comment by dobbelina** [comment]
Will be in the next 1.1.52 release https://github.com/dobbelina/repository.dobbelina/commit/cf28e0d8e81825c7d6f18b333f622ed16ce3c468

**Comment by mmhappy1971** [comment]
Thank you!
