### ISSUE TITLE
video issues

### ISSUE THREAD

**Issue by letterale** [dobbelina/repository.dobbelina#826]
### Bug reports:

I report video playback issues for all sites except live camshow ones.

The link of the log file is this:

https://paste.kodi.tv/elokacawih

In practice, the video starts but after a few seconds or minutes it stops with the player still in the play state.  If at this point I click stop in the player then kody freezes and I am forced to terminate the application.  The strange thing is that if when video playback stops kodi continues to respond to commands.  For example, I can back up from frozen video playback and browse directories.  But if I start another video then kodi freezes and I have to finish it 

### OS environment
What OS, Device, version etc

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.

**Comment by dobbelina** [comment]
This solution will probably resolve your issue:https://github.com/dobbelina/repository.dobbelina/issues/796

**Comment by letterale** [comment]
Hi, thx, it's ok now
