### ISSUE TITLE
Xnxx

### ISSUE THREAD

**Issue by demex2008** [dobbelina/repository.dobbelina#827]
Hallo can you fix the Download Funktion Form xnxx
Mfg .

**Comment by Gujal00** [comment]
Can't be done using builtin downloader as the site only serves hls streams.
The builtin download option for this site will be removed in the next release

You can try this solution for downloading if you are on Windows
https://github.com/dobbelina/repository.dobbelina/issues/392

**Comment by dobbelina** [comment]
Tip above works, but you need ffmpeg also in the same folder as youtube-dl-recorder.
solution below also works https://github.com/dobbelina/repository.dobbelina/issues/368
