### ISSUE TITLE
Site Addition Request https://pornxp.com/

### ISSUE THREAD

**Issue by Kodionpi** [dobbelina/repository.dobbelina#828]
https://pornxp.com/

DMCA: https://pornxp.com/legal/dmca

**Comment by onknight** [comment]
https://www.camhub.cc/dmca/

**Comment by imurreflection** [comment]
This is really a good site. OP requested this in Aug 2022. Can we please kindly look at the addition now since many new sites are being added

**Comment by ErosVece** [comment]
It looks good yes, but the few videos I've checked are only 360p quality.
Are there better videos to find there, or are they all 360p?

**Comment by imurreflection** [comment]
They have a separate "HD" category hosting about 130+, pages and each page has 30+ videos. However, it's completely up to the Dev's discretion to get this added or not.

**Comment by ErosVece** [comment]
Indeed, you are correct. I'm positive it gets added.... 😉

**Comment by ErosVece** [comment]
Closed, this has been added
