### ISSUE TITLE
Why do I get a much longer list of files from the Firestick Kodi compared with that from my Laptop

### ISSUE THREAD

**Issue by Budgie2** [dobbelina/repository.dobbelina#829]
**Is your feature request related to a problem? Please describe.**
I have working and up to date Kodi installations with Cumination add-on installed.  Both are working as expected but the number of files made available on my selected cumination site on laptop total 5 but on Firestick the same selection yields over 20 files. 

**Describe the solution you'd like**
What I would like is to have the same selection available on both systems.

For example going to Laptop Kodi:- Video add-ons>Cumination>Sites>SpeedPorn>Studios>SexArt gives me about half a dozen files.
Firestick:- Ditto gives me over 20 files

Any advice on what I am doing wrong?

**Comment by Gujal00** [comment]
Something wrong with your installation, share a debug log to troubleshoot the issue
Normally Video add-ons>Cumination>Sites>SpeedPorn>Studios>SexArt should give you 50 titles and then NextPage with 36 titles.

**Comment by Gujal00** [comment]
Something wrong with your installation, share a debug log to troubleshoot the issue
Normally Video add-ons>Cumination>Sites>SpeedPorn>Studios>SexArt should give you 49 titles and then NextPage with 36 titles.

**Comment by dobbelina** [comment]
**Sex Art** gives 6 titles, **SexArt** give 49 titles and page 2
Are you sure you clicked the right/same link on both systems?

**Comment by dobbelina** [comment]
No response, closing thread.
