### ISSUE TITLE
Sxyprn(yourporn)

### ISSUE THREAD

**Issue by xyz236** [dobbelina/repository.dobbelina#83]
Yourporn seems to be down for about three days.

**Comment by 12asdfg12** [comment]
fixed
[sxyprn.zip](https://github.com/dobbelina/repository.dobbelina/files/3580457/sxyprn.zip)

**Comment by xyz236** [comment]
“Failed to install due to invalid structure” is what is said, I’m on android device just FYI not sure if that would make a difference.

**Comment by DJMix-I-Can** [comment]
> 
> 
> “Failed to install due to invalid structure” is what is said, I’m on android device just FYI not sure if that would make a difference.

Did you try to install that sxyprn.zip file via install from zip file? If so, that's not how to do it. You would need to extract the file inside that zip file called sxyprn.py and transfer it to android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.uwc/resources/lib/sites It should ask you to overwrite an existing file already called sxyprn.py, select ok/yes. That should be it. I use the FX File Explorer to browse the folder on Android.

**Comment by jdoedev123** [comment]
Trying new code. Video browsing etc seems to work but playback does not.
Log file contains errors like:
 ERROR: Open - error probing input format, https://sxyprn.com/cdn8/c6/m197o24z2980iz47c64zn1g7y80/YHNoMreJ9pY8mPyJR5RRDQ/-577636210734/k57br9z146w7gd6aa7n8s3t7jbr/a5rdg7q1bcnf89yarajfx853ubu.vid

**Comment by 12asdfg12** [comment]
yesterday, the website used this javascript function to encrypt the video link:
```
	function preda(arg){
		arg[5]-= parseInt(arg[6].replace(/[^0-9]/g,''))+parseInt(arg[7].replace(/[^0-9]/g,''));
		return arg; 
	}
```

today they changed the function in:
```
	function preda(arg){
		arg[5]-= parseInt(ssut51(arg[6]))+parseInt(ssut51(arg[7]));
		return arg; 
	}
	function ssut51(arg){
		var str = arg.replace(/[^0-9]/g,'');
		var sut = 0;
		for (var i = 0; i < str.length; i++) {
		sut += parseInt(str.charAt(i), 10);
		}
		return sut;
	}
```
this code works now:
[sxyprn.zip](https://github.com/dobbelina/repository.dobbelina/files/3584303/sxyprn.zip)
