### ISSUE TITLE
Streamate video playback issue on Android.

### ISSUE THREAD

**Issue by DJMix-I-Can** [dobbelina/repository.dobbelina#830]
### Bug reports:
What's up guys! First off,  hope all is well with you & yours. Soooo, I've had this issue for a while in which the Streamate streams wouldn't play on my Nvidia Shield. I let it be & thought others would have the same issue & someone would've made an issue report. That never happened. I had a chance last night to test it on my Windows laptop being I've been busy with work. Streamate did play on my Windows installation. So, I thought, let me transfer that PY file to my android device. It didn't work. I re-installed Cumination on the Sheild & it did not work. I tried to see if I could figure it out but I can't. I don't know if it's a user-agent issue or what. Am I talking out of my ass...lol I'm trying to learn python but life gets in the way. I did get debug files for both Windows & Android installations.

### OS environment
Windows 7, 64bit. Kodi 19.4, Cumination 1.1.50
Android 9, 64bit, Kodi 19.4, Cumination 1.1.50

Windows 7 Debug File
https://pastebin.com/KL0tDRUm

Nvidia Shield Android 9 Debug File
https://zerobin.net/?363a6699e563210b#f7Km6yCkKWZ05EUIVZp89u/LfwFmUoYm9StpqHbw0GQ=
Edit: I had to replace the Android link because I noticed that it wasn't on Cumination 1.1.50, it was at 49. Redid the debug file with 1.1.50.

I had to use two different services because of the size differences between Windows & Android.

Thanks guys... Be well.. Enjoy your weekend...

**Comment by Gujal00** [comment]
The Android debug file unfortunately has nothing related to cumination except showing the version installed. In debug mode did you try playing the streamate stream?

**Comment by DJMix-I-Can** [comment]
Ok, I redid the debug file on my Shield. Here it goes.. 
https://zerobin.net/?f0d1110a2fb41de7#M+dvtGIPEMCTa//V6Q7hGii9HmNqNU9jRlhW3AuN6G4=
Error is on line 20179. Thanks @Gujal00

**Comment by Gujal00** [comment]
I think zerobin is truncating the file at 20000 lines, so cant see the error.
I suggest turn the debug mode on just before you go into cumination. The above logs have all the other debug information required, so dont need to that in the new log

**Comment by DJMix-I-Can** [comment]
You're correct, it did truncate it. Here it goes again.. Thanks..
https://pastebin.com/iCgJpDpK

**Comment by dobbelina** [comment]
_Error, this is a private paste or is pending moderation. If this paste belongs to you, please login to Pastebin to view it._ 
Upload here instead:https://paste.kodi.tv/

**Comment by DJMix-I-Can** [comment]
Here it goes...
https://paste.kodi.tv/tobokilupa.kodi

**Comment by Gujal00** [comment]
It is a user-agent issue. cumination generates a random UA and uses it for one week.
if the UA is from an older browser then the site is giving this message when looking for the video
```html
<h1>Your browser is no longer supported.</h1>
<p>Please upgrade to the latest version of Chrome, Microsoft Edge, Firefox or Safari to continue to enjoy our site.</p>
```
The random generation should be reprogrammed to not include old versions

**Comment by dobbelina** [comment]
A fix will be provided in the next 1.1.51 version https://github.com/dobbelina/repository.dobbelina/commit/67e68ebb54228631ac6c36104220600835191147

**Comment by DJMix-I-Can** [comment]
What's up guys... That fix didn't help. I've added an updated debug file. Thanks..
https://paste.kodi.tv/ojovagetuw.kodi

**Comment by 12asdfg12** [comment]
You should wait until the generated UA expires (up to 7 days) or you can delete the line starting with "<setting id="current_ua" ... " from the file settings.xml located in the folder "user_data/addon_data/plugin.video.cumination/"

**Comment by DJMix-I-Can** [comment]
Thanks @12asdfg12 I'll try that when I get home.

**Comment by DJMix-I-Can** [comment]
Thanks @Gujal00 & @12asdfg12  It's up and running again.
