### ISSUE TITLE
JavHD Porn 

### ISSUE THREAD

**Issue by Cr4zyM0f01** [dobbelina/repository.dobbelina#831]
Hi I seem to be having a problem playing videos from JavHD. Any time I try to play a video it's saying "No Video Found" but if I was to go on the site and play the same video on my phone or laptop it works fine after skipping through all the ads. I'm on xbox if that means anything, thanks for everything you guys do.

**Comment by Gujal00** [comment]
Yes, site have changed the obfuscated code again, broken for now

**Comment by dobbelina** [comment]
A fix will be provided in the next release 1.1.51 https://github.com/dobbelina/repository.dobbelina/commit/bb8d613b6d8846c78e0c80667b90c9f2bfea927c
