### ISSUE TITLE
Filtrages & Catégorie

### ISSUE THREAD

**Issue by victore447** [dobbelina/repository.dobbelina#832]
![téléchargé](https://user-images.githubusercontent.com/48101775/183446522-7db2fc02-a6a8-449f-9173-2285536b517d.jpg)
![byeb](https://user-images.githubusercontent.com/48101775/169663040-4ba49144-400c-4204-ad7c-38472f2121a0.gif)
**Hello**, 
👉Can you add in the categories "videos in hd, fhd etc.., and videos of 5,10,20, +50 minutes etc.. ". 
👉And not possible to create a filtration of duration and quality (  from 0 to (+50 min, hd, fhd etc.) of videos during the result of a search with sites such as xhamster, xvideos etc...? 
![xplugin video xhamstergay png pagespeed ic WydjTNCm6D](https://user-images.githubusercontent.com/48101775/183446620-499930ed-8c78-4833-9d3d-306f1de8fb74.png)
👉This is possible on the pages of these websites online but not  on your extension. 
**Thanks for your answer** ![respect-chapeau](https://user-images.githubusercontent.com/48101775/169663108-88eef6d7-0c80-4067-b390-c17b100067e2.gif)

**Comment by imurreflection** [comment]
It's already there in xvideos and xhamster. Once you search a keyword,press context menu and select your desired selections

**Comment by victore447** [comment]
🖐️
![86](https://user-images.githubusercontent.com/48101775/183825415-9979b85b-c1e6-4e41-add8-b923c7bc1e6f.gif)Yes _Exact.
 I overlooked that without 
reading it properly👌Ingenious 
**Thanks**._![114](https://user-images.githubusercontent.com/48101775/183825756-aed6606f-c34a-46d7-96d5-56b6c78cb428.gif)
