### ISSUE TITLE
Javbanger playback got issue

### ISSUE THREAD

**Issue by rogerwee** [dobbelina/repository.dobbelina#835]
I encounter previously got problem in playing Javbanger in cumination..and I believe now it is fixed and able to playback, but the moment u forward the video while playing, it would  stop and you are back in the main page of javbanger. Can anyone look into this. Thanks

**Comment by DJMix-I-Can** [comment]
Just tested three videos. I was able to forward, continues playing, forward some more, continues playing, forward some more & it continues playing. Could be a cache issue on your device.

**Comment by dobbelina** [comment]
No provided logfile, closing thread.
