### ISSUE TITLE
Aagmal/Aagmal Pro never works

### ISSUE THREAD

**Issue by Lifehilarity** [dobbelina/repository.dobbelina#836]
I'm always frustrated when i click on aagmal and aagmal pro section it always gives a error. Im sure I'm not the only one as well. I Google the sites and it's working so there's definitely an issue within cumination 

Can you please fix it so it works, i wish there were more Indian porn sites but aagmal seems good if it works.

**Comment by DJMix-I-Can** [comment]
Both sites are working on Android. Provided a debug log.

**Comment by dobbelina** [comment]
No provided logfile, closing thread.
