### ISSUE TITLE
Beeg Not Working

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#837]
Please see the debug enabled log

https://paste.kodi.tv/ilajihuxoj

**Comment by dobbelina** [comment]
Will be a fix in the 1.1.52 release https://github.com/dobbelina/repository.dobbelina/commit/cf28e0d8e81825c7d6f18b333f622ed16ce3c468

**Comment by imurreflection** [comment]
Thanks... closing the issue now
