### ISSUE TITLE
Please fix Pornoo - not playing vids

### ISSUE THREAD

**Issue by Watleukhe** [dobbelina/repository.dobbelina#839]
On this excellent addon the Pornoo part is no longer working. Would be great to have fix.  Android and windows 

### OS environment
What OS, Device, version etc

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.

**Comment by dobbelina** [comment]
Just tested Porn00, working on windows.

**Comment by DJMix-I-Can** [comment]
Same here, tested on Windows & Android. It's working...

**Comment by dobbelina** [comment]
Closing issue.
