### ISSUE TITLE
Issues & some fixes...

### ISSUE THREAD

**Issue by DJMix-I-Can** [dobbelina/repository.dobbelina#84]
Hey "dobbelina"... I went through all of UWC to see what's working and what isn't.  Github doesn't allow DMs so what's the best option on posting all this info. I was able to fix some but there's numerous issues.
Thanks.

**Comment by dobbelina** [comment]
Unresolved issues you can post here,  fixes you can add to a zip and drop here as well.

**Comment by DJMix-I-Can** [comment]
I understand that we would post here, but there's more than 10 issues for numerous sites. I don't know if you would like a separate post for each site or if explaining everything on one post would be ok.

**Comment by jdoedev123** [comment]
DJ, my suggestion would be for each website fixed start a new issue. Briefly describe the issue and post the corrected site code in a zipped file.
This makes it easier to track corrections and minimize duplication of effort.
