### ISSUE TITLE
Xhamster broken

### ISSUE THREAD

**Issue by dobbelina** [dobbelina/repository.dobbelina#843]
Seems a new regex is needed for Xhamster, thumbnails and links are gone.

**Comment by tetzy** [comment]
ElreyX and Vidoz8 aren't working either.

**Comment by DJMix-I-Can** [comment]
@tetzy ElReyX & Vidoz8 are working on my Nvidia Shield. 
@dobbelina Same here on both Windows  & Android. Oddly, I had trouble checking the website via the browser. It eventually loaded but still can't view it in Kodi. I noticed a couple of days ago that it didn't load as well. That didn't last long, assuming they were testing their changes.

**Comment by darktones123** [comment]
> @tetzy ElReyX & Vidoz8 are working on my Nvidia Shield. @dobbelina Same here on both Windows & Android. Oddly, I had trouble checking the website via the browser. It eventually loaded but still can't view it in Kodi. I noticed a couple of days ago that it didn't load as well. That didn't last long, assuming they were testing their changes.

Vidoz8 is working for me but both xHamster and ElReyX are not.

**Comment by dobbelina** [comment]
A fix will be in the next 1.1.52 release https://github.com/dobbelina/repository.dobbelina/commit/6cb978c0e6e9e67dd6c38ff25d400334cda79fe1
I will release it tomorrow.
