### ISSUE TITLE
Webcam Shows site has Error

### ISSUE THREAD

**Issue by marsrover1-ops** [dobbelina/repository.dobbelina#844]
### Bug reports:

When trying to select a site or do a search, get error message "Site is too slow"

### OS environment
Android, Firestick

**Comment by DJMix-I-Can** [comment]
That's because the website is down. https://www.webcamshows.org/

**Comment by joxdfrt** [comment]
Hope this can get sorted was just about to raise an issue I’m using a vpn too.

**Comment by dobbelina** [comment]
Site has been removed https://github.com/dobbelina/repository.dobbelina/commit/c4da3a9643cb74d77cfbf55d897e1ca7c38fdb3e
