### ISSUE TITLE
Linux Mint 21 Vanessa

### ISSUE THREAD

**Issue by woolfman99** [dobbelina/repository.dobbelina#845]
Hello,
first exuse my bad English
i shortly installed LM 21 Vanessa but your great addon seems not be compatible with Python3.10.4, wich version of Python have i to install to run your addon?

**Comment by c99tn** [comment]
With python 2.7, it should work properly, give it a try!

**Comment by woolfman99** [comment]
Thanks but Python 2.7 is deprecated since 1.Jan.2020, the addon works with LM 19.3 Tricia with Version 3.6.9. I am asking for the latest Python version it works.

**Comment by 12asdfg12** [comment]
3.8.xx
Kodi for Windows uses Python v3.8.5 and the latest version of Coreelec uses Python 3.8.11

**Comment by Gujal00** [comment]
Python 3.10 has major issues with sqlite
https://bugs.python.org/issue47019

Stick to LM 20.3 Una (I use this) for now if you want to use Kodi

**Comment by woolfman99** [comment]
Hello,
today Vanessa updated Python to version 3.10.6 now all works fine.

**Comment by Gujal00** [comment]
@woolfman99 please close the issue if it is working fine on Vanessa.

**Comment by dobbelina** [comment]
I'm closing it.
