### ISSUE TITLE
Stripchat preview/thumbs broken

### ISSUE THREAD

**Issue by nrk666** [dobbelina/repository.dobbelina#846]
### Bug reports:

Stripchat preview/thumbs broken, but models still play if you click on them. 

### OS environment
Kodi 19.4
Cumination 1.1.52
Tried on nvidia shield, linux native, and windows, same issue across all platforms. 

Logfile (below) is from nvidia shield. 

Steps to reproduce: 
1. Launch Cumination
2. Select stripchat.com
3. Select "HD"
4. wait for model list
5. view model list, move selector down - no preview windows/thumbs are shown. 

Logfile: [https://paste.kodi.tv/bukacujide](url)

No screen errors are generated, just no preview/thumb. Logfile likely more verbose. 

I looked through the closed issues and didn't see this listed, so here it is.

**Comment by nrk666** [comment]
FWIW, another piece of software that integrates with stripchat had the same issue, previews weren't loading and they were able to fix it, so probably just some url change or something.

**Comment by DJMix-I-Can** [comment]
Same here...
I changed line 62 to the following in order for the images to load again.
        img = model['previewUrlThumbBig'] if utils.addon.getSetting("previewUrlThumbBig") == "0" else model['previewUrlThumbSmall']

**Comment by 12asdfg12** [comment]
There is no "previewUrlThumbBig" setting in Cumination, also model['previewUrl'], model['previewUrlThumbSmall'] and model['previewUrlThumbBig'] are the same image, just different resolutions, so that's enough:
`    img = model['previewUrlThumbBig'] `

**Comment by DJMix-I-Can** [comment]
@12asdfg12 Thanks, I see what you're talking about...

**Comment by dobbelina** [comment]
A fix will be provided in the next 1.1.53 release https://github.com/dobbelina/repository.dobbelina/commit/8ef3977f5eb8b3d2368a75bfc03c71c76adcac12

**Comment by nrk666** [comment]
Thank you!

**Comment by nrk666** [comment]
One thing though, using DJMix's code, the thumbs are profile pics, not video preview images. The old style was video preview images and is sooo much better than profile pics which are nearly always way better than the model. If there is any way to put it back to video preview (and do it to MFC if you can also, that would be nice) instead of profile pic, I feel like that's a much better setting. Or, if possible, make it a setting that can be toggled.

**Comment by Gujal00** [comment]
Stripchat can be fixed, but mfc cant be as there are too many hoops to jump to get the live snapshot and it will slowdown navigation

**Comment by nrk666** [comment]
Well, I'll take what I can get with just Stripchat then. The models always use ridiculously fake/filtered profile pics so I feel like video preview thumbs are much better.

**Comment by Gujal00** [comment]
@nrk666 fixed in https://github.com/dobbelina/repository.dobbelina/commit/6598ed99c6fc805618fc9ef6581c2444dc6148b0

**Comment by nrk666** [comment]
whoah, you got MFC too? Thanks!
