### ISSUE TITLE
Aagmaal site change

### ISSUE THREAD

**Issue by Napster955** [dobbelina/repository.dobbelina#850]
https://aagmaal.com/

**Comment by prettyaverage02** [comment]
Yes, site to be changed to https://aagmaal.com/

[kodi.log](https://github.com/dobbelina/repository.dobbelina/files/9692844/kodi.log)

**Comment by 12asdfg12** [comment]
In the next release, the domains will be changed from aagmaal.site to aamaal.com and aagmaal.pro to aagmaal.today, however, the old domains should also work because they are redirected.
