### ISSUE TITLE
Cumination 1.1.53 not working.

### ISSUE THREAD

**Issue by neo659** [dobbelina/repository.dobbelina#852]
### Bug reports:

Cumination 1.1.53 not working.

### OS environment
Android TV. Kodi v19.3 Matrix

Errors -
![B3DD673E-DF36-4518-B57D-9AE1552D3131](https://user-images.githubusercontent.com/113297600/189564484-d0cc2658-f178-4da1-ab15-e6f176c29162.jpeg)
![0018A698-F3F8-49AD-AD89-396336AD5F17](https://user-images.githubusercontent.com/113297600/189564499-6eafe6da-2f5d-46d2-b075-09800c8e1110.jpeg)
![5174EAE0-7244-41F4-828C-4B7F4046D47B](https://user-images.githubusercontent.com/113297600/189564505-e15deb25-448a-4fe1-a35c-1148b4ecd92e.jpeg)

**Comment by dobbelina** [comment]
1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

**Comment by neo659** [comment]
> 1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
> 
> 2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
> 
> 3. Restart Kodi (Important)
> 
> 4. Go into Cumination and open the site (wait for the error message)
> 
> 5. Come out of cumination
> 
> 6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
> 
> 7. launch Kodi Logfile uploader and upload your log. This will give you a url
> 
> 8. provide the url from step 7 here

https://paste.kodi.tv/udulujowuz

**Comment by neo659** [comment]
> Did you update within Kodi or did you manually make the changes in the Python files? The error is coming from the MyFreeCams.py file. I'm also using Android on the Nvidia Shield & it's working on my end. Try updating it again... Another thing If I may suggest, you have three repositories that no longer exist. You should consider removing them...
> 
> Do you get loading delays with Kodi on the HiSense TV?  Any reason you're still on 19.3?
> 
> 
> 
> ![Errors](https://user-images.githubusercontent.com/35236592/189726816-c7cedea7-5c7a-45d4-af02-0b964ff44ccb.jpg)
> 
> 

I updated within kodi. I'm not into programming so didn't make any changes in python. 

What are those three repos to delete?

I have no loading issues on the TV.

I'm not able to update to 19.4, downloaded 19.4 from kodi website but shows as 19.3.

**Comment by neo659** [comment]
> Did you update within Kodi or did you manually make the changes in the Python files? The error is coming from the MyFreeCams.py file. I'm also using Android on the Nvidia Shield & it's working on my end. Try updating it again... Another thing If I may suggest, you have three repositories that no longer exist. You should consider removing them...
> 
> Do you get loading delays with Kodi on the HiSense TV?  Any reason you're still on 19.3?
> 
> 
> 
> ![Errors](https://user-images.githubusercontent.com/35236592/189726816-c7cedea7-5c7a-45d4-af02-0b964ff44ccb.jpg)
> 
> 

I updated within kodi. I'm not into programming so didn't make any changes in python.

What are those three repos to delete?

I have no loading issues on the TV.

Updated to 19.4 & reinstalled Cumination again but getting same error.

**Comment by DJMix-I-Can** [comment]
The three repositories (Repo) is where the Diggz Build, Venom addon & the Oath Addon were from. They're discontinued & not being updated. Every time you start Kodi, when the addon checks for an update & communicates with those repos, it's taking some time, not much but it's trying to find them until it times out since they no longer exist. I'm not familiar with having Kodi installed on a TV compared to a separate peripheral device. That's why I asked about loading time.  You did update Kodi to 19.4 & re-installed Cumination to no avail. No one else has chimed in on this issues. Sorry I couldn't help...

**Comment by neo659** [comment]
> The three repositories (Repo) is where the Diggz Build, Venom addon & the Oath Addon were from. They're discontinued & not being updated. Every time you start Kodi, when the addon checks for an update & communicates with those repos, it's taking some time, not much but it's trying to find them until it times out since they no longer exist. I'm not familiar with having Kodi installed on a TV compared to a separate peripheral device. That's why I asked about loading time.  You did update Kodi to 19.4 & re-installed Cumination to no avail. No one else has chimed in on this issues. Sorry I couldn't help...

Is there a diggz repo? I didn't know.

I have been using Kodi on TV for a year now, & I have never faced any issues. The loading time is excellent too.

Thanks for your help though. 👍🏻

**Comment by ErosVece** [comment]
No idea why it doesn't want to load the MyFreeCams server list on your t

But I've pushed a fix, so Cumination will at least start for you. You can't use MyFreeCams though.

**Comment by neo659** [comment]
> No idea why it doesn't want to load the MyFreeCams server list on your tv
> 
> 
> 
> But I've pushed a fix, so Cumination will at least start for you. You can't use MyFreeCams though.

Thanks. Do I have to update the addon again when it releases?

**Comment by ErosVece** [comment]
Yes, but Kodi should auto update the addon when the newer version is released.

**Comment by neo659** [comment]
> Yes, but Kodi should auto update the addon when the newer version is released.

Thanks once again. When can I expect the update to come?

**Comment by hbkpreet** [comment]
Facing the same issue with cumination

**Comment by DJMix-I-Can** [comment]
> Facing the same issue with cumination

Provide a debug file to see if it's the same issue.

**Comment by DJMix-I-Can** [comment]
> > The three repositories (Repo) is where the Diggz Build, Venom addon & the Oath Addon were from. They're discontinued & not being updated. Every time you start Kodi, when the addon checks for an update & communicates with those repos, it's taking some time, not much but it's trying to find them until it times out since they no longer exist. I'm not familiar with having Kodi installed on a TV compared to a separate peripheral device. That's why I asked about loading time.  You did update Kodi to 19.4 & re-installed Cumination to no avail. No one else has chimed in on this issues. Sorry I couldn't help...
> 
> Is there a diggz repo? I didn't know.
> 
> I have been using Kodi on TV for a year now, & I have never faced any issues. The loading time is excellent too.
> 
> Thanks for your help though. 👍🏻

Apologies, it wasn't the Diggz build, it was Diamond. Your welcome & someone else chimed in on the "same issues" but will see since a debug file wasn't provided.

**Comment by neo659** [comment]
> Apologies, it wasn't the Diggz build, it was Diamond. You're welcome & someone else chimed in on the "same issues" but we'll see since a debug file wasn't provided.

No worries mate. I'm expecting the other guy also has the same issue.

**Comment by hbkpreet** [comment]
> > Facing the same issue with cumination
> 
> 
> 
> Provide a debug file to see if it's the same issue.

https://paste.kodi.tv/itadexawuh

That's a fresh file from now , yesterday I was trying the steps to figure out how to make log file and send in between all of that it worked. But now again when I tried getting same error.

**Comment by hbkpreet** [comment]
https://paste.kodi.tv/ugojukeruz

Log file from MacBook with 19.4 matrix , in this install fails

**Comment by DJMix-I-Can** [comment]
> > > Facing the same issue with cumination
> > 
> > 
> > Provide a debug file to see if it's the same issue.
> 
> https://paste.kodi.tv/itadexawuh
> 
> That's a fresh file from now , yesterday I was trying the steps to figure out how to make log file and send in between all of that it worked. But now again when I tried getting same error.

So, you were able to open Cumination while trying to make the debug file? Were you able to go to myfreecams? Or it didn't last long? I looked at your debug file, you're also getting the myfreecams error.
Are you using a VPN? if so, can you try without it.

**Comment by Johnhay3s** [comment]
Hi. 
Any information on the fix to cuminations not installing the dependencies and how to fix? Or, how to disable dependencies with problems. I am on android box with 19.3. Thanks

**Comment by neo659** [comment]
Any update on this issue?

**Comment by DJMix-I-Can** [comment]
@neo659 There is a fix for it. It's not being released as of right now because there hasn't been any other site issues. As of right now, this issue is isolated to you & hbkpreet.  Once there are multiple site updates is when it will be released. You mentioned that you're not into programming but can you browse to your Kodi folder on your Hisense TV?. If so, go to Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cumination/resources/lib/sites & delete the myfreecams.py file. Close Kodi, restart & you should be good to go. Once the next update has enough fixes, it will be released & you'll get the fixed myfreecams file. If you're not comfortable doing it or can't because of Android 11 restriction (even though from your debug file, it looks like you're on 9) You'll have to wait for the next update.

**Comment by neo659** [comment]
> @neo659 There is a fix for it. It's not being released as of right now because there hasn't been any other site issues. As of right now, this issue is isolated to you & hbkpreet.  Once there are multiple site updates is when it will be released. You mentioned that you're not into programming but can you browse to your Kodi folder on your Hisense TV?. If so, go to Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cumination/resources/lib/sites & delete the myfreecams.py file. Close Kodi, restart & you should be good to go. Once the next update has enough fixes, it will be released & you'll get the fixed myfreecams file. If you're not comfortable doing it or can't because of Android 11 restriction (even though from your debug file, it looks like you're on 9) You'll have to wait for the next update.

Thanks a lot once again. My issue is sorted.

I tried to fix the issue through x-plore app but couldn't go beyond files, tried to unhide folder as well but didn't work. So installed fx, clicked hidden folder & worked like a charm. 

Thanks to everyone who tried to help.

**Comment by DJMix-I-Can** [comment]
That's what I use FX Explorer. After my Nvidia shield updated to Android 11, I could no longer view the files. That is why I rolled back. Glad to hear it's sorted out for you.

**Comment by dobbelina** [comment]
Closing thread, A fix will be in the next 1.1.54 release https://github.com/dobbelina/repository.dobbelina/commit/265b73ac468f08865166642bf8d376866d29f7e4
