### ISSUE TITLE
SxyPrn

### ISSUE THREAD

**Issue by joxdfrt** [dobbelina/repository.dobbelina#855]
### Bug reports:

Looks like this site is not getting updated been like this for 3 days now. Click on the videos under Top this week etc and no video plays.

### OS environment
Firetv Cube Matrix 19.4.

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.

https://paste.kodi.tv/ubiwazoseg

**Comment by Gujal00** [comment]
That log is not a debug log, follow the instructions above correctly to provide debug log

**Comment by dobbelina** [comment]
No log file, closing.
