### ISSUE TITLE
Webcam shows has been removed  https://github.com/dobbelina/repository.dobbelina/commit/c4da3a9643cb74d77cfbf55d897e1ca7c38fdb3e

### ISSUE THREAD

**Issue by assanecisse1965** [dobbelina/repository.dobbelina#856]
Webcam shows has been removed  https://github.com/dobbelina/repository.dobbelina/commit/c4da3a9643cb74d77cfbf55d897e1ca7c38fdb3e

_Originally posted by @dobbelina in https://github.com/dobbelina/repository.dobbelina/issues/853#issuecomment-1249055094_

**Comment by assanecisse1965** [comment]
Why did you remove it

**Comment by DJMix-I-Can** [comment]
It literally explains why on the comment you posted. "Dead site removal www.webcamshows.org/"
It's a dead site, it no longer exists.
