### ISSUE TITLE
Downloads not working from xvideos

### ISSUE THREAD

**Issue by toaster345** [dobbelina/repository.dobbelina#858]
Am I the only one experiencing this? When clicking the download button of a video, the download dialogue pops up for a second then closes.

**Comment by dobbelina** [comment]
I can't tell you if the failing download reason can be fixed or not, other members maybe can share a light on it?
A workaround while above is being addressed is to use this tool:
(Windows only,Tested works) https://github.com/dobbelina/repository.dobbelina/issues/392

**Comment by 12asdfg12** [comment]
Downloading from Cumination works only for non-hls streams.
In the ResolveURL settings, you should uncheck "Automatically pick best quality", then select the "UrlHigh" or "UrlLow" link when you download the video.

![image](https://user-images.githubusercontent.com/48175015/191763431-5eaad78b-ac79-4d2b-ac1e-7cbe502f2dba.png)

![image](https://user-images.githubusercontent.com/48175015/191763695-dac90028-27af-4ec8-9f37-8e2f6bc35dd5.png)

**Comment by toaster345** [comment]
> Downloading from Cumination works only for non-hls streams. In the ResolveURL settings, you should uncheck "Automatically pick best quality", then select the "UrlHigh" or "UrlLow" link when you download the video.
> 
> ![image](https://user-images.githubusercontent.com/48175015/191763431-5eaad78b-ac79-4d2b-ac1e-7cbe502f2dba.png)
> 
> ![image](https://user-images.githubusercontent.com/48175015/191763695-dac90028-27af-4ec8-9f37-8e2f6bc35dd5.png)

That worked. Thanks!
