### ISSUE TITLE
Request: Stripchat/OtherCams Add config option to disable background profile pics

### ISSUE THREAD

**Issue by nrk666** [dobbelina/repository.dobbelina#861]
**Is your feature request related to a problem? Please describe.**
No, this is a pure quality of life feature request, nothing is broken, it is probably low priority. 

**Describe the solution you'd like**
Recently Stripchat stopped showing video preview in side window while browsing models. This was fixed (thank you), and added a feature to display model profile picture as background. My request is make the background picture a setting in Config for "on/off" much like the video preview setting in General. 

**If it's a site addition request, add url below**
N/A

**Comment by dobbelina** [comment]
There will be a fix in the next release 1.1.55 https://github.com/dobbelina/repository.dobbelina/commit/0778b2b27e6d82dbe1c2b8dedd21e18aa7488e17

**Comment by nrk666** [comment]
Thanks!
