### ISSUE TITLE
Porn One/Porn EZ/Anybunny/Daftsex Issues

### ISSUE THREAD

**Issue by darktones123** [dobbelina/repository.dobbelina#863]
Not sure if anyone else is having these issues as I am on the firestick.
-Porn One
No videos are listed.

-Porn EZ
First page works fine but when you hit the next page it keeps spinning.

-Anybunny
Search feature is not working. 

-Daftsex
Site videos do not seem to update. The videos only change once a update comes out from you.

Thanks ahead of time and thanks for all the work you do.

**Comment by DJMix-I-Can** [comment]
Anybunny changed their domain name. That's why it wasn't finding any results. I created a pull request for the fix.
PornEZ next page is functioning. 
DaftSex I created a pull request in order to get the latest videos.
PornOne doesn't load the list for me either.

**Comment by dobbelina** [comment]
Thanks @DJMix-I-Can  I have merged the fixes https://github.com/dobbelina/repository.dobbelina/pull/864
