### ISSUE TITLE
Netflixporno 

### ISSUE THREAD

**Issue by xerel89** [dobbelina/repository.dobbelina#872]
### Bug reports:

The newest porn movies are not anymore refreshing, please fix it 

### OS environment
What OS, Device, version etc

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.

**Comment by DJMix-I-Can** [comment]
I created a pull request for a fix. https://github.com/dobbelina/repository.dobbelina/pull/873

**Comment by dobbelina** [comment]
Thanks [DJMix-I-Can](https://github.com/DJMix-I-Can)
