### ISSUE TITLE
Porn TV Network 

### ISSUE THREAD

**Issue by xerel89** [dobbelina/repository.dobbelina#874]
### Bug reports:

No list showing and now video shows! 

### OS environment
What OS, Device, version etc

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.

**Comment by DJMix-I-Can** [comment]
Personally, i don't think it's worth fixing. They haven't posted any new videos since Oct 2021. Their trending videos just keeps recycling content that's already been posted.

**Comment by xerel89** [comment]
Oh OK, I don't have look on the website, I think we can delete this site's...

**Comment by 12asdfg12** [comment]
Will be removed, they no longer host videos, only embed videos from other sites.
