### ISSUE TITLE
JavHD Porn videos not playing

### ISSUE THREAD

**Issue by Cr4zyM0f01** [dobbelina/repository.dobbelina#875]
### Bug reports

Videos will not play for me, I just get an error every time. Not sure if this is an xbox only problem or what but hopefully someone can help.

### OS environment
Kodi (19.4 (19.4.0) Matrix, Microsoft Xbox Series S with WINDOWS 10.0.22621.2486

### LogFile
[LogFile](https://paste.kodi.tv/guqehoxaze)

**Comment by EXTIINCT** [comment]
Same problem on Windows

**OS**
Kodi (19.4 (19.4.0) Git:20220302-e12e66e019). Platform: Windows NT x86 64-bit

**LogFile**
[kodi.log](https://github.com/dobbelina/repository.dobbelina/files/10312888/kodi.log)

**Comment by Patient6038** [comment]
Also not working for me.
