### ISSUE TITLE
FreeOmovie Categories not opening and populating

### ISSUE THREAD

**Issue by durangorob** [dobbelina/repository.dobbelina#882]
Upon opening the site  "FreeOmovie"  and clicking on Categories it is NOT opening and populating like it used to do.   Please fix this issue as this is one of the best sites for full length movies.

durangorob@sbcglobal.net

**Comment by dobbelina** [comment]
A fix will be provided in the next 1.1.58 release https://github.com/dobbelina/repository.dobbelina/commit/2bb601a8a1ff5a8e772a579d523365fdcefd38ef

**Comment by durangorob** [comment]
Thank you fir all you do.

Sent from AT&T Yahoo Mail on Android 
 
  On Tue, Nov 8, 2022 at 12:56 PM, ***@***.***> wrote:   


A fix will be provided in the next 1.1.58 release 2bb601a
