### ISSUE TITLE
Pornhub not working and Xhamster next page not working!!

### ISSUE THREAD

**Issue by Buddha2400** [dobbelina/repository.dobbelina#883]
### Bug reports:

No shows up in Pornhub and any favorites for Pornhub won't play. Xhamster the page next button just repeats the same page 1.

### OS environment
What OS, Device, version etc
SDMC Jetstream AGT418 with Android 9.0.0, 32-bit version 4.9.113

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here: https://paste.kodi.tv/ufilatiyen
Any bugreports without logfile will be deleted.

**Comment by DJMix-I-Can** [comment]
I created a pull request (fix) for Pornhub. Even though it will load, the videos won't play. It fails when it gets passed off to the ResolveURL. @Gujal00 is there a problem with Pornhub in the Resolver? It keeps failing once it's handed off to it.
Here is a debug file for it. Thanks https://paste.kodi.tv/uvekobujud.kodi

**Comment by Gujal00** [comment]
@DJMix-I-Can The logs contain HTTP 472, try the same video on the browser and it takes to `Pornhub under maintenance` page. Is pornhub working for you on the browser?

**Comment by DJMix-I-Can** [comment]
Sorry, should've mentioned that. When I check the same videos in the browser, they play. My browser is Firefox. Thanks

**Comment by Gujal00** [comment]
there is some detection happening by PH site, regardless of the video, when ResolveURL pull the page for scraping it gets the same `Tons of Hard Cobs getting Grabbed` page, so cant get the stream details
