### ISSUE TITLE
Context menu for Xnxx 

### ISSUE THREAD

**Issue by Buddha2400** [dobbelina/repository.dobbelina#884]
Why doesn't Xnxx have a context menu? There is no way to sort out SD videos from HD videos. There's no video length sort nor is there a way to sort out video gender. That seems kind of lacking in lazy Bean for the fact that the website gives you these options. And most of the other sites on Cumination have these options. Please add them Thank you.

**Comment by ErosVece** [comment]
Well, you are 'kind of lacking in lazy Bean' for not learning Python and add this yourself.

For me personally, all the latest 'Lookup info' context items are added because I wanted this for myself, and the community should be glad I added this.
Heck, everything in here wouldn't exist if I (or some dude ;) ) wasn't interested in learning Python and work on it as a challenge.

**Comment by Buddha2400** [comment]
@ErosVece For one you dumb fuck i’m nowhere near lazy. I don’t have the patience nor the attention to learn computer language. Computer language, and computer program is not something I was ever interested in. Would you want a Carpenter to do heart surgery on you?

**Comment by Gujal00** [comment]
Wow @Buddha2400 for someone with a great name you sir have a filthy mouth. You are not welcome here. @Buddha2400 please ban such behaviour

**Comment by Buddha2400** [comment]
@Gujal00 I speak like that for dumb ass people. @ErosVece assumed that I’m being lazy for not learning Python. I have no interest in learning computer programming that shit bores the hell out of me. I try not to say anything on here because of dumb ass people like @ErosVece. So shouldn't be getting mad when you got somebody on here pissing off somebody with some dumb ass shit. That's why I hate talking to people because they say dumb ass shit especially men!!

**Comment by dobbelina** [comment]
Site removed https://github.com/dobbelina/repository.dobbelina/commit/c0d0c29581efa38471a499a711471afe216cbf79 
closing issue

**Comment by Buddha2400** [comment]
@dobbelina that was some real lazy shit you did. Instead fixing the issue you just felt it better to just remove the site. Just lazy plain and simple.
