### ISSUE TITLE
Voyeur-house.life stopped working

### ISSUE THREAD

**Issue by Micpau** [dobbelina/repository.dobbelina#886]
Voyeur-house.life stopped working a few days ago. please fix :-)

Keep up the good work.

**Comment by Buddha2400** [comment]
Don’t hold your breath thinking that someone is going to fix that. The Devs are to busy with their thumbs up their ass to be able to do anything helpful.

**Comment by 12asdfg12** [comment]
They used Cloudflare protection, which prevented the site from being scraped.
Now it works again without Cloudflare protection, and the site will be fixed in Cumination, also voyeurhouse.life will be added.
