### ISSUE TITLE
Ero-Tik Partial Fix

### ISSUE THREAD

**Issue by DJMix-I-Can** [dobbelina/repository.dobbelina#89]
Ero-tik-Main & Top Rated directory didn't load before but videos don't play.
Yourfreetube should be removed since it's the same as Ero-Tik.
[erotik.zip](https://github.com/dobbelina/repository.dobbelina/files/3598586/erotik.zip)

**Comment by dobbelina** [comment]
Thanks for finding the double.
Later when i update the addon i will remove Ero-tik and keep YourFreeTube as 
12asdfg12 made a fix for it.
