### ISSUE TITLE
Daftsex no content.

### ISSUE THREAD

**Issue by Tyke101** [dobbelina/repository.dobbelina#890]
Daftsex no content.  This may be a website issue?

**Comment by manad132** [comment]
The site entirely doesn’t load on my phone. And when I click on an old link I am redirected to redtube for no reason.

**Comment by DJMix-I-Can** [comment]
I don't know what's going on but their Twitter page states the [following.](https://twitter.com/DaftPost/status/1591221921680539648) At the same time, those websites they're provide are Russian sites... Personally, think it's time to remove this site.....

**Comment by Gujal00** [comment]
Daftsex was bankrupted due to $32million infringement settlement against them
https://www.xbiz.com/news/269962/mindgeek-wins-32m-judgement-against-copyright-infringer-daftsex-com
SO yes site should be removed from cumination

**Comment by dobbelina** [comment]
Site removed https://github.com/dobbelina/repository.dobbelina/commit/9c8f67fa8a5042b472cdff6a8a60c3ad6b5d1e76
