### ISSUE TITLE
Additional functionality to paradisehills 

### ISSUE THREAD

**Issue by Zee346** [dobbelina/repository.dobbelina#893]
Would it be possible to add functionality to the search menu, in that one could also search by model name and/or studio,  instead of just movie title?  It would then work just like the website.

**Comment by DJMix-I-Can** [comment]
What's up guys...Hope all is well with you & yours. Thought I'd try to full-fill this request out. I'm able to get the directory for actors & studios to load up BUT next page doesn't appear. I looked at the HTML code from the main, actors & studio page & they look the same. What am I missing? Thanks...
![ParadiseHill](https://user-images.githubusercontent.com/35236592/202344873-bf7ce658-5389-4145-9ea5-e8014a51cdc6.jpg)

**Comment by 12asdfg12** [comment]
In this case, you don't need the "Actors" and "Studios" functions, use the "Cat" function, just add the code for the next page, something like:

```
    npage = re.compile(r'class="next"><a href="([^"]+)"\s*data-page="(\d+)"', re.DOTALL | re.IGNORECASE).findall(cathtml)
    if npage:
        nurl, np = npage[0]
        nurl = site.url[:-1] + nurl.replace('&amp;', '&')
        lp = re.compile(r'class="last"><a href="[^"]+"\s*data-page="(\d+)"', re.DOTALL | re.IGNORECASE).findall(cathtml)[0]
        site.add_dir("Next Page (Currently in Page {} of {})".format(np, lp), nurl, 'Cat', site.img_next)
```

**Comment by ErosVece** [comment]
This site is also nice to add the 'lookup info' contextmenu item, so you can quickly look up the actors, studio or category from a movie

**Comment by DJMix-I-Can** [comment]
> This site is also nice to add the 'lookup info' contextmenu item, so you can quickly look up the actors, studio or category from a movie

Will give it a try at some point. I'm still crawling with Python... Thanks.

**Comment by DJMix-I-Can** [comment]
> In this case, you don't need the "Actors" and "Studios" functions, use the "Cat" function, just add the code for the next page, something like:
> 
> ```
>     npage = re.compile(r'class="next"><a href="([^"]+)"\s*data-page="(\d+)"', re.DOTALL | re.IGNORECASE).findall(cathtml)
>     if npage:
>         nurl, np = npage[0]
>         nurl = site.url[:-1] + nurl.replace('&amp;', '&')
>         lp = re.compile(r'class="last"><a href="[^"]+"\s*data-page="(\d+)"', re.DOTALL | re.IGNORECASE).findall(cathtml)[0]
>         site.add_dir("Next Page (Currently in Page {} of {})".format(np, lp), nurl, 'Cat', site.img_next)
> ```

Thanks, I saw what I did wrong.

**Comment by dobbelina** [comment]
Thanks for the fix @DJMix-I-Can ! https://github.com/dobbelina/repository.dobbelina/pull/895
