### ISSUE TITLE
Chaturbate playback failed

### ISSUE THREAD

**Issue by scorsese50** [dobbelina/repository.dobbelina#896]
Chaturbate section getting playback failed for each performer in each category. Thanks.

**Comment by dobbelina** [comment]
Works for me, you need to create a log file:
1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

**Comment by dvgm506** [comment]
Same issue.  Both on a 2019 Shield Pro & win11 PC.

http://paste.kodi.tv/ebawireluj

**Comment by dvgm506** [comment]
Some more digging, chrome/firefox/edge playback is borked direct from CB. Falls back to JPEG player. Looks like they don't like the cert for highwebmedia.

https://pastebin.com/2B0234aZ

**Comment by nrk666** [comment]
They aren't crazy, having the same problem here. 

Kodi 19.4, 
Cumination 1.1.57
Nvidia Shield Kodi and Linux Desktop Kodi

I'm also east coast, but configured a SOCKS5 proxy (within Kodi) for LA and Netherlands, same problems. Unless addons don't use the proxy. (I restarted Kodi after configuring the proxy info if that makes any difference.)  

Debug log (no proxy, straight internet):

https://paste.kodi.tv/ehiyukuhib.kodi

**Comment by Gujal00** [comment]
Switch to RTMP playback in Cumination settings and it plays fine. HLS playback is broken on all browsers, so until it starts working on browsers cant to much
```
curl -i -v -A iPad https://edge157.stream.highwebmedia.com/live-hls/amlst:jackandjill-sd-f82dc33a58fe238d1132a827ad5eeb63ef676e8d2bac8cbfd3042fbca24444f1_trns_h264/playlist.m3u8
*   Trying 131.153.46.70:443...
* Connected to edge157.stream.highwebmedia.com (131.153.46.70) port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server accepted http/1.1
> GET /live-hls/amlst:jackandjill-sd-f82dc33a58fe238d1132a827ad5eeb63ef676e8d2bac8cbfd3042fbca24444f1_trns_h264/playlist.m3u8 HTTP/1.1
> Host: edge157.stream.highwebmedia.com
> User-Agent: iPad
> Accept: */*
>
* schannel: server closed the connection
* Empty reply from server
* Closing connection 0
* schannel: shutting down SSL/TLS connection with edge157.stream.highwebmedia.com port 443
curl: (52) Empty reply from server
```

**Comment by scorsese50** [comment]
It is working now. Thanks.
