### ISSUE TITLE
Pornhub link couldn't be resolved 

### ISSUE THREAD

**Issue by bOuNtYhUnTeR2022** [dobbelina/repository.dobbelina#897]
sadly Pornhub still doesn't works. Categories and files are back visible, but not any link is working.

Error Message is : Pornhub link couldn't be resolved

**Comment by DJMix-I-Can** [comment]
Aware of the [issue](https://github.com/dobbelina/repository.dobbelina/issues/883)

**Comment by Buddha2400** [comment]
@DJMix-I-Can could you be any lazier?

**Comment by dobbelina** [comment]
Just tried a few links, works fine for me, closing thread.

**Comment by cbikl** [comment]
Same issue happening for me in firestick

**Comment by cbikl** [comment]
Getting either ljnk could not be resolved or Playback failed
