### ISSUE TITLE
Streamate

### ISSUE THREAD

**Issue by wedoro** [dobbelina/repository.dobbelina#898]
Hi, Cams does`nt open. Kodi 19.4 Android

**Comment by Gujal00** [comment]
`www.streamate.com` site is down for the last few days. Have to wait till the site comes back

**Comment by wedoro** [comment]
Hi, I test it and https://www.streamate.com/ is back.

**Comment by dobbelina** [comment]
A fix will be provided in the next 1.1.59 version https://github.com/dobbelina/repository.dobbelina/commit/b080771740ccf45e84e78e00ea7cd0c10e60a23e
