### ISSUE TITLE
Tag Search on Chaturbate Not Working

### ISSUE THREAD

**Issue by marsrover1-ops** [dobbelina/repository.dobbelina#904]
### Bug reports:

The search by Tags option in Chaturbate is not working. Returns no results.

### OS environment
Kodi on Firestick

There is no error given. The search just doesn't return any results.

**Comment by 12asdfg12** [comment]
It works for me, come back with a log file if you still have issues.

**Comment by dobbelina** [comment]
Closing, no log file provided.
