### ISSUE TITLE
Go to Page Coding

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#907]
Hi,  can someone share example coding for any site where the user can go directly to the desired page.

Example.. Site xyz has 900 pages in a particular search and i would like to visit a random page example 375. 

We can have a tab above current search option like "Go to Page" and possibility of adding numerical figure. 

An example coding on any site example javbangers etc would help to test and check for universal adaptation.

**Comment by DJMix-I-Can** [comment]
https://github.com/dobbelina/repository.dobbelina/search?q=GoToPage

**Comment by imurreflection** [comment]
What exactly is this? It just takes me to Dobbelina repo and i don't see anything related to my request. M i missing something mate?

**Comment by DJMix-I-Can** [comment]
All those sites have the GoToPage code that you're looking for. You asked for the coding & those sites have the coding.
PornVid, Porno365, Netfapx, TNAFlix, Beemtube, Palimas, Yrprno, nonktube, trendyporn, yespornplease, blendporn, youcrazyx, thepornfull, uflash, erogarga, familyporndhd, beeg, avple & pornwild. If you've never used it, go to one of those sites. Scroll down to next page. Highlight it & long press for the context menu. You should see "Goto Page #" click on it & it will let you enter a page number.

**Comment by imurreflection** [comment]
My apologies if I missed this feature as i normally don't browse these sites. Let me check them.

**Comment by imurreflection** [comment]
@DJMix-I-Can Thanks a lot mate..i just checked AVPLE.

Closing the issue now.
