### ISSUE TITLE
Cannot update?

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#910]
Hi @dobbelina. I can't update the version 1.1.59 or your new repo. It says update failed but no log is available. I am on Android TV box running Android 10  

Update: i tried downloading the zip file using desktop and laptop for updating the add-on manually but the file is not downloaded. Can you provide me the zip file here please?

**Comment by dobbelina** [comment]
https://github.com/dobbelina/repository.dobbelina/raw/master/plugin.video.cumination/plugin.video.cumination-1.1.59.zip

**Comment by imurreflection** [comment]
This is the same link, i have been trying for quite some time now. No download though..is it working at your end?. Can you provide me the downloaded zip file here?

**Comment by imurreflection** [comment]
Seems to be some issue with setup. Formatted the box. All fine now. Thank you
