### ISSUE TITLE
👋 Preview image of 👉 mrsexe.com video lists

### ISSUE THREAD

**Issue by victore447** [dobbelina/repository.dobbelina#911]
![logo-mrsexe](https://user-images.githubusercontent.com/48101775/205998846-4ed9895a-3ba7-40cc-947c-5bdb2016fb5f.png)
🖐️![241](https://user-images.githubusercontent.com/48101775/205998645-1559cea0-892a-4c8f-a2d4-64e613e5f4f6.gif) There is no longer a video preview of the site https://www.mrsexe.com/ in Cumination "rebrique recherche, Category etc..." unlike other sites (xvideos etc..) and the site itself  .

For several weeks or even months the videos have been opening but no images when scrolling through the lists.
![46](https://user-images.githubusercontent.com/48101775/205999081-03be3f89-58fa-4dee-992f-2429c849c880.gif)
![mrsexe com](https://user-images.githubusercontent.com/48101775/205999286-92f82f49-be52-49b5-9f01-04fc1d972520.jpg)

 On the other hand in the actress rebrique there are the images of the actresses (the previews).

 **Thanks for the answer**,✔️

**Comment by dobbelina** [comment]
Works fine for me under windows.
Please provide a log file as instructions below:
1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

**Comment by victore447** [comment]
![612](https://user-images.githubusercontent.com/48101775/206009015-80d15718-7f4b-412f-8c2b-f8b3014335b7.gif)**I am under Android Tv version 10 and 11** (Nvidia Tv, Tcl Android tv etc..). 

![674](https://user-images.githubusercontent.com/48101775/206009324-666fbfac-43ea-4e6d-866b-adce9ebc3eb9.gif) What you are asking me is it possible on TV boxes etc..?

**Comment by DJMix-I-Can** [comment]
I'm on Android Nvidia Shield & it's also working on my end.

**Comment by victore447** [comment]
🖐️☝️On Nvidia Shield Tv I have no error message after going to mrsexe.com site when I enable debugging, restart kodi and then go there.

![6 Cumination](https://user-images.githubusercontent.com/48101775/206181099-91f6453c-92d1-4574-8e30-1863cfb1f145.jpg)
![241](https://user-images.githubusercontent.com/48101775/206181005-7b164209-5f7a-4a79-8ac2-b6b77b52d851.gif) I just have results (dates etc.) and haven't touched anything on that configuration.
 Also I have nothing telling me to download anything tonight when I run kodi logfile update (see).

 **Here are the step-by-step screenshots**.
![1 Cumination](https://user-images.githubusercontent.com/48101775/206182221-72f7ff40-2b24-4425-a01e-c116db06435f.jpg)
![2 Cumination](https://user-images.githubusercontent.com/48101775/206182268-34753a90-d359-41f8-ad5a-d01e6eb7fe68.jpg)
![4 Cumination](https://user-images.githubusercontent.com/48101775/206182533-7ae5fc9a-b1c6-4d8b-8882-100ac9e3b967.jpg)
![5 Cumination](https://user-images.githubusercontent.com/48101775/206182603-3843e596-9020-4fc9-a2e3-fe1b30420886.jpg)
![6 Cumination](https://user-images.githubusercontent.com/48101775/206182696-a5eda836-6d70-4b63-8c5f-b3bf507d30c8.jpg)

![684](https://user-images.githubusercontent.com/48101775/206181956-0f6cf0a6-b5d2-4b49-9b24-87d854667670.gif) Only images from the actresses category are visible. **Weird that this is the only Cumination Site that faces me with this.✔️**
![3 Cumination](https://user-images.githubusercontent.com/48101775/206183111-9df73b87-5d96-47c4-b33c-17029204b408.jpg)

**Comment by dobbelina** [comment]
You should have been provided a url somewhere there in the process.

**Comment by victore447** [comment]
🖐️![300](https://user-images.githubusercontent.com/48101775/206417355-e9a31673-37a8-48e2-b246-0a38cdfae21e.gif) **No no message etc.. received.
 Maybe because the videos on the site themselves work.** Only the preview of these videos is not displayed.

 If it can help you, I'll join you on this Ogoogle drive link 👉 https://drive.google.com/drive/folders/13JCQZiCup-z0NQ3R27hMdvW2WX9Dnxic
 The Archives of my Kodi log uploader "Userdata and Addon", and the Archive my Cumination "Userdata and Addon".

 ☝️I browsed several sites and videos two nights ago and it's that mrsexe.com that's weird for the preview.✔️

**Comment by dobbelina** [comment]
Closing, no log file.
