### ISSUE TITLE
XFreehd. Login

### ISSUE THREAD

**Issue by mywayorhighway0** [dobbelina/repository.dobbelina#914]
**Is your feature request related to a problem? Please describe.**
Can we add login information as there are good amount of subscribed content.

**Describe the solution you'd like**
Please enable login credentials so that we can watch new videos uploaded by our subscribed content. Like  we have in javbangers,porntrex etc

**If it's a site addition request, add url below**
Sites with no DMCA information will not be added

**Comment by dobbelina** [comment]
Will be in the next v 1.1.60 https://github.com/dobbelina/repository.dobbelina/commit/41a8e955b6a458b61979ea9921d24c10335e967c

**Comment by imurreflection** [comment]
Thank you .i will wait for the update but i will close this now.
