### ISSUE TITLE
Pornhub.com status

### ISSUE THREAD

**Issue by bOuNtYhUnTeR2022** [dobbelina/repository.dobbelina#916]
Hi there, 

i know you guys are aware about the issue, but is there already any idea how to solve this problem? 

Maybe we can support you by gathering information about the changes in their URLs or code

**Comment by dobbelina** [comment]
Please post in existing thread instead of starting new ones https://github.com/dobbelina/repository.dobbelina/issues/897

**Comment by bOuNtYhUnTeR2022** [comment]
I would, but I'm seeing 3 different requests inside the pornhub.com thread marked 'closed' but not any fix. That's why the additional thread 🤷‍♂️😬
