### ISSUE TITLE
Jav.Guru Tags etc

### ISSUE THREAD

**Issue by EvelK1203** [dobbelina/repository.dobbelina#917]
Is it possible to add the tags, series categories for JavGuru?

Top Tags - https://jav.guru/jav-tags-list/
Series - https://jav.guru/jav-series/
Full Tags - https://jav.guru/tags/

Thanks

**Comment by ErosVece** [comment]
Here, it's added: https://github.com/dobbelina/repository.dobbelina/commit/fca10e0e4713d5c17b24d63e7b5c7b02961ce50f
The full tag list, that gives a 6000+ item list in Kodi, I did not add. You can see parts of those in the Tags, Studio etc lists.
