### ISSUE TITLE
Encountering error when loading next page in searching model/studio

### ISSUE THREAD

**Issue by Zee346** [dobbelina/repository.dobbelina#918]
I have noticed that when using the search model or studio command in Paradisehills, an error is encountered if you go to the 2nd page or beyond.  It won't  happen if you put in the exact name (causing only a few entries to appear), but giving partial information ( such as only the first or last name) will generate more than one page, and the error is encountered. I don't know if anyone else has mentioned this issue, but I thought it best to mention it.

Other than that, the additions that you have made to this site are excellent.  Keep up the good work!

**Comment by dobbelina** [comment]
A fix will e provided in the next release https://github.com/dobbelina/repository.dobbelina/commit/b43d2bae3e643e945a74b0b730e505e0a54b8e10

**Comment by Zee346** [comment]
Sure,

An example would be a actor with the first name of "Stacy".  Typing this
into the search option in the web page generates more than 1 page of
possibilities. While the website allows you to select and go to page 2, an
error will be encountered in the paradisehills application, in the search
actor section.
