### ISSUE TITLE
Porno365 down again

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#920]
Hi @erosvece. Looks like the site is down again. Debug log is below. Kindly fix it

https://paste.kodi.tv/ocetucalaf

**Comment by DJMix-I-Can** [comment]
HTTP Error 451: Unavailable For Legal Reasons
http://wew.porno365.bond/
Page is not found.

**Comment by imurreflection** [comment]
Strange..the site is available via mobile though and videos are playing.  Please see
http://m.porno365.pics/

**Comment by dobbelina** [comment]
> Strange..the site is available via mobile though and videos are playing. Please see http://m.porno365.pics/

In my computer browser the above link redirects to http://wew.porno365.bond/ which opens a blank page with the message "Not Found".
User agent issue?

**Comment by imurreflection** [comment]
I agree it appears to be "User Agent" issue but can it be a legal issue as well what error 451 pertain to?

**Comment by dobbelina** [comment]
A fix will be provided in the next release https://github.com/dobbelina/repository.dobbelina/commit/4aa0461380fc603c9b09088e2030bd5811267b0c

**Comment by imurreflection** [comment]
Looks like the fix is intended for windows users only as copying the py file breaks Cumination completely.

**Comment by DJMix-I-Can** [comment]
It's not, i'm on Android and it's working.

**Comment by imurreflection** [comment]
Again i apologize
I don't know what i copied. This is working fine now. Thank you so much..closing the issue now
