### ISSUE TITLE
Cumination Chaturbate Favourites on (Kodi Main Menu) still will not refresh

### ISSUE THREAD

**Issue by milleniaxx** [dobbelina/repository.dobbelina#922]
### Bug reports:

Please replace this line with a brief summary of your issue 

### OS environment
What OS, Device, version etc

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.
https://paste.kodi.tv/equkezulic

**Comment by dobbelina** [comment]
What in favourites needs to be refreshed?
If a link goes down, it goes down.

**Comment by milleniaxx** [comment]
Hello, I am trying to say that any saved models in favourites use to not display there pictures if they weren’t online. Now whenever I open favourites, the models that are online and the models that were online earlier in the day are still displayed. Kodi always would only display the online model pictures only and not the ones that were online earlier or the day before. I reinstalled and tried everything, and it does the same on both firesticks and on kodi on my computer too.  I hope I explained the problem to you, if not let me know. Thank you so much for the work that you do, Brian

Sent from Mail for Windows

**Comment by Tyke101** [comment]
Yes, I can confirm this behaviour.  It started several weeks ago but
unfortunately I cannot remember which update it occurred after.

Taking Chaturbate as an example,  models showing pictures in favourites are
current models but may not have been “live” on Chaturbate for several
hours.  In the past their picture shown in favourites used to disappear
shortly after they logged off.
Doing a picture refresh in the Chaturbate app removes some of these
pictures but NOT most of them.  It is now not possible to look at your
favourites to discover which of them are live.  It was possible previously.
Obviously this may be a Chaturbate issue if something has changed at their
end.

**Comment by 12asdfg12** [comment]
> In the past their picture shown in favourites used to disappear shortly after they logged off.

I checked the website and the offline rooms that were live up to 9 hours ago still have pictures.

>It is now not possible to look at your favourites to discover which of them are live.

You can use the Online Favorites menu, which works fine.

**Comment by frankee123** [comment]
I don't mean to interfere here, but I would also like a fix if possible. My chaturbate girls that I have in my favorites show their pic as if they are online as well, when in fact they are not or have been for a long time. It never used to do this and it has been lately. Is there a fix for it please? Ty

**Comment by milleniaxx** [comment]
Thank you for todays update for chaturbate. But I'm still having the same problem of favourites not refreshing. And I can't seem to brouse anything on chaturbate either. This is happening on all 3 of my devices

**Comment by milleniaxx** [comment]
Thank you for fixing the browsing on todays update. But the favourites refreshing issue is still not working

**Comment by milleniaxx** [comment]
Is anybody else having the favourites not refreshing issue still??  Or am I the only one?  I have tried everything I can think of to fix this but it still won't refresh.

**Comment by dobbelina** [comment]
A fix will be provided in the next release https://github.com/dobbelina/repository.dobbelina/commit/7f7a3fc286ffcda08077b3130a61d3d614c5a0b5

**Comment by milleniaxx** [comment]
Thank you so much


Sent from Mail for Windows

**Comment by milleniaxx** [comment]
The recent update still hasn't fixed the refresh images on Favourites. It still shows models that were on hours before and that are not online anymore.  I am talking about the screen when you first open Kodi menu and it is spelt Favourites not Favorites

**Comment by frankee123** [comment]
Sorry to say the update did not fix the problem. I still see pics of girls that show they are online when they are not.

**Comment by 12asdfg12** [comment]
This is how Chaturbate (the website) works. After a model is offline, the image is still displayed for several hours.
There is nothing to be fixed.

**Comment by milleniaxx** [comment]
Some are displayed for up to 14 hours after they signed off.  It never used to take that long before

**Comment by 12asdfg12** [comment]
That's how it works now.
The image disappears after about 10 hours.


![image](https://user-images.githubusercontent.com/48175015/211338695-358674d8-0c5c-4c68-8476-0e7c35e527de.png)

**Comment by milleniaxx** [comment]
I'm not talking about the website, I am talking about in the Kodi app itself

**Comment by milleniaxx** [comment]
I am talking about the screen when you first open Kodi menu that is spelt Favourites not Favorites.  Thats the one that takes so long to refresh

**Comment by 12asdfg12** [comment]
The addon fetches the data from the website, if the website displays an image for a model, the addon will do the same.

**Comment by milleniaxx** [comment]
Then can I ask you why when you go to the Chaturbate - online favorites in Kodi. When a model leaves, her picture is gone in a few minutes there?

**Comment by 12asdfg12** [comment]
When you go to Online Favorites, a list of all online models (about models 8-9000) is downloaded, and only favorites that are in the online model list are displayed. If the model is offline, it will not be shown in Online Favorites, whether it has a picture or not.

**Comment by milleniaxx** [comment]
Ok  Thank you for all the help
