### ISSUE TITLE
Xhamster no videos listing 

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#924]
Please check the video listings are empty on xHamster. No such issue on mobile browser though. It did not generate any log as there are no videos listing. I tried on VPN too but no use. Kindly check.

**Comment by dobbelina** [comment]
A fix will be provided in the next release https://github.com/dobbelina/repository.dobbelina/commit/077531db977a8d1da4ecacc27efdba8582c02fb8

**Comment by imurreflection** [comment]
Thank you so much. This is working fine. Closing the issue now
