### ISSUE TITLE
Spankbang not working 

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#926]
Here is the debug log

https://paste.kodi.tv/liweguqoza

**Comment by dobbelina** [comment]
A fix will be provided in the next release https://github.com/dobbelina/repository.dobbelina/commit/222d16fb6e1eac95c8dfabe0136a68be583d2d2d

**Comment by imurreflection** [comment]
Please refer to the above fix. It appears it directs to porno365 fix.Request you to check this please

**Comment by imurreflection** [comment]
After applying above fix, porno365 is down again and spankbang has started working. Please let me know if you need a log for this as it appears to be some mixup.
