### ISSUE TITLE
Chaturbate - Online Favorites bug

### ISSUE THREAD

**Issue by TarkusLV** [dobbelina/repository.dobbelina#927]
### Bug reports:

I have a favorite model with the name mila_1.  There is another model, who is not a favorite, with the name mila_.  Online Favorites sees mila_ and shows her online as mila_1, but with her own thumbnail.  Clicking on her thumbnail produces the "Couldn't find a playable link" error, presumably because it's trying to load the real mila_1, who is not online.

In short, Online Favorites is ignoring the "1" in the name, when doing its online search.

Incidentally, when adding mila_ as a favorite, it shows her thumbnail twice, once for mila_ and once for mila_1.

### OS environment
Fire TV Stick 4K Max

http://paste.kodi.tv/itiqacopan

**Comment by dobbelina** [comment]
A fix will be provided in the next release https://github.com/dobbelina/repository.dobbelina/commit/222d16fb6e1eac95c8dfabe0136a68be583d2d2d
