### ISSUE TITLE
Chaturbate not working on recent update

### ISSUE THREAD

**Issue by scorsese50** [dobbelina/repository.dobbelina#928]
### Bug reports
Chaturbate hangs when trying to access categories. Thanks.

### OS environment
What OS, Device, version etc

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.

**Comment by dobbelina** [comment]
I can confirm the behaviour, spinning circle never ending show.

**Comment by DJMix-I-Can** [comment]
Same here... I undid the changes that were made on this [fix](https://github.com/dobbelina/repository.dobbelina/commit/2af0be05e77718ab8e5985edfbf8c2471a891f2f#diff-0a89ff398a75c967cbf3867a28384c6517bdd2ddf060a9eb773a5be605ec8266) & it's back up.

**Comment by scorsese50** [comment]
Seems to be still down.

**Comment by milleniaxx** [comment]
Same here and favourites still is not refreshing

**Comment by dobbelina** [comment]
Update will be reverted in the next release https://github.com/dobbelina/repository.dobbelina/commit/27228ba9ce95ccfae47a803ae4a0f085f9a7418a

**Comment by scorsese50** [comment]
Thanks

**Comment by hbkpreet** [comment]
Yup , same issues as above.

**Comment by scorsese50** [comment]
Fixed on the update. Thanks.
