### ISSUE TITLE
Remove strict verification of SSL

### ISSUE THREAD

**Issue by ruinernin** [dobbelina/repository.dobbelina#93]
Potentially could be an optional switch (though I doubt in this case anyone _really_ cares). 

Some (HTTPS) video sources by times are failing SSL verification checks by Kodi itself, some deeper analysis suggests these sources aren't automating their Let's Encrypt renewals. Not that that's our problem.

Example error:

```
$ awk '/CCurlFile/{sub("mangovideo.pw.*", "mangovideo.pw");print substr($0, index($0, $4))}' kodi.old.log
ERROR: CCurlFile::Stat - Failed: Peer certificate cannot be authenticated with given CA certificates(60) for https://mangovideo.pw
ERROR: CCurlFile::Stat - Failed: Peer certificate cannot be authenticated with given CA certificates(60) for https://mangovideo.pw
ERROR: CCurlFile::FillBuffer - Failed: Peer certificate cannot be authenticated with given CA certificates(60)
ERROR: CCurlFile::Open failed with code 0 for https://server2.mangovideo.pw
```

Fix:
```
$ diff utils.py utils.py.orig
369c369
<         xbmc.Player().play(videourl + '|verifypeer=false', listitem)
---
>         xbmc.Player().play(videourl, listitem)
```

Can I also suggest the code is hosted unzipped to make it possible to just submit this type of issue as a PR?

**Comment by dobbelina** [comment]
Hi ruinernin,

Thanks for your input!
I'll let the coding gurus here have a look at your code so they can comment on it.
Regarding uploading everything unzipped i have just been to lazy and never saw the need for it.
However, i did upload utils.py to the plugin.video.uwc folder, as  most of the machinery
is in that file.

**Comment by 12asdfg12** [comment]
the fix doesn't work if videourl already contains '|'
... maybe something like this:
```
        videourl += '|verifypeer=false' if '|' not in videourl else '&verifypeer=false' if 'verifypeer=false' not in videourl.lower() else ''
        xbmc.Player().play(videourl, listitem)

```

**Comment by jdoedev123** [comment]
Interesting observation I had never really thought much of this subtlety in the code. Although I have been known to force "bad" videos to download with commands like:
wget  --no-check-certificate  --output-document=DOWNLOADFILENAME.mp4 -c  URL  --secure-protocol=TLSv1_2 --referer=https://mangovideo.pw (or other referer URL)

Which is roughly the equivalent of the proposed turning off of certificate checking.

**Comment by ruinernin** [comment]
> the fix doesn't work if videourl already contains '|'
> ... maybe something like this:
> 
> ```
>         videourl += '|verifypeer=false' if '|' not in videourl else '&verifypeer=false' if 'verifypeer=false' not in videourl.lower() else ''
>         xbmc.Player().play(videourl, listitem)
> ```

Are there other flags/options that can be passed in here other than `verifypeer` with a pipe at the end of the string where `&` allows additional flags/options?

I was trying to look for documentation on this to no avail (even this option itself appears undocumented).

**Comment by 12asdfg12** [comment]
I used this option mostly for passing the Referer and User-Agent, but probably works for other header options too.

**Comment by dobbelina** [comment]
Fix applied by 12asdfg12, closing issue.
