### ISSUE TITLE
Format of .bal backup file.

### ISSUE THREAD

**Issue by p8ckachu** [dobbelina/repository.dobbelina#934]
I can no longer access the favorites.db file since the file system got locked down.

Would like to know how the .bak favorites backup file is formatted, so I can't edit favorites manually. 

Looks like an archive, but can't access the file after unpacking it.

**Comment by DJMix-I-Can** [comment]
Throwing my two cents in here.... I'm assuming you were updated to a newer Android version which locked you out. If so, I feel your pain. It happened to me on my Nvidia Shield & reverted back to the previous version.  I'm able to look at the favorites,db file with a portable version of SQLiteDataBaseBrowser without any issues. When I tried again with the favorites.bak file, I was asked for a password. I changed the extension to ".db" & tried again, it sill asked for a password. I'm still going to try to play with it but feel it's an encryption within Kodi, or not... I'm guessing as I'm still learning......

**Comment by 12asdfg12** [comment]
You can choose a custom location for favorites.db in settings.
The uncompressed backup file (.bak) is a JSON-formatted text file, that can be opened with any text editor.

**Comment by p8ckachu** [comment]
> Throwing my two cents in here.... I'm assuming you were updated to a newer Android version which locked you out. If so, I feel your pain. It happened to me on my Nvidia Shield & reverted back to the previous version. I'm able to look at the favorites,db file with a portable version of SQLiteDataBaseBrowser without any issues. When I tried again with the favorites.bak file, I was asked for a password. I changed the extension to ".db" & tried again, it sill asked for a password. I'm still going to try to play with it but feel it's an encryption within Kodi, or not... I'm guessing as I'm still learning......

I'm surprised it prompts for a password, since I don't think it's actually a dB file.

**Comment by p8ckachu** [comment]
> You can choose a custom location for favorites.db in settings. The uncompressed backup file (.bak) is a JSON-formatted text file, that can be opened with any text editor.

I'll try this option

**Comment by p8ckachu** [comment]
Suggestion worked. Created a backup of favorites. chose download folder as custom location for favorites.db, restored from backup. And was able to access the db file in the download folder.
