### ISSUE TITLE
xHamster Duration Display

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#937]
On videos duration display are displaying in numbers instead of hour, Minutes and seconds..kindly check

**Comment by dobbelina** [comment]
A fix will be provided in the next release https://github.com/dobbelina/repository.dobbelina/commit/7f7a3fc286ffcda08077b3130a61d3d614c5a0b5

**Comment by imurreflection** [comment]
Thanks. This is working fine. Closing the issue now
