### ISSUE TITLE
Bio in Chaturbate Online Favorites

### ISSUE THREAD

**Issue by TarkusLV** [dobbelina/repository.dobbelina#938]
I really like the (new?) format of the Bio displayed in the Chaturbate listings.  It's very clean, well-organized and easy to read.  I was wondering if that format could be ported to the Online Favorites?

Thanks.

**Comment by dobbelina** [comment]
A fix will be provided in the next release https://github.com/dobbelina/repository.dobbelina/commit/b3e8475951b77c427bcb66791c0b3f9e18554732
