### ISSUE TITLE
AnimeID-Hentai

### ISSUE THREAD

**Issue by DaisyF8** [dobbelina/repository.dobbelina#94]
Some Issues

Next Page doesn't show in lists (or in search results)
Clicking the header "Uncensored" does nothing
Image-art doesn't show

**Comment by 12asdfg12** [comment]
fixed
[animeidhentai.zip](https://github.com/dobbelina/repository.dobbelina/files/3639848/animeidhentai.zip)

**Comment by DaisyF8** [comment]
Is fixed :)

Thx

**Comment by s4ik0s4n** [comment]
Looks like they changed their website again. New url is Hentai.tv

**Comment by dobbelina** [comment]
Still works for me.

**Comment by s4ik0s4n** [comment]
My apologies. It seems to be working today. When I tried visiting from the add-on, I got ther error message about the site being down. When I visited from my phone, it redirected me to Hentai.tv. I assumed they changed their website since the set up and font looked so similar.
