### ISSUE TITLE
Search in Chaturbate Not Finding Results

### ISSUE THREAD

**Issue by marsrover1-ops** [dobbelina/repository.dobbelina#942]
### Bug reports:

Searching in Chaturbate is no longer returning results. Search names match the name of the models that are actively broadcasting live during the search, but the search does not find them. No error messages are being returned, so nothing is being uploaded/written to the log.

### OS environment
Android FireTV.

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.

**Comment by 12asdfg12** [comment]
Website error, search (mostly) does not work on the website.
If you keep trying, sometimes it works.
