### ISSUE TITLE
Favorites issue on Android/Fire TV using Kodi Nexus

### ISSUE THREAD

**Issue by TarkusLV** [dobbelina/repository.dobbelina#945]
### Bug reports:

Since upgrading to Nexus, when using straight Android or Fire TV, Favorites are always sorted by Date, with oldest first, regardless of setting.  Also, all move options are missing from the context menu.  Tried one Android device and two different Fire TV devices.  Seems to work fine on Windows, though.

### OS environment
Android/Fire TV with Kodi Nexus

Seems unnecessary to upload a logfile, but will do so if requested.

**Comment by frankee123** [comment]
Yes, I noticed this as well. I had my favorites so my mfc girls are all on top with chatubate girls on bottom, and I cannot get it to show it like that. Please fix. Ty

**Comment by dobbelina** [comment]
A fix will be provided in the next release https://github.com/dobbelina/repository.dobbelina/commit/fb4300015a18e19f00152e94d3b86de41693bd7c
