### ISSUE TITLE
Issues with Chaturbate online favorites i have provided log info

### ISSUE THREAD

**Issue by losthelp815** [dobbelina/repository.dobbelina#946]
Issues since last update can no longer see online favorites through chaturbate was working in the last prior release.

Windows 7 Ultimate
Kodi v18 Leia

https://paste.kodi.tv/kibonadego

**Comment by dobbelina** [comment]
A fix will be provided in the next release https://github.com/dobbelina/repository.dobbelina/commit/0e5fd894836f2815ce86012cf45ee6d583484f12
