### ISSUE TITLE
XHAMSTER  does not show option for next page

### ISSUE THREAD

**Issue by jp194978** [dobbelina/repository.dobbelina#952]
On main page does not show option for next page. on windows 10  Kodi 20 nexus will upload upload a logfile,  if requested.  thank you

**Comment by dobbelina** [comment]
What version of the Cumination add-on you got?

**Comment by jp194978** [comment]
> What version of the Cumination add-on you got? There was a fix released for that in v.1.1.63 that's working for me on windows 10 Kodi 19.4

using cumination version 1.1.64  on kodi 20 nexus

**Comment by jp194978** [comment]
Cumination version 1.1.64 kodi 20 nexus

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Airwolf1978** [comment]
Running 19.3 and v1.164 no next page either

**Comment by Airwolf1978** [comment]
Just upgraded to Jodi 20 still the same using via firestick

**Comment by 12asdfg12** [comment]
xhamster is fixed in 1.1.65, not in 1.1.64

[B]Version 1.1.65[/B]
xhamster - fix pagination, categories

**Comment by Airwolf1978** [comment]
> xhamster is fixed in 1.1.65, not in 1.1.64
> 
> 
> 
> [B]Version 1.1.65[/B]
> 
> xhamster - fix pagination, categories
> 
>  

Thanks for clearing that up I thought I was doing something wrong

**Comment by dobbelina** [comment]
1.1.65 released today.

**Comment by jp194978** [comment]
Thank you


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
