### ISSUE TITLE
Motherless.com site request 

### ISSUE THREAD

**Issue by TapeMeOh** [dobbelina/repository.dobbelina#953]
Would it be possible to add motherless.com?

There is a custom site version of it but it doesn't seem to work anymore.
https://github.com/dobbelina/repository.dobbelina/issues/786#issuecomment-1146831470

Motherless.com
https://motherless.com/dmca

**Comment by 12asdfg12** [comment]
https://github.com/dobbelina/repository.dobbelina/issues/786

**Comment by TapeMeOh** [comment]
I've tried that custom site version and it doesn't seem to work. Doesn't display any videos.

**Comment by 12asdfg12** [comment]
Fixed:
[motherless.zip](https://github.com/dobbelina/repository.dobbelina/files/10537460/motherless.zip)

**Comment by TapeMeOh** [comment]
Thats working.

Thank you.
