### ISSUE TITLE
Site Request - maturetube.com - thank you!

### ISSUE THREAD

**Issue by Spanktacular** [dobbelina/repository.dobbelina#960]
**If it's a site addition request, add url below**
Sites with no DMCA information will not be added
maturetube.com

DMCA info - https://www.maturetube.com/dmca/

**Comment by DJMix-I-Can** [comment]
I don't think this will be added. This site is part of a network called PornTV. PornTV was implemented into Cumination back in May of 2022. Eventually it was removed.

**Comment by ErosVece** [comment]
This has been added with the AWM Network addition
