### ISSUE TITLE
Chaturbate Online Favorites - missing models

### ISSUE THREAD

**Issue by dvgm506** [dobbelina/repository.dobbelina#962]
### Bug reports:

A number of models just don't show up in the chaturbate online favorites list. The show up in the chaturbate full & tag listings and in the general cumination favorites vidoes.

Maybe related to this closed bug?

https://github.com/dobbelina/repository.dobbelina/issues/946

This has been going on for a while, just never looked to see if there was a workaround.

Few examples would be:

x__rose__x
thecherie
_jikey_
alexa_dream
raisakitty
danikanappi online with description: private is open ♥welcome to my room! [#bigboobs](https://chaturbate.com/tag/bigboobs) [#lovense](https://chaturbate.com/tag/lovense) [#squirt](https://chaturbate.com/tag/squirt) [#new](https://chaturbate.com/tag/new) [#teen](https://chaturbate.com/tag/teen) 

### OS environment

Win11 Pro. Kodi 20. Updated Cumination & Nvidia Shield Pro with Kodi 20

Logs from my windows machine with only 2 favorites set in chaturbate

https://paste.kodi.tv/ahugocobuj

**Comment by 12asdfg12** [comment]
You are right, but this is not a Cumination bug, but rather a Chaturbate bug.
The add-on downloads the list of the online models from this URL:
https://chaturbate.com/affiliates/api/onlinerooms/?format=json&wm=C9m5N
but for some reason, some models are missing from the list even if they are online.

**Comment by dvgm506** [comment]
Thanks for the info 12as

Did some digging, looks like models have the option to disable "appear on network sites". Guessing that's what doesn't add them to the API online list.
