### ISSUE TITLE
PornTrex broken

### ISSUE THREAD

**Issue by jdoedev123** [dobbelina/repository.dobbelina#97]
Change in website has broken PornTrex. No fix yet.

**Comment by dobbelina** [comment]
Thanks for noticing,
I can confirm links don't play.

**Comment by DJMix-I-Can** [comment]
I just tried it and everything works besides the private videos.

**Comment by dobbelina** [comment]
Yep, same here, now it works.
The site was down temporarily a few days ago as well, probably doing some maintenance.

**Comment by jdoedev123** [comment]
UWC and website now working for me. Website was broken in Chrome and Firefox a few days ago as well. I suspect they accidentally broke their own website and rolled it back to fix it. With the website broken in browsers, I was not working on a fix but waiting for the hoped for roll back.
