### ISSUE TITLE
New site add - porndish

### ISSUE THREAD

**Issue by Napster955** [dobbelina/repository.dobbelina#972]
https://www.porndish.com/

**Comment by imurreflection** [comment]
I requested addition of this site on July 12, 2022. Good luck to you if it's added as it's a very good site. Probably, you are not aware but without DMCA, they will not add this site so here you go:
https://www.porndish.com/dmca/

**Comment by ErosVece** [comment]
Well, I've started to work on it.....so expect it soon, it depends how much i'm getting distracted by other stuff :)

**Comment by dobbelina** [comment]
Thanks for the update, will be in the next version https://github.com/dobbelina/repository.dobbelina/commit/be2fa1c1cfd1557827effe118e46365f26196838
