### ISSUE TITLE
Javhdporn - No Playback 

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#975]
Kindly check. I have tried 4 videos but there was no playback. Tried VPN also.

Here is the debug enabled log

https://paste.kodi.tv/wekomatami

**Comment by dobbelina** [comment]
I get errors to.
Here's a quick snippet of my log file:https://paste.kodi.tv/winoyopoqu.kodi

**Comment by 12asdfg12** [comment]
The video links are obfuscated and the code was changed. No solution atm.

**Comment by imurreflection** [comment]
We must remove this site. As such, we now have 140+ Site. It is quite hard to maintain these many sites. Closing the issue now.
