### ISSUE TITLE
Can we add this search engine? Noodle Magazine

### ISSUE THREAD

**Issue by Napster955** [dobbelina/repository.dobbelina#977]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**If it's a site addition request, add url below**
Sites with no DMCA information will not be added

https://noodlemagazine.com/

**Comment by CableSix** [comment]
UP this site is so good

**Comment by imurreflection** [comment]
Well you need to mention DMCA for developers to consider adding it. I have mentioned here for you

https://noodlemagazine.com/removal

**Comment by Napster955** [comment]
@imurreflection Sure will add when new site request is done from my side.

**Comment by ErosVece** [comment]
Wait for the next update of Cumination ;)

**Comment by imurreflection** [comment]
Have you added it already. I can't see any pull request

**Comment by imurreflection** [comment]
Thank you for the addition @erosvece. Can you please add filters in noodlemagazine please. I can only see "Long" and "HD" filters present on the site. Can you please add them? Thanks

**Comment by ErosVece** [comment]
I know, the current sort order is on date. So the video is was looking for should have be as one of the first hits.

**Comment by imurreflection** [comment]
No, i simply copy relevant py files directly to the desired folder by using "Send files to TV" app. No hassles at all

**Comment by ErosVece** [comment]
Expect a commit by Dobbelina that adds changing the sorting options

**Comment by CableSix** [comment]
it doesn't show up for me, why?

**Comment by DJMix-I-Can** [comment]
@CableSix Dude... You really need to read. This is for the next update that is going to get pushed. Even though ErosVece made changes for it within Github, You will not get it UNTIL the next Cumination update gets pushed to the users. ErosVece posted [this](https://github.com/dobbelina/repository.dobbelina/issues/1022) for those who are impatient on getting the next Cumination update. If you can't figure this out THEN you're going to have to wait till the next update.

**Comment by DJMix-I-Can** [comment]
@ErosVece Thanks for the information. The way you described it in the first paragraph is exactly how I became involved in it. I started mimicking other add-ons to see how it worked. Change things here & there. Look at the errors & what not. I honestly don't spend a lot of time with Python, but still intrigued with it. I'll definitely take a look at that website. Thanks.
