### ISSUE TITLE
Cumination chaturbate categories are empty

### ISSUE THREAD

**Issue by scorsese50** [dobbelina/repository.dobbelina#979]
Chaturbate has no feeds under each category.

**Comment by zzyuui** [comment]
Same here as well.  No results for any of the Chaturbate categories.  Can confirm that the "Online Favorites" is still working.
First noticed the problem yesterday afternoon.  Was working normally earlier in the day.

Using Fire TV (2nd Gen). Fire OS 5.2.9.4, Kodi 19.4, Cumination 1.1.68

**Comment by CableSix** [comment]
actually yesterday it stopped working

**Comment by dobbelina** [comment]
A fix will be available in the next release https://github.com/dobbelina/repository.dobbelina/commit/3c0facceb5114e4ebaa9f5589def2ba26300f7d0

**Comment by psyco752** [comment]
To this day this problem continues, I can confirm it, hopefully the update will arrive soon.

**Comment by TarkusLV** [comment]
The fix is in the repository, but you'll have to edit/replace chaturbate.py manually, or wait for the next Cumination update (which I would guess is coming tomorrow, but that's just a guess).

**Comment by scorsese50** [comment]
Thanks it is fixed.
