### ISSUE TITLE
Eroticage movies are not working

### ISSUE THREAD

**Issue by cgx47275** [dobbelina/repository.dobbelina#98]
they dont load or play

**Comment by dobbelina** [comment]
Issue confirmed on new links.
If one does a search, most old links still work.

**Comment by 12asdfg12** [comment]
Verystream uses a new domain, woof.tube which is not recognized in resolveurl. This will be fixed, probably, in next release of resolveurl.
Until then, here is a fix for eroticage and xtheatre.
[eroticage.zip](https://github.com/dobbelina/repository.dobbelina/files/3661882/eroticage.zip)
[xtheatre.zip](https://github.com/dobbelina/repository.dobbelina/files/3661883/xtheatre.zip)

**Comment by cgx47275** [comment]
noob question. how do I install the fix files?

**Comment by dobbelina** [comment]
> 
> 
> noob question. how do I install the fix files?

Replace files in this folder:
`plugin.video.uwc\resources\lib\sites`

**Comment by dobbelina** [comment]
Fixes committed to v.1.1.96, closing issue
