### ISSUE TITLE
Missav- no "Next" tab

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#980]
"Next" tab is not available on Main page and on any of the categories and sub-categories. No log is available for this issue. No such issue on mobile and PC. Kindly check

**Comment by dobbelina** [comment]
A fix will be available in the next release https://github.com/dobbelina/repository.dobbelina/commit/3c0facceb5114e4ebaa9f5589def2ba26300f7d0

**Comment by imurreflection** [comment]
Thanks. Closing the issue now.
