### ISSUE TITLE
Avple.com- No "Next" tab

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#981]
No "Next" tab is available on main page. No log is available.

Kodi crashes when you click on "Uncensored" category. Kindly check.

**Comment by 12asdfg12** [comment]
No problem with Avple here, there is no next page on the website's main page.

**Comment by imurreflection** [comment]
Yes,it's now there on all sub-categories and Clicking on 'Uncensored" doesn't crashes Kodi. So all is fine now. Thank you
