### ISSUE TITLE
Custom list -doodstream

### ISSUE THREAD

**Issue by inoculate23** [dobbelina/repository.dobbelina#982]
It would be great to be able to integrate our own doodstream accounts as custom sites. I've tried and failed. Any he would be great.

**Comment by dobbelina** [comment]
That is handled by ResolveURL, make a request here instead:[ResolveURL for Kodi](https://github.com/Gujal00/ResolveURL)
![bild](https://user-images.githubusercontent.com/46063764/224792584-98fb77c7-b7b5-44a7-919d-d76742dcb267.png)
