### ISSUE TITLE
Spankbang - No Playback

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#984]
Here is the debug enabled log

https://paste.kodi.tv/eciqewemew

**Comment by 12asdfg12** [comment]
They are using Cloudflare protection now:



![image](https://user-images.githubusercontent.com/48175015/222965181-7add859e-59a3-47c4-889e-f66f9a1e4b6b.png)

**Comment by imurreflection** [comment]
May be region specific. Here we don't have such issue. The site is opening and working fine on mobile and PC browser.

**Comment by 12asdfg12** [comment]
Of course, it works in a browser, Cloudflare protection only prevents site scraping (= using automated tools to extract data from a website), that's why it doesn't work in Kodi.

**Comment by imurreflection** [comment]
Oh..i am sorry i was not aware if Scraping is possible. If you remember, there was a site which could not be added for similar reason was added eventually. Can you check it please.

**Comment by 12asdfg12** [comment]
In that case, the protection was regional, that site still does not work in some regions.

**Comment by Spanktacular** [comment]
Southeast U.S. here. Not working here either.

**Comment by Spanktacular** [comment]
Hopefully, this is helpful.
https://www.zenrows.com/blog/bypass-cloudflare-python

**Comment by EvelK1203** [comment]
It is a regional issue. Setting VPN to Brazil and South Africa allowed access. Most other regions no go.

**Comment by frankee123** [comment]
Dang this stinks, spankbang and porntrex are my favorite.

**Comment by Spanktacular** [comment]
https://scrapeops.io/web-scraping-playbook/how-to-bypass-cloudflare/

**Comment by imurreflection** [comment]
Looks like site is back and videos are playing. Closing the issue. Thanks

**Comment by Spanktacular** [comment]
> Looks like site is back and videos are playing. Closing the issue. Thanks

This statement is incorrect. The site is still not functioning within the add-on. 

Android TV 10
Southeast US
