### ISSUE TITLE
Entries

### ISSUE THREAD

**Issue by jegfonseca** [dobbelina/repository.dobbelina#986]
Hello 

The entries are not working in chaturbate 

Thanks

**Comment by DJMix-I-Can** [comment]
Are you using the latest version?
 2023-03-05 Bumped to v.1.1.69

chaturbate - fix listing
missav - fix pagination
search - added "Edit keyword" to context menu

**Comment by jegfonseca** [comment]
.sorry . My updates are not  automátic

Thanks
