### ISSUE TITLE
Three new features request for downloading and clipboard copying

### ISSUE THREAD

**Issue by neptunus123** [dobbelina/repository.dobbelina#989]
Feature requests:

1. Background file download feature.
2. Multiple simultaneous videos download feature
3. Copy link of a video to clipboard feature.

For the  background download feature; it is requested to download files in the bacground even if the site or page is left.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**If it's a site addition request, add url below**
Sites with no DMCA information will not be added

**Comment by bOuNtYhUnTeR2022** [comment]
> Feature requests:
> 
> 1. Background file download feature.
> 2. Multiple simultaneous videos download feature
> 3. Copy link of a video to clipboard feature.
> 
> For the background download feature; it is requested to download files in the bacground even if the site or page is left.
> 
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **If it's a site addition request, add url below** Sites with no DMCA information will not be added

Very good ideas, supporting them strongly 👍😉

**Comment by dobbelina** [comment]
This does all of the above including copying the link to the clipboard:
[youtube-dl-Recorder-for-Kodi (Windows)](https://github.com/dobbelina/repository.dobbelina/issues/392)
