### ISSUE TITLE
Spankbang 

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#99]
Kindly check..no thumbnails and no playback. The site is under "Tubes" section.

**Comment by DJMix-I-Can** [comment]
The old file was put in instead of the fixed one, this is the working one.
[spankbang.zip](https://github.com/dobbelina/repository.dobbelina/files/3682925/spankbang.zip)

**Comment by dobbelina** [comment]
Fix committed to v.1.1.96, closing issue
