### ISSUE TITLE
PornEZ doesn't show any content

### ISSUE THREAD

**Issue by saidma** [dobbelina/repository.dobbelina#991]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**If it's a site addition request, add url below**
Sites with no DMCA information will not be added

**Comment by bOuNtYhUnTeR2022** [comment]
Just download the fixed pornEz.py file in 'sites' directory and replace the existing file in your install directory. All will be fine again 😊

**Comment by dobbelina** [comment]
[fixed - javmoe, pornez, okporn](https://github.com/dobbelina/repository.dobbelina/commit/343476790cebb51362488d075845678ab6cb5fcf)
