### ISSUE TITLE
Xhamster

### ISSUE THREAD

**Issue by Airwolf1978** [dobbelina/repository.dobbelina#993]
Unable to enter site 'no video found' firestick & Kodi Nexus

**Comment by dobbelina** [comment]
A fix will be available in the next release [xhamster fix listing](https://github.com/dobbelina/repository.dobbelina/commit/f765c4b162947b5e862c1331f6afde9c66c14f5a)

**Comment by Airwolf1978** [comment]
No messing around with you guys 👍
