### ISSUE TITLE
It keeps asking for my Chaturbate login / I get logged out all the time

### ISSUE THREAD

**Issue by rokdrei** [dobbelina/repository.dobbelina#995]
### Bug reports:

The Cumination Addon is great, thanx for the awesome work. However the new feature with cb-login doesn’t work for me, I keep getting logged out.
Just updated from matrix to nexus, but the problem remains. I installed the Logfile uploader, but I’m not sure if it helps you, cause I don’t get an error message, it just keeps asking for my login although I already logged in. If I try to ignore it and I don’t login (I just dont input any username and password and click on „done“) it still keeps asking for it.

Logfile: https://paste.kodi.tv/otocazoqiz

### OS environment
OS: fire os 6.2.9.5 (NS6295/4448), fire tv stick 4k

**Comment by 12asdfg12** [comment]
After a successful login, authentication is done through cookies, so probably, there is a problem with saving cookies on your device.
You can try to delete the cookies, in settings/delete all cookies.
The cookies are stored in the **cookies.lwp** file,  **userdata/addon_data/plugin.video.cumination/** folder.
You can check if in the **cookies.lwp** file, after logging in, you have a cookie with the name **sessionid** for **domain=".chaturbate.com"**

**Comment by dobbelina** [comment]
No reply, closing issue.
