### ISSUE TITLE
Site Addition Request - http://www.incestflix.com/

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#996]
Request you to consider adding this site.

http://www.incestflix.com
DMCA: http://www.incestflix.com/dmca

**Comment by imurreflection** [comment]
Dear @erosevece. Please take a look at above site and check if it's worth adding. This site has largest collection of some hard to find studios like primalfetish has 60 pages and others. Moreover, all videos are hosted on their own server. If you think it's not worth, i will immediately close this issue. Kindly consider as we recently have added more than 40 sites sir

**Comment by ErosVece** [comment]
I remember I started it months ago, but there was something why I didn't finish it. Can't remember what it was :)

I'll have another look.

**Comment by imurreflection** [comment]
Thank you my friend. This site is really worth adding.

**Comment by ErosVece** [comment]
https://github.com/dobbelina/repository.dobbelina/commit/2468b97ea2869a002a300239c7f8476a10ca1b57

I named it Iflix in Cumination, I don't want the word Incest in the main sitelist

**Comment by imurreflection** [comment]
Thank you so much sir..all is working fine..it took me some time to search for content i was looking for but with the help of 'lookup info' i was able to find it. I never realised that this site was so vaste.
Thank you again..

**Comment by imurreflection** [comment]
What we have is more than enough..and i can't thank you enough for the addition. I would like to close this issue now. Thans again and have a nice day
